### ISSUE TITLE
[Pokemon Brillant Diamond] black screen and hang when ending a battle (Regression?)

### ISSUE THREAD

**Issue by Chilledwaffles** [Ryujinx/Ryujinx#2878] opened 2021-11-25 06:50 UTC
### What's the issue you encountered?

sometimes when you finish a battle the screen goes black and nothing happens (the emulator stays at 0 fps). 
did not happen before I updated Ryujinx today.

### How can the issue be reproduced?

fight trainers until you crash

### Log file
[Ryujinx_1.0.7108_2021-11-24_22-15-23.log](https://github.com/Ryujinx/Ryujinx/files/7600786/Ryujinx_1.0.7108_2021-11-24_22-15-23.log)

### Environment?

- Ryujinx version: 1.0.7108</br>
- Game version: 1.1.1</br>
- System Specs:
  - OS: *Windows 10*
  - CPU: *Ryzen 1600*
  - GPU: *GTX 1070 Ti*
  - RAM: *16GB*
- Applied Mods : No

**Comment by gdkchan** [comment] 2021-11-26 16:15
Duplicate of #2865.

**Closed by gdkchan** 2021-11-26 16:15 UTC
