### ISSUE TITLE
Non combined Joycons are not recognized

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#2127] opened 2021-03-20 10:03 UTC
## Bug Report

Current version of opentk fork is based on opentk 3.2.1, which do not detect isolate joycons

On version 4.6.1 they are correctly recognized (see related issue on upstream opentk):

https://github.com/opentk/opentk/issues/1260#issuecomment-803281795

### What's the issue you encountered?

Having two pair of joycons, I can only play games with two players, while it should be possible to use 4 characters

### How can the issue be reproduced?

Sync joycons one by one (one led, two led, three led, four led) and see they are not recognized on Ryujinx

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6794
- Game version: N/A
- System Specs:
  - OS: Fedora 33
  - CPU: i7-6700
  - GPU: intel
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Possible workaround is to map one side of each combined joycon to one player

**Comment by MisterPrintf** [comment] 2021-04-03 00:38
Have you tried BetterJoy? It has always worked fine for myself.

**Comment by albfan** [comment] 2021-04-03 05:32
Betterjoy depends on Microsoft .net so can only be used on windows.

Recognize the controllers is not the problem, jstest-gtk detects them correctly combined or isolated.

Is opentk 3.2.1 which do not recognize them. Opentk 4.6.1 detects isolated joycons.

**Comment by AcK77** [comment] 2021-04-11 19:57
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by albfan** [comment] 2021-04-12 07:33
Of course! I'm sure this will work as sdl2 alone recognizes controllers perfectly.

In a side note, I see some problems on Linux with HDMI audio and I will provide feedback on PR too

🤘

**Comment by albfan** [comment] 2021-04-13 07:02
@AcK77 I tested PR and almost fix this issue.

I reworked on top of it other ongoing features here: https://github.com/albfan/Ryujinx/ branch new-ryujinx

- I need to put a recent controller db to detect Joy-Con Left
- I filter IMU controllers as they are not needed for config a controller: https://github.com/albfan/Ryujinx/commit/90e73c271dac4275a2ea500f64e46c12bd101075

Plan to add button press animation to see the mapping, and try to load mapping from game controller

**Comment by BenGost** [comment] 2021-05-01 22:13
Hello :)

will the problem be solved? ideally it would take a function to add two controllers for a single player that would allow you to configure the two joycon.

Tankyou :)

**Comment by albfan** [comment] 2021-05-02 15:00
Currently there're two approaches:

- Add a device "Any" that allows to map several controllers to a player

- XJoy maps two controllers as one x360 controller: https://github.com/sam0x17/XJoy

- joycon driver maps two joycons as one and offer motion parameters. https://github.com/fossephate/JoyCon-Driver

None of them allows to map more than one pair of joycons, I'm working on it: https://github.com/sam0x17/XJoy/issues/57

**Comment by albfan** [comment] 2021-05-09 18:04
I fixed XJoy to allow to combine several pairs of joycons:  https://github.com/sam0x17/XJoy/pull/69

And rework a simple tool to test input: https://github.com/nenslen/xbox-360-controller-tester/pull/1

Input from 4 joycons (2 pair of combined controllers) works as expected, but configuring input on Ryujinx, the combined joycons as xbox 360 gets mad and becomes unusable) Ryujinx is doing something to detect input that corrupts the XJoy setup.

@BenGost I will keep fixing joycon-driver, as it provides motion input too, but something wrong is done for xbox 360 controllers

NOTE: single joycons (all 4) works correctly on riujinx)
NOTE2: A 8bitdo usb (providing a xbox 360 controller) works correctly too

**Comment by albfan** [comment] 2021-05-28 14:38
XJoy is fixed to pair several joycons: https://github.com/sam0x17/XJoy/pull/72

Still the ryujinx input conflicts with it. Making false positives on axis.

I tried with Betterjoy: https://github.com/Davidobot/BetterJoy and it has a feature that put in red joycons with duplicate timestamp.

My suspiction is that SDL2 conflicts with hidapi.

So the only option I see here is to allow a "any" device mapping double joycon with two isolated joycons.

**Comment by BenGost** [comment] 2021-05-28 14:55
@albfan 

> NOTE2: A 8bitdo usb (providing a xbox 360 controller) works correctly too

No, the 8Bitdo adapter allows you to connect only 1 joycon at the time. (no coupled joycon)

I had a conflict by going through it with Betterjoy, I had to uninstall everything and reboot the machine then reinstall everything and now it works perfectly.
For motions, only motions of a single joycon are recognized.

**Comment by albfan** [comment] 2021-05-28 16:07
Yes I just know about hidhide.

Whitelisting betterjoy and hiding all real joycons, xbox360 controllers works nice, and cemuhook too.

Seems would be plans to deal with this directly from Ryujinx (mix two joycons), that would be the better option. But this works (hidhide probably will help with any third party app to mix joycons)

**Comment by turntable97** [comment] 2021-07-17 15:05
Has there been found a workaround yet for using Dual Joy-Cons with motion controls to play Skyward Sword HD on Ryujinx?

**Comment by albfan** [comment] 2021-07-19 07:51
Betterjoy +hidhide offers you joycon buttons and axis and cemuhook for motion controls (from this video https://www.youtube.com/watch?v=SR00kYnphbQ looks like it only needs one joycon motion control as better joy provides)

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 01:22
Fixed by #2194.

**Closed by MetrosexualGarbodor** 2022-02-11 01:22 UTC
Labels: bug, input
