### ISSUE TITLE
Rendering glitches in SNACK WORLD: THE DUNGEON CRAWL — GOLD

### ISSUE THREAD

**Issue by Hootek** [Ryujinx/Ryujinx#3199] opened 2022-03-14 02:04 UTC
## Bug Report

Rendering glitches in SNACK WORLD: THE DUNGEON CRAWL — GOLD

### What's the issue you encountered?
![01](https://user-images.githubusercontent.com/42515119/158092238-6d21ad8a-b3e5-423c-97da-05b34e87f500.png)
![02](https://user-images.githubusercontent.com/42515119/158092242-e7a45498-8d13-4e5f-970e-e4f041dd3d32.png)

### How can the issue be reproduced?

It's all over the game, from the character creation menu to rendering during gameplay

### Log file

[Ryujinx_1.1.55_2022-03-13_22-46-06.log](https://github.com/Ryujinx/Ryujinx/files/8241205/Ryujinx_1.1.55_2022-03-13_22-46-06.log)

### Environment?

- Ryujinx version: 1.1.55</br>
- Game version: 1.0.0</br>

- System Specs:
  - OS: *Windows 11*
  - CPU: *i5-9300H*
  - GPU: *NVIDIA GTX 1650*
  - RAM: *16GB*
- Applied Mods : [No ]

**Comment by gdkchan** [comment] 2022-03-14 02:05
Duplicate of #2734.

**Closed by gdkchan** 2022-03-14 02:05 UTC
