### ISSUE TITLE
[Feature Request] iOS support

### ISSUE THREAD

**Issue by Iamthebestintheworld222** [Ryujinx/Ryujinx#5485] opened 2023-07-24 03:20 UTC
### Overview

Android has skyline, eggns, and yuzu, but mobile switch emulation on iOS is not available yet. Think you can join the mobile action and recode ryujinx to iOS.

### Smaller details

AltStore jit can be supported. I can play all of my favorite switch games on my phone.

### Nature of request

I would like to play switch games on my phone
I have a 14 pro max
A16, 6GB, 512GB, iOS16.5.1(c)

### Why would this feature be useful?

It would be great to have a switch emulator on iOS to catch up with android

**Comment by OldManKain** [comment] 2023-07-24 03:23
Duplicate of #4198

**Closed by OldManKain** 2023-07-24 03:23 UTC
