### ISSUE TITLE
Ryujinx on macOS 

### ISSUE THREAD

**Issue by joker5bb** [Ryujinx/Ryujinx#1072] opened 2020-03-30 17:08 UTC
ryujinx-1.0.4096-osx_x64
running macOS version 10.15.4
ryujinx simply crashes when running any of the homebrew games such as the mGBA

sudo ./Ryujinx
Password:

(Ryujinx:10726): Gtk-WARNING **: 12:09:07.859: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita

(Ryujinx:10726): Gtk-WARNING **: 12:10:40.423: Error loading theme icon 'view-refresh' for stock: Icon 'view-refresh' not present in theme Adwaita
00:00:00.302 | Application LoadApplication: Loading as homebrew.
00:00:00.330 | ServiceTime InitializeLocationNameCache: TimeZoneBinary system title not found! TimeZone conversions will not work, provide the system archive to fix this error. (See https://github.com/Ryujinx/Ryujinx#requirements for more information)
00:00:00.472 | Loader LoadStaticObjects: Loading image 0 at 0x0000000008000000...
00:00:00.879 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:01.087 | ServiceAm GetAppletResourceUserId: Stubbed. 
00:00:01.130 | ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.137 | ServiceAm SetFocusHandlingMode: Stubbed. 
00:00:01.139 | ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. 
00:00:01.175 | ServiceAm SetOperationModeChangedNotification: Stubbed. 
00:00:01.179 | ServiceAm SetPerformanceModeChangedNotification: Stubbed. 
00:00:01.211 | ServiceHid ActivateNpad: Stubbed. appletResourceUserId: 0
00:00:01.215 | ServiceHid SetSupportedNpadStyleSet: Stubbed. appletResourceUserId: 0 - _npadStyleSet: 1610612767
00:00:01.220 | ServiceHid SetSupportedNpadIdType: Stubbed. appletResourceUserId: 0 - npadIdType: ControllerPlayer1
00:00:01.221 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer1 - _npadJoyAssignmentMode: Dual
00:00:01.221 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer2 - _npadJoyAssignmentMode: Dual
00:00:01.221 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer3 - _npadJoyAssignmentMode: Dual
00:00:01.221 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer4 - _npadJoyAssignmentMode: Dual
00:00:01.222 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer5 - _npadJoyAssignmentMode: Dual
00:00:01.222 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer6 - _npadJoyAssignmentMode: Dual
00:00:01.222 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer7 - _npadJoyAssignmentMode: Dual
00:00:01.222 | ServiceHid SetNpadJoyAssignmentModeDual: Stubbed. appletResourceUserId: 0 - hidControllerId: ControllerPlayer8 - _npadJoyAssignmentMode: Dual
00:00:01.226 | ServiceHid SetNpadJoyHoldType: Stubbed. appletResourceUserId: 0 - _npadJoyHoldType: Vertical
00:00:01.497 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:01.575 | ServiceVi CreateStrayLayer: Stubbed. 
00:00:02.350 | ServiceBsd RegisterClient: Stubbed. 
00:00:02.367 | ServiceBsd StartMonitoring: Stubbed. unknown0: 0
00:00:02.922 | ServiceNv InitializeEx: Stubbed. 
00:00:03.009 | ServiceNv Create: Created map 1 with size 0x00080000!
00:00:03.027 | ServiceNv Create: Created map 2 with size 0x00080000!
00:00:03.031 | ServiceNv Create: Created map 3 with size 0x00080000!
00:00:03.035 | ServiceNv Create: Created map 4 with size 0x00080000!
00:00:03.040 | ServiceNv Create: Created map 5 with size 0x00001000!
00:00:03.040 | ServiceNv Create: Created map 6 with size 0x00001000!
00:00:03.052 | ServiceNv SetNvMapFd: Stubbed. 
00:00:03.053 | ServiceNv BindChannel: Stubbed. 
00:00:03.055 | ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:03.056 | ServiceNv AllocObjCtx: Stubbed. 
00:00:03.075 | ServiceNv SetErrorNotifier: Stubbed. 
00:00:03.077 | ServiceNv SetPriority: Stubbed. 
00:00:03.079 | ServiceNv ZcullBind: Stubbed. 
00:00:03.088 | ServiceNv Create: Created map 7 with size 0x00001000!
00:00:03.789 | ServiceNv Create: Created map 8 with size 0x00080000!
00:00:03.811 | ServiceNv Create: Created map 9 with size 0x000d0000!
00:00:03.881 | ServiceNv Create: Created map 10 with size 0x04080000!
00:00:04.257 | ServiceNv Create: Created map 11 with size 0x00020000!
00:00:04.876 | ServiceNv Create: Created map 12 with size 0x00870000!
00:00:04.943 | ServiceNv Create: Created map 13 with size 0x00870000!
00:00:04.988 | ServiceNv Create: Created map 14 with size 0x00870000!
00:00:07.262 | ServiceNv Create: Created map 15 with size 0x00080000!
00:00:13.784 | ServiceNv Create: Created map 16 with size 0x00040000!
00:00:13.861 | ServiceNv Create: Created map 17 with size 0x00040000!
00:00:20.185 | ServiceNv Create: Created map 18 with size 0x00001000!
00:00:20.244 | ServiceNv Create: Created map 19 with size 0x00100000!
00:00:20.291 | ServiceNv Create: Created map 20 with size 0x00040000!
00:00:20.308 | ServiceNv Create: Created map 21 with size 0x00040000!
00:00:20.486 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:20.487 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:20.487 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:20.487 | HLE.HostThread.0 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:20.489 | ServiceHid StartSixAxisSensor: Stubbed. appletResourceUserId: 0 - sixAxisSensorHandle: 5
00:00:20.489 | ServiceHid StartSixAxisSensor: Stubbed. appletResourceUserId: 0 - sixAxisSensorHandle: 65541
00:00:20.489 | ServiceHid StartSixAxisSensor: Stubbed. appletResourceUserId: 0 - sixAxisSensorHandle: 131075
00:00:20.489 | ServiceHid StartSixAxisSensor: Stubbed. appletResourceUserId: 0 - sixAxisSensorHandle: 139268
00:00:20.554 | Emulation CurrentDomain_UnhandledException: Unhandled exception caught: Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 67

Guest Stack Trace:
Process: mGBA, PID: 81
   rtld:0x0000940c Sub000000000800940c
   rtld:0x000009fc Sub00000000080009fc
   rtld:0x00000338 Sub0000000008000338

Raw Request Data:
00000000   01 00 10 00 06 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  43 00 00 00 00 00 00 00   SFCI····C·······
00000020   04 20 02 00 00 00 00 00  00 00 00 00 00 00 00 00   · ··············

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Unhandled exception. Ryujinx.HLE.Exceptions.ServiceNotImplementedException: Ryujinx.HLE.HOS.Services.Am.AppletAE.AllSystemAppletProxiesService.SystemAppletProxy.ISelfController: 67

Guest Stack Trace:
Process: mGBA, PID: 81
   rtld:0x0000940c Sub000000000800940c
   rtld:0x000009fc Sub00000000080009fc
   rtld:0x00000338 Sub0000000008000338

Raw Request Data:
00000000   01 00 10 00 06 00 00 00  00 00 00 00 00 00 00 00   ················
00000010   53 46 43 49 00 00 00 00  43 00 00 00 00 00 00 00   SFCI····C·······
00000020   04 20 02 00 00 00 00 00  00 00 00 00 00 00 00 00   · ··············

   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 95
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, MemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 110
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 169
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
Abort trap: 6

**Comment by IvarWithoutBones** [comment] 2020-03-30 17:23
That's an unimplemented service, you can enable the option to ignore those in the settings.

**Comment by Ghostotakoi** [comment] 2020-03-31 01:55
Mac OS.... BAD FOR EMULATION AND GENERAL GAMING. why people still don´t know this... most you can do on ryu with mac is some scrolling games and homebrew no matter how powerfull your mac is, the problem is the OS not the specs.

**Comment by AcK77** [comment] 2020-03-31 20:59
Closed in favor of #348

**Closed by AcK77** 2020-03-31 20:59 UTC

**Comment by DrHacknik** [comment] 2020-04-28 15:05
> > That's an unimplemented service, you can enable the option to ignore those in the settings.
> 
> How do I do that?

This isn't the place to ask questions like that. Enable missing services. But next time ask questions on our Discord server and not here.
