### ISSUE TITLE
시작이 안됨

### ISSUE THREAD

**Issue by Minyound** [Ryujinx/Ryujinx#2562] opened 2021-08-17 12:25 UTC
## Bug Report
![D00D181A-DAB9-4CB8-B96D-9EF0781A2D4A](https://user-images.githubusercontent.com/88719375/129725205-3e66ca05-f1fd-436a-8058-828108357c72.jpeg)
시작하는중애 자꾸 작동이 중지됩니다
어떻게해야 하나요?
[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br>
[ Did you make any changes related to Ryujinx itself? ]</br>
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.X</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. i7-6700)*
  - GPU: *(e.g. NVIDIA RTX 2070)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by Niwu34** [comment] 2021-08-17 12:33
duplicate of #2558 
the fix:
> Delete the `%appdata%\Ryujinx\sdcard\Nintendo` directory

**Comment by gdkchan** [comment] 2021-08-17 17:05
Closing as duplicate.

**Closed by gdkchan** 2021-08-17 17:05 UTC
