### ISSUE TITLE
Mouse panning [Feature Request]

### ISSUE THREAD

**Issue by Garou312** [Ryujinx/Ryujinx#6492] opened 2024-03-14 18:50 UTC
### Overview

Mouse Panning is the feature from with we can use our mouse cursor in game.

### Smaller details

Mouse Panning

### Nature of request

Feature

### Why would this feature be useful?

This will be very useful for all pc gamers all, as ryujinx is made for pc, it would be nice with mouse panning.

**Comment by MutantAura** [comment] 2024-03-14 18:51
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2063

**Closed by MutantAura** 2024-03-14 18:51 UTC
