### ISSUE TITLE
[Bug] Paper Mario TTYD crashing on start.

### ISSUE THREAD

**Issue by Artr7** [Ryujinx/Ryujinx#6968] opened 2024-06-22 15:43 UTC
### Description of the issue

The game crashes immediately when starting. It's similar to [this error](https://github.com/Ryujinx/Ryujinx/wiki/FAQ-and-Troubleshooting#-e-hleguestthread20-cpu-invalidaccesshandler-invalid-memory-access-at-virtual-address-0x0000000000000000-e-hleguestthread20-application--unhandled-exception-caught-ryujinxmemoryinvalidmemoryregionexception-attempted-to-access-an-invalid-memory-region) but no mods/cheats are installed. Other games work perfectly. 

### Reproduction steps

Just starting the game. Crashes before/when the red nintendo screen appears.

### Log file

[Ryujinx_1.1.1336_2024-06-22_13-39-21.log](https://github.com/user-attachments/files/15937275/Ryujinx_1.1.1336_2024-06-22_13-39-21.log)

### OS

Windows 10

### Ryujinx version

1.1.1336

### Game version

1.0

### CPU

i5-13600KF

### GPU

AMD AMD Radeon RX 7900 XT 

### RAM

32 GB

### List of applied mods

0. They are not deactived since I never installed them. 

### Additional context?

Just in case: had mods installed when I tried the game on Yuzu but now I deleted all, when I moved to Ryujinx.

**Comment by c-eid** [comment] 2024-06-22 20:46
Same issue with 5800x3d and rtx3080 windows 11. No mods installed.

**Comment by piplup55** [comment] 2024-06-23 07:19
duplicate of #6964

**Closed by piplup55** 2024-06-23 07:19 UTC
Labels: bug
