### ISSUE TITLE
Flatpak package

### ISSUE THREAD

**Issue by someone423** [Ryujinx/Ryujinx#2524] opened 2021-08-02 16:10 UTC
### What feature are you suggesting?
Make a flatpak package for ryujinx, available in a flatpak repo(e.g. flathub). 

### Why would this feature be useful?
This will make install and update easier for end user.

**Comment by choppymaster** [comment] 2021-08-03 10:18
Duplicate of #1077 / #2492

**Comment by gdkchan** [comment] 2021-08-04 17:16
Closing as duplicate.

**Closed by gdkchan** 2021-08-04 17:16 UTC
