### ISSUE TITLE
No More Heroes 3 Video Cutscene Playback Issue

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2656] opened 2021-09-18 22:38 UTC
### What's the issue you encountered?

At a certain point in one of the cutscenes after killing the first boss (Mr. Blackhole), when the game is supposed to play a pre-recorded video instead of rendering in-game, the game appears to have trouble choosing the right video, causing it to glitch out and overlay the videos on each other. This happens again a little later when another pre-recorded video is supposed to play.

### How can the issue be reproduced?

Watch the cutscenes after killing Mr. Blackhole.

### Environment?

- Ryujinx version: 1.0.7047
- Game version: 1.0.1
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Video Example:
https://www.youtube.com/watch?v=kIE0QZrZlUk

Here is the log file:
[video issue.log](https://github.com/Ryujinx/Ryujinx/files/7192915/video.issue.log)

**Comment by gdkchan** [comment] 2021-09-18 22:43
Possibly a duplicate of #2077?

**Comment by NikkMann** [comment] 2021-09-18 23:15
Here's the mediainfo for the dumped movie files
![Screenshot 2021-09-18 181503](https://user-images.githubusercontent.com/90150509/133910846-be735a18-e740-459f-a55a-152550aaa88c.png)

**Comment by NikkMann** [comment] 2021-09-19 21:03
uploaded log

**Comment by gdkchan** [comment] 2021-09-20 18:41
Can you check if #2671 fixes the issue?

**Comment by NikkMann** [comment] 2021-09-20 20:21
> Can you check if #2671 fixes the issue?

It did, but now after the video that glitched before finishes, the game crashes. 
Here's the log.
[Ryujinx_1.0.0+5392113_2021-09-20_15-08-25.log](https://github.com/Ryujinx/Ryujinx/files/7198536/Ryujinx_1.0.0%2B5392113_2021-09-20_15-08-25.log)

**Comment by gdkchan** [comment] 2021-09-20 20:27
Nothing in this log indicates a crash. Did it print anything on the console?

**Comment by GamerzHell9137** [comment] 2021-09-20 20:30
@NikkMann Can you send your save so i can test it too?

**Comment by NikkMann** [comment] 2021-09-20 20:33
I wasn't looking at the console when it happened, and sure, heres my save. Load up the Inner UFO one that has 15 minutes playtime on it, then fight and beat all phases of the mr.blackhole bossfight. You can skip all the cutscenes after that until you get to the one that starts with Fu and Damon standing on the skyscraper. Then you've gotta watch that cutscene for around 3 or 4 minutes until it gets to the part where someone launches missiles at the skyscraper and Fu throws them back. The video right after that shows some russia-looking place getting blown up by the missiles. Thats the one that glitched out before and works now, but it crashes right after.
[JCTSaveSlot.zip](https://github.com/Ryujinx/Ryujinx/files/7198582/JCTSaveSlot.zip)

**Comment by NikkMann** [comment] 2021-09-20 20:33
I'll give it another run myself here in a bit too.

**Comment by NikkMann** [comment] 2021-09-20 21:37
Did it again, froze and crashed at the same spot. Nothing red or abnormal came up in the console, it just kind of stopped.

**Comment by gdkchan** [comment] 2021-09-20 21:40
Look at the event viewer, it will have the crash reason. You don't need to launch the game again to view it.

**Comment by NikkMann** [comment] 2021-09-20 21:42
![image](https://user-images.githubusercontent.com/90150509/134079814-0deb6151-cfbe-4346-a232-d1b3f81a246a.png)

**Comment by gdkchan** [comment] 2021-09-20 21:44
This is not the event viewer. I was talking about the Windows event viewer.

**Comment by NikkMann** [comment] 2021-09-20 21:46
How do you get to it

**Comment by gdkchan** [comment] 2021-09-21 00:17
I believe it's fixed now.

**Comment by NikkMann** [comment] 2021-09-21 00:31
> I believe it's fixed now.

Another PR build or in the main build?

**Comment by gdkchan** [comment] 2021-09-21 00:35
Same PR, the build links are updated automatically.

**Comment by NikkMann** [comment] 2021-09-21 01:19
Yep, looks like that fixed it. Nice job!

**Comment by gdkchan** [comment] 2021-09-21 01:20
Thanks for testing, must be annoying to play the same section over and over again 😅

**Comment by NikkMann** [comment] 2021-09-21 01:23
Hmm, now I just had an issue where an in-game cutscene a bit after the video cutscene was just a black screen, but I could hear the audio and subtitles were playing. If I load into a save directly before the in-game cutscene though, it works fine. It only glitched out after watching the video.
[Ryujinx_1.0.0+8bd528e_2021-09-20_20-08-58 - Copy.log](https://github.com/Ryujinx/Ryujinx/files/7199528/Ryujinx_1.0.0%2B8bd528e_2021-09-20_20-08-58.-.Copy.log)

**Comment by NikkMann** [comment] 2021-09-21 22:20
Tried the new PR and also retsarted my comp for good measure. Looks like the issues fixed :)

**Closed** 2021-09-28 22:43 UTC
Labels: bug, nvdec
