### ISSUE TITLE
Crash on Pokemon BDSP when talking to underground trader

### ISSUE THREAD

**Issue by RBNXI** [Ryujinx/Ryujinx#2898] opened 2021-12-03 22:29 UTC
In Pokemon Brilliant Diamond and Shining Pearl, when talking to a trader in the underground, if you select the first option to trade spheres, the game crashes with this output:

Unhandled exception. Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise)
Killed

- Ryujinx version: Tried with the 3 latest, and ldn2.4
- Game version: 1.1.1
- System Specs:
Operating System: Linux 5.4.150-1-MANJARO 
CPU: Intel(R) Core(TM) i7-4790K CPU @ 4.00GHz ; 8 logical
RAM: Total 15847 MB ; Available 9354 MB
GPU: Nvidia GTX 1060 - 6GB
- Applied Mods : No

**Comment by Beanow** [comment] 2021-12-15 17:59
Not sure which first option you mean, but I'm guessing when you're choosing between buying or selling?
I've had no issues trading (or performing glitches) with either the small or large sphere traders. Either on 1.1.1 or 1.1.2 of the game. Also Manjaro, but on AMD CPU/GPU.

![image](https://user-images.githubusercontent.com/497556/146239522-f328716a-0d11-4d1a-937d-1f9382d7cbf2.png)

`InvalidMemoryRegionException` is a pretty generic error, and could even be caused by the game (like one of the many crashes you can cause when doing glitches in DBSP). So you'll probably want to share the rest of your logs, which would include as well what memory management mode you're in.

**Comment by RBNXI** [comment] 2021-12-15 18:29
Yes, I mean the option to buy.
I don't know why it happens, but the game works PERFECT apart from that crash, it's weird.

The log is this: 

00:03:23.117 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 47!
00:03:34.380 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 31!
00:03:34.382 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 32!
00:03:34.383 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 30!
00:03:34.383 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 22!
00:03:36.093 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 309201 bytes, profiled functions: 88488).
00:03:42.649 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 46!
00:03:42.919 |I| HLE.OsThread.9 ServiceNv Create: Created map 22 with size 0x02000000!
00:03:54.672 |I| Application VSyncStatus_Clicked: VSync toggled to: True
00:04:14.273 |I| Configuration LogValueChange: EnableVsync set to: True
00:05:03.662 |I| HLE.GuestThread.14 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 91
   0x000000000a222bf4	main:0x221ebf4	
   0x000000000aaf6ec0	main:0x2af2ec0	
   0x00000000081826dc	main:0x17e6dc	
   0x0000000008057dc0	main:0x53dc0	
   0x00000000082d9820	main:0x2d5820	
   0x00000000082c6e1c	main:0x2c2e1c	
   0x00000000089632f0	main:0x95f2f0	
   0x0000000008962eb0	main:0x95eeb0	
   0x0000000008960250	main:0x95c250	
   0x00000000089605d8	main:0x95c5d8	
   0x0000000008e17ad8	main:0xe13ad8	
   0x0000000009a95bd0	main:0x1a91bd0	
   0x000000000aaf6ec0	main:0x2af2ec0	
   0x00000000081826dc	main:0x17e6dc	
   0x0000000008057dc0	main:0x53dc0	
   0x00000000082d9820	main:0x2d5820	
   0x00000000082c6e1c	main:0x2c2e1c	
   0x00000000089632f0	main:0x95f2f0	
   0x0000000008962eb0	main:0x95eeb0	
   0x0000000008960250	main:0x95c250	
   0x00000000089605d8	main:0x95c5d8	
   0x0000000008e17ad8	main:0xe13ad8	
   0x0000000009a92030	main:0x1a8e030	
   0x000000000a6cbfd4	main:0x26c7fd4	
   0x000000000a596fe4	main:0x2592fe4	
   0x000000000aaf6ec0	main:0x2af2ec0	
   0x00000000081826dc	main:0x17e6dc	
   0x0000000008057dc0	main:0x53dc0	
   0x00000000082d9820	main:0x2d5820	
   0x00000000082c6e1c	main:0x2c2e1c	
   0x00000000089632f0	main:0x95f2f0	
   0x0000000008962eb0	main:0x95eeb0	
   0x0000000008962f54	main:0x95ef54	
   0x0000000008962f54	main:0x95ef54	
   0x00000000084c462c	main:0x4c062c	
   0x0000000008376594	main:0x372594	
   0x000000000837655c	main:0x37255c	
   0x00000000083768b0	main:0x3728b0	
   0x00000000082c4c40	main:0x2c0c40	nnMain:0x0680
   0x000000000d9754c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:05:03.668 |I| HLE.GuestThread.14 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x000000000000000c
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x000000000b9d6b42
	X[06]:	0x0000000000000000
	X[07]:	0x000000000000004e
	X[08]:	0x00000000fffffffd
	X[09]:	0x0000000100000000
	X[10]:	0x0000001b00000000
	X[11]:	0x0000000000000000
	X[12]:	0x0000000000000001
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000001
	X[16]:	0x000000000e3357d8
	X[17]:	0x000000000da16810 (sdk:0x351810)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x0000001670f5bc00
	X[19]:	0x00000016592a00d0
	X[20]:	0x0000000000000000
	X[21]:	0x0000000000000000
	X[22]:	0x00000000ffffffff
	X[23]:	0x0000000000000002
	X[24]:	0x0000000000000000
	X[25]:	0x00000016554342d0
	X[26]:	0x00000049f0908628 (SP:-0x09a8)
	X[27]:	0x0000000000000000
	X[28]:	0x0000000008962df8 (main:0x95edf8)	=> 
	FP:	0x00000049f0907cb0 (SP:-0x0030)
	LR:	0x0000000009d142d0 (main:0x1d102d0)	=> 
	SP:	0x00000049f0907c80 (SP)
	PC:	0x0000000000000000


00:05:03.668 |E| HLE.GuestThread.14 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:05:03.757 |E| HLE.GuestThread.14 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in C:\projects\ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 220

**Comment by RBNXI** [comment] 2021-12-15 18:40
I just tried Memory Manager Mode Host (the safe one) and it crashes too.

**Comment by Beanow** [comment] 2021-12-15 19:43
Well `Invalid memory access at virtual address 0x0000000000000000` seems like a null pointer issue. And judging by how it's `HLE.GuestThread.14 Cpu` spitting that out, I assume that should be interpreted as the game triggering it.

I'd ask normally, if you happen to be using glitched pokemon or menu glitches. But even then it's quite weird to have this problem on the buy/sell menu of the trader! Not sure what this is about.

**Comment by RBNXI** [comment] 2021-12-15 19:45
I haven't used any glitch or something similar. Also, I can sell, the only problem is buying.

**Comment by Beanow** [comment] 2021-12-15 19:56
> I haven't used any glitch or something similar. Also, I can sell, the only problem is buying.

Haha well, that specific buy menu (sell menu is fine) also has a money duping glitch on retail hardware, so you never know with this game. I doubt v1.1.2 of the game or FW 13.2.0 is likely to address it, but what you could try is updating to the latest Ryujinx release. Log says you're on `1.0.7113` which is two weeks or so old.

**Comment by RBNXI** [comment] 2021-12-15 20:15
I just tried newer version of Ryujinx and 1.1.2 and still crashes. I'll try new firmware when I can access the emulator menu (because I currently have a bug that happens some times that hides all the menus from me because of some kwin problem until I restart)
![Screenshot_20211215_210633](https://user-images.githubusercontent.com/35869848/146257397-505648d7-62e2-4544-950b-ef3bdfd26d76.png)

- I have a "é" in the path of the game and updates, and also with symbolic links. 
- I play the game in spanish but have console in english.  
- I play at 60fps with vsync.
Could something of that be causing the crash?
This is my config (just in case):
```
{
  "version": 32,
  "enable_file_log": false,
  "backend_threading": "Auto",
  "res_scale": 2,
  "res_scale_custom": 1,
  "max_anisotropy": 2,
  "aspect_ratio": "Fixed16x9",
  "graphics_shaders_dump_path": "",
  "logging_enable_debug": false,
  "logging_enable_stub": false,
  "logging_enable_info": false,
  "logging_enable_warn": false,
  "logging_enable_error": false,
  "logging_enable_guest": false,
  "logging_enable_fs_access_log": false,
  "logging_filtered_classes": [],
  "logging_graphics_debug_level": "None",
  "system_language": "AmericanEnglish",
  "system_region": "USA",
  "system_time_zone": "UTC",
  "system_time_offset": 0,
  "docked_mode": true,
  "enable_discord_integration": false,
  "check_updates_on_start": false,
  "show_confirm_exit": true,
  "hide_cursor_on_idle": false,
  "enable_vsync": true,
  "enable_shader_cache": true,
  "enable_multicore_scheduling": false,
  "enable_ptc": true,
  "enable_fs_integrity_checks": true,
  "fs_global_access_log_mode": 0,
  "audio_backend": "SDL2",
  "memory_manager_mode": "HostMapped",
  "expand_ram": false,
  "ignore_missing_services": false,
  "gui_columns": {
    "fav_column": true,
    "icon_column": true,
    "app_column": true,
    "dev_column": true,
    "version_column": true,
    "time_played_column": true,
    "last_played_column": true,
    "file_ext_column": true,
    "file_size_column": true,
    "path_column": true
  },
  "column_sort": {
    "sort_column_id": 0,
    "sort_ascending": false
  },
  "game_dirs": [
    "/run/media/ruben/Rub\u00E9n/Users/Rubén/LinuxLinks/yuzu/Games/"
  ],
  "enable_custom_theme": false,
  "custom_theme_path": "",
  "start_fullscreen": false,
  "enable_keyboard": false,
  "enable_mouse": false,
  "hotkeys": {
    "toggle_vsync": "Tab",
    "screenshot": "F8",
    "show_ui": "F4",
    "pause": "F5"
  },
  "keyboard_config": [],
  "controller_config": [],
  "input_config": [
    {
      "left_joycon_stick": {
        "joystick": "Left",
        "invert_stick_x": false,
        "invert_stick_y": false,
        "stick_button": "LeftStick"
      },
      "right_joycon_stick": {
        "joystick": "Right",
        "invert_stick_x": false,
        "invert_stick_y": false,
        "stick_button": "RightStick"
      },
      "deadzone_left": 0.05,
      "deadzone_right": 0.05,
      "trigger_threshold": 0,
      "motion": {
        "motion_backend": "GamepadDriver",
        "sensitivity": 100,
        "gyro_deadzone": 1,
        "enable_motion": false
      },
      "rumble": {
        "strong_rumble": 1,
        "weak_rumble": 1,
        "enable_rumble": false
      },
      "left_joycon": {
        "button_minus": "Minus",
        "button_l": "LeftShoulder",
        "button_zl": "LeftTrigger",
        "button_sl": "Unbound",
        "button_sr": "Unbound",
        "dpad_up": "DpadUp",
        "dpad_down": "DpadDown",
        "dpad_left": "DpadLeft",
        "dpad_right": "DpadRight"
      },
      "right_joycon": {
        "button_plus": "Plus",
        "button_r": "RightShoulder",
        "button_zr": "RightTrigger",
        "button_sl": "Unbound",
        "button_sr": "Unbound",
        "button_x": "Y",
        "button_b": "A",
        "button_y": "X",
        "button_a": "B"
      },
      "version": 1,
      "backend": "GamepadSDL2",
      "id": "0-00000003-20d6-0000-1520-000001010000",
      "controller_type": "ProController",
      "player_index": "Player1"
    }
  ]
}
```

**Comment by Beanow** [comment] 2021-12-15 20:23
> I play at 60fps with vsync.
Could something of that be causing the crash?

Worth trying this one :shrug:.

I use basically all the default / native settings for this game, as it seems to have some kind of internal resolution scaling so the graphical settings don't make a difference besides text. And with 60FPS I had issues with NPCs walking faster than normal, though I haven't tested it in a while.

**Comment by RBNXI** [comment] 2021-12-15 20:52
I tried no vsync (30fps) and a savedata from internet (english version of SP) and it still crashes...

**Comment by Beanow** [comment] 2021-12-15 20:55
Well that's about all I can think of for now. Will have to wait for someone who knows more than I do I suppose.

**Comment by RBNXI** [comment] 2021-12-15 20:58
Thanks a lot anyways!.

**Comment by Beanow** [comment] 2021-12-16 15:43
So I had a similar crash now way into post game (menu glitching after catching rotom). I'll have to see if I can reproduce it.

```

00:02:48.621 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x000000000aa2e160	main:0x2a2a160	
   0x00000000080e78dc	main:0xe38dc	
   0x0000000008273770	main:0x26f770	
   0x00000000082d9830	main:0x2d5830	
   0x00000000082c6e2c	main:0x2c2e2c	
   0x0000000008963300	main:0x95f300	
   0x0000000008962ec0	main:0x95eec0	
   0x0000000008960260	main:0x95c260	
   0x00000000089605e8	main:0x95c5e8	
   0x0000000008e17ae8	main:0xe13ae8	
   0x000000000ac5f540	main:0x2c5b540	
   0x000000000aa2e160	main:0x2a2a160	
   0x00000000080e78dc	main:0xe38dc	
   0x0000000008273770	main:0x26f770	
   0x00000000082d9830	main:0x2d5830	
   0x00000000082c6e2c	main:0x2c2e2c	
   0x0000000008963300	main:0x95f300	
   0x0000000008962ec0	main:0x95eec0	
   0x0000000008960260	main:0x95c260	
   0x00000000089605e8	main:0x95c5e8	
   0x0000000008e17ae8	main:0xe13ae8	
   0x000000000ac5b9a0	main:0x2c579a0	
   0x0000000009756080	main:0x1752080	
   0x0000000009756af4	main:0x1752af4	
   0x0000000009743a5c	main:0x173fa5c	
   0x000000000974456c	main:0x174056c	
   0x00000000098328b8	main:0x182e8b8	
   0x000000000ac5cc6c	main:0x2c58c6c	
   0x000000000ac5cb90	main:0x2c58b90	
   0x00000000080d5d34	main:0xd1d34	
   0x0000000008273770	main:0x26f770	
   0x00000000082d9830	main:0x2d5830	
   0x00000000082c6e2c	main:0x2c2e2c	
   0x0000000008960000	main:0x95c000	
   0x00000000084c721c	main:0x4c321c	
   0x00000000083765a4	main:0x3725a4	
   0x000000000837656c	main:0x37256c	
   0x00000000083768c0	main:0x3728c0	
   0x00000000082c4c50	main:0x2c0c50	nnMain:0x0680
   0x000000000d9754c4	sdk:0x2b04c4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4	rtld:0x00d4	


00:02:48.622 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x0000001672efc800
	X[03]:	0x0000000009f3ba80 (main:0x1f37a80)	=> 
	X[04]:	0x00000015c5490698
	X[05]:	0x000000000a916820 (main:0x2912820)	=> 
	X[06]:	0x000000000ac3b820 (main:0x2c37820)	=> 
	X[07]:	0x00000049f0908360 (SP:-0x07b0)
	X[08]:	0x0000000000000000
	X[09]:	0x0000000000000080
	X[10]:	0x00000000000001e0
	X[11]:	0x0000000000000000
	X[12]:	0x0000000000000001
	X[13]:	0x00000015c0756cb0
	X[14]:	0x0000000000000005
	X[15]:	0x000000000cc95538
	X[16]:	0x000000000e3357d8
	X[17]:	0x000000000da16810 (sdk:0x351810)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x00000015cfa22b00
	X[19]:	0x00000016449f42a0
	X[20]:	0x000000165bfe5000
	X[21]:	0x0000001660db92b8
	X[22]:	0x00000016446c3200
	X[23]:	0x000000163b7ec100
	X[24]:	0x0000000000000000
	X[25]:	0x00000015d0d38190
	X[26]:	0x0000000000001386
	X[27]:	0x000000000cc25800
	X[28]:	0x0000000000000004
	FP:	0x00000049f0907be0 (SP:-0x0030)
	LR:	0x0000000009a9f914 (main:0x1a9b914)	=> 
	SP:	0x00000049f0907bb0 (SP)
	PC:	0x0000000000000000


00:02:48.622 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:02:48.625 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise)
```

**Comment by B3astTech** [comment] 2022-01-24 19:33
## Bug Report

### What's the issue you encountered?

None

### How can the issue be reproduced?

I did what I seen to attempt to reproduce the issue but it never crashed on me. if anyone else could try please do.

![Screenshot from 2022-01-24 14-22-45](https://user-images.githubusercontent.com/45114656/150850607-3dd276c0-0603-4e56-8c6d-0ec9cba0682d.png)


![Screenshot from 2022-01-24 14-23-04](https://user-images.githubusercontent.com/45114656/150850626-c4e85452-f367-49e3-8a32-a869a6a03247.png)

![Screenshot from 2022-01-24 14-23-26](https://user-images.githubusercontent.com/45114656/150850634-0f02b1d7-f6fc-4439-83e9-2f495d5e1f58.png)

![Screenshot from 2022-01-24 14-23-40](https://user-images.githubusercontent.com/45114656/150850646-f4418c4d-ac75-4173-94bb-eab83e21e860.png)

![Screenshot from 2022-01-24 14-23-59](https://user-images.githubusercontent.com/45114656/150850671-2a35e11b-fae5-4e26-b13f-7e7ffb259278.png)

### Log file

[Ryujinx_1.1.8.log](https://github.com/Ryujinx/Ryujinx/files/7928322/Ryujinx_1.1.8.log)


### Environment?

- Ryujinx version: 1.1.8</br>
- Game version: 1.1.1</br>

- System Specs:
  - OS: *Fedora 35*
  - CPU: *i7-2600k*
  - GPU: *1050ti*
  - RAM: *16GB*
- Applied Mods : [N/A]

### Additional context?

Additional info about your environment:</br>

I bought items in succession one after another and to no avail any issues come up

**Comment by GamerzHell9137** [comment] 2022-02-11 14:02
@Beanow @RBNXI Is it still happening? Also i can't reproduce it either. If you still can drop us your saves so we can check.

**Comment by MetrosexualGarbodor** [comment] 2022-04-22 09:12
Closing this as no one has reported it in months and there's 2 reports of it being fixed.

**Closed by MetrosexualGarbodor** 2022-04-22 09:12 UTC
Labels: bug
