### ISSUE TITLE
[Feature Request] Restart or Reoload the game

### ISSUE THREAD

**Issue by IshanChakraborty96** [Ryujinx/Ryujinx#6076] opened 2023-12-30 17:44 UTC
### Overview

Currently, I am just looking and able to see only pause and stop
it will be really helpful if there is a restart option is there

### Smaller details

Sometimes I need to restart the game but now I need to stop and start the game again and it also takes some time to boot up or start that's a waste of time for users like us.

![image](https://github.com/Ryujinx/Ryujinx/assets/91935558/9a3f01a1-6ef9-42f6-a335-e17cb5edb071)

### Nature of request

![image](https://github.com/Ryujinx/Ryujinx/assets/91935558/a1a07719-0ac7-4cee-9bbe-af89aafb5c10)

### Why would this feature be useful?

Sometimes I need to restart the game but now I need to stop and start the game again and it also takes some time to boot up or start that's a waste of time for users like us.

**Comment by rmg-x** [comment] 2023-12-31 16:16
Duplicate of #2974 ?

**Comment by MutantAura** [comment] 2024-01-03 11:43
Duplicate of #2974

**Closed by MutantAura** 2024-01-03 11:43 UTC
