### ISSUE TITLE
Sight through the gyroscope jumps

### ISSUE THREAD

**Issue by katatin31** [Ryujinx/Ryujinx#3977] opened 2022-12-01 18:14 UTC
Gyro aiming jumps in games. I encountered such a problem in the games "splatoon 2, 3" and "BOTW". There is a problem with the standard use of the gyroscope as well as with the help of betterjoy. For the game, the gamepad "gamesir t4 pro" is used in the "pro controller" mode.

https://user-images.githubusercontent.com/101261355/205129054-f1fa4e4d-3e41-4d70-9550-e9f5da1c0183.mp4

**Comment by Serfrost** [comment] 2022-12-02 07:41
Likely a duplicate of #2765 in relation to [#2632](https://github.com/Ryujinx/Ryujinx/pull/2632)

**Comment by katatin31** [comment] 2022-12-05 09:57
> Likely a duplicate of #2765 in relation to [#2632](https://github.com/Ryujinx/Ryujinx/pull/2632)

yes, it seems that the problem is not solved

**Comment by katatin31** [comment] 2022-12-05 11:57
Using ds4windows can solve the problem, but I would like to have the gyroscope work by default, without using additional programs

**Comment by MutantAura** [comment] 2022-12-05 11:59
Duplicate of #2765

**Closed by MutantAura** 2022-12-05 11:59 UTC

**Comment by jesrric17** [comment] 2022-12-06 13:18
Hi
how can i make the gyro work with my dualsense

**Comment by katatin31** [comment] 2022-12-06 13:46
> Привет , как я могу заставить гироскоп работать с моим DualSense


https://user-images.githubusercontent.com/101261355/205928812-981ca768-8793-446f-b703-209673e3413a.mp4

use "DS4Windows" and try to do as I did in the video, hope it helps

**Comment by jesrric17** [comment] 2022-12-07 00:42
> > Hola 
> > , ¿cómo puedo hacer que el giroscopio funcione con mi dualsense?
> 
>  bandicam.2022-12-06.16-43-16-639.mp4 
> hola, use "DS4Windows" e intente hacer lo que hice en el video, espero que ayude

Thanks, I did everything you told me but it didn't work, could you tell me how you have the profile configuration please?

**Comment by katatin31** [comment] 2022-12-07 07:19
how the profile is configured in "ds4windows" or in "Ryujinx"?

**Comment by katatin31** [comment] 2022-12-07 07:29
[PadTest_1011.zip](https://github.com/Ryujinx/Ryujinx/files/10173699/PadTest_1011.zip)
try to write data in this program as in the video, the program should show the position of the gamepad in space

**Comment by jesrric17** [comment] 2022-12-07 10:43
> como se configura el perfil en "ds4windows" o en "Ryujinx"?

ds4windows please
