### ISSUE TITLE
When DLC moved to new location game crashes, DLC menu crashes too

### ISSUE THREAD

**Issue by Denadan** [Ryujinx/Ryujinx#2322] opened 2021-05-29 11:44 UTC
### What's the issue you encountered?

I Start to organise my dlc/update to separate folder and after that games that have installed DLC moved failed to load. Also DLC menu dont open too. they throw TargetInvocationException in console
Games without dlc installed not affected. Title Updates menu work correctly removing missing update

### How can the issue be reproduced?

Install DLC to any game
remove DLC file

tested on Animal Crossing New Horisonts, Monster Hunter Rise.

### Log file

log for  Animal Crossing

[Ryujinx_1.0.0-ldn2.3_2021-05-29_14-34-55.log](https://github.com/Ryujinx/Ryujinx/files/6564593/Ryujinx_1.0.0-ldn2.3_2021-05-29_14-34-55.log)

### Environment?

- Ryujinx version: LDN 2.3</br>
- Game version: 1.10.0( Animal Crossing) 3.0.0 (MH Rise)</br>
- System Specs:
  - OS: Windows 10
  - CPU:. i5-3320
  - GPU: NVIDIA 1050
  - RAM:  16GB
- Applied Mods :  No

**Comment by EmulationFanatic** [comment] 2021-05-29 11:46
Delete the dlc.json file in appdata\roaming\ryujinx\games\game ID. Closing as duplicate of #1366

**Closed by EmulationFanatic** 2021-05-29 11:46 UTC
