### ISSUE TITLE
Pokemon Shield: repeated crashes

### ISSUE THREAD

**Issue by RangerKevin2** [Ryujinx/Ryujinx#2856] opened 2021-11-18 22:20 UTC
hello, i have repeated crashes in pokemon shield. it seems random but in reality It happens in average every 1 hour. my other games are working perfect, they never crashed so i think it's a game related issue. I provided my last log

Ryujinx v1.0.7106 ; settings:
docked mode
VSync, PPTC and FS integrity checks enabled
audio backend: SDL2
Memory manager set to Host
RAM expanded to 6GB
shader cache enabled
16x anisotropic filtering
2x resolution scale (4K)
Multithreading enabled

My PC specs:
Windows 10 Pro 64 bit
i5 9300h
RTX 2060
16 GB RAM
1 TB NVMe
[Ryujinx_1.0.7106_2021-11-18_21-44-18.log](https://github.com/Ryujinx/Ryujinx/files/7566321/Ryujinx_1.0.7106_2021-11-18_21-44-18.log)

**Comment by gdkchan** [comment] 2021-11-18 22:22
Duplicate of #1641.

**Closed by gdkchan** 2021-11-18 22:22 UTC
