### ISSUE TITLE
Gpu crash

### ISSUE THREAD

**Issue by godpow** [Ryujinx/Ryujinx#3322] opened 2022-05-06 00:15 UTC
### What's the issue you encountered?
Was playing bravely default 2 and I was walking around I moved the camera and it crashed.

### How can the issue be reproduced?

Just playing the game

### Log file

[Ryujinx_1.1.118_2022-05-05_20-05-03.log](https://github.com/Ryujinx/Ryujinx/files/8636778/Ryujinx_1.1.118_2022-05-05_20-05-03.log)

### Environment?

- Ryujinx version: 1.1.118</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 3700X
  - GPU: NVIDIA RTX 2070 Super
  - RAM: 32 GB
- Applied Mods : [ Yes (Which ones) / No ]
no

**Comment by MetrosexualGarbodor** [comment] 2022-05-06 00:27
Duplicate of #2529. By the way, memory manager mode should always be set to host unchecked.

**Closed by MetrosexualGarbodor** 2022-05-06 00:27 UTC
