### ISSUE TITLE
Amiibo Renaming/Mii Change Support

### ISSUE THREAD

**Issue by CoolNatu** [Ryujinx/Ryujinx#7118] opened 2024-07-27 14:33 UTC
### Overview

While the Amiibo are capable of saving data, such as SSBU Spirits or the fact that they were used in general, they are stuck with the name "Ryujinx", and any attempt to change that will cause the game to crash, likely due to the emulator trying to bring up the Amiibo tab in the normal Switch settings, something which cannot be done.

### Smaller details

The implementation of this I imagine could be something similar to the Mii Edit applet, where you can open the Amiibo tab of the settings and edit your Amiibo's name and assigned Mii. I assume this would be able to change them, given that the Amiibo are able to save data locally (since I doubt I'm the only person to ever try the Kazuya Amiibo on SSBU).

### Nature of request

As a sort of Quality of Life/Cosmetic request, I'm sure this would be low-priority.

### Why would this feature be useful?

While it wouldn't necessarily be "useful", it would allow for more customization on the part of the user, which is always a nice thing to have.

**Comment by IsaacMarovitz** [comment] 2024-07-28 11:12
Duplicate of #3245

**Closed by IsaacMarovitz** 2024-07-28 11:12 UTC
Labels: enhancement
