### ISSUE TITLE
[Bug] Pokemon Sw/Sh is unable to enable two Ryujinx on the same device for LAN connectivity

### ISSUE THREAD

**Issue by NereeScarlet** [Ryujinx/Ryujinx#6243] opened 2024-02-02 13:59 UTC
### Description of the issue

I asked the same question in #6229 and got the answer 'need to have two different IP addresses'.
I experimented and tried setting each of the two Ryujinx network interfaces to wired network as well as wlan.
However this still doesn't seem to do anything, or is there something I have set up incorrectly?
![image](https://github.com/Ryujinx/Ryujinx/assets/61875283/d51fad87-03ca-462b-ae66-7c5eece4f87a)

### Reproduction steps

Settings-Network-Network Interface
Two Ryujinx are set to Wlan/Ethernet respectively
Try to connect
No response

### Log file

[Ryujinx_1.1.1141_2024-01-31_07-01-53.log](https://github.com/Ryujinx/Ryujinx/files/14141006/Ryujinx_1.1.1141_2024-01-31_07-01-53.log)

### OS

win10

### Ryujinx version

test-ava-ryujinx-1.1.1141-win_x64

### Game version

Pokemon Sw1.3.2/switch Firmware 17.0.0

### CPU

i7-7700

### GPU

1050ti

### RAM

8gib

**Comment by piplup55** [comment] 2024-02-02 16:30
pokemon sw/sh lan mode is known to cause issues it's a game issue not a ryujinx issue, it's better to use mitm

**Comment by NereeScarlet** [comment] 2024-02-02 18:36
> pokemon sw/sh lan mode is known to cause issues it's a game issue not a ryujinx issue, it's better to use mitm

I think I have the 'ldnmitm' option turned on.

**Comment by NereeScarlet** [comment] 2024-02-02 18:37
![Screenshot_20240203_023636_com android chrome](https://github.com/Ryujinx/Ryujinx/assets/61875283/b9aa3146-c8e4-4c9f-b7c9-ad578c39de12)

**Comment by TSRBerry** [comment] 2024-04-15 17:48
Duplicate of #6229

**Closed by TSRBerry** 2024-04-15 17:48 UTC
Labels: bug
