### ISSUE TITLE
Blank screen in Fullscreen in Game Mode on any game on Steamdeck (still in 1.1.510)

### ISSUE THREAD

**Issue by BananaAcid** [Ryujinx/Ryujinx#4208] opened 2023-01-05 01:19 UTC
### What's the issue you encountered?

Screen is blank on start, sounds plays in Fullscreen in Game Mode.
a. Set a trigger to F4 to show UI - with the UI enabled, the game is visible for 2 seconds.
b. When touching the screen, the game is visible for 4 seconds.

Just Updated.</br>
No Changes made, worked before recent updates the last few months..</br>

### How can the issue be reproduced?

Use EmuDeck to install, add games, use "Gaming Mode" to start a game.

### Log file

[blank screen.log](https://github.com/Ryujinx/Ryujinx/files/10348584/blank.screen.log)
No previous log files available.

### Environment?

- Ryujinx version: 1.1.497+, current 1.1.510</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: SteamDeck (Jupiter v1), Linux 5.13.0-valve36-1-neptune
  - CPU: AMD Custom APU 0405
  - GPU: AMD Custom GPU 0405 (RadV Vangogh)
  - RAM: 16GiB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
Was forwarded to me to post here, can not verify any of the log data.

**Comment by gdkchan** [comment] 2023-01-05 01:21
Duplicate of #3874?

**Comment by BananaAcid** [comment] 2023-01-05 01:24
Yes, is a dup. Sorry, did not search well enough

**Comment by BananaAcid** [comment] 2023-01-05 01:27
@gdkchan was ist fixed in the meantime and is new again? I saw the posts being 3 weeks old.

**Closed** 2023-01-05 01:26 UTC
