### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by tremon36** [Ryujinx/Ryujinx#5401] opened 2023-06-26 16:04 UTC
### Overview

It would be great to have some sort of motion controls emulation like in dolphin emulator for the wii console, mapping movements to key presses.
I know it would be difficult to play some games with this sort of emulated controls, but I was playing a game which requires a little usage of motion controls, and it is impossible to beat without them.
Thank you for your great work

### Smaller details

It could be implemented using the same scheme the dolphin emulator uses

### Nature of request

Motion controls emulation

### Why would this feature be useful?

Some games require usage of motion control and not everyone has a motion control capable controller

**Comment by MutantAura** [comment] 2023-06-26 16:37
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3749

**Closed by MutantAura** 2023-06-26 16:37 UTC
