### ISSUE TITLE
[Bug] Crash on macOS with AMD 5300M GPU、intel i7-9750H CPU 

### ISSUE THREAD

**Issue by zanshuxun** [Ryujinx/Ryujinx#6124] opened 2024-01-14 08:20 UTC
### Description of the issue

 Crash on MacOS with AMD 5300M GPU、intel i7-9750H CPU 

### Reproduction steps

1、start the game and play several secons
2、crash

### Log file

[ryujinx crash.log](https://github.com/Ryujinx/Ryujinx/files/13930797/ryujinx.crash.log)

### OS

macOS 14.2.1

### Ryujinx version

1.1.1109

### CPU

intel i7-9750H CPU 

### GPU

AMD 5300M GPU

### RAM

16GB

**Comment by AcK77** [comment] 2024-02-11 01:40
macOS AMD drivers is not the best way to get games playable... We can't do much more here sadly, in that way I close this issue. Log file is wrong in any case so the issue is pretty incomplete.
Thanks.

**Closed by AcK77** 2024-02-11 01:40 UTC
Labels: bug
