### ISSUE TITLE
[Bug] TotK freezes when registering first horse

### ISSUE THREAD

**Issue by livni** [Ryujinx/Ryujinx#5201] opened 2023-06-02 13:03 UTC
### Description of the issue

Caught my first horse and brought it to a stable to register, when the person asked me to name the horse the game froze, but the music continued

### Reproduction steps

1. Play TotK
2. Catch a horse
3. Bring to stable to register

I don't know if this is reproducible, I hope the logs give some insight

### Log file

[Ryujinx_1.1.855_2023-06-02_15-08-38.log](https://github.com/Ryujinx/Ryujinx/files/11635497/Ryujinx_1.1.855_2023-06-02_15-08-38.log)

### OS

macOS Ventura 13.3.1 (a)

### Ryujinx version

1.1.855

### Game version

1.1.1

### CPU

Apple M1 Pro

### RAM

32GB

### List of applied mods

32 fps

**Comment by OiCkilL** [comment] 2023-06-02 17:42
I had the same problem when I registered my second horse.

**Comment by jvperoni** [comment] 2023-06-02 18:26
Does it really freeze? In my case I just had to type in the horse name in the keyboard, but it was like a "hidden" text box. after pressing enter it goes back to the game!

**Comment by MalicT** [comment] 2023-06-02 19:12
That text box pops up in front for mine

**Comment by livni** [comment] 2023-06-02 19:39
I couldn't reproduce, when I loaded the game and tried again it indeed prompted me with a Ryujinx pop up prompt that worked. I guess sometimes this prompt fails and crashes freezes the game; not only the game actually as I couldn't even exit fullscreen mode with ESC

**Comment by AcK77** [comment] 2023-06-03 04:35
Is that still happen with latest version of Ryujinx? (I wonder if #5207 would fix something)

**Comment by alessandro893** [comment] 2023-06-04 06:05
Try to type something on keyboard and press enter, it will unfreeze.

**Comment by livni** [comment] 2023-06-04 08:03
When this freeze happened I tried it and it didn't work. Note the dialog
box didn't even appear.

**Comment by donut** [comment] 2023-06-19 20:53
I was having this issue, but then I tried out of fullscreen and then it worked. So, maybe try exiting fullscreen before registering a horse?

**Comment by MutantAura** [comment] 2023-06-24 23:03
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5186

**Closed by MutantAura** 2023-06-24 23:03 UTC
Labels: bug
