### ISSUE TITLE
[Bug] Updater error on macOS

### ISSUE THREAD

**Issue by xiongpahao** [Ryujinx/Ryujinx#4954] opened 2023-05-15 03:06 UTC
### Description of the issue

In-App Update Failures

### Reproduction steps

I am experiencing consistent failures after in-app updating, with the following prompt appearing after the downloading process:
"An error occurred during Ryujinx update (updater.sh:37)
Please download the update manually from our website if the problem persists."
<img width="420" alt="Screenshot 2023-05-15 at 10 56 08" src="https://github.com/Ryujinx/Ryujinx/assets/12950426/70831d1e-45ee-4297-8595-7c7e8968b87d">

### Log file

[Ryujinx_1.1.799_2023-05-15_10-55-27.log](https://github.com/Ryujinx/Ryujinx/files/11473791/Ryujinx_1.1.799_2023-05-15_10-55-27.log)

### OS

macOS 13.3.1

### Ryujinx version

1.1.799

### CPU

M1 Pro

### RAM

16GB

**Comment by Foul-Tarnished** [comment] 2023-05-15 19:01
This is definitely one of the bug of all time

**Comment by Pbird99** [comment] 2023-05-15 23:02
Happens to me too. The error seems to be with "rm -rf "$INSTALL_DIRECTORY" from line 37 in updater.sh and com.apple.quarantine (from the log). Maybe something to do with permissions?

**Comment by marysaka** [comment] 2023-05-16 16:58
I can reproduce, will look into it.

**Comment by marysaka** [comment] 2023-05-16 19:31
> Happens to me too. The error seems to be with "rm -rf "$INSTALL_DIRECTORY" from line 37 in updater.sh and com.apple.quarantine (from the log). Maybe something to do with permissions?

The issue seems to only happens with release packages when not running from command line...
I cannot reproduce it locally with a fresh build for some reasons.

The quarantine error can be safely ignored, that's a safety check in case Apple decide that this file come from the web (toi avoid reasking for user permissions to run the app)

For the rm operation... the only thing I can think of is that something is locking the application directory, so it might be Ryujinx still running at that moment or something else on the OS.

**Comment by nickolay-smyk** [comment] 2023-05-18 07:10
Having same issue.
A fix would be to place the app in the USER/Applications or /Applications folder.

**Comment by marysaka** [comment] 2023-05-28 09:09
Not sure why that was closed, the issue is still present.

https://github.com/Ryujinx/Ryujinx/pull/5064 might contribute to fix that issue.

**Comment by AcK77** [comment] 2023-05-29 04:15
Is the issue fixed now?

**Comment by MR-UNI** [comment] 2023-06-05 03:45
a similar issue happens to me where when I try to update, it will give an error saying that my version of Ryujinx is unsupported and I need to get one from the official git, however, I reinstalled Ryujinx using the same download and it worked fine.

**Comment by xiongpahao** [comment] 2023-06-09 13:02
OK, I will check it soon
> Can you check again when #5270 is merged?
> 
> For me everything works fine..
> 
> If the location of your `Ryujinx.app` is on an external drive (or outside of Applications folder), you should move it to your Applications folder and try again.
> 
> It's just a guess because there was another user with permission issues on his external drive.
> 
> 
> 
> If the issue still encounters, please post a log file here.

**Comment by xiongpahao** [comment] 2023-06-10 03:22
> 



> Can you check again when #5270 is merged? For me everything works fine.. If the location of your `Ryujinx.app` is on an external drive (or outside of Applications folder), you should move it to your Applications folder and try again. It's just a guess because there was another user with permission issues on his external drive.
> 
> If the issue still encounters, please post a log file here.

I just tried 1.1.879&1.1.880, looked like there was a new problem was introduced.
<img width="420" alt="Screenshot 2023-06-10 at 11 14 15" src="https://github.com/Ryujinx/Ryujinx/assets/12950426/1cd9cce3-ad59-4754-80aa-5890b343b89c">
[Ryujinx_1.1.879_2023-06-10_11-15-12.log](https://github.com/Ryujinx/Ryujinx/files/11711398/Ryujinx_1.1.879_2023-06-10_11-15-12.log)
[Ryujinx_1.1.880_2023-06-10_11-17-50.log](https://github.com/Ryujinx/Ryujinx/files/11711399/Ryujinx_1.1.880_2023-06-10_11-17-50.log)

**Comment by siegmund-heiss-ich** [comment] 2023-06-10 09:58
Nothing unusual happens in your provided logs and everything works as intended up to this point.
@xiongpahao what's the path of your Ryujinx.app?

I could implement an appropriate error handling for `rm -rf` but that won't fix this problem.
At least we would know (unless it returns a generic error), what the problem is. @marysaka do you have a better idea?
When it tries to remove the old app, the process is already terminated and the fds are closed. This couldn't be an issue. 
My guess is that it's most likely a permission or a filesystem error.

**Comment by xiongpahao** [comment] 2023-06-10 10:15
> Nothing unusual happens in your provided logs and everything works as intended up to this point.
> 
> @xiongpahao what's the path of your Ryujinx.app?
> 
> 
> 
> I could implement an appropriate error handling for `rm -rf` but that won't fix this problem.
> 
> At least we would know (unless it returns a generic error), what the problem is. @marysaka do you have a better idea?
> 
> When it tries to remove the old app, the process is already terminated and the fds are closed. This couldn't be an issue. 
> 
> My guess is that it's most likely a permission or a filesystem error.

The Ryujinx is right in the Application folder

**Comment by marysaka** [comment] 2023-07-18 08:43
> > Nothing unusual happens in your provided logs and everything works as intended up to this point.
> > @xiongpahao what's the path of your Ryujinx.app?
> > I could implement an appropriate error handling for `rm -rf` but that won't fix this problem.
> > At least we would know (unless it returns a generic error), what the problem is. @marysaka do you have a better idea?
> > When it tries to remove the old app, the process is already terminated and the fds are closed. This couldn't be an issue.
> > My guess is that it's most likely a permission or a filesystem error.
> 
> The Ryujinx was in the Application folder

The Application requires elevated permission to be touch I think so that make sense it would fail there...

**Comment by efraimkent** [comment] 2023-10-07 00:27
> Having same issue. A fix would be to place the app in the USER/Applications or /Applications folder.

Still having this issue in macOS 14 Sonoma. I have the app in a subfolder in /Applications (which shouldn't matter)

**Closed** 2024-01-03 00:13 UTC
Labels: bug, os:macOS
