### ISSUE TITLE
Unable to re-setup while DLC files moved 

### ISSUE THREAD

**Issue by Ryan2603** [Ryujinx/Ryujinx#2318] opened 2021-05-27 12:30 UTC
## Bug Report

N/A

### What's the issue you encountered?

Once DLC file moved out, the game unable to start and unable to correct the right path

### How can the issue be reproduced?

After your game dlc installed, delete them in your harddisk,  you 100% stuck at the same.

### Log file

Marshaling row-activated signal
00:00:00.795 |N| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'R:\Monster Hunter Rise [NSP]\MONSTER HUNTER RISE (NSP)(US)(56 DLCs)\MONSTER HUNTER RISE [Airy Short Bob hairstyle][0100B0401174300E][US][v0].nsp'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.AddAocItem(UInt64 titleId, String containerPath, String ncaPath, Boolean enabled) in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\Content\ContentManager.cs:line 254
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 332
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 277
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 659
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 1013
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

**Comment by EmulationFanatic** [comment] 2021-05-27 12:45
Delete the dlc.json file in appdata\roaming\ryujinx\games\game ID\. Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/1366

**Closed by EmulationFanatic** 2021-05-27 12:45 UTC
