### ISSUE TITLE
Pokémon Sword crashes several times during different loading screens

### ISSUE THREAD

**Issue by TheDarkSeraphim** [Ryujinx/Ryujinx#2882] opened 2021-11-26 05:37 UTC
Playing Pokemon Sword, during different loading screens (changing zone, going into building), the game will crash.

Specs
i7-7700k @ 4.4GHz
GTX 1080ti
32GB Ram @ 3867MHz

Game was set to undocked, without the expanded DRAM size, resolution size is 4x

Below is the log of one of the crashes

```
00:04:27.766 |E| GPU.MainThread Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Not mapped: va=0xFFFFFFFFFFFFFFFF, size=0x000000000000027F
   at Ryujinx.Cpu.MemoryManagerHostMapped.AssertMapped(UInt64 va, UInt64 size)
   at Ryujinx.Cpu.MemoryManagerHostMapped.GetSpan(UInt64 va, Int32 size, Boolean tracked)
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.ReadImpl(UInt64 va, Span`1 data, Boolean tracked)
   at Ryujinx.Graphics.Gpu.Memory.MemoryManager.GetSpan(UInt64 va, Int32 size, Boolean tracked)
   at Ryujinx.Graphics.Gpu.Shader.GpuAccessor.GetCode(UInt64 address, Int32 minimumSize)
   at Ryujinx.Graphics.Shader.Decoders.Decoder.FillBlock(ShaderConfig config, Block block, UInt64 limitAddress, UInt64 startAddress)
   at Ryujinx.Graphics.Shader.Decoders.Decoder.Decode(ShaderConfig config, UInt64 startAddress)
   at Ryujinx.Graphics.Shader.Translation.Translator.DecodeShader(UInt64 address, IGpuAccessor gpuAccessor, TranslationOptions options, TranslationCounts counts)
   at Ryujinx.Graphics.Gpu.Shader.ShaderCache.GetGraphicsShader(ThreedClassState& state, GpuChannel channel, GpuAccessorState gas, ShaderAddresses addresses)
   at Ryujinx.Graphics.Gpu.Engine.Threed.StateUpdater.UpdateShaderState()
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount)
   at Macro(MacroJitContext , IDeviceState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, IDeviceState state)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls()
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__63_0()
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass48_0.<RunLoop>b__0()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

**Comment by Mou-Ikkai** [comment] 2021-11-26 06:09
Duplicate of #2667

**Comment by gdkchan** [comment] 2021-11-26 16:17
Seems different since the other ones seems to hang instead of actually crashing, but maybe it's related. Would be nice to have the *full* log to confirm if the shader was corrupt.

**Comment by TheDarkSeraphim** [comment] 2021-11-26 16:45
> Seems different since the other ones seems to hang instead of actually crashing, but maybe it's related. Would be nice to have the _full_ log to confirm if the shader was corrupt.

I tried copying the entire log into Pastebin, but it was too big. I guess I'll try posting it here instead and see if it works

**Comment by gdkchan** [comment] 2021-11-26 17:05
You can just drag and drop the log file on the message box and GitHub will attach it to the message.

**Comment by TheDarkSeraphim** [comment] 2021-11-26 17:06
> You can just drag and drop the log file on the message box and GitHub will attach it to the message. If the file is too large, you can just zip it before attaching.

Oh! Thanks for letting me know

**Comment by TheDarkSeraphim** [comment] 2021-11-26 17:07
[Ryujinx_1.0.7108_2021-11-26_05-15-41.log](https://github.com/Ryujinx/Ryujinx/files/7610035/Ryujinx_1.0.7108_2021-11-26_05-15-41.log)
[Ryujinx_1.0.7108_2021-11-26_05-15-41.log](https://github.com/Ryujinx/Ryujinx/files/7610039/Ryujinx_1.0.7108_2021-11-26_05-15-41.log)

**Comment by EmulationFanatic** [comment] 2022-09-08 17:37
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Closed by EmulationFanatic** 2022-09-08 17:37 UTC
Labels: bug, gpu
