### ISSUE TITLE
[Feature Request] Mouse feature for Ryujinx

### ISSUE THREAD

**Issue by engineer289347** [Ryujinx/Ryujinx#6544] opened 2024-03-21 09:34 UTC
### Overview

I want a mouse feature like yuzu

### Smaller details

No

### Nature of request

No

### Why would this feature be useful?

This will help not to use the third program to emulator mouse anymore

**Comment by piplup55** [comment] 2024-03-21 12:16
duplicate of #2063

**Closed by piplup55** 2024-03-21 12:16 UTC
