### ISSUE TITLE
[Feature Request] Please add "Capture" Button Mapping to "Settings">"Input".

### ISSUE THREAD

**Issue by SuperMarioOdysseyCaptureButtonPlease** [Ryujinx/Ryujinx#6731] opened 2024-04-27 05:58 UTC
### Overview

The Nintendo Switch Joy Con controller has a "Capture" button on the left side of the left Joycon and the Switch Pro Controller has a "Capture" button in the centre of the Controller next to the "Home" button, however in Ryujinx, I can't seem to find a way to assign the "Capture" button to a controller button.  Also, the game "Super Mario Odyssey" requires you to take an in-game photo using the in-game camera by pressing the "Capture" button to get certain Power Moons in the game.  I would imagine there are other games also which require use of the "Capture" button to complete certain in-game objectives.

On the Xbox One S Controller, there is no "Capture" button.  If Ryujinx could please add an option into the "Settings">"Input" section allowing you to assign the "Capture" button to any button on the Xbox One S Controller (eg. assign "Capture" to "R3"), this would be really appreciated?

### Smaller details

Please add the Switch Joy Con & Switch Pro Controller "Capture" button as an assignable button in the "Settings">"Input" section.

### Nature of request

Please add the Switch Joy Con & Switch Pro Controller "Capture" button as an assignable button in the "Settings">"Input" section.

### Why would this feature be useful?

Without this functionality added, you cannot get all the "Power Moons" in the game "Super Mario Odyssey", and I imagine other games would likewise need the "Capture" button to achieve certain things in those games, so adding this button would be helpful to be able to use all Joy Con controller buttons a game needs.

**Comment by piplup55** [comment] 2024-04-27 08:45
duplicate of #5952

**Closed by piplup55** 2024-04-27 08:45 UTC
