### ISSUE TITLE
Keyboard arrows activate the emulator menu during emulation

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#2521] opened 2021-08-01 08:47 UTC
### What's the issue you encountered?

Keyboard arrows open the menus of the emulator so its impossible to use the arrows when keyboard is chosen as the controller.

### How can the issue be reproduced?

Get into a game and use the arrow keys to move.

### Log file

N/A

### Environment?

- Ryujinx version: 1.0.6976</br>
- System Specs:
  - OS: *Windows 10)*

### Additional context?
![image](https://user-images.githubusercontent.com/2002038/127764261-86c5d2ac-b38a-4d06-853a-7e9d02258ae0.png)

PR that introduced the issue was #2411

**Comment by Sakura0134** [comment] 2021-08-01 09:27
This is a duplicate of #2502 . Also, A PR is available to fix this issue.

**Closed** 2021-08-01 17:05 UTC
