### ISSUE TITLE
Under the LAN, Ryujinx LND2.3 could not connect to the Switch, and the game was Pokemon sword 1.3.2

### ISSUE THREAD

**Issue by lzxdgba** [Ryujinx/Ryujinx#2616] opened 2021-09-03 13:25 UTC
## Bug Report
HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.

### What's the issue you encountered?
On the same wifi， Ryujinx LND2.3 could not connect to the Switch, and the game was Pokemon sword 1.3.2
Ryujinx has set LAN mode.The game versions are consistent.All games have LAN mode enabled including the Pokemon Sword on the Switch.The log “HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.”appears when the Pokemon sword on Ryujinx is in LAN mode

### How can the issue be reproduced?
Enable LAN mode in the Pokemon Sword menu

### Log file
00:00:50.530 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:50.546 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:50.546 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:50.546 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:50.546 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:50.547 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:50.547 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:51.162 |I| HLE.OsThread.15 ServiceLdn GetIpv4Address: LDN obtained proxy IP.
00:00:51.240 |S| HLE.OsThread.17 ServiceNifm CreateRequest: Stubbed. {version: 2}
00:00:51.241 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:51.464 |I| HLE.OsThread.15 ServiceLdn : LDN TCP client disconnected a session with Id e6bafbc0-2c19-4c20-a8ac-7d8939d2e37e
00:00:51.464 |W| HLE.GuestThread.36 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.613 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.613 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.613 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.613 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.614 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:51.647 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:51.649 |S| HLE.OsThread.17 ServiceNifm Submit: Stubbed. 
00:00:51.649 |S| HLE.OsThread.17 ServiceNifm GetRequestState: Stubbed. 
00:00:51.651 |S| HLE.OsThread.17 ServiceNifm GetResult: Stubbed. 
00:00:51.681 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:51.685 |S| HLE.OsThread.6 ServiceBsd RegisterClient: Stubbed. 
00:00:51.685 |S| HLE.OsThread.6 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:51.686 |S| HLE.OsThread.17 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:51.928 |I| HLE.OsThread.17 ServiceNifm GetCurrentIpConfigInfo: Console's local IP is "192.168.1.104".
00:00:52.598 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:52.598 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:52.598 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:54.715 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2434!
00:00:54.715 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2433!
00:00:54.717 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2432!
00:00:54.719 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2431!
00:00:54.720 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2430!
00:00:54.912 |I| HLE.OsThread.10 ServiceNv Create: Created map 2430 with size 0x000d5000!
00:00:54.913 |I| HLE.OsThread.10 ServiceNv Create: Created map 2431 with size 0x00003000!
00:00:54.939 |I| HLE.OsThread.10 ServiceNv Create: Created map 2432 with size 0x00009000!
00:00:54.942 |I| HLE.OsThread.10 ServiceNv Create: Created map 2433 with size 0x0000b000!
00:00:54.943 |I| HLE.OsThread.10 ServiceNv Create: Created map 2434 with size 0x00003000!
00:00:54.946 |I| HLE.OsThread.10 ServiceNv Create: Created map 2435 with size 0x00009000!
00:00:54.947 |I| HLE.OsThread.10 ServiceNv Create: Created map 2436 with size 0x00006000!
00:00:55.031 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:55.031 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:55.031 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:56.476 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2436!
00:00:56.477 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2435!
00:00:56.478 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2432!
00:00:56.479 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2434!
00:00:56.480 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2433!
00:00:56.481 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2431!
00:00:56.482 |I| HLE.OsThread.10 ServiceNv DecrementMapRefCount: Deleted map 2430!
00:00:56.682 |I| HLE.OsThread.10 ServiceNv Create: Created map 2430 with size 0x0004d000!
00:00:56.684 |I| HLE.OsThread.10 ServiceNv Create: Created map 2431 with size 0x00003000!
00:00:56.700 |I| HLE.OsThread.10 ServiceNv Create: Created map 2432 with size 0x00009000!
00:00:56.701 |I| HLE.OsThread.10 ServiceNv Create: Created map 2433 with size 0x00006000!
00:00:56.704 |I| HLE.OsThread.10 ServiceNv Create: Created map 2434 with size 0x00001000!
00:00:57.553 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:57.885 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.887 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.888 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.888 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.888 |W| HLE.GuestThread.19 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:57.888 |S| HLE.OsThread.17 ServiceNifm Cancel: Stubbed. 
00:00:57.915 |S| HLE.OsThread.17 ServiceNifm SetConnectionConfirmationOption: Stubbed. 
00:00:57.920 |S| HLE.OsThread.6 ServiceBsd RegisterClient: Stubbed. 
00:00:57.920 |S| HLE.OsThread.6 ServiceBsd StartMonitoring: Stubbed. {unknown0: 0}
00:00:57.923 |S| HLE.OsThread.17 ServiceSsl SetInterfaceVersion: Stubbed. {interfaceVersion: 3}
00:00:58.152 |I| HLE.OsThread.17 ServiceNifm GetCurrentIpConfigInfo: Console's local IP is "192.168.1.104".
00:00:58.844 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:58.844 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:00:58.844 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:01.165 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:01:01.165 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:01:01.165 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:03.605 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:01:03.605 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:01:03.606 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:06.095 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:01:06.096 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:01:06.096 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:08.768 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:01:08.768 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:01:08.768 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:11.325 |S| HLE.OsThread.17 ServiceAm GetPseudoDeviceId: Stubbed. 
00:01:11.325 |S| HLE.OsThread.17 ServiceAcc CheckAvailability: Stubbed. 
00:01:11.325 |S| HLE.OsThread.17 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:01:12.623 |W| HLE.GuestThread.19 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.16 KernelSvc PrintResult: SendSyncRequest64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.18 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.21 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.20 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.22 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.23 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.24 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.25 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.26 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.27 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.28 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.42 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.43 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.44 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.623 |W| HLE.GuestThread.45 KernelSvc PrintResult: WaitProcessWideKeyAtomic64 returned error ThreadTerminating.
00:01:12.633 |E| HLE.OsThread.13 SurfaceFlinger DequeueBuffer: No available buffer slots
00:01:12.633 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
00:01:12.662 |I| HLE.OsThread.8 AudioRenderer ReleaseSessionId: Unregistered output (0)
00:01:12.665 |W| GUI.WindowThread ServiceNv Close: Closing channel

### Environment?

- Ryujinx version: ryujinx-1.0.0-ldn2.3

- Game version:Pokemon sword 1.3.2

- System Specs:
  - OS: Windows 10
  - CPU:i5-8400
  - GPU:NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : NO

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by lzxdgba** [comment] 2021-09-03 13:32
Someone can help me please

**Comment by lzxdgba** [comment] 2021-09-03 13:33
Who can help me please?

**Comment by AcK77** [comment] 2021-09-05 18:29
Duplicate of #2074

**Closed by AcK77** 2021-09-05 18:29 UTC
