### ISSUE TITLE
[Bug] Pokemon Sword and Shield Freeze After Finishing Dynamax Adventures

### ISSUE THREAD

**Issue by fadhilmulyono** [Ryujinx/Ryujinx#7209] opened 2024-08-16 15:27 UTC
### Description of the issue

Game freezes after finishing Dynamax Adventures. I already disabled Shader Cache and that would allow me to perform actions that require mandatory saving without freezing the game. The freeze happened after the cutscenes where I rescue Peonia and Peony collapsed in the entrance of Max Lair. As a result of this bug I can't progress the Crown Tundra expansion storyline.

### Reproduction steps

Play the Crown Tundra expansion until you reach the point where you need to try a Dynamax Adventure and rescue Peonia. Catch some Pokemon and keep one of the caught Pokemon. After the cutscene where you return to the Max Lair entrance where Peony collapsed, the game freezes.

### Log file

[Ryujinx_1.1.1375_2024-08-16_22-18-58.log](https://github.com/user-attachments/files/16638690/Ryujinx_1.1.1375_2024-08-16_22-18-58.log)
[Ryujinx_1.1.1375_2024-08-16_22-22-15.log](https://github.com/user-attachments/files/16638691/Ryujinx_1.1.1375_2024-08-16_22-22-15.log)
[Ryujinx_1.1.1375_2024-08-16_20-12-04.log](https://github.com/user-attachments/files/16638692/Ryujinx_1.1.1375_2024-08-16_20-12-04.log)

### OS

Windows 10

### Ryujinx version

1.1.1375

### Game version

1.3.2

**Comment by MetrosexualGarbodor** [comment] 2024-08-16 15:29
Duplicate of #5837

**Closed by MetrosexualGarbodor** 2024-08-16 15:29 UTC
Labels: bug
