### ISSUE TITLE
[Bug] Ryujinx freezes when there are no input device for Zelda TOTK

### ISSUE THREAD

**Issue by xuan** [Ryujinx/Ryujinx#5195] opened 2023-06-01 23:24 UTC
### Description of the issue

When game controller is not present, Ryujinx freezes.  No menu options work, I have to force quit Ryujinx.

### Reproduction steps

On a MacOS Ventura:

1. Start Ryujinx
2. Set  Input Device to Disabled under Options -> Settings -> Input.
3. Load a TOTK in the dashboard.

Once Ryujinx finishes Compile Shaders for TOTK, the screen is black and is completely frozen.

### Log file

[Ryujinx_1.1.1+0_2023-06-01_17-20-22.log](https://github.com/Ryujinx/Ryujinx/files/11630522/Ryujinx_1.1.1%2B0_2023-06-01_17-20-22.log)

### OS

macOS Ventura

### Ryujinx version

Nightly Build

### Game version

1.1.1

### CPU

M2 Pro

### RAM

16GB

**Comment by MutantAura** [comment] 2023-06-24 23:04
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5186

**Closed by MutantAura** 2023-06-24 23:04 UTC
Labels: bug
