### ISSUE TITLE
[Bug] Unepic - UI screen glitch

### ISSUE THREAD

**Issue by SPUAP** [Ryujinx/Ryujinx#6150] opened 2024-01-19 06:37 UTC
### Description of the issue

![K-003](https://github.com/Ryujinx/Ryujinx/assets/118019130/0b35a647-a019-4705-a327-7727c4506b91)
![K-004](https://github.com/Ryujinx/Ryujinx/assets/118019130/b053f6d5-8fa6-47c7-8b8d-6b92e66e959a)

Incorrect graphic glitch. reverse UI screen.
Top UI screen's correct location is bottom.
Bottom UI screen's correct location is top.
So top UI screen(correct location is bottom) hide detailed inventory screen. can't see detailed inventory screen.
Global version(01008F80049C6000) and Asia version(010036400DFF0000) have the same problem.

### Reproduction steps

Always

### Log file

[Ryujinx_1.1.1114_2024-01-19_15-31-36.log](https://github.com/Ryujinx/Ryujinx/files/13985187/Ryujinx_1.1.1114_2024-01-19_15-31-36.log)

### OS

Windows 10

### Ryujinx version

1.1.1114

### Game version

1.0

### CPU

Ryzen 5 5600X

### GPU

RTX 3060 Ti

### RAM

16GB

**Comment by AcK77** [comment] 2024-02-11 01:14
You already reported it in the games list since the issue is duplicated between those 2 repos, I close this one.
Thanks for the report!

**Closed by AcK77** 2024-02-11 01:14 UTC
Labels: bug
