### ISSUE TITLE
Linux executable not having correct permissions after update

### ISSUE THREAD

**Issue by Rstar284** [Ryujinx/Ryujinx#2606] opened 2021-08-30 12:11 UTC
### What's the issue you encountered?

I updated ryujinx trough the auto-updater, when i restarted it, nothing happened so i check it out and the executable didn't have the executable permission</br>

### How can the issue be reproduced?

Update ryujinx on linux

### Environment?

- Ryujinx version: 1.0.7021</br>
- Game version: N/A
- System Specs:
  - OS: ArchLinux
  - CPU: i7-4510U
  - GPU: N/A
  - RAM: *8GB
- Applied Mods :  No

### Additional context?

Additional info about your environment: N/A</br>

**Comment by Mou-Ikkai** [comment] 2021-08-30 12:44
Duplicate of: #2497

**Closed** 2021-08-30 21:51 UTC
