### ISSUE TITLE
[Bug] Strange thing happening to 3d Models in pokemon Scarlet starting from 1.1733

### ISSUE THREAD

**Issue by AreoGit** [Ryujinx/Ryujinx#5251] opened 2023-06-06 18:32 UTC
### Description of the issue

Starting from version 1.1733 all pokemon and characters look strange / washed out. 
The first screenshot shows how it should be and was before 1.1733. The second screenshot is how it is now up until the newest version. I can post more examples  if necessary.

![Screenshot 2023-06-06 202438](https://github.com/Ryujinx/Ryujinx/assets/1416943/946bf4c9-db88-4181-9333-caa9573f9bf4)
![Screenshot 2023-06-06 202621](https://github.com/Ryujinx/Ryujinx/assets/1416943/06095480-df2d-4889-92ec-4f20d35eef31)

As said before the issue is introduced in 1.1733. Version 1.1732 does not have this problem. It is version 1.03 of Pokemon Scarlet.
Clean install with wiping the folder in AppData does not resolve the problem so it was a change introduced in the code in 1.1733.

Machine specs:

i7-1255u Intel Irix XE (96EU) with 16GB of RAM.

No alterations made to stock Ryujinx settings (so Vulkan is used).

### Reproduction steps

Start Pokemon Scarlet with any Ryujinx version newer then 1.1733 on a Intel Irix XE gpu.

### Log file

00:00:00.038 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.042 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.042 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.042 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.043 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.043 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.044 |I| Configuration LogValueChange: PreferredGpu set to: 0x8086_0x46A8
00:00:00.044 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.045 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.045 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.046 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.052 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.052 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.053 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.053 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.053 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.053 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.053 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.053 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.053 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.054 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.054 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.054 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.100 |N| Application Load: Configuration file updated to version 47
00:00:00.101 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.869
00:00:00.106 |N| Application Print: Operating System: Microsoft Windows 10.0.22621 (X64)
00:00:00.106 |N| Application Print: CPU: 12th Gen Intel(R) Core(TM) i7-1255U ; 12 logical
00:00:00.107 |N| Application Print: RAM: Total 16209 MiB ; Available 10096 MiB
00:00:00.110 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.110 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.442 |I| GUI.ApplicationLibraryThread Application LoadApplications: last_played found: "06/06/2023 18:23:06", migrating to last_played_utc
00:00:00.070 |I| Gpu : Backend Threading (Auto): True
00:00:00.379 |N| Application LoadApplication: Using Firmware Version: 16.0.3
00:00:00.379 |I| Application LoadApplication: Loading as NSP.
00:00:00.408 |I| Application AddAocItem: Found AddOnContent with TitleId 0100A3D008C5D001
00:00:00.426 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.426 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100A3D008C5D001
00:00:00.427 |I| ModLoader QueryContentsDir: Searching mods for Title 0100A3D008C5C000
00:00:00.427 |I| ModLoader QueryContentsDir: Searching mods for DLC 0100A3D008C5D001
00:00:00.429 |I| Loader Load: Loading rtld...
00:00:00.437 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:00.437 |I| Loader Load: Loading main...
00:00:00.716 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\sudachi\rom\rom_build\programs\prog\app\msvc\main_app\NX64\Release\main_app.nss
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libcurl-13_3_9-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-1_8_3-Release
                   SDK MW+Nintendo+NintendoSDK_Google_APIs_For_NPLN-1_8_3-Release
                   SDK MW+Nintendo+NintendoSDK_gRPC_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+NintendoSDK_OpenSSL_For_NPLN-0_0_0-Release
                   SDK MW+Nintendo+PiaCommon-6_20_1
                   SDK MW+Nintendo+Pia-6_20_1
                   SDK MW+Nintendo+PiaLocal-6_20_1
                   SDK MW+Nintendo+PiaLan-6_20_1
                   SDK MW+Nintendo+PiaReckoning-6_20_1
                   SDK MW+Nintendo+PiaSession-6_20_1
                   SDK MW+Nintendo+PiaTransport-6_20_1
                   SDK MW+Nintendo+PiaNpln-6_20_1
                   SDK MW+NINTENDO+nlib_LZ4-22_0201
                   SDK MW+Nintendo+NintendoWare_Font-13_3_9-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-13_3_9-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-13_3_9-Release
                   SDK MW+Nintendo+NintendoWare_G3d-13_3_9-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-13_3_9-Release
                   SDK MW+Microsoft+Havok_AI-2021_1
00:00:00.716 |I| Loader Load: Loading subsdk0...
00:00:00.737 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-13_3_9-Release
00:00:00.737 |I| Loader Load: Loading sdk...
00:00:00.787 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 13.3.9
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-13_3_9-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-13_3_9-Release
                   SDK MW+Nintendo+NintendoSdk_BuildTarget-64Bit
                   SDK MW+Nintendo+NintendoSDK_NVN-13_3_9-Release
00:00:00.887 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.812 |I| Ptc Load: Loaded Translation Cache (size: 77451054 bytes, translated functions: 43455).
00:00:01.831 |I| Ptc Load: Loaded Profiling Info (size: 135389 bytes, profiled functions: 43432).
00:00:01.845 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.848 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.878 |I| Loader LoadNsos: Loading image 2 at 0x000000000c556000...
00:00:01.881 |I| Loader LoadNsos: Loading image 3 at 0x000000000cbf0000...
00:00:01.890 |I| ModLoader LoadCheats: Build ids found for title 0100A3D008C5C000:
    C1C80268F07394EA0ECA8BD0B1E3F0D44A763131000000000000000000000000
    6EE2D5E3216EBDA553FC6D5D090C6F65318273A7000000000000000000000000
    FA071FEA82ADFF2E5E710381AFE04EEE1C751129000000000000000000000000
    D1CD500523EA5B360DA446CC314E606DF44474C7000000000000000000000000
00:00:01.895 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.945 |I| Loader Start: Application Loaded: Pokémon Scarlet v1.3.0 [0100a3d008c5c000] [64-bit]
00:00:01.956 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.980 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:05.656 |N| GUI.RenderLoop Gpu PrintGpuInformation: Intel Intel(R) Iris(R) Xe Graphics (Vulkan v1.3.246, Driver v0.405.273)
00:00:05.663 |I| GPU.MainThread Gpu LoadShaders: Loading 92 shaders from the cache...
00:00:06.550 |I| GPU.MainThread Gpu LoadShaders: Rebuilding 92 shaders...
00:00:07.567 |I| GPU.MainThread Gpu LoadShaders: Rebuilt 92 shaders successfully.
00:00:07.567 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:08.476 |I| HLE.GuestThread.21 Ptc LoadTranslations: 43415 translated functions loaded
00:00:08.488 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 0 of 17 functions translated | Thread count: 11
00:00:08.623 |I| HLE.GuestThread.21 Ptc MakeAndSaveTranslations: 17 of 17 functions translated | Thread count: 11 in 0,1343931 s
00:00:08.703 |S| HLE.OsThread.22 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:08.714 |S| HLE.OsThread.22 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:08.714 |S| HLE.OsThread.22 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:08.714 |S| HLE.OsThread.22 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:08.740 |S| HLE.OsThread.22 ServicePctl Initialize: Stubbed. 
00:00:08.815 |W| HLE.GuestThread.21 KernelSvc : MapPhysicalMemory() = LimitReached
00:00:08.961 |S| HLE.OsThread.22 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:08.964 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:08.968 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:08.969 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:09.057 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:09.058 |I| HLE.OsThread.22 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:09.067 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:09.078 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:09.094 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:09.096 |S| HLE.OsThread.10 ServiceNv ZbcSetTable: Stubbed. 
00:00:09.097 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:09.167 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:09.168 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:09.168 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:09.169 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:09.169 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:09.169 |S| HLE.OsThread.10 ServiceNv SetTimeout: Stubbed. 
00:00:09.172 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:09.877 |I| HLE.OsThread.6 AudioRenderer AcquireSessionId: Registered new renderer (0)
00:00:09.879 |I| HLE.OsThread.6 AudioRenderer Initialize: Initializing with REV10
00:00:09.893 |I| AudioProcessor.Worker AudioRenderer Work: Starting audio processor
00:00:09.893 |I| AudioRendererManager.Worker AudioRenderer SendCommands: Starting audio renderer
00:00:09.910 |I| HLE.OsThread.6 AudioRenderer Start: Starting renderer id 0
00:00:09.964 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:10.058 |I| AudioProcessor.Worker Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 240
00:00:10.105 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:10.144 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 98 ; appletResourceUserId: 1 ; type: ProController, Handheld, JoyconPair}
00:00:10.144 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:10.146 |S| HLE.OsThread.9 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:10.147 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: -7363015679965921280}
00:00:10.147 |S| HLE.OsThread.9 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: -7363015473807491072}
00:00:10.675 |S| HLE.OsThread.22 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72237707933630464}
00:00:10.677 |S| HLE.OsThread.22 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:10.677 |S| HLE.OsThread.22 ServiceNs CheckAddOnContentMountStatus: Stubbed. 
00:00:10.694 |S| HLE.OsThread.9 ServiceHid ActivateTouchScreen: Stubbed. {appletResourceUserId: 1}
00:00:11.025 |I| Ptc Save: Saved Translation Cache (size: 77470822 bytes, translated functions: 43472).
00:00:11.780 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.782 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100A3D008C5D001
00:00:11.783 |S| HLE.OsThread.22 ServiceNs PrepareAddOnContentImpl: Stubbed. {index: 1}
00:00:11.784 |I| HLE.OsThread.8 Loader OpenDataStorageByDataId: Opened AddOnContent Data TitleID=0100A3D008C5D001
00:00:11.792 |S| HLE.OsThread.6 ServiceAudio GetActiveChannelCount: Stubbed. 
00:00:11.794 |I| HLE.OsThread.7 AudioRenderer AcquireSessionId: Registered new output (0)
00:00:11.810 |I| HLE.OsThread.7 Audio EnsureAudioStreamSetup: New audio stream setup with a target sample count of 1024
00:00:11.814 |S| HLE.OsThread.9 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 5}
00:00:11.815 |S| HLE.OsThread.9 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 1 ; sixAxisSensorHandle: 65541}
00:00:48.608 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:00:50.607 |S| HLE.OsThread.22 ServiceAm GetLibraryAppletLaunchableEvent: Stubbed. 
00:00:50.613 |I| HLE.OsThread.22 ServiceAm .ctor: Applet 'SoftwareKeyboard' created.
00:00:54.841 |I| HLE.OsThread.22 ServiceAm .ctor: Applet 'SoftwareKeyboard' created.
00:00:57.651 |W| GUI.RenderLoop Gpu TryGetGraphicsPipeline: Background pipeline compile missed on draw - incorrect pipeline state?
00:01:08.633 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 135454 bytes, profiled functions: 43440).
00:01:20.352 |W| HLE.GuestThread.21 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.26 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.23 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.27 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.28 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.30 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.25 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.31 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.29 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.34 KernelSvc : SendSyncRequest() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.33 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.40 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.36 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.32 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.35 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.48 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.39 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.38 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.37 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.41 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.42 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.44 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.43 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.47 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.45 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.352 |W| HLE.GuestThread.46 KernelSvc : WaitProcessWideKeyAtomic() = TerminationRequested
00:01:20.358 |E| HLE.OsThread.13 SurfaceFlinger DequeueBuffer: No available buffer slots
00:01:20.359 |E| HLE.OsThread.13 SurfaceFlinger OnTransact: Error returned by transaction DequeueBuffer: Busy
00:01:20.365 |I| HLE.OsThread.6 AudioRenderer Stop: Stopping renderer id 0
00:01:20.365 |I| HLE.OsThread.6 AudioRenderer Stop: Stopped renderer id 0
00:01:20.366 |I| HLE.OsThread.6 AudioRenderer ReleaseSessionId: Unregistered renderer (0)
00:01:20.373 |I| AudioProcessor.Worker AudioRenderer Work: Stopping audio processor
00:01:20.378 |W| GUI.WindowThread ServiceNv Close: Closing channel
00:01:20.397 |I| HLE.OsThread.6 AudioRenderer StopLocked: Stopped audio renderer
00:01:20.417 |I| HLE.OsThread.7 AudioRenderer ReleaseSessionId: Unregistered output (0)

### OS

Windows 11

### Ryujinx version

1.1733 - till newest

### Game version

1.03

### CPU

i7-1255u

### GPU

Intel Irix XE (96eu)

### RAM

16GB

**Comment by gdkchan** [comment] 2023-06-07 04:19
Probably a duplicate of #4863.

**Comment by gdkchan** [comment] 2023-06-07 04:20
Issue is probably `gl_FrontFacing` that doesn't work properly with Intel compiler. I had a ugly work around in the backend to make it work, but this change moved it out of the backend. Maybe that changed it enough to make it not work in some cases anymore.

**Comment by Kurochi51** [comment] 2023-06-14 12:33
@gdkchan I looked at the workaround pre and post change, didn't it go from `FP32` to `S32` before negation / comparison? whereas now it goes from `S32` to `FP32` in the negation / comparison.

Workaround pre:

```
var valueFloat = Select(TypeFP32(), value, Constant(TypeFP32(), 1f), Constant(TypeFP32(), 0f));
var valueAsInt = Bitcast(TypeS32(), valueFloat);
var valueNegated = SNegate(TypeS32(), valueAsInt);
value = SLessThan(TypeBool(), valueNegated, Constant(TypeS32(), 0));
```
and post:
```
res = context.ICompareLess(context.INegate(context.IConvertS32ToFP32(res)), Const(0));
```

**Comment by gdkchan** [comment] 2023-06-14 19:39
It seems that `Select` changed to `IConvertS32ToFP32`. Maybe that is the problem.

**Comment by Kurochi51** [comment] 2023-06-14 19:42
I have a local build going with the change, alas no Intel GPU to test 😞

**Comment by AreoGit** [comment] 2023-06-14 21:04
@Kurochi51 if you upload the local build here or send me a link to it I can test it.

**Comment by Kurochi51** [comment] 2023-06-14 21:05
I opened a PR with it #5311, the bot will comment builds as soon as they're finished

**Comment by AreoGit** [comment] 2023-06-14 21:08
I see the build running. Will let you know as soon as I tested it tomorrow.

**Comment by AcK77** [comment] 2023-06-22 19:36
Fixed by https://github.com/Ryujinx/Ryujinx/pull/5311

**Closed by AcK77** 2023-06-22 19:36 UTC
Labels: bug
