### ISSUE TITLE
Native Gamecube Controller Support

### ISSUE THREAD

**Issue by FaultyPine** [Ryujinx/Ryujinx#1978] opened 2021-01-29 02:24 UTC
#### Overview:
A "native" implementation for Gamecube controllers. The end result of this feature would allow users to simply plug their Gamecube controllers in and Ryujinx would automatically map default input bindings to that controller. At the moment, Some gamecube adapters are usable with Ryu, for example the [Nintendo Gamecube controller adapter](https://www.amazon.com/GameCube-Controller-Adapter-Nintendo-Switch/dp/B07DJX3ZR8/), or the [Mayflash adapter](https://www.amazon.com/Mayflash-GameCube-Controller-Adapter-Switch/dp/B00RSXRLUE) which can be set to a "PC" mode which works but requires the user to then manually set up controls and controller profiles and such. If your adapter doesn't have that, using an external program that produces xinput for ryu to read is the only option.
Ideally, one would be able to use the other mode, which is what is used when using the adapter with a Wii U or Switch. 

#### Smaller Details: 
In an ideal world, this implementation would also support things like:
- hotplugging (being able to plug in a controller while the emulator is running and it would properly detect/handle it)
- HID implementation (games like Smash would detect that the current input device is a gamecube controller, as opposed to a pro controller or something)
- Analog triggers...?

#### Nature of Request:  
 I _believe_ both Yuzu and Dolphin currently have a native gamecube controller implementation under the GPLv2+ license, both using libusb. (Don't take my word for it though, obviously)

### Why would this feature be useful?
The majority of the use cases apply to people looking to play Super Smash Brothers Ultimate, as that audience widely uses Gamecube controllers as their preferred peripheral of choice. Making it easier to use for that audience would make lots of people more comfortable navigating/using the emulator.

**Comment by AcK77** [comment] 2021-04-11 19:57
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by FaultyPine** [comment] 2021-04-13 00:32
Just tested, I still need to turn my mayflash adapter to "PC mode" to get it to register. But when it is in pc mode, it works great.

**Closed** 2021-04-14 10:28 UTC
Labels: enhancement, service:hid
