### ISSUE TITLE
[Feature Request] Agnostic game configs

### ISSUE THREAD

**Issue by InsertCleverNameHere** [Ryujinx/Ryujinx#3602] opened 2022-08-18 12:18 UTC
#### Overview:
- Extensive per-game config profiles including controller profiles, emulation settings, game updates/add-ons, and mods of choice. 

#### Smaller Details: 

- Other emulators usually implement this by allowing the creation of separate config files that override the existing global one when running a game instance. 

### Why would this feature be useful?

Now that Vulkan has been merged, changing the backend for 1 game only then changing it back afterwards is frustrating
to do every time, a simple game config would make the experience better for users as well as devs looking to investigate bugs involving certain settings on a per-game basis. This also serves to declutter input profiles if users create one for every game and makes experimenting with mod compatibility for example easier, as well as having the added benefit of streamlining per-game desktop shortcuts by a simple launch argument should the feature be implemented later on.

**Comment by EmulationFanatic** [comment] 2022-08-18 12:25
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1796

**Closed by EmulationFanatic** 2022-08-18 12:25 UTC
