### ISSUE TITLE
Can only type a single letter in Monster Hunter Generations Ultimate [Bug]

### ISSUE THREAD

**Issue by OxygenMlcl** [Ryujinx/Ryujinx#6629] opened 2024-04-08 17:34 UTC
### Description of the issue

When you open a dialogue that requires you to insert text, the entire previously written default text will be selected and be replaced with a single letter you write. You can only write a single letter. If you press another letter after writing one, it will just change the letter selected in the bottom part into the one you have just entered. Copy+Paste also is not option in this situation. I do not know what "Toggle Input" does, but pressing that does not seem to help with this issue. The issue persists in any and all windows that require you to put text in.

Prior to making any changes to the text:
![keyboardInputBug_Prior](https://github.com/Ryujinx/Ryujinx/assets/78594268/1d2d92ab-c538-4c32-8219-b2262a5edb72)

After pressing a key:
![keyboardInputBug](https://github.com/Ryujinx/Ryujinx/assets/78594268/66ff37cb-cd56-4840-8270-f197358eb982)

There is a workaround however: You can enter a single letter, confirm, open the dialogue again, and it will allow you to write another letter to the right of the one you have written previously. You repeat this action until you are satisfied with the changes.

After confirming and repening the text window:
![keyboardInputBug_After](https://github.com/Ryujinx/Ryujinx/assets/78594268/3e0fc55b-8b37-43a4-8bdf-d033f1b5fed0)

I do not own any games that require text input via keyboard besides MHGU so I cannot test it in other games. However, I have not met any persons who are also using the same version of Ryujinx and MHGU who also seem to have this issue. All of my drivers are up-to-date.

### Reproduction steps

Simply interact with any window that requires input from the keyboard and press any key on your keyboard.

### Log file

[Uploading Ryujinx_1.1.1268_2024-04-08_20-09-49.log…]()

### OS

Windows 10

### Ryujinx version

1.1.1268

### Game version

1.4.0

### CPU

Ryzen 7 4800h

### GPU

NVIDIA RTX 2060 mobile (not the refreshed model)

### RAM

16GB

**Comment by gdkchan** [comment] 2024-04-08 18:48
Duplicate of #6542.

**Closed by gdkchan** 2024-04-08 18:48 UTC
Labels: bug
