### ISSUE TITLE
[Bug] Avalonia dialogs not showing properly under Full-screen or loss of focus

### ISSUE THREAD

**Issue by Sponge-bink** [Ryujinx/Ryujinx#5186] opened 2023-06-01 10:32 UTC
### Description of the issue

When Ryujinx main window is maximized and a prompt for text pops, the window will not show at all, and the game will stall since I cannot interact with the window. 

Normally in a not maximized window, it shows properly like this:

<img width="1289" alt="Screen Shot 2023-06-01 at 6 14 45 午後" src="https://github.com/Ryujinx/Ryujinx/assets/33798984/4eb5913e-5f2d-4980-8597-4564f2a3a07f">

But when the game asks for input in full-screen, the software keyboard window will not show. You can see both windows after quitting full-screen with Mission Control (see all your open windows in all spaces), and entering App Exposé (to see all the open windows in the current app), but you cannot interact with either of them. You will have to force Ryujinx to quit.

<img width="1641" alt="Screen Shot 2023-06-01 at 6 15 49 午後" src="https://github.com/Ryujinx/Ryujinx/assets/33798984/595630fa-dd15-4e81-a7cb-6d398e9eee0e">

### Reproduction steps

Launch a game that can ask for input, go in full-screen, trigger the prompt.

### Log file

[Ryujinx_1.1.848_2023-06-01_16-23-32.log](https://github.com/Ryujinx/Ryujinx/files/11624108/Ryujinx_1.1.848_2023-06-01_16-23-32.log)

### OS

macOS 12.6.6

### Ryujinx version

1.1.848

### Game version

1.0.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16 GB

### List of applied mods

60FPS

**Comment by ExE-Boss** [comment] 2023-06-02 04:08
Duplicate of #2877

**Comment by AcK77** [comment] 2023-06-03 04:36
Is that still happen with latest version of Ryujinx? (I wonder if https://github.com/Ryujinx/Ryujinx/pull/5207 would fix something)

**Comment by ExE-Boss** [comment] 2023-06-03 15:57
This would probably be fixed by <https://github.com/Ryujinx/Ryujinx/issues/2877>

**Comment by MutantAura** [comment] 2023-06-03 16:02
> This would probably be fixed by #2877

Not really relevant. This would likely affect all dialogs, the fact it is just the keyboard applet in this example is coincidence.
This issue was fixed here on Windows: https://github.com/Ryujinx/Ryujinx/pull/4663 but clearly it hasn't been a universal fix.

**Comment by Sponge-bink** [comment] 2023-06-05 22:43
> Is that still happen with latest version of Ryujinx? (I wonder if #5207 would fix something)

Yes, 

> This would probably be fixed by #2877

and no. I'm on the latest version 1.1.869 and I can reproduce this issue.

**Closed** 2023-07-21 11:24 UTC
Labels: bug
