### ISSUE TITLE
Change DLC file position will cause client crash

### ISSUE THREAD

**Issue by Catiks** [Ryujinx/Ryujinx#2545] opened 2021-08-12 04:32 UTC
## Bug Report

00:00:45.369 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/media/catik/XXX/gameDLC/DLC/METAL MAX Xeno Reborn [DLC][0100900012F23001][v0].nsp'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ryujinx.Ui.Windows.DlcWindow..ctor(Builder builder, VirtualFileSystem virtualFileSystem, String titleId, String titleName)
   at Ryujinx.Ui.Widgets.GameTableContextMenu.ManageDlc_Clicked(Object sender, EventArgs args)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### How can the issue be reproduced?

when I start a game which DLC is installed but the DLC file position is changed,the Ryujinx will crash.

### Environment?

- Ryujinx version: 1.0.6994</br>

- Game version: 1.0.0</br>
[ Replace X's with the game version at time of crash. ]
- System 
  - OS: Ubuntu 20.04
  - CPU: i9-9700K
  - GPU:Intel
  - RAM: 32G
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by Shahil-Ayato** [comment] 2021-08-12 04:46
Duplicate of #1366. Next time please check to see if your issue is reported.

**Comment by gdkchan** [comment] 2021-08-12 04:48
Closing as duplicate.

**Closed by gdkchan** 2021-08-12 04:48 UTC
