### ISSUE TITLE
Pro Controller right analog stick not recognized in <Controller Settings> without BetterJoy

### ISSUE THREAD

**Issue by EpicNicks** [Ryujinx/Ryujinx#1465] opened 2020-08-09 20:12 UTC
## Bug Report

Pro Controller right analog stick axis not recognized in Controller Settings when using Steam drivers.
Recognized in all other programs including Dolphin, Yuzu, MS Wireless GamePad Properties, etc.
I personally think it's worth looking into for best compatibility.

### What's the issue you encountered?

Pro Controller right analog stick axis not recognized in Controller Settings when using Steam drivers.

### How can the issue be reproduced?

Use a Pro Controller set up using Steam

Options 
-> Settings 
-> Input 
-> [Player 1] Configure 
-> RStick (Lt/Rt)/(Up/Dn) Unbound 
-> Move right control stick in any direction
-> Nothing happens

Note: All other buttons work including HOME, Screen Capture, and Right Stick click down

### Log file

[N/A]

### Environment?

- Ryujinx version: 1.0.5142</br>
- System Specs:
  - OS:  Windows 10
  - CPU: i7-8750H
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : No

**Comment by Nogardrevlis** [comment] 2020-11-22 10:25
Same Problem for me, right Stick gets not recognized as axis and nothing happend if you press it right or left, click works.

**Comment by LazerScythe** [comment] 2021-01-07 22:12
Yeah, same issue for me. Everything EXCEPT the right stick works in Hyrule Warriors: Age of Calamity.

**Comment by OneTwoMint** [comment] 2021-01-23 20:02
I am also experiencing this issue, using a PowerA Wireless Gamecube Controller. To the best of my awareness, I'm not using the Steam drivers.

**Comment by ShahilSharma** [comment] 2021-01-23 20:04
For now it’s best to use BetterJoy instead of the steam drivers, hopefully soon this issue can be fixed with controllers!

**Comment by OneTwoMint** [comment] 2021-01-23 20:45
Unfortunately, I'm having some difficulties using Betterjoy with this controller too. Starting to look like I'm at a bit of a dead end.

**Comment by AcK77** [comment] 2021-04-11 19:56
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by Nogardrevlis** [comment] 2021-04-12 07:18
Controller Inputs work for me on Build 1.0.6824 now on my Power A Controller , it seems fixed

**Closed** 2021-04-14 10:28 UTC
Labels: bug, gui
