### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by lijia80622** [Ryujinx/Ryujinx#6531] opened 2024-03-20 01:25 UTC
### Description of the issue

Currently, the simulator crashes frequently on my intel ultra7 155h and cannot be used at all. I don’t know if any settings need to be changed or if this is a current bug.

### Reproduction steps

If you open any game normally and select vlkan mode, it will crash. If you select opengl, the texture will be wrong.

### Log file

[Ryujinx_1.1.1239_2024-03-19_13-52-41.log](https://github.com/Ryujinx/Ryujinx/files/14659097/Ryujinx_1.1.1239_2024-03-19_13-52-41.log)
[Ryujinx_1.1.1239_2024-03-19_13-54-16.log](https://github.com/Ryujinx/Ryujinx/files/14659098/Ryujinx_1.1.1239_2024-03-19_13-54-16.log)
[Ryujinx_1.1.1239_2024-03-20_09-05-07.log](https://github.com/Ryujinx/Ryujinx/files/14659099/Ryujinx_1.1.1239_2024-03-20_09-05-07.log)
[Ryujinx_1.1.1239_2024-03-19_13-52-41.log](https://github.com/Ryujinx/Ryujinx/files/14659100/Ryujinx_1.1.1239_2024-03-19_13-52-41.log)
[Ryujinx_1.1.1239_2024-03-19_13-54-16.log](https://github.com/Ryujinx/Ryujinx/files/14659101/Ryujinx_1.1.1239_2024-03-19_13-54-16.log)
[Ryujinx_1.1.1239_2024-03-20_09-05-07.log](https://github.com/Ryujinx/Ryujinx/files/14659102/Ryujinx_1.1.1239_2024-03-20_09-05-07.log)

### OS

win11

### Ryujinx version

1.1.1239

### CPU

intel ultra7 155h 

### RAM

32G

**Comment by gdkchan** [comment] 2024-03-20 01:28
Sounds like a duplicate of #6474. and #6512.

**Comment by lijia80622** [comment] 2024-03-20 01:32
> Sounds like a duplicate of #6474. and #6512.

yes，maybe we meet same problem

**Comment by lijia80622** [comment] 2024-03-21 04:38
I tested it and found that version 1186 is still functioning properly and can be used

**Comment by MutantAura** [comment] 2024-03-22 16:36
Duplicate of #6512

**Closed by MutantAura** 2024-03-22 16:36 UTC
Labels: bug
