### ISSUE TITLE
[Bug]Repeated change tabs in setting GUI causes crash（ava edition）

### ISSUE THREAD

**Issue by CatAndBeer** [Ryujinx/Ryujinx#4589] opened 2023-03-23 17:52 UTC
### Description of the issue

**Clicking on any TAB that has already been viewed crashes**（_It doesn't matter what order it's in_）
**there is no error in clicking on an unvisited label**
![011441](https://user-images.githubusercontent.com/52226250/227284629-c49af818-dfd6-4398-b6a7-c6e81edcd7a1.png)

### Reproduction steps

This has been a bug for a long time（ava）
1.open settings
2.Click the upper and lower tabs repeatedly

### Log file

[Ryujinx_1.1.677_2023-03-24_01-14-20.log](https://github.com/Ryujinx/Ryujinx/files/11054041/Ryujinx_1.1.677_2023-03-24_01-14-20.log)

### OS

Windows11

### Ryujinx version

1.1.677

**Comment by Squall-Leonhart** [comment] 2023-03-25 07:46
Just like the last bug for this (as this is a duplicate) i cannot reproduce it, so its likely coming from external hooks.

**Comment by CatAndBeer** [comment] 2023-03-26 15:54
I found two other issues with similar logs.
[issues#4496](https://github.com/Ryujinx/Ryujinx/issues/4496)
[issue#4592](https://github.com/Ryujinx/Ryujinx/issues/4592)

**Comment by Squall-Leonhart** [comment] 2023-03-26 16:35
what language are you using?

is the windows utf8 beta support turned on?

**Comment by CatAndBeer** [comment] 2023-03-27 03:36
> what language are you using?
> 
> is the windows utf8 beta support turned on?

oh,thanks for reminding,
the use of utf-8 does solve this bug.
but there is no problem in the same environment in the virtualBox,which is strange.

**Comment by Squall-Leonhart** [comment] 2023-03-27 12:19
This will be fixed when Avalonia is updated to 11.

**Comment by AcK77** [comment] 2023-05-02 14:49
This is an Avalonia issue. We can't do anything.
Waiting for an Avalonia update is the only solution for now. Thanks.

**Closed by AcK77** 2023-05-02 14:49 UTC
Labels: bug, gui
