### ISSUE TITLE
[Feature Request] Controller UI mode

### ISSUE THREAD

**Issue by Xxxsusx** [Ryujinx/Ryujinx#7316] opened 2024-09-16 21:10 UTC
### Overview

Basically the concept of this feature would be something similar to steam's Big Picture mode or some UI for selecting stuff and open games by using the controller since this would give the person a feeling they're like playing on some platform or an entire new console.

### Smaller details

Well, I'm not sure how the feature can be implemented in Ryujinx but this is just a suggestion so I thought it would be a nice idea

### Nature of request

im asking about a feature of the UI to be also used with a controller

### Why would this feature be useful?

So people can feel they're on some kind of console

**Comment by MetrosexualGarbodor** [comment] 2024-09-16 23:45
Duplicate of #2793

**Closed by MetrosexualGarbodor** 2024-09-16 23:45 UTC
Labels: enhancement
