### ISSUE TITLE
[Feature Request] Save & Load anywhere

### ISSUE THREAD

**Issue by playgithub** [Ryujinx/Ryujinx#7337] opened 2024-09-21 14:04 UTC
### Overview

Like a snapshot, which can be resumed.
It could be very helpful for some games that needs practice at special point.

### Smaller details

e.g.

"Mario Kart 8 Delux"

If you want to practice at a fixed position on the road,
you can only pracice once a round,
that's not efficient.

If save & load anywhere is supported, it would be super efficient.

### Nature of request

Cool hacking

### Why would this feature be useful?

Much more efficient for games that needs practice

**Comment by ekuland** [comment] 2024-09-21 14:15
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1765
Don't hold out hopes.

**Closed by ekuland** 2024-09-21 14:15 UTC
Labels: enhancement
