### ISSUE TITLE
DLC window does not appear if files were moved

### ISSUE THREAD

**Issue by FelicitusNeko** [Ryujinx/Ryujinx#1981] opened 2021-01-30 19:42 UTC
## Bug Report

DLC window does not appear if files were moved

### What's the issue you encountered?

I've done some reorganising of my NSP directory. Unfortunately, because updates and DLC were moved to different places, Ryujinx now throws a non-fatal exception if I try to open the DLC manager for any game for which DLC was registered. Conversely, any games that had updates registered to them simply had them unregistered, allowing me to add them again.

### How can the issue be reproduced?

1. Register a DLC NSP to a game using the "Manage DLC" right-click option.
2. Close the DLC manager.
3. Move the DLC file.
4. Try to open the DLC window again through the "Manage DLC" right-click option.

### Log file

[Ryujinx_1.0.6455_2021-01-30_15-34-57.log](https://github.com/Ryujinx/Ryujinx/files/5898599/Ryujinx_1.0.6455_2021-01-30_15-34-57.log)

### Environment?

- Ryujinx version: 1.0.6455
- Game version: N/A
- System Specs:
  - OS: Win10 Pro 20H2
  - CPU: Intel i7-8700K
  - GPU: NVIDIA GTX 1050
  - RAM: 16GB
- Applied Mods : N/A

### Additional context?

N/A

**Comment by EmulationFanatic** [comment] 2021-01-30 19:48
You know may know this already, but you can fix this by deleting the dlc.json file in appdata\roaming\ryujinx\games\(ID of game with the issue)\

**Comment by EmulationFanatic** [comment] 2021-01-30 19:52
Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/1366

**Closed by EmulationFanatic** 2021-01-30 19:52 UTC
