### ISSUE TITLE
Add vertical flip/mirror

### ISSUE THREAD

**Issue by HerrIrrtum** [Ryujinx/Ryujinx#1461] opened 2020-08-08 17:41 UTC
#### Overview:
Some games have a mirrored vertical Axis - i.e. "Fire Emblem: Three Houses" or "Axiom Verge".</br>
Other games work fine (i.e. Mario Kart 8,  Lost Sphear).</br>
It appears, that's a known problem and sometimes it's suggested to update the video driver, which sometimes but not always helps. Switching between handheld/docked mode doesn't help either. 

#### Smaller Details: 

Just to be more clear. When taking a screenshot, loading this into an image editing software (i.e. Gimp) and use "vertical mirror" the screenshot looks correct.

#### Technical specifications

  * **Version Ryujinx:** ryujinx-git r1236.e36e97c6-1 (and versions before)
  * **OS:** Linux, Kernel 5.7.12
  * **Video driver:** Mesa 20.1.5 / radeonsi (POLARIS10, DRM 3.37.0, 5.7.12-arch1-1, LLVM 10.0.1)
  * **Graphics Card:** Advanced Micro Devices, Inc. [AMD/ATI] Ellesmere [Radeon RX 580X]

#### Nature of Request:  

- Addition
  - Simple Solution. Add an option to vertically flip/mirror the screen.
  - In the long term: Try to detect this and "autoflip",

### Why would this feature be useful?
You can't playing games upside down without getting insane. Would be quite helpful to stay sane.

**Comment by jduncanator** [comment] 2020-08-09 00:14
This is a bug that should be fixed in the emulator, rather than time spent adding a workaround. 

If you could open an issue, much like this one, explaining what issues you have with those games (Eg. Flipping), which games it affects, what configuration and drivers your machine is running, then we can take a look.

**Comment by gdkchan** [comment] 2020-08-09 00:17
fwiw this happens due to the like of viewport swizzle support (NV_viewport_swizzle). It does viewport flipping on the shader when it is not supported, but the lack of proper shader specialization is probably making it fail in some cases.

**Comment by HerrIrrtum** [comment] 2020-08-09 15:00
@jduncanator said:
> This is a bug that should be fixed in the emulator, rather than time spent adding a workaround.

I was thinking about this too, but decided against it (for now), because: 

  * The problem doesn't seem to exist for people with a decent Nvidia card on Windows.
  * i.e. when looking at Fire Emblem: Three Houses on the "games database" the screenshots there do not show this problem
    * Talking about Fire Emblem: The nv videos show correctly on Linux with AMD Hardware and Mesa drivers, but the menues do not, so it's even more complicated, and you can't go with a simple "check which game is running"-approach
  * For now developers may focus on other things than specific AMD driver issues on a right now not so popular platform (that's what I  imagine at least) - plus given the fact that the emu works on AMD cards on Linux while the Switch operates on Nivida hardware I am most impressed it works at all in such nice quality, so I won't hassle the devs right now with "figure my specific driver issue" tasks... 
  * What I didn't tell you before. In Yuzu it's the same (but Axiom Verge is the only title which works in it at all on Linux with AMD hardware), which makes things even more look like: it's not your problem but an issue with AMD gfx on Linux in this very specific edge case (and I am using the newest Kernel with the newest drivers here: Arch Linux btw.)

Tl'dr: As it looks like a problem with a combination of a not sooooo popular OS-platform combined with a non-ideal Hardware/driver configuration, I think at the current point in time the workaround would be a matter of like 15min of coding while going to the exotic root of it may take days. I do not intend to plague the devs with this right now.

That's why I'd stick to a workaround feature request. Do you still think, considering all I wrote, I should open this as a bug report,  @jduncanator  ?

**Comment by HerrIrrtum** [comment] 2020-09-26 08:57
Hey,
I've checked out r1286.16e9d156 this morning and guess what:
"Fire Emblem: Three Houses" and "Axiom Verge" render just fine now.

Whoever did this for whatever reason: Thank you!!

If some other once affected users can confirm the same, I think this request may be
closed as "irrelevant" :)

**Comment by pPkMnh4to8994h** [comment] 2020-09-26 08:58
> Hey,
> I've checked out r1286.16e9d156 this morning and guess what:
> "Fire Emblem: Three Houses" and "Axiom Verge" render just fine now.
> 
> Whoever did this for whatever reason: Thank you!!
> 
> If some other once affected users can confirm the same, I think this request may be
> closed as "irrelevant" :)

It was fixed week ago, this can be verified through the changelog.
I can confirm this as well.

**Comment by HerrIrrtum** [comment] 2020-09-26 09:04
Yes, seems like commit [#1556](https://github.com/Ryujinx/Ryujinx/pull/1549) fixed it. 
@gdkchan  is da man! Thanks again!

**Closed** 2020-09-26 09:13 UTC
Labels: enhancement, gpu, gui

**Comment by jduncanator** [comment] 2020-09-26 09:28
Glad to here your issue was resolved! Thanks for following up and marking the issue as resolved :)
