### ISSUE TITLE
[Bug] GPU Scheduling Issue Crashing Gamestream?

### ISSUE THREAD

**Issue by QuirkyKirkHax** [Ryujinx/Ryujinx#6408] opened 2024-03-05 14:53 UTC
### Description of the issue

Whenever Ryujinx is launched and shaders have to be compiled, it crashes Sunshine and NVidia gamestream.  I am unsure of what specifically is happening here, but it seems to be a new issue within the last couple of months or so...I am assuming its GPU related since it is doing the shader compilation as well as the video stream encoding.  Given that this seems to only happen with Ryujinx, I think it is safe to say this is a Ryujinx issue and not a Sunshine/Gamestream issue.  This also happens with every game I have tried in the past couple days.

### Reproduction steps

Connect to PC via sunshine/moonlight, launch game over Ryujinx, and during shader compilation the stream will crash.  You can launch back into the stream, but after a while the stream crashes again (presumably due to shader compilation on the fly)

### Log file

[Ryujinx_1.1.1217_2024-03-05_08-40-32.log](https://github.com/Ryujinx/Ryujinx/files/14497012/Ryujinx_1.1.1217_2024-03-05_08-40-32.log)
[Ryujinx_1.1.1217_2024-03-05_08-42-25.log](https://github.com/Ryujinx/Ryujinx/files/14497013/Ryujinx_1.1.1217_2024-03-05_08-42-25.log)

### OS

Windows 10

### Ryujinx version

1.1.1217

### Game version

2.1.0

### CPU

AMD Ryzen 9 7900X

### GPU

NVidia RTX 3070

### RAM

32GB

### List of applied mods

None outside of the Title Update.  Though this happens on every game with Ryujinx.

### Additional context?

This was not always a problem with Ryujinx.  Something borked within the last 2 or 3 months where this crash began occurring...

**Comment by piplup55** [comment] 2024-03-05 14:59
duplicate of #6383

**Closed by piplup55** 2024-03-05 14:59 UTC
Labels: bug
