### ISSUE TITLE
[Bug] The Legend of Zelda: Breath of the Wild visual glitchs and blueish smoke

### ISSUE THREAD

**Issue by JJ-Singh** [Ryujinx/Ryujinx#6088] opened 2024-01-04 19:24 UTC
### Description of the issue

Blueish smoke/fog in BOTW every time you break a vase or when you find a korok seed under a stone. There are also other glitchs in the game. I'll add screenshot everytime I encounter one. 

### Reproduction steps

Try to break vases in the Temple of Time.

### Log file

[Ryujinx_1.1.1104_2024-01-04_13-48-20.log](https://github.com/Ryujinx/Ryujinx/files/13834573/Ryujinx_1.1.1104_2024-01-04_13-48-20.log)
[Ryujinx_1.1.1104_2024-01-04_14-09-13.log](https://github.com/Ryujinx/Ryujinx/files/13834574/Ryujinx_1.1.1104_2024-01-04_14-09-13.log)
[Ryujinx_1.1.1104_2024-01-04_14-11-49.log](https://github.com/Ryujinx/Ryujinx/files/13834575/Ryujinx_1.1.1104_2024-01-04_14-11-49.log)

### OS

MacOS 14.2

### Ryujinx version

1.1.1104

### Game version

1.6.0

### CPU

M1 Max

### GPU

M1 Max

### RAM

32 GB

**Comment by JJ-Singh** [comment] 2024-01-04 19:26
<img width="912" alt="Screenshot 2024-01-04 at 2 17 55 PM" src="https://github.com/Ryujinx/Ryujinx/assets/22187754/66eebbc7-05e3-46b9-a7c9-97cd4f92cfcf">

**Comment by JJ-Singh** [comment] 2024-01-04 20:20
<img width="984" alt="Screenshot 2024-01-04 at 3 14 05 PM" src="https://github.com/Ryujinx/Ryujinx/assets/22187754/44887c50-4255-4498-bf86-79b698df86bf">

**Comment by JJ-Singh** [comment] 2024-01-04 20:21
Also occasionally game goes to infinite loading(it's not freezing but stays at loading screen for minutes).

**Comment by Vosa23** [comment] 2024-01-04 21:46
Yeah, I have the very same issue with the loading screen - the game does not freeze but stays on the loading screen. (Macbook M1, Ventura)

**Comment by JJ-Singh** [comment] 2024-01-06 18:03
<img width="1340" alt="Screenshot 2024-01-06 at 1 01 52 PM" src="https://github.com/Ryujinx/Ryujinx/assets/22187754/3d518c4b-6490-4818-8c1b-1760d5456e02">
Missing Icons.

**Comment by JJ-Singh** [comment] 2024-01-07 10:51
<img width="1340" alt="Screenshot 2024-01-07 at 5 46 25 AM" src="https://github.com/Ryujinx/Ryujinx/assets/22187754/147796c2-c8db-4946-b9f1-398596c045ea">

[Ryujinx_1.1.1104_2024-01-07_04-36-42.log](https://github.com/Ryujinx/Ryujinx/files/13853040/Ryujinx_1.1.1104_2024-01-07_04-36-42.log)
The wrong hue of snow effects.

**Comment by funk4d** [comment] 2024-01-07 16:42
> Yeah, I have the very same issue with the loading screen - the game does not freeze but stays on the loading screen. (Macbook M1, Ventura)

Disabling hypervisor helped me.

**Comment by JJ-Singh** [comment] 2024-01-07 17:06
> Disabling hypervisor may help you.
Yes, it does help with the loading screen issues but the game becomes unplayable. I have M1 Max 32 core and I get 20 FPS 😂

**Comment by JJ-Singh** [comment] 2024-01-07 17:08
<img width="1340" alt="Screenshot 2024-01-07 at 8 14 15 AM" src="https://github.com/Ryujinx/Ryujinx/assets/22187754/68cac8ed-e3e2-4ba7-b8d1-99f9477dec91">

Wrong hue of smoke/fog/dust effects.

**Comment by funk4d** [comment] 2024-01-07 17:21
> > Disabling hypervisor may help you.
> 
> Yes, it does help with the loading screen issues but the game becomes unplayable. I have M1 Max 32 core and I get 20 FPS 😂

Same, 20-25 fps on M1 Pro 14' 🤷‍♂️

**Comment by JJ-Singh** [comment] 2024-01-08 09:29
[Ryujinx_1.1.1104_2024-01-08_02-47-36.log](https://github.com/Ryujinx/Ryujinx/files/13858228/Ryujinx_1.1.1104_2024-01-08_02-47-36.log)

Link glitches and is thrown towards the sky.

**Comment by JJ-Singh** [comment] 2024-01-16 16:09
I hope this can be fixed. I think the game looks much better on Ryujinx than anywhere else.

**Comment by gdkchan** [comment] 2024-03-27 02:51
Duplicate of #5963.

**Closed by gdkchan** 2024-03-27 02:51 UTC
Labels: bug, gpu, os:macOS
