### ISSUE TITLE
[Feature Request] Game by Game "Profiles Settings"

### ISSUE THREAD

**Issue by BigBoss320** [Ryujinx/Ryujinx#6400] opened 2024-03-04 21:42 UTC
### Overview

Hello ! Just suggesting a feature that can avoid having to change everytime the settings when changing games.
Right Clicking on a game on the list shows the actions we can do. The new one can be "Profile settings" or "Properties" or something else. These settings can be chosen independently from the main settings.

### Smaller details

Example: i want to play all my games using Vulkan in native x1, but one of them using OpenGL in 4k. So I have to set it in the "Game's properties".
(That option can also be merged with the manage update/DLC/Cheats/mods as they can be considered as properties.)

### Nature of request

Greater customization of individual settings

### Why would this feature be useful?

This can improve the experience without having to change the main settings every time. Because with the same settings, games can have different performances. Having individuals settings, help us to find the best ones for each game independently, and save time.

**Comment by MutantAura** [comment] 2024-03-04 21:51
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1796

**Closed by MutantAura** 2024-03-04 21:51 UTC

**Comment by BigBoss320** [comment] 2024-03-04 21:57
never thought that the feature was asked over 3 years ago, and is still not yet implemented.

**Comment by TSRBerry** [comment] 2024-03-04 22:07
You do know that this is an open source project and nobody is paid for their work here, right?
I'd understand that comment if you were talking about a product that you paid for and is actively developed by some company.

I'd personally love to spend more time developing for Ryujinx, but unfortunately that's just not possible right now.
But comments like this are at best demotivating and nobody goes "oh yeah we really need to do this right now" after reading them.
