### ISSUE TITLE
Pokémon Sw/Sh LAN issue 

### ISSUE THREAD

**Issue by Doooooozi** [Ryujinx/Ryujinx#2313] opened 2021-05-26 08:01 UTC
## Bug Report
#2074 
it dose not connect / found my switch even if they are conncected on the same network and has the same version, the only differences i could found is that on ryujinx when i look for a link trade or a battle through the ycomm functions the sticker that appear on the bottom left it happears many times but on the switch it happear just one time. 

I checked the log files and compared them with successful files and failed files, and found this information in the logs of connection failures

- HLE.OsThread.15 ServiceLdn CreateNetworkCommon: Locally hosted proxy server was not externally reachable. Proxying through the master server instead. Expect higher latency

### How can the issue be reproduced?

i don't know, i know that this issue is happening to a lot of people，I have 131 people have failed to connect and 2 people have succeeded

### Log file

This is a log of failed connections
[Ryujinx_1.0.0-ldn2.3_2021-05-26_03-43-23.log](https://github.com/Ryujinx/Ryujinx/files/6544794/Ryujinx_1.0.0-ldn2.3_2021-05-26_03-43-23.log)
This is someone else's successful connection log
[successful connection log.txt](https://github.com/Ryujinx/Ryujinx/files/6544851/successful.connection.log.txt)

### Environment?

- Ryujinx version: 1.0.0-Ldn2.3-win_x64
- Game version: Pokémon Shield 1.3.2
- Switch Firmware: 12.0.2
- System Specs:
  - OS: Microsoft Windows 10.0.19042 (X64)
  - CPU:  Intel(R) Core(TM) i5-9400F CPU @ 2.90GHz ; 6 logical
  - GPU:  AMD Vega56 8GB
  - RAM:  32GB
- Applied Mods : No

**Comment by AcK77** [comment] 2021-06-05 20:59
Duplicate of #2074

**Closed by AcK77** 2021-06-05 20:59 UTC
