### ISSUE TITLE
Dual Joy-Con Motion Controls not working in Ryujinx with BetterJoy set up properly

### ISSUE THREAD

**Issue by turntable97** [Ryujinx/Ryujinx#2484] opened 2021-07-17 12:07 UTC
## Bug Report

Dual Joy-Con Motion Controls not working in Ryujinx with BetterJoy set up properly.

### What's the issue you encountered?

When I tried to set up Dual Joy-Cons gyro for Skyward Sword HD and started the game, the motion controls didn't work at all.

### How can the issue be reproduced?

You can try different input settings, setting the server exactly like in BetterJoy but it seems the motion controls don't work at all when trying to play with Dual Joy-Cons. There seems to be a problem between the communication of Ryujinx and BetterJoy as in Yuzu playing with Dual Joy-Cons and motion controls is no problem at all (e.g. in Skyward Sword HD).

### Environment?

- Ryujinx version: 1.0.6970</br>
- Game version: 1.0.0</br>
- Applied Mods : [ No ]

**Comment by AcK77** [comment] 2021-07-17 12:57
Duplicate of #2127

**Closed by AcK77** 2021-07-17 12:57 UTC
