### ISSUE TITLE
[Bug]macOS playing Pokémon Scarlet v3.0.1 often gets stuck

### ISSUE THREAD

**Issue by hopesyj** [Ryujinx/Ryujinx#6347] opened 2024-02-22 14:35 UTC
### Description of the issue

Every time I open the game, it will freeze after playing for a while, the frame rate will become 0, and I can only restart the game.
ProdKey & Firmware Version：17.0.0
<img width="1280" alt="image" src="https://github.com/Ryujinx/Ryujinx/assets/37163020/12b19cfe-09aa-4fff-a39a-ea7ed8f415d3">

### Reproduction steps

open Pokémon Scarlet v3.0.1 ,  play for a while（about 3-5 minutes）

### Log file

[Ryujinx_1.1.1204_2024-02-22_22-29-42.log](https://github.com/Ryujinx/Ryujinx/files/14375219/Ryujinx_1.1.1204_2024-02-22_22-29-42.log)

### OS

macOS

### Ryujinx version

1.1.1204

### Game version

V3.0.1

### CPU

M3MAX

### GPU

M3MAX

### RAM

64G

**Comment by MutantAura** [comment] 2024-03-07 20:30
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5976

**Closed by MutantAura** 2024-03-07 20:30 UTC
Labels: bug
