### ISSUE TITLE
[Feature Request] Cache game info on listing loading

### ISSUE THREAD

**Issue by nixxou** [Ryujinx/Ryujinx#5885] opened 2023-11-02 17:23 UTC
### Overview

On startup, Ryujinx load games. Depending of the number of game (or the speed of the device where they are stored), it could take some time.
It would be nice if thoses loaded games stays in cache, to make quicker loading

### Smaller details

One easy way i have in mind is that, if the application is loaded from a file, it should be easy to store file size and modification date and pull info from cache if there is no change ?

### Nature of request

Improvement

### Why would this feature be useful?

my games stored on a network device that can be quite slow, usually when i go serious about an app, i move it to a local folder, but the auto loading stuff is annoying.

**Comment by MutantAura** [comment] 2023-11-02 18:11
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3285

**Closed by MutantAura** 2023-11-02 18:11 UTC
