### ISSUE TITLE
Emulator video feed freezes

### ISSUE THREAD

**Issue by XenderLord** [Ryujinx/Ryujinx#2012] opened 2021-02-11 17:29 UTC
### What's the issue you encountered?

The video feed freezes when i want to play mariokart 8 deluxe multiplayer with LDN with 2 controllers.
my friend is connected to my pc through parsec (because his pc is very weak) and is playing with keyboard (because he can't buy a controller from his parents). If we play by ourselfs not LDN everything works perfectly but if we want to play with someone else through LDN the video feed just freezes but audio still plays, audio doesn't react to any button presses though.

### How can the issue be reproduced?

Just try to play LDN with 2 controllers. I don't think parsec is the issue because other games/gamemodes (within mariokart 8 deluxe) works perfectly fine on the emulator.

### Log file

[Ryujinx_1.0.0-ldn2.1_2021-02-11_18-17-48.log](https://github.com/Ryujinx/Ryujinx/files/5967274/Ryujinx_1.0.0-ldn2.1_2021-02-11_18-17-48.log)

### Environment?

- Ryujinx version: 1.0.0-ldn2.1
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Intel Core I7-8700
  - GPU: NVIDIA Geforce RTX 3070
  - RAM: 16GB + 20GB Pagefile
- Applied Mods : No

### Additional context?

![obraz_2021-02-11_182641](https://user-images.githubusercontent.com/46809371/107673894-b0151d00-6c96-11eb-9c55-87acf9c91aae.png)

Video:
https://drive.google.com/file/d/1u8UDaWk6WB1O4_h8z-U875goMt8otNSh/view?usp=sharing

**Comment by EmulationFanatic** [comment] 2021-02-11 18:25
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1499

**Closed by EmulationFanatic** 2021-02-11 18:25 UTC
Labels: applet, bug
