### ISSUE TITLE
Keys not installed error

### ISSUE THREAD

**Issue by KnightDragon140** [Ryujinx/Ryujinx#2531] opened 2021-08-05 19:55 UTC
I followed the tutorial at https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#initial-setup---placement-of-prodkeys and I copied my prod.keys file into the system folder as instructed. I then tried installing the firmware and it won't do it as it says that it could not find my prod.keys file.

![part 1](https://user-images.githubusercontent.com/84480265/128412768-8f57d4de-256a-4388-ac61-9237d889f2f8.png)
-------------------------------------------------------------------------------------------------------------------------------------------
![part 2](https://user-images.githubusercontent.com/84480265/128412814-b4a0df16-e6ed-4832-9503-30c78f336590.png)
-------------------------------------------------------------------------------------------------------------------------------------------
![part 3](https://user-images.githubusercontent.com/84480265/128412832-3266ef8b-0e35-4811-b854-cab175a58a0f.png)

**Comment by gdkchan** [comment] 2021-08-05 19:57
Whats the version of the firmware you're trying to install? Maybe you don't have the latest keys.

**Comment by AcK77** [comment] 2021-09-11 21:18
I'm pretty sure the issue is about outdated keys.
Since there is no answer from the user, I close it. I'll reopen it if it's a real issue.
Thanks.

**Closed by AcK77** 2021-09-11 21:18 UTC
Labels: bug, gui
