### ISSUE TITLE
[Bug] Tiny Thor emulator crashes while loading

### ISSUE THREAD

**Issue by cwscws** [Ryujinx/Ryujinx#5810] opened 2023-10-16 14:42 UTC
### Description of the issue

Some seconds after starting the game and displaying the GAMEFORGE logo the emulator crashes (quits) with the standard MacOS crash report.

### Reproduction steps

Just load

### Log file

[Ryujinx_1.1.1051_2023-10-16_16-40-26.log](https://github.com/Ryujinx/Ryujinx/files/12918147/Ryujinx_1.1.1051_2023-10-16_16-40-26.log)

### OS

MacOS 13.5.2

### Ryujinx version

1.1.1051

### Game version

1.0.2 (and 1.0)

### CPU

M1

### GPU

M1

### RAM

8 GB

**Comment by AcK77** [comment] 2023-10-18 04:53
Duplicate of #5665

**Closed** 2023-10-18 04:54 UTC
Labels: bug
