### ISSUE TITLE
[Bug] Mouse cursor doesn't hide anymore

### ISSUE THREAD

**Issue by ElGranSmokio** [Ryujinx/Ryujinx#4759] opened 2023-05-02 02:57 UTC
### Description of the issue

Before one of the recent updates the cursor used to hide itself after a few seconds on fullscreen. Now it doesn't anymore.

### Reproduction steps

Switch to fullscreen, mouse won't hide automatically.

### Log file

I deleted the latest version and now I'm using one from a month ago that doesn't have this issue. If it's really necessary I can download it again. 

### OS

Windows 10

### Ryujinx version

1.1.743

**Comment by gdkchan** [comment] 2023-05-02 03:00
did you enable this option in the settings?

**Comment by OldManKain** [comment] 2023-05-02 03:03
I cannot reproduce, just tested 1.1.743 on both GTK and Ava hides the mouse cursor on idle.

**Comment by ElGranSmokio** [comment] 2023-05-02 05:31
@gdkchan Sorry, I didn't notice that a new option was added. Sucks that the previous behavior was changed though, in my opinion it should auto hide by default (which is how it always worked).

**Comment by OldManKain** [comment] 2023-05-02 05:33
Closing as Resolved.

**Comment by gdkchan** [comment] 2023-05-02 05:33
It never auto-hide by default, you had to check the "Hide mouse cursor on idle" option. Now there are 3 possible options (never, on idle and always).

**Closed by OldManKain** 2023-05-02 05:33 UTC
Labels: bug

**Comment by ElGranSmokio** [comment] 2023-05-02 05:34
Then it changed my preference since I didn't touch the settings menu at all after updating. Anyway, sorry.

**Comment by gdkchan** [comment] 2023-05-02 05:37
Yes, it probably changed it on the latest version since the old option doesn't exist anymore, now there's 3 options, so it probably reverted to the default one which is "Never".
