### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by juanestragon** [Ryujinx/Ryujinx#5032] opened 2023-05-20 10:45 UTC
### Overview

It would be great that ryujinx detect both joycons as one

### Smaller details

In the controller configuration will appears: Joycon(R), Joycon(L) and Joycon(pair) as yuzu.

### Nature of request

It is imposible to play with both joycons conected to the pc without external software

### Why would this feature be useful?

it would be useful because of the "switch experience" and fast configuration.

**Comment by MutantAura** [comment] 2023-05-20 10:46
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3293

**Closed by MutantAura** 2023-05-20 10:46 UTC
