### ISSUE TITLE
[Bug] Pokemon Scarlet & Violet crashing upon language selection menu (Apple Silicon)

### ISSUE THREAD

**Issue by Lacrymossa** [Ryujinx/Ryujinx#5262] opened 2023-06-08 07:33 UTC
### Description of the issue

I've tried running Pokemon Violet and Scarlet on Firmware 15.0.1 and no matter what I do, the emulator crashes after I pick a language and the avatar selection menu comes up. 

https://github.com/Ryujinx/Ryujinx/assets/29276752/e8c6aa57-1bea-4155-ad7d-ad6cb406dfa5

### Reproduction steps

1. Use Ryujinx version 1.1.869 on Apple Silicon.
2. Launch either Pokemon Scarlet or Violet, the version or selected DLCs notwithstanding.
3. Pick English from the language selection menu (or Spanish, which I've also tried)

### Log file

[Ryujinx_1.1.869_2023-06-08_10-20-52.log](https://github.com/Ryujinx/Ryujinx/files/11685257/Ryujinx_1.1.869_2023-06-08_10-20-52.log)

### OS

macOS Ventura 13.0

### Ryujinx version

1.1.869

### Game version

1.0.0 & 1.3.1

### CPU

Apple M2

### GPU

Apple M2

### RAM

8 GB

### List of applied mods

None.

**Comment by gdkchan** [comment] 2023-06-08 14:51
Duplicate of #5068.

**Closed by gdkchan** 2023-06-08 14:51 UTC
Labels: bug
