### ISSUE TITLE
[Bug] (maybe) Shader issue (or idk)

### ISSUE THREAD

**Issue by hermitoff** [Ryujinx/Ryujinx#6896] opened 2024-05-29 09:03 UTC
### Description of the issue

Today I switched from my Windows laptop to a Mac book pro M1 and when I tried to start Animal Crossing I have what I think is a problem with the shader when I'm in a building, also my game has crashed randomly but I can't reproduce this crash anymore.
Note : Everything was working perfectly on Windows, I just copied my save file to continue on my island from Windows to my Mac.
I tried the firmware 18.0.0 and 17.0.1 but I have the same issue.
<img width="1440" alt="Capture d’écran 2024-05-29 à 19 38 41" src="https://github.com/Ryujinx/Ryujinx/assets/82811865/cdc51947-9e6e-42eb-8435-0764a9504221">
(Don't judge my house I'm just getting started)

### Reproduction steps

1. Migrate data from a Windows save files to my Mac
2. Simply start the game and enter a building

### Log file

[Ryujinx_1.1.1325_2024-05-29_17-36-09.log](https://github.com/Ryujinx/Ryujinx/files/15481645/Ryujinx_1.1.1325_2024-05-29_17-36-09.log)
[Ryujinx_1.1.1325_2024-05-29_19-07-07.log](https://github.com/Ryujinx/Ryujinx/files/15481648/Ryujinx_1.1.1325_2024-05-29_19-07-07.log)
[Ryujinx_1.1.1325_2024-05-29_19-24-14.log](https://github.com/Ryujinx/Ryujinx/files/15481649/Ryujinx_1.1.1325_2024-05-29_19-24-14.log)

### OS

MacOS Sonoma 14.5

### Ryujinx version

1.1.1325

### Game version

2.0.6

### CPU

M1

### GPU

M1

### RAM

8Go

### List of applied mods

N/A

But I have the 3 DLC

**Comment by hermitoff** [comment] 2024-05-29 10:48
Oh and by the way I'm sorry I don't use Discord, So I couldn't go and see if this was a known problem.

**Comment by MutantAura** [comment] 2024-05-30 13:54
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5308

**Closed by MutantAura** 2024-05-30 13:54 UTC
Labels: bug
