### ISSUE TITLE
[Feature Request] Native frame limiter (VSync off)

### ISSUE THREAD

**Issue by VSofter** [Ryujinx/Ryujinx#4514] opened 2023-03-06 02:24 UTC
### Overview

Native frame limiter with no VSync enabled would be very helpful as neither Radeon Chill nor RTSS can limit fps reliably when Ryujinx VSync is off (titles are rendering in 200+ fps so gameplay speed is enormously fast).

### Smaller details

GPU is AMD RX 6900XT. Ryujinx render is Vulkan.
Titles to reproduce: almost all, but for example: Yoshi's Crafted World, Slay the Spire, Horizon Chase Turbo.

### Nature of request

None.

### Why would this feature be useful?

None.

**Comment by MetrosexualGarbodor** [comment] 2023-03-06 02:26
Duplicate of #4164

**Closed by MetrosexualGarbodor** 2023-03-06 02:26 UTC
