### ISSUE TITLE
[Bug] Steam + Ryujinx does not detect DualSense and Motion Control does not work.

### ISSUE THREAD

**Issue by Parandreu** [Ryujinx/Ryujinx#5015] opened 2023-05-19 09:13 UTC
### Description of the issue

I open Ryujinx via Steam for screenshot keybindings with DualSense (with Playstation settings support within Steam).

But then when choosing the controller inside the Ryujinx it doesn't detect the DualSense, just an XBOX 360 controller and the motion doesn't work.

If I open Ryujinx without Steam, the motion works but I can't get the light photos from Steam.

I have to choose between motion controls or being able to take the screenshot from the controller.

### Reproduction steps

Connect the DualSense to the computer via bluetooth.

Open Ryujinx through Steam as a non-steam game.

On the Ryujinx go to Options > Settings > Input > Player 1 Configure > select Input Device and instead of "PS5 Controller" it says "Controller (XBOX 360 for Windows)" and Motion Controls doesn't work.

Without Steam: https://i.imgur.com/0d35crp.png
With Steam: https://i.imgur.com/3WEMtq4.png

### Log file

00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.035 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.039 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.039 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.040 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.041 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.041 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.042 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2206
00:00:00.042 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.043 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.043 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.045 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.046 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.046 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.046 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.046 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.046 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.046 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.046 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.046 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.047 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.047 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.048 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.048 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.048 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.048 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.053 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.806
00:00:00.057 |N| Application Print: Operating System: Microsoft Windows 10.0.19045 (X64)
00:00:00.057 |N| Application Print: CPU: AMD Ryzen 5 5600X 6-Core Processor ; 12 logical
00:00:00.058 |N| Application Print: RAM: Total 32684 MiB ; Available 29187 MiB
00:00:00.060 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Guest, Stub
00:00:00.060 |N| Application PrintSystemInfo: Launch Mode: Portable

### OS

Windows 10

### Ryujinx version

1.1.806

**Comment by MutantAura** [comment] 2023-05-19 16:37
Does the steam pass-through actually expose motion? It sounds like it isn't considering its providing an Xbox controller which ofc won't have a gyro. I don't think this is strictly a Ryujinx issue.

**Comment by fatjesusonabike** [comment] 2023-05-19 17:30
I think the Dualsense supports Cemuhook. Have you tried using BetterJoy?

**Comment by Parandreu** [comment] 2023-05-19 22:52
> Does the steam pass-through actually expose motion? It sounds like it isn't considering its providing an Xbox controller which ofc won't have a gyro. I don't think this is strictly a Ryujinx issue.

That's right, the problem must be Steam, motion control doesn't work on Steam + yuzu either.

On yuzu I can take photos from the controller with the mute button of the DualSense (the share button of the Xbox series X controller doesn't work) without Steam.
In Ryujinx I only see F8 to take screenshots. With Steam I can take photos with the Xbox and DualSense controllers.

But on both emulators the photos are still 2MB instead of 200KB like on Steam.

Thank you so much.

**Comment by Kyle-Leu** [comment] 2023-05-20 02:49
It is not a bug. Just because the Steam input converts your ds5 to a xbox input for all the apps.You could disable the Steam input in your Steam settings.

**Comment by MutantAura** [comment] 2023-05-20 14:57
Closing as it doesn't seem like an issue on our end. I think in general you're asking for: https://github.com/Ryujinx/Ryujinx/issues/3423

**Closed by MutantAura** 2023-05-20 14:57 UTC
Labels: bug, input
