### ISSUE TITLE
vulkan configuration causing stack smashing

### ISSUE THREAD

**Issue by Brunz40** [Ryujinx/Ryujinx#4016] opened 2022-12-05 00:33 UTC
## Bug Report

Whenever i try to load a game on ryujinx using vulkan, my commandline outputs the error : ***smash stacking detected*** and ryujinx is shut down

### What's the issue you encountered?

Trying to run anything on ryujinx just make it close, and the terminal says stack smashing detected

### How can the issue be reproduced?

Running a game on ryujinx with the vulkan setting

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.415</br>

- Game version: any </br>
- System Specs:
  - OS:ubuntu 22.04.1LTS
  - CPU: amd ryzen 7 3700u
  - GPU: radeon vega 10
  - RAM: 16gb
- Applied Mods : no

### Additional context?

N/A

**Comment by TSRBerry** [comment] 2022-12-05 00:43
You can get the actual error if you set this env var: `DOTNET_EnableAlternateStackCheck=1`

**Comment by TSRBerry** [comment] 2022-12-05 13:47
@Brunz40 We can't really work with this bug report as long as the error message is just
> ***smash stacking detected*** 

Could you edit your report with the env var (as I replied before) set, so the correct error message is included instead?

**Comment by Deytron** [comment] 2023-01-05 15:03
Since the issue is still open, I'm taking this opportunity to report that I have the same issue.

**Environment?**

    Ryujinx version: 1.1.500

    Game version: any

    System Specs:
        OS: EndeavourOS Linux x86_64
        CPU: AMD Ryzen 5 3600X
        GPU: NVidia GeForce RTX 2060
        RAM: 32GB

    Applied Mods : no

**Some more informations**

Here's the error message : 

`00:00:00.701 |W| GUI.RenderLoop Gpu CreateInstance: Missing layer VK_LAYER_KHRONOS_validation`

Using NVidia driver version 525.60.11. Could this be a regression from Nvidia ? Used to work fine before.
Worth noting : the issue does not happen on Windows

**Comment by TSRBerry** [comment] 2023-01-05 15:06
If you could add a Ryujinx log that would help a lot

**Comment by Deytron** [comment] 2023-01-05 19:22
My bad, forgot to do that

[Ryujinx_1.1.500_2023-01-05_20-17-27.log](https://github.com/Ryujinx/Ryujinx/files/10355054/Ryujinx_1.1.500_2023-01-05_20-17-27.log)

Unfortunately there's nothing really interesting in the logs, apart from the usual Warnings about Wayland (not the culprit here)

## After digging a little bit

[A thread on Nvidia developers forum seems to have revealed the issue.](https://forums.developer.nvidia.com/t/vk-khr-present-id-wait-causes-device-loss-on-nvidia-525-60-11-on-prime-setup/236510)

Latest Nvidia Linux drivers 525.78.01 seem to have fixed the issue :

`Fixed a bug where usage of VK_KHR_present_id could cause applications to crash with Xid 32 errors. `

I can't test the new drivers right now as they have not landed yet in my repos, but I will once I update. And by the way, the included workaround `VKD3D_DISABLE_EXTENSIONS=VK_KHR_present_id,VK_KHR_present_wait` didn't work for me.

**Comment by Deytron** [comment] 2023-01-08 20:19
Okay, so it looks like the issue is fixed with the latest drivers and latest Ryujinx.
Also, make sure Mangohud isn't enabled globally, that could help.
No idea of the root cause unfortunately, the issue can be closed if needed.

**Comment by TSRBerry** [comment] 2023-01-08 22:18
Awesome, sounds like it was a driver issue then as you said!

**Closed by TSRBerry** 2023-01-08 22:18 UTC
Labels: needs-update, graphics-backend:vulkan, os:linux
