### ISSUE TITLE
[Feature Request] Cache amiibo info

### ISSUE THREAD

**Issue by User670** [Ryujinx/Ryujinx#5355] opened 2023-06-24 06:36 UTC
### Overview

Cache amiibo info after getting them from the API. Make the cache at least valid for the session.

### Smaller details

N/A

### Nature of request

addition

### Why would this feature be useful?

My connection to the amiibo info API seems to be slow, and every time I want to scan an amiibo it takes 5-10 seconds of waiting, even when I just loaded the info a bit earlier. Would like the amiibo info be cached so that scanning multiple amiibos don't need waiting multiple times.

**Comment by MutantAura** [comment] 2023-06-24 23:49
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4904

**Closed by MutantAura** 2023-06-24 23:49 UTC
