### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by aoyegudu** [Ryujinx/Ryujinx#6560] opened 2024-03-25 05:29 UTC
### Description of the issue

The 1.1.1198 update causes many games to crash when rendering with vulkan on Intel graphics card A770, including but not limited to Master of Monsters, Etrian Odyssey,Xenoblade3,Disgaea: Hour of Darkness,Fire Emblem Engage...
I can even say that almost all the games in my library are not playing properly.
I was able to play as many games as before with 1.1.1197, but after 1.1.1198 even with the latest version 1.1.1244 I am still unable to play any of the games with the A770.
hope this problem can be fixed.

### Reproduction steps

Vulkan ,Intel A770 Graphics Card
Version 1.1.1198 and above, the
Crashes within a few minutes of play

### Log file

Unfortunately, I don't see the resulting file in the log after this problem crashes.

### OS

win11

### Ryujinx version

1.1.1198 and above

### Game version

Almost any game

### CPU

i7-13700k

### GPU

Intel(R) Arc(TM) A770 Graphics

### RAM

16GB

**Comment by gdkchan** [comment] 2024-03-25 05:32
Duplicate of #6512.

**Closed by gdkchan** 2024-03-25 05:32 UTC
Labels: bug
