### ISSUE TITLE
[Feature Request]update scanner/directory??

### ISSUE THREAD

**Issue by Okamiissun** [Ryujinx/Ryujinx#5816] opened 2023-10-18 02:03 UTC
### Overview

Update scanner

### Smaller details

-Something that adds updates similar to how game directory is added.(update directory) 
-Go into options->settings->general(new option "title updates) Select the update directory and it cross references to the game directory or whatever to match the game id and automatically add the update to said game. 
-If the directory/toggle for this is turned off but was previously on just keep the last update scanned/selected for each title
-if multiple of the same game id are found add the newest one by default. If none match leave it version 0.
-It would be cool if theres an option for both this and the current "choose title update" incase you want a specific version.
-Assuming ryujinx loads the game list first wait till it loads full directory then load update directory unless both can be done simultaneously with no issue.

### Nature of request

Cool idea to implement

### Why would this feature be useful?

It would let you update your entire catalog with a single toggle/directory scan.

**Comment by gdkchan** [comment] 2023-10-18 02:08
Duplicate of #3265?

**Comment by Okamiissun** [comment] 2023-10-18 02:15
> Duplicate of #3265?

Very similar. I Didnt know someone previously had the full idea tbh

**Closed** 2023-10-31 11:27 UTC
