### ISSUE TITLE
[Bug] - Pokémon Sword/Shield freeze on saving (or in many other random occasions...)

### ISSUE THREAD

**Issue by lo11o94** [Ryujinx/Ryujinx#7227] opened 2024-08-20 22:05 UTC
### Description of the issue

Pokémon Sword/Shield freezing on saving (or in many other random occasions...)

### Reproduction steps

When the game tries to save (or even you in some occasions) after some actions in the game everything freeze and you cannot recover the game so you lose everything you've done before.

### Log file

This issue doesn't produce any log, I checked many times.
[Ryujinx_1.1.1377_2024-08-20_23-54-01.log](https://github.com/user-attachments/files/16682784/Ryujinx_1.1.1377_2024-08-20_23-54-01.log)

### OS

Windows 10

### Ryujinx version

1.1.1377

### Game version

1.3.2

### CPU

i7-10750H

### GPU

NVIDIA RTX 2060 Mobile

### RAM

16 GB

**Comment by MetrosexualGarbodor** [comment] 2024-08-20 22:06
Duplicate of #5837

**Closed by MetrosexualGarbodor** 2024-08-20 22:06 UTC
Labels: bug
