### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by saber1540mm** [Ryujinx/Ryujinx#5773] opened 2023-10-07 13:26 UTC
### Description of the issue

Fate/Samurai Remnant will crash when reach these situations:
<img width="1090" alt="截屏2023-10-07 20 41" src="https://github.com/Ryujinx/Ryujinx/assets/147252795/5efb96e5-1513-441a-a38d-157f62f20bc0">
<img width="1095" alt="截屏2023-10-07 20 43" src="https://github.com/Ryujinx/Ryujinx/assets/147252795/3ebb1ef0-7185-4ae3-af3c-960c73172077">

### Reproduction steps

[DATA.zip](https://github.com/Ryujinx/Ryujinx/files/12837884/DATA.zip)

### OS

macos&win all have these problems

### Ryujinx version

1.1.1047

### Game version

Fate/Samurai Remnant1.0.1

**Comment by gdkchan** [comment] 2023-10-07 16:10
Duplicate of #5772.

**Closed by gdkchan** 2023-10-07 16:10 UTC
Labels: bug
