### ISSUE TITLE
[Feature Request] Visual feedback in the controller mapping UI

### ISSUE THREAD

**Issue by Ghostotakoi** [Ryujinx/Ryujinx#2064] opened 2021-02-27 01:14 UTC
#### Overview:
Add visual feedback in the controller mapping UI Like highlight the button you are pressing.

#### Smaller Details: 
N/A

#### Nature of Request:  
- Addition
 
### Why would this feature be useful?
More friendly UI

**Comment by AcK77** [comment] 2021-08-29 02:11
Duplicate of #2586

**Closed by AcK77** 2021-08-29 02:11 UTC
Labels: enhancement, gui, input
