### ISSUE TITLE
Deleting DLC files causes crash

### ISSUE THREAD

**Issue by SafinWasi** [Ryujinx/Ryujinx#2490] opened 2021-07-18 04:43 UTC
### What's the issue you encountered?

After deleting DLC files, Ryujinx will crash upon attempting to boot the game or Manage DLC.

### How can the issue be reproduced?

Enable any DLC on any game. Then, delete the file. After that, attempt to run the game. Ryujinx will crash with an exception.

### Environment?

- Ryujinx version: 1.0.6970</br>

- Game version: 2.1.0</br>

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 4800HS
  - GPU: NVIDIA RTX 2060
  - RAM: 16GB
- Applied Mods : No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment] 2021-07-18 12:22
Duplicate of #1366

**Closed by AcK77** 2021-07-18 12:22 UTC
