### ISSUE TITLE
Fire Emblem Three houses freeze on shader cache boot

### ISSUE THREAD

**Issue by ShannonEgoiste** [Ryujinx/Ryujinx#2603] opened 2021-08-29 12:25 UTC
### What's the issue you encountered?
Ryujinx seem's to freeze when trying to re compil an shader from cache 

### How can the issue be reproduced?
launching the game with a shader cache with the specific shader

or (matter of guesses) do choir on a free days in monasteries (don't deadlock as in booting but the shader seems to came from here)

### Environment
- Ryujinx version: 1.0.7018</br>
- Game version: 1.2.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-7700hq
  - GPU: NVIDIA GTX 1070
  - RAM: 8GB
### Additional context
Some version ago the game was working without any problem...

**Comment by Aghathis** [comment] 2021-08-29 12:27
[Ryujinx_1.0.7018_2021-08-29_03-56-07.log](https://github.com/Ryujinx/Ryujinx/files/7072471/Ryujinx_1.0.7018_2021-08-29_03-56-07.log)
[e66f540726c0564281dee2819eeae89f.zip](https://github.com/Ryujinx/Ryujinx/files/7072472/e66f540726c0564281dee2819eeae89f.zip)

**Comment by gdkchan** [comment] 2021-08-29 19:01
I can't reproduce this issue here, I have noticed that a few shaders takes a long time to compile on this game (about 2 minutes), but it does eventually compile.

**Comment by Aghathis** [comment] 2021-08-30 23:44
not a matter of time... i've tried more than 15 minute and change nothing...
the game was working fine some version ago ! with the same shader cache... 

here at each launch (if i delete this specific shader in cache (e66f...)) the game run... but the shader is recreated (guess it's in the choir in monastery till it's the only place where the game totally freeze more than 10 minute before continuing)

here the full shader cache if it can help :
[shader.zip](https://github.com/Ryujinx/Ryujinx/files/7080147/shader.zip)

**Comment by Mou-Ikkai** [comment] 2021-08-30 23:50
> not a matter of time... i've tried more than 15 minute and change nothing...
> the game was working fine some version ago ! with the same shader cache...
> 
> here at each launch (if i delete this specific shader in cache (e66f...)) the game run... but the shader is recreated (guess it's in the choir in monastery till it's the only place where the game totally freeze more than 10 minute before continuing)
> 
> here the full shader cache if it can help :
> [shader.zip](https://github.com/Ryujinx/Ryujinx/files/7080147/shader.zip)

You uh... Can't share shaders, bud. It's against the rules and also possibly illegal since it holds game code.

**Comment by MetrosexualGarbodor** [comment] 2022-04-22 19:17
Haven't seen any reports of this in close to a year. The new shader cache is also more resilient to getting stuck during boot. Closing now.

**Closed by MetrosexualGarbodor** 2022-04-22 19:17 UTC
Labels: bug, gpu
