### ISSUE TITLE
Ryujinx crashes after stopping emulation

### ISSUE THREAD

**Issue by beyond9thousand** [Ryujinx/Ryujinx#2798] opened 2021-10-31 09:38 UTC
## Bug Report
- Emulator stuck/crashes after stopping emulation

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]
- DragonBallFighterZ, game works fine. But after pausing and consequently stopping emulation, emulator gets frozen/stops responding/crashes.

[ Did you make any changes related to Ryujinx itself? ]
- No

### How can the issue be reproduced?

[ Include a detailed step by step process for recreating your issue. ]
- Start the game, run for any amount of time
- Pause emulation and/or stop emulation

### Log file
- [Ryujinx_1.0.7094_2021-10-31_12-54-50.log](https://github.com/Ryujinx/Ryujinx/files/7448449/Ryujinx_1.0.7094_2021-10-31_12-54-50.log)

### Environment?

Ryujinx version: 1.0.7094
Game version: 1.29
-
Windows 11
i5-9300H
NVIDIA GTX 1650
16GB DDR4

**Comment by WicCaesar** [comment] 2021-11-05 12:20
It also happens upon stopping emulation on Animal Crossing: New Horizons (only started after I installed update 2.0.0).

**Comment by AcK77** [comment] 2021-11-06 17:06
> It also happens upon stopping emulation on Animal Crossing: New Horizons (only started after I installed update 2.0.0).

It's not related to this current issue, see #2814

**Comment by beyond9thousand** [comment] 2021-11-19 16:41
> > It also happens upon stopping emulation on Animal Crossing: New Horizons (only started after I installed update 2.0.0).
> 
> It's not related to this current issue, see #2814

Is there any solution to this thus far?

**Comment by twilightsophie** [comment] 2022-01-21 07:22
> > It also happens upon stopping emulation on Animal Crossing: New Horizons (only started after I installed update 2.0.0).
> 
> It's not related to this current issue, see #2814

But that thread is about starting emulation and the person you're replying to said it happens on **stopping** the emulation. I have this issue too with Animal Crossing: New Horizons 2.0.

**Comment by IzaacJ** [comment] 2022-02-08 16:27
I have this issue with the few games I've tried so far: Pokemon Shield and Animal Crossing.

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 03:37
Duplicate of #2863.

**Closed by MetrosexualGarbodor** 2022-02-11 03:37 UTC
Labels: bug

**Comment by NaturalHarmonia** [comment] 2023-05-06 13:56
I've had this problem as well. The emulator often crashes when I stop emulation.
