### ISSUE TITLE
gpu speed too low

### ISSUE THREAD

**Issue by 820Mockingjay** [Ryujinx/Ryujinx#2278] opened 2021-05-09 08:18 UTC
I use xps15 9570 8300H and thunderbolt3 egp gtx1050ti.When i play mario,if there is no problem the usage of gpu between 40%-60%,but it often toast gpu speed to low,then the usage of gpu drop down to 0% the fps will down to 0-1fps. If no problem the frame rate will between 25-35fps
00:03:31.022 |W| HLE.OsThread.10 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU... like this

**Comment by Linear524** [comment] 2021-05-18 05:31
Your CPU is very weak (mobile downgraded Coffee Lake) for heavy loaded emulation like this, and its 4 cores is not enough for all recompilation tasks with the speed of 8300H...

**Comment by AcK77** [comment] 2021-05-19 06:22
As stated in the above comment, the issue is due to your hardware, not a bug in Ryujinx.
In that way I close this PR.

**Closed by AcK77** 2021-05-19 06:22 UTC

**Comment by 820Mockingjay** [comment] 2021-05-19 06:31
But when i use laptop Lenovo y7000 i5 8300H with GTX1060，seldom said gpu speed too low，the average frame rate between 40-60fps

**Comment by jduncanator** [comment] 2021-05-19 07:08
Are you sure Ryujinx is using your external GPU, and no the Intel GPU on you XPS15?

**Comment by 820Mockingjay** [comment] 2021-05-19 08:52
I do sure it use my external GPU，there are two pictures，one it run on intel gpu frame rate is 7 fps，another run on nvidia gpu frame rate is 24 fps.The frame rate is different between intel and nvidia.

**Comment by Linear524** [comment] 2021-05-20 02:48
Your GPU speed is too low because you CPU is too slow to recompilate all GPU-needed stuff and get it ready in time. Mobile CPU are always far slower than normal stationary CPU models.

**Comment by MagentaPuppy** [comment] 2021-11-22 03:39
```
|W| HLE.OsThread.9 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...
|E| HLE.OsThread.9 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 2 took more than 1000ms, resuming execution...
```

i'm getting these even though i have a 5950x

**Comment by Zatchhg** [comment] 2021-11-27 19:14
Hey, i'm having this problem too, but only for BDSP games, all the others working for mee and my pc runs him in Yuzu

**Comment by MondinoJuan** [comment] 2022-02-01 02:43
|W| HLE.OsThread.9 ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...

I have the same problem as all of you have but I believe I have a PC good enough for the emulator.
AMD ryzen 5 2600 Six-Core
16Gb RAM
Radeon RX570

Am I right and that's not the problem or my PC is not that good?

**Comment by SamuelsLeeite** [comment] 2022-02-07 01:40
same problem here

**Comment by riperiperi** [comment] 2022-02-07 01:58
This is not an issue. The emulator will print this when guest threads waiting on the GPU time out for _any reason_. This includes things like excessive texture loading, shader compilation. There is no hardware on the planet that can compile any shader without printing this message.

The log is specifically because the emulator deliberately _ignores_ the guest provided timeout and decides to wait forever on the gpu - mainly to mitigate cases where the game would just decide that the GPU has been non-responsive for too long and crashes itself. It's just there to let developers know that this path has been taken, and unless the game crashes immediately after, it's probably working as intended.

If the game _freezes_ after printing this message, then it's actually probably something in the GPU emulation that's taking forever, rather than your hardware.
