### ISSUE TITLE
Xenoblade Chronicles 3 random crashes (DeviceLoss/TDR)

### ISSUE THREAD

**Issue by jmwangde3** [Ryujinx/Ryujinx#3530] opened 2022-08-02 08:56 UTC
## Bug Report

Xenoblade Chronicles 3 Vulkan device loss, OpenGL TDR

### What's the issue you encountered?

Xenoblade Chronicles 3 will randomly crash.

### How can the issue be reproduced?

Random crashes entering the menu or elsewhere in the game.

### Error segment

``` 
00:00:59.348 |E| GPU.MainThread Gpu : VK Sync Object 33936 failed to signal within 1000ms. Continuing...
00:01:00.348 |E| GPU.MainThread Gpu : VK Sync Object 33937 failed to signal within 1000ms. Continuing...
00:01:00.485 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 215
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 46
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_4(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()
```

### Environment?

- Ryujinx version: 1.1.201
- Game version: xenoblade 1.1.0
- System Specs:
  - OS: Windows 10
  - CPU: 5800x
  - GPU: 1060 6gb
  - RAM: 32gb
- Applied Mods : yes(without mod will still crash)

**Comment by meisiek** [comment] 2022-08-02 11:39
It's slightly different for me. With my NVidia 3080 I can enter the heroes menu on Vulcan without a crash, but as soon as I leave it, the NVidia display driver crashes and restarts (nvlddmkm). On the windows event viewer the following was reported:

`Application: Ryujinx.exe
CoreCLR Version: 6.0.722.32202
.NET Version: 6.0.7
Description: The process was terminated due to an unhandled exception.
Exception Info: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 215
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 46
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_4(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 62
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 131
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 108
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()
`
But I suppose this message is only the result of the display driver crash and restart.

This crash only happens if I select Ethel in the heroes menu. The crash still occurs when I select her and then select another hero and than leave the menu. When I enter the heroes menu and never select Ethel, the crash won't occur.

On OpenGL the game crashes instantly as soon as you select Ethel. 

The same thing happens at the end of the very first video in the event theater on Vulcan. Every other video is fine.

**Comment by meisiek** [comment] 2022-08-02 11:54
I wouldn't label it "random crashes". This crash happens every time at the same place and can be reproduced with the save file in this incident...

**Comment by MutantAura** [comment] 2022-08-02 11:55
This is a known issue and it is fully random. I'm simply using this post as the foundation for further reporting.
People get it in different places. Seems to be completely system specific.

**Comment by MetrosexualGarbodor** [comment] 2022-08-02 12:05
Once you get it, it can become consistent, but as it is now, everyone gets it in different places, and some don't even have it at all.

**Comment by S0gnat0re** [comment] 2022-08-03 09:44
Took a while but i managed to make it happen consistently when gathering ether at any spot, specifically the last "big orb" cause a ctd every time

Vulkan gives the generic device loss message so i'm assuming it is the same issue

OpenGL gives this instead 

> 00:03:17.084 |E| HLE.GuestThread.15 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:03:17.134 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MemoryTracking.cs:line 252
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()

Hardware is Gtx 1060 6GB, Ryzen 5 3600, 16GB of ram
OS is Windows 10

Log if for some reason it helps
[Ryujinx_1.1.205_2022-08-03_11-15-26.log](https://github.com/Ryujinx/Ryujinx/files/9250013/Ryujinx_1.1.205_2022-08-03_11-15-26.log)

**Comment by tedios** [comment] 2022-08-03 14:02
Can confirm happens randomly on save file, workaround is to move around a little and try opening the menu then for example. 
They are random but consistent only until data loaded into memory is not updated much, but moving around a zone for a while and then opening menu should work

**Comment by jmwangde3** [comment] 2022-08-04 04:42
ryujinx-Release-1.1.0+b6f2014-win_x64
I test this build,and crash still happen on vulkan

here is my save,save slot 1;may change zip to rar
[heros menu crash.zip](https://github.com/Ryujinx/Ryujinx/files/9256667/heros.menu.crash.zip)

**Comment by Wabinab** [comment] 2022-08-05 09:54
Yeah this is quite random. It doesn't matter OpenGL or Vulkan it also crashes. And to be honest, just don't do the same thing again. Say maybe you open a container and walk to a specific spot and open the menu to save, it crashes. Try moving further from it, maybe pick up something or kill an enemy, then try open the menu again, it **might** not crash then. Also, preferably, save your game as often as possible so you don't lose too much progress even if it crashes.

**Comment by CloneIX** [comment] 2022-08-05 23:15
Same Problem here. Anything I can do to give more information? It appears to be random on opening the menu with "X".

`00:16:04.971 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 172528 bytes, profiled functions: 50796).
00:16:15.404 |E| GPU.MainThread Gpu : VK Sync Object 1688628 failed to signal within 1000ms. Continuing...
00:16:16.405 |E| GPU.MainThread Gpu : VK Sync Object 1688632 failed to signal within 1000ms. Continuing...
00:16:17.508 |E| GUI.RenderLoop Application : Unhandled exception caught: Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 299
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 215
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_71(Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 203
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 130
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(Action gpuLoop) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at Ryujinx.Ui.RendererWidgetBase.Render() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 399
   at System.Threading.Thread.StartCallback()`

**Comment by tedios** [comment] 2022-08-07 12:10
on 1.1.208 seems to crash a lot more often with Vulkan reaching read only memory and invalid memory regions

**Comment by jmwangde3** [comment] 2022-08-09 15:50
1.1.209 opengl crash too.
00:05:40.825 |I| .NET ThreadPool Worker Ptc Save: Saved Profiling Info (size: 212636 bytes, profiled functions: 62621).
00:05:48.124 |E| Gpu : GL Sync Object 28024 failed to signal within 1000ms. Continuing...
[Ryujinx_1.1.209_2022-08-09_23-42-03.log](https://github.com/Ryujinx/Ryujinx/files/9292674/Ryujinx_1.1.209_2022-08-09_23-42-03.log)

**Comment by Wabinab** [comment] 2022-08-12 02:26
Guys, as mentioned in the [Changelog](https://github.com/Ryujinx/Ryujinx/wiki/Changelog), as of 1.1.213, if you use OpenGL, it won't crash any more. I only tried once, the character will first not come out (after purging Vulkan's shader cache), but it won't crash (like usual when characters don't come out). Just wait for it to load (like 30 seconds or something) then it would be fine. At least that's one experience, try discover if there's any more problems with that on OpenGL.

**Comment by Fonkay** [comment] 2022-08-22 20:55
soooo... we're just left praying it doesn't crash?

**Comment by EmulationFanatic** [comment] 2022-08-22 20:58
> soooo... we're just left praying it doesn't crash?

Yep, there are currently no plans to improve the emulator.

**Comment by Fonkay** [comment] 2022-08-22 21:05
> Yep, there are currently no plans to improve the emulator.

Well that's real reassuring

**Comment by EmulationFanatic** [comment] 2022-08-22 21:08
> > Yep, there are currently no plans to improve the emulator.
> 
> Well that's real reassuring

I was just adopting the same energy you came in with (the fatalist attitude). Obviously the emulator is going to continue improving indefinitely.

**Comment by MetrosexualGarbodor** [comment] 2022-09-20 16:08
Closing this as we're now only tracking game-specific issues on the compatibility list. Thanks.
https://github.com/Ryujinx/Ryujinx-Games-List/issues/3960

**Closed by MetrosexualGarbodor** 2022-09-20 16:08 UTC
Labels: bug, gpu
