### ISSUE TITLE
[Bug] Changing System Time in Settings Crashes

### ISSUE THREAD

**Issue by DzXAnt22** [Ryujinx/Ryujinx#6730] opened 2024-04-27 00:41 UTC
### Description of the issue

Attempting to change the time in system settings within ryujinx results in a crash. Changing the date works fine. It worked once, played animal crossing for a bit.

### Reproduction steps

Change date and time in ryujinx
play animal crossing new horizons
save and quit
close ryujinx
open ryujinx
attempt to change system time (time, not date)
crash

### Log file

00:00:00.048 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.056 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.056 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.057 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.058 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.058 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.059 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x2488
00:00:00.059 |I| Configuration LogValueChange: AntiAliasing set to: SmaaHigh
00:00:00.060 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.060 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.062 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.067 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.068 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.068 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.068 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.068 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.068 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.068 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.068 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.068 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.069 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.069 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.070 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.070 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.070 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.070 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.073 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.076 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1291
00:00:00.080 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.080 |N| Application Print: CPU: AMD Ryzen 9 5950X 16-Core Processor ; 32 logical
00:00:00.081 |N| Application Print: RAM: Total 31.9 GiB ; Available 22.1 GiB
00:00:00.083 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.084 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.264 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:00:13.473 |E| Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at Avalonia.Controls.Primitives.DateTimePickerPanel.set_SelectedValue(Int32)
   at Avalonia.Controls.TimePickerPresenter.InitPicker()
   at Avalonia.Controls.TimePickerPresenter.OnApplyTemplate(TemplateAppliedEventArgs)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness, Thickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness)
   at Avalonia.Controls.Decorator.MeasureOverride(Size)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness)
   at Avalonia.Controls.Decorator.MeasureOverride(Size)
   at Avalonia.Controls.LayoutTransformControl.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size)
   at Avalonia.Controls.WindowBase.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.WindowBase.Show()
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1)
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__21_1(Popup x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore, StyledProperty`1, T, BindingPriority, Boolean , Boolean )
   at Avalonia.PropertyStore.ValueStore.SetLocalValue[T](StyledProperty`1, T)
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1, T, BindingPriority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1, T, BindingPriority )
   at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean)
   at Avalonia.Controls.TimePicker.OnFlyoutButtonClicked(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.Interactive.<AddHandler>g__InvokeAdapter|4_0[TEventArgs](Delegate, Object, RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.<>c__4`1.<AddHandler>b__4_1(Delegate baseHandler, Object sender, RoutedEventArgs args)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Input.InputElement.<>c.<.cctor>b__32_9(InputElement x, PointerReleasedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 52

### OS

Windows 11

### Ryujinx version

1.1.1291

### Game version

2.0.6

### CPU

Ryzen 9 5950x

### GPU

RTX 3070 8GB

### RAM

32GB 

### List of applied mods

none

**Comment by DzXAnt22** [comment] 2024-04-27 00:48
Same issue is happening to my friend too, same ryujinx version, same steps to reproduce.

**Comment by piplup55** [comment] 2024-04-27 01:01
duplicate of #6632

**Closed by piplup55** 2024-04-27 01:01 UTC
Labels: bug
