### ISSUE TITLE
[Feature Request] Add gamepad input to control GUI in Ryujinx game selection homepage

### ISSUE THREAD

**Issue by Bobble80** [Ryujinx/Ryujinx#6447] opened 2024-03-09 13:06 UTC
### Overview

I’d like to see if it’s possible to add the feature into Ryujinx for it to automatically detect gamepads so you can navigate through the GUI using said gamepad instead of needing to use a mouse and keyboard.

I use Ryujinx on some gaming handheld PC’s like the ROG Ally and the emulator currently doesn’t pick up the built in gamepad on the device. I have to use either a mouse and keyboard or the touch screen on the handheld to select the game I want to play.

### Smaller details

This feature is currently available in a couple of emulators at the moment, like Yuzu (when active), PPSSPP, RetroArch and recently RPCS3 has just added it.

![60F4644E-CA76-4F56-9C4E-7C10E26AA377](https://github.com/Ryujinx/Ryujinx/assets/155309955/2179bb5f-7c9f-4c90-82ac-5346d058001b)

### Nature of request

N/A

### Why would this feature be useful?

I’m not asking for any complicated functions to be implemented. I’d just like to be able to use the d-pad / joystick to be able to navigate through the game library and then use the A button to start up the game.

A couple of the main PC emulators have this feature right now and makes things a lot easier when playing on a gaming handheld with built in controls. It makes things a more pick up and play console like experience.

**Comment by MutantAura** [comment] 2024-03-14 18:57
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2793

**Closed by MutantAura** 2024-03-14 18:57 UTC
