### ISSUE TITLE
Mouse Feature[Feature Request]

### ISSUE THREAD

**Issue by anonymouse201** [Ryujinx/Ryujinx#6653] opened 2024-04-11 14:29 UTC
### Overview

Control camera with mouse

### Smaller details

Mouse feature

### Nature of request

Mouse Feature

### Why would this feature be useful?

Controlling camera with mouse

**Comment by piplup55** [comment] 2024-04-11 14:30
duplicate of https://github.com/Ryujinx/Ryujinx/issues/2063

**Closed by piplup55** 2024-04-11 14:30 UTC
