### ISSUE TITLE
[Feature Request] Add changelog to update window

### ISSUE THREAD

**Issue by Zorklis** [Ryujinx/Ryujinx#6681] opened 2024-04-18 15:52 UTC
### Overview

So a changelog in the Update window like how PCSX2 does it or details tab in "Update available" window like in RPCS3.

### Smaller details

-

### Nature of request

Educational purpose on what's in the update.

### Why would this feature be useful?

Convenient way of knowing instead of checking github, saves time.

**Comment by gdkchan** [comment] 2024-04-18 16:02
Duplicate of #3262.

**Closed by gdkchan** 2024-04-18 16:02 UTC
