### ISSUE TITLE
[Bug] [The Legend of Zelda: Tears of the kingdom] Game crashes when you try to register a horse and give it a name

### ISSUE THREAD

**Issue by brandonsarte** [Ryujinx/Ryujinx#5252] opened 2023-06-06 19:31 UTC
### Description of the issue

[The Legend of Zelda: Tears of the kingdom] Game crashes when you try to register a horse and give it a name

### Reproduction steps

Get any wild horse and try to register horse to any stable. Game will crash when stable guy asks you on what to name the horse

### Log file

[Ryujinx_1.1.869_2023-06-07_01-37-41.log](https://github.com/Ryujinx/Ryujinx/files/11668381/Ryujinx_1.1.869_2023-06-07_01-37-41.log)
[Ryujinx_1.1.869_2023-06-07_01-40-17.log](https://github.com/Ryujinx/Ryujinx/files/11668382/Ryujinx_1.1.869_2023-06-07_01-40-17.log)
[Ryujinx_1.1.869_2023-06-07_03-28-55.log](https://github.com/Ryujinx/Ryujinx/files/11668383/Ryujinx_1.1.869_2023-06-07_03-28-55.log)

### OS

MacOS

### Ryujinx version

1.1.869

### Game version

1.1.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

### List of applied mods

30FPS mod and MasterSword durability mod

**Comment by Favoryoung** [comment] 2023-06-08 10:32
I've had the same issue, but it wasn't game crashing. If the game's bgm didn't interrupt, then it might be the same situation as mine.
When you need to name the horse, the emulator pops up a keyboard input box, but we can't see this box in fullscreen mode. In this case, you can try exiting fullscreen mode.

**Comment by MutantAura** [comment] 2023-06-12 10:48
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5186 then?

**Comment by MutantAura** [comment] 2023-06-12 10:52
Also of https://github.com/Ryujinx/Ryujinx/issues/5201

**Closed by MutantAura** 2023-06-12 10:52 UTC
Labels: bug
