### ISSUE TITLE
Pokemon Sword and Shield freezing after auto-save in game.

### ISSUE THREAD

**Issue by broprosame** [Ryujinx/Ryujinx#6800] opened 2024-05-13 11:39 UTC
### Description of the issue

Hello, Please fix the issue where in pokemon sword and shield where the game freezes but the audio plays in the background after auto save happens. it mostly happens after a dynamax adventure and also when the game auto saves when throwing a wishing star in dynamax den. The fix will let me continue the crown of tundra pass. Not only me, this helps many people as well. As a kind request please fix this issue as soon as possible

### Reproduction steps

I dont know any reproduction steps as i am not a programmer but hope ryujinx devs would be able to fix this issue

### Log file

I dont think a log file is needed for this issue to be fixed

### OS

Windows 11

### Ryujinx version

Latest Version

### Game version

1.3.2

### CPU

Ryzen 7 7840HS

### GPU

NVIDIA RTX 4050 LAPTOP

### RAM

8 GB

### List of applied mods

No mods

**Comment by MetrosexualGarbodor** [comment] 2024-05-13 11:40
Duplicate of #5837

**Closed by MetrosexualGarbodor** 2024-05-13 11:40 UTC
Labels: bug
