### ISSUE TITLE
Borderless Fullscreen request

### ISSUE THREAD

**Issue by loool3** [Ryujinx/Ryujinx#3506] opened 2022-07-31 13:51 UTC
Hi there,

I would like to put a request of enabling Borderless Fullscreen for Oled HDR users.

In windows 10-11 when using Ryujinx in small window mode HDR does work, but when going fullscreen it goes off. 
This could be avoided if there is an option for fullscreen borderless mode. 

This seems to be an issue for 4k pc users, theres a workout by changing your resolution to 3802x2160 in CP but it gives a lot of headache, so this would be a big help for HDR users.

Thank you,

Kind regards.

**Comment by MetrosexualGarbodor** [comment] 2022-07-31 13:56
Duplicate of #3109.

**Closed by MetrosexualGarbodor** 2022-07-31 13:56 UTC

**Comment by Adamantt777** [comment] 2024-09-30 18:28
Borderless window fullscreen mode is very useful. I hope it gets implemented, yuzu emulator does it, so it's no impossible.
