### ISSUE TITLE
[Feature Request] settings -> input show input feedback in ui 

### ISSUE THREAD

**Issue by Redhawk18** [Ryujinx/Ryujinx#7294] opened 2024-09-06 23:23 UTC
### Overview

To show a ui indication when a button is press or a joystick stick is moved on the input page for the current controller.  

### Smaller details

Change the background color of a button to red, I'm not sure how you would treat a joystick or gyro for example.

### Nature of request

Quality of life

### Why would this feature be useful?

It's very common to have two of the same controller, and its hard to tell who's player 1 or player 2.

**Comment by ekuland** [comment] 2024-09-07 00:10
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2586

**Closed by ekuland** 2024-09-07 00:10 UTC
Labels: enhancement
