### ISSUE TITLE
[Feature Request] navigate using controller input?

### ISSUE THREAD

**Issue by eyeonus** [Ryujinx/Ryujinx#4405] opened 2023-02-11 23:59 UTC
### Overview

As title.
Enable using Xinput to navigate the application menu for handheld computers like the AYA NEO and the Steam Deck

### Smaller Details

For myself, I have the following set up using Steam Input:
Dpad up = up arrow key
Dpad down = down arrow key

Y button = PgUp key
A button = PgDn key
B button = Enter key

So basically apply the function of those keys to those Xinputs? I'm not sure what "smaller details" is asking for.

### Nature of Request

Ease of use? Again, not sure what this is asking from me.

### Why would this feature be useful?

It would mean that people without easy access to keyboard controls would still be able to navigate through the list of installed games and launch a chosen game without having to do something finicky like make a custom profile via Steam Input (my current solution)

**Comment by gdkchan** [comment] 2023-02-12 00:02
Sounds like #2793.

**Comment by eyeonus** [comment] 2023-02-12 00:04
Yeah, pretty much.
Sorry, I did a search before submitting this, but I didn't find that one

**Comment by MutantAura** [comment] 2024-03-14 18:57
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2793

**Closed by MutantAura** 2024-03-14 18:57 UTC
Labels: enhancement, gui
