### ISSUE TITLE
Some games not upscale at all

### ISSUE THREAD

**Issue by Djipi71** [Ryujinx/Ryujinx#3581] opened 2022-08-13 17:56 UTC
Test on 1.1.213 Build
Test on Vulkan or Open GL

The game not upscale at all or only upscale in undocked mode . When the game upscale on undocked mode , seems to have a blurry effect on dock mode but not upscale.

you can reproduced the problem by upscaling a game on this list:
- Little Nightmare 1 (upscale on undocked mode)
- Little Nightmare 2 (Not upscale at all)
- Crash Bandicoot 4 (upscale on undocked mode)
- Arise - A simple Story (Not upscale at all)

SCREEN: for example Little Nightmare 1
4X scaling Dock
![ryujinx_capture_2022-08-13_19-11-44](https://user-images.githubusercontent.com/35375131/184505373-2219f81d-e08a-4e5f-9fdc-3c2b8337fb68.png)

4X scaling undocked

![ryujinx_capture_2022-08-13_19-56-09](https://user-images.githubusercontent.com/35375131/184505347-5e956566-6434-4f8b-a5d6-c3938c6a84ca.png)

LOG :
[Ryujinx_1.1.213_2022-08-13_19-53-54.log](https://github.com/Ryujinx/Ryujinx/files/9331941/Ryujinx_1.1.213_2022-08-13_19-53-54.log)

**Comment by MutantAura** [comment] 2022-08-13 18:04
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1488

**Closed by MutantAura** 2022-08-13 18:04 UTC
