### ISSUE TITLE
inflateValidate Issue

### ISSUE THREAD

**Issue by chaptero** [Ryujinx/Ryujinx#1175] opened 2020-04-28 21:30 UTC
Seen this in one previous issue and it was discredited. 

https://i.imgur.com/sQdB9yJ.png

Would like some help.

**Comment by AcK77** [comment] 2020-04-28 21:33
Duplicate of #1103 
You can see a temporary solution there.
If you needs more help you can go to our Discord!
Thanks!

**Closed by AcK77** 2020-04-28 21:33 UTC
