### ISSUE TITLE
[Bug] Keyboard controls aren't working well [Mac?]

### ISSUE THREAD

**Issue by UsRnM44** [Ryujinx/Ryujinx#6386] opened 2024-03-03 01:34 UTC
### Description of the issue

I reported on this issue already. Not only it got ignored, but I even can't find my report anymore.
My Ryujinx setting controls on keyboard are setting the left-stick to my D-controls. From somewhere like 1.1.1100 update the controls are just wacky. Sometimes I'm clicking left but the character (say, Mario in Odyssey) doesn't going left while going straight too.
Other setting in the keyboard is somehow better, but since this bug is only in Ryujinx, I just can't play any games on it since I can't adjust myself to other control scheme.

https://github.com/Ryujinx/Ryujinx/assets/122369709/465b74cd-bd10-455c-affd-29d8fd5cea3a

notice on this video toward the end, where Mario can't just walk right or left.

<img width="1104" alt="Screenshot 2024-03-03 at 3 37 53" src="https://github.com/Ryujinx/Ryujinx/assets/122369709/1de6d2ec-1d8d-4322-b674-8fecd7f2cc02">

### Reproduction steps

Setting the left stick to the D-controls. 

### Log file

Not producing any crash logs

### OS

MacOS

### Ryujinx version

1.1.1217

### Game version

1.3.0

### CPU

Intel

### GPU

AMD

### RAM

16GB

### List of applied mods

None

**Comment by piplup55** [comment] 2024-03-03 06:38
duplicate of #5849

**Closed by piplup55** 2024-03-03 06:38 UTC
Labels: bug

**Comment by UsRnM44** [comment] 2024-03-03 21:41
Why you marked it as not planned?

**Comment by Schaefers** [comment] 2024-03-03 22:40
> @piplup55 Why you marked it as not planned?

Because you opened the same issue again, duplicates don't make things go faster.

**Comment by piplup55** [comment] 2024-03-03 23:12
> @piplup55 Why you marked it as not planned?

as mention in my [original comment](https://github.com/Ryujinx/Ryujinx/issues/6386#issuecomment-1975063637) "duplicate of https://github.com/Ryujinx/Ryujinx/issues/5849"
