### ISSUE TITLE
Mouse and Keyboard support ingame

### ISSUE THREAD

**Issue by agestrada450** [Ryujinx/Ryujinx#2252] opened 2021-04-28 13:05 UTC
What feature are you suggesting?
Overview:

Being able to map mouse to any stick to use it as the camera stick, also being able to map the right, left, middle, button 4... etc. to a controller input
Smaller Details:

N/A
Nature of Request:

    Addition

Why would this feature be useful?

Easier to play games with mouse and keyboard.

**Comment by EmulationFanatic** [comment] 2021-04-28 13:06
Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/2063

**Closed by EmulationFanatic** 2021-04-28 13:06 UTC
