### ISSUE TITLE
[Bug] Graphics bug Crysis remastered

### ISSUE THREAD

**Issue by iAmSuperMan12** [Ryujinx/Ryujinx#5703] opened 2023-09-20 09:31 UTC
### Description of the issue

textures are constantly flickering

<img width="1508" alt="Снимок экрана 2023-09-20 в 14 24 21" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/b049b42c-0098-4ce1-a865-de9e3b389dfb">
<img width="1508" alt="Снимок экрана 2023-09-20 в 14 24 31" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/393b1128-b861-4113-a586-a5477c3e2522">
<img width="1508" alt="Снимок экрана 2023-09-20 в 14 24 37" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/dc8c15fa-72c6-42a8-8a41-43105f91b3e9">
<img width="1508" alt="Снимок экрана 2023-09-20 в 14 24 47" src="https://github.com/Ryujinx/Ryujinx/assets/79256563/16f33840-1413-47b3-a11d-6c84ddfd2081">

### Reproduction steps

play game

### Log file

[Ryujinx_1.1.1019_2023-09-20_14-02-09.log](https://github.com/Ryujinx/Ryujinx/files/12671457/Ryujinx_1.1.1019_2023-09-20_14-02-09.log)

### OS

mac os 12.6

### Ryujinx version

1.1.1019

### Game version

1.8

### CPU

apple m1

### GPU

apple gpu

### RAM

16

**Comment by AcK77** [comment] 2023-09-20 13:11
Are you able to reproduce using build here: https://github.com/Ryujinx/Ryujinx/pull/5700#issuecomment-1726685346

**Comment by iAmSuperMan12** [comment] 2023-09-20 17:47
> Можете ли вы воспроизвести с помощью сборки здесь: [#5700 (комментарий)](https://github.com/Ryujinx/Ryujinx/pull/5700#issuecomment-1726685346)

nothing changed

**Comment by AcK77** [comment] 2023-09-27 22:38
It's already reported for other OS at https://github.com/Ryujinx/Ryujinx-Games-List/issues/2140
You can report the macOS state there if you want.
I close this issue since it's a game specific one.

**Closed by AcK77** 2023-09-27 22:38 UTC
Labels: bug
