### ISSUE TITLE
NVHOST_IOCTL_CTRL_EVENT_KILL (0x40080021) not implemented

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#1122] opened 2020-04-16 10:07 UTC
NVHOST_IOCTL_CTRL_EVENT_KILL (0x40080021) is not implemented.

## Service description:
[Switchbrew](https://switchbrew.org/wiki/NV_services#NVHOST_IOCTL_CTRL_EVENT_KILL)
```
struct {
  __in u64 user_events;       // 64-bit bitfield where each bit represents one event
};
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/153

**Comment by AcK77** [comment] 2020-04-16 10:13
Duplicate of #632. Closed.

**Closed by AcK77** 2020-04-16 10:13 UTC
