### ISSUE TITLE
[Bug] Ryujinx freezes instead of exits

### ISSUE THREAD

**Issue by livni** [Ryujinx/Ryujinx#5107] opened 2023-05-26 13:12 UTC
### Description of the issue

Before exiting Ryujinx I usually go to TOTK title screen and then select File/Exit - after confirming I'm ok with losing any unsaved information it gets stuck rather than exists. I then have to force quit the application with macOS' cmd+opt+esc

### Reproduction steps

1. play TOTK
2. In the game exit to title screen
3. exit full screen
4. From Ryujinx menu choose File/Exit
5. It freezes

### Log file

[Ryujinx_1.1.824_2023-05-26_11-14-51.log](https://github.com/Ryujinx/Ryujinx/files/11575548/Ryujinx_1.1.824_2023-05-26_11-14-51.log)
[Ryujinx_1.1.824_2023-05-26_11-21-47.log](https://github.com/Ryujinx/Ryujinx/files/11575549/Ryujinx_1.1.824_2023-05-26_11-21-47.log)
[Ryujinx_1.1.824_2023-05-26_14-57-36.log](https://github.com/Ryujinx/Ryujinx/files/11575550/Ryujinx_1.1.824_2023-05-26_14-57-36.log)

### OS

macOS Ventura 13.3.1 (a)

### Ryujinx version

1.1.824

### Game version

1.1.1

### CPU

Apple M1 Pro

### RAM

32GB

### List of applied mods

30 fps

### Additional context?

this has been consistently happening in the last few Ryujinx versions

**Comment by livni** [comment] 2023-05-26 13:13
Minor observation - File/Exit actually seems not to do anything while using the macOS bar menu/Ryujinx/Quit freezes it

**Comment by systox** [comment] 2023-05-26 18:28
This is a forever issue even on PC. After launching a game, Ryujinx just hangs if you try to close it with file -> exit and action -> stop emulation. To reliably close, many users just alt tab to the console window and close that instead.

**Comment by MetrosexualGarbodor** [comment] 2023-05-26 18:29
Duplicate of #2863

**Closed by MetrosexualGarbodor** 2023-05-26 18:29 UTC
Labels: bug
