### ISSUE TITLE
Input profile does not retain changes

### ISSUE THREAD

**Issue by zozeeky** [Ryujinx/Ryujinx#6487] opened 2024-03-14 00:13 UTC
### Description of the issue

Profile does not save my controller keybinds.
I press save but whenever I press load profile it reverts to default settings. 

Also ryujinx will not detect the my controller until I go into Settings>Input>Configure, then select the controller from the dropdown menu which can be a bit tedious that I have to repeat this process every time my controller disconnects.

### Reproduction steps

make a profile > save it > load profile

### Log file

[Ryujinx_1.1.1227_2024-03-13_19-37-49.log](https://github.com/Ryujinx/Ryujinx/files/14595024/Ryujinx_1.1.1227_2024-03-13_19-37-49.log)

### OS

Windows 10

### Ryujinx version

1.1.1227

### Game version

not relevant

### CPU

AMD Ryzen 5 5600X 6-Core Processor

### GPU

AMD Radeon RX 6600

### RAM

16 GB

### List of applied mods

not relevant

**Comment by IsaacMarovitz** [comment] 2024-03-14 11:15
Duplicate of #6395

**Closed by IsaacMarovitz** 2024-03-14 11:15 UTC
Labels: bug
