### ISSUE TITLE
Ryujinx.exe application error when updating to newer version.

### ISSUE THREAD

**Issue by Zyute1991** [Ryujinx/Ryujinx#3033] opened 2022-01-23 23:56 UTC
### What's the issue you encountered?

Every time when it comes to updating ryujinx to the newer version it goes through the normal steps and when it goes to restart ryujinx I get a message that says Ryujinx.exe application error

![20220123_181644 1](https://user-images.githubusercontent.com/83191605/150703076-363296f9-c1a9-4813-805c-d4cc4b4c6cbe.jpg)

### How can the issue be reproduced?

No matter if I do a clean install or not all that has to be done is to check for a update or wait till one pops up and go through the update process until it asks to restart ryujinx then the error will show.
### Log file

[Ryujinx_1.1.6_2022-01-23_18-22-40.log](https://github.com/Ryujinx/Ryujinx/files/7921741/Ryujinx_1.1.6_2022-01-23_18-22-40.log)

### Environment?

- Ryujinx version: 1.1.6
- Game version: N/A
- System Specs:
  - OS: Windows 10
  - CPU: i9-10850k
  - GPU: NVIDIA RTX 3080
  - RAM: 32gb
- Applied Mods : N/A

### Additional context?

Since I only open ryujinx to update I don't know what is going on. It seems to function fine and doesn't effect games in terms of playability. I have even looked at the windows event viewer and get this

![20220123_185401 1](https://user-images.githubusercontent.com/83191605/150703372-d73c2578-3ace-4c13-86df-1ca0918ec5c5.jpg)

**Comment by Squall-Leonhart** [comment] 2022-01-24 00:37
Move the folder to a shorter directory chain, some of the files included would go well beyond the 266 path limit in your current location.

**Comment by Zyute1991** [comment] 2022-01-24 00:39
> Move the folder to a shorter directory chain, some of the files included would go well beyond the 266 path limit in your current location.

is that the reason i get the error?

**Comment by Squall-Leonhart** [comment] 2022-01-24 00:44
I can only suggest that it could be, the exception code is dotnets equivalent of an access violation and trying to manipulate files beyond the path limit has thrown similar in the past(and this one comes up often with mapped network drivers)

there is an alternative if you have a Pro edition of windows and  thats setting the GPO for long paths to enabled.

![image](https://user-images.githubusercontent.com/1098176/150705361-5c1b7b1f-590b-4c3f-b0c7-630c9e939353.png)

**Comment by Zyute1991** [comment] 2022-01-24 00:51
> I can only suggest that it could be, the exception code is dotnets equivalent of an access violation and trying to manipulate files beyond the path limit has thrown similar in the past(and this one comes up often with mapped network drives)
> 
> there is an alternative if you have a Pro edition of windows and thats setting the GPO for long paths to enabled.
> 
> ![image](https://user-images.githubusercontent.com/1098176/150705361-5c1b7b1f-590b-4c3f-b0c7-630c9e939353.png)
> 
> Regedit equivalent is at HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\FileSystem, LongPathsEnabled dword set to 1

all i have is windows 10 home so i dont think it is pro

**Comment by Thog** [comment] 2022-01-25 22:36
DId you attempted to re download the zip?

This looks like a corruption of the main executable

**Comment by Zyute1991** [comment] 2022-01-25 22:56
> DId you attempted to re download the zip?
> 
> This looks like a corruption of the main executable

Yes I've tried redownloading both the most recent versions and older builds and every time there is a update I get the same error issue. It has me baffled

**Comment by Passingby1** [comment] 2022-01-27 05:37
Try with this:
https://www.microsoft.com/en-us/download/details.aspx?id=30135

or also this:
https://www.thewindowsclub.com/how-to-run-system-file-checker-analyze-its-logs-in-windows-7-vista

gl

**Comment by Zyute1991** [comment] 2022-01-27 20:59
> Try with this: https://www.microsoft.com/en-us/download/details.aspx?id=30135
> 
> or also this: https://www.thewindowsclub.com/how-to-run-system-file-checker-analyze-its-logs-in-windows-7-vista
> 
> gl

I've tried those and everything people have suggested above. It still pops up with the error.

**Comment by edisionnano** [comment] 2022-01-27 21:15
Do you have any antivirus

**Comment by Zyute1991** [comment] 2022-01-27 21:22
> Do you have any antivirus

Yes i use Norton 360. For every new updated version of Ryujinx i make an exception.

**Comment by edisionnano** [comment] 2022-01-27 21:29
> > Do you have any antivirus
> 
> Yes i use Norton 360. For every new updated version of Ryujinx i make an exception.

Try disabling it and check if it updates

**Comment by Zyute1991** [comment] 2022-01-27 21:51
> > > Do you have any antivirus
> > 
> > 
> > Yes i use Norton 360. For every new updated version of Ryujinx i make an exception.
> 
> Try disabling it and check if it updates

I cant get it to close. It keeps telling me access is denied.

**Comment by AcK77** [comment] 2022-02-07 11:04
The issue is probably due to you antivirus.

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 06:18
Closing as this hasn't been reported by anyone else, and a solution wasn't found. Sorry.

**Closed by MetrosexualGarbodor** 2022-02-11 06:18 UTC
