### ISSUE TITLE
Pokemon Arceus does bullshit I'm locked. On Ryujinx

### ISSUE THREAD

**Issue by Redflux1779** [Ryujinx/Ryujinx#3050] opened 2022-01-27 23:15 UTC
## Bug Report
Pokemon Arceus does anything, It's like if I touched the buttons at the same time.
I've tried to relaunch the game but nothing changed.
So now I'm locked into the house where I sleep in the game.

**Comment by AcK77** [comment] 2022-02-07 11:02
Duplicate of #3066

**Closed by AcK77** 2022-02-07 11:02 UTC
