### ISSUE TITLE
The screen becomes blurry after certain operations in the game

### ISSUE THREAD

**Issue by tazevam** [Ryujinx/Ryujinx#2639] opened 2021-09-14 01:47 UTC
## Bug Report
The game screen becomes very blurry after some operations. 

### What's the issue you encountered?
In two games, when i setting the resolution scaling (2x), after performing some operations such as opening the status menu or fighting, the game screen will become very blurry. and only restart the game to restore.

### How can the issue be reproduced?
anytime you can. 

### Log file
[Ryujinx_1.0.7032_2021-09-14_09-15-27.log](https://github.com/Ryujinx/Ryujinx/files/7158319/Ryujinx_1.0.7032_2021-09-14_09-15-27.log)

### Environment?

- Ryujinx version: 1.0.7032</br>

- Game version: 1.01and1.02</br>

- System Specs:
  - OS: Windows 10
  - CPU: i3 8350k
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : [ No ]

### Additional context?
METAL MAX Xeno Reborn v1.0.2 [0100e8f00f6be000]
![1](https://user-images.githubusercontent.com/73407337/133179919-c83cad6d-7a7c-463e-bb7d-af0c6068fbc5.PNG)
after open the status menu..
![2](https://user-images.githubusercontent.com/73407337/133179925-5cbcd41f-952c-4ae6-b670-76336263d492.PNG)
![3](https://user-images.githubusercontent.com/73407337/133179927-991b26d5-d95c-4718-9b0b-e7339b582fef.PNG)

黄泉ヲ裂ク華 v1.01 [0100e640118c4000]
![4](https://user-images.githubusercontent.com/73407337/133179931-ff81672d-09c9-4b53-a22f-9c2fdefa05a7.PNG)
after battle..
![5](https://user-images.githubusercontent.com/73407337/133179935-3516b607-ba33-49ff-b346-2eda2ba25ab5.PNG)
![6](https://user-images.githubusercontent.com/73407337/133179936-519cf80a-673a-4802-a7eb-053ec459cd36.PNG)

**Comment by gdkchan** [comment] 2021-09-14 01:50
This looks like a duplicate of #2598, but on the other issue the user seems to imply that the problem happens regardless of the resolution scale, can you confirm?

**Comment by tazevam** [comment] 2021-09-14 02:04
> This looks like a duplicate of #2598, but on the other issue the user seems to imply that the problem happens regardless of the resolution scale, can you confirm?

If setting the default, there should be no problem. If the setting is greater than the default resolution, it will happen. 
![7](https://user-images.githubusercontent.com/73407337/133182534-42225186-47e2-4436-be2a-f4db92c04cde.PNG)
![8](https://user-images.githubusercontent.com/73407337/133182541-03293af4-73ca-45da-bbd6-f7670f7fc489.PNG)
after open the status menu.
![9](https://user-images.githubusercontent.com/73407337/133182543-4effb470-a180-4e7d-9620-09b65c81ed35.PNG)

**Comment by tazevam** [comment] 2021-09-14 02:32
Later, I tried to run the game with the default resolution, first entered the status menu operation or battles, and then set 2X, but the blur problem still appeared. It seems that the problems are in no order, as long as you enter the game and perform these operations, the resolution scaling will be abnormal.

**Closed** 2022-12-05 16:18 UTC
Labels: bug, gpu
