### ISSUE TITLE
[Bug] TOTK - Gloom damage broken in Depths.

### ISSUE THREAD

**Issue by TheShotte** [Ryujinx/Ryujinx#4924] opened 2023-05-13 02:17 UTC
### Description of the issue

So, as far as I can tell, the Depths themselves render properly (at least for me), however the damage effect for the Gloom is completely broken. When you step into actual Gloom (marked as purple on your minimap as well), Link should loose hearts. This doesn't happen. As you can see below, Link is completely fine standing in the middle of the Gloom and no damage is applied.

![ryujinx_capture_2023-05-12_22-13-33](https://github.com/Ryujinx/Ryujinx/assets/3834786/d69c13f9-0832-4807-bf7f-49079b677875)

Furthermore, a part of the story requires you to go into the Depths, and now I can't continue because the normal part of the landscape (no gloom) is now doing damage to me. As soon as I step off the Lightroot, as visible in the screenshot below.

![ryujinx_capture_2023-05-12_22-07-33](https://github.com/Ryujinx/Ryujinx/assets/3834786/fbcd64e0-fb63-4b51-b33c-7e3a694cf5b3)

I am using the Vulkan renderer, however I tried using OpenGL and the same exact thing happens. 

### Reproduction steps

Walk into random areas of the Depths, including Gloom. 

### Log file

[Ryujinx_1.1.796_2023-05-12_21-37-06.log](https://github.com/Ryujinx/Ryujinx/files/11468669/Ryujinx_1.1.796_2023-05-12_21-37-06.log)

### OS

Windows 11 Home

### Ryujinx version

1.1.796

### Game version

1.1

### CPU

i7-12700K

### GPU

AMD 6600XT

### RAM

32Gb

### List of applied mods

30 FPS Mod (unfortunately still necessary as game is locked to 20FPS by default)

### Additional context?

Thank you for the spectacular work.

**Comment by gdkchan** [comment] 2023-05-13 02:22
Duplicate of #4915.

**Closed by gdkchan** 2023-05-13 02:22 UTC
Labels: bug
