### ISSUE TITLE
Remove not used icons and files [Feature Request]

### ISSUE THREAD

**Issue by Johanfer12** [Ryujinx/Ryujinx#6137] opened 2024-01-15 20:52 UTC
### Overview

Please consider to remove unused icons from installation such as adwaita and hicolor ones, I have my installation folder in Onedrive and each time I run update Onedrive gives me a warning of ransomware because 8000+ files has been modified.

### Smaller details

Remove unused icons in Ryujinx app

### Nature of request

Suggestion

### Why would this feature be useful?

Less installation size, less index time, avoid onedrive and another cloud services warnings.

**Comment by IsaacMarovitz** [comment] 2024-01-16 01:56
If you don't want many loose files, use the Avalonia UI, which doesn't store resources like GTK. However, the bigger concern here is that you are storing Ryujinx in OneDrive. Running programs from cloud storage is highly not recommended.

**Comment by TSRBerry** [comment] 2024-01-16 03:28
Duplicate of https://github.com/Ryujinx/GtkSharp.Dependencies/issues/3

**Closed by TSRBerry** 2024-01-16 03:28 UTC
