### ISSUE TITLE
Motion controls are reset involuntarily on the Pro Controller.

### ISSUE THREAD

**Issue by 7456344534d** [Ryujinx/Ryujinx#4366] opened 2023-02-04 22:47 UTC
### Description of Issue

When aiming in Splatoon 2 and 3 using a Switch Pro Controller, it is common to have unintentional abrupt camera movements.

Even when the controller is left resting on a flat surface, there is a constant shaking of the camera that (to my knowledge) should not occur.

In all my tests, I have only encountered this problem in Ryujinx, both in Master and LDN builds (with their respective GTK and Avalonia GUI variants).

In addition to that:

 · I do not use software such as DS4Windows or Betterjoy.

 · I have tried changing the Gyro Deadzone settings, but to no avail.
 
 · I connect the controller to the computer via a cable, due to the lack of bluetooth support on my computer.

### Reproduction Steps

1) Connect an original Switch Pro controller to your computer.

2) Run any version of Ryujinx of your choice.

3) Enable motion controls both in the game and on the Ryujinx input screen.

4) Tilt the controller and point it at a target to verify that the camera does indeed reset unintentionally.

### Log File

[Ryujinx_1.1.0-ldn3.0.1_2023-02-04_22-58-26.log](https://github.com/Ryujinx/Ryujinx/files/10609777/Ryujinx_1.1.0-ldn3.0.1_2023-02-04_22-58-26.log)

### OS

Windows 10 21H2

### Ryujinx version

Any release to date (eg: Master: 1.1.599 | LDN: 1.1.0-ldn3.0.1)

### Game version

Splatoon 2: 5.5.1 | Splatoon 3: 2.1.0

### Environment?

- CPU: Intel(R) Core(TM) i7-4790K
- GPU: NVIDIA GTX 960
- RAM: 16GB
- Applied Mods: No

### Additional context?

https://user-images.githubusercontent.com/124469126/216792608-921c6088-3238-411e-be63-721c3ebab857.mp4

**Comment by quanghuy1242** [comment] 2023-02-05 14:32
Have the same problem with game Captain Toad, the blue dot keeps moving to the bottom of the screen.

**Comment by legend800** [comment] 2023-02-05 18:18
I can confirm this. Gyro in Pro Controller has been unusable since day 1 of it's native implementation a year ago because of this issue.

**Comment by P-G19** [comment] 2023-02-08 04:34
Same issue with a 3rd party PS4 Controller (doesn't have DS4Windows support but Gyro works fine with Steam so not controller fault i guess)...

**Comment by turkeynaruto** [comment] 2023-02-09 01:25
This Issue also makes it impossible to play Metroid Prime Remaster in "Pointer" Mode (Full Gyro Camera Control) with my Dualsense Controller.
I dont use any third Party software just directly connected it via USB to my PC.

**Comment by Ritaku02** [comment] 2023-02-09 16:08
> This Issue also makes it impossible to play Metroid Prime Remaster in "Pointer" Mode (Full Gyro Camera Control) with my Dualsense Controller. I dont use any third Party software just directly connected it via USB to my PC.

Same, in fact the game constantly brings up a box saying its recalibration the motion controls. This is with both native motion support, and using DS4Windows.

**Comment by coolllman** [comment] 2023-02-10 07:27
Same, dualsense and ds4

**Comment by SixelAlexiS90** [comment] 2023-02-12 15:32
Same issue with DS4, both on Captain Toad and Mario 3D World.

**Comment by iKillThis** [comment] 2023-03-08 15:28
It seems when I hold down any button or move the sticks constantly it works fine.
Maybe it helps to track down where the issue comes from.

https://user-images.githubusercontent.com/127325011/223754533-53d32802-2d1e-4624-88fd-535f665f54b7.mp4

(Dualsense Controller)

**Comment by JaleSwiftpaw** [comment] 2023-04-15 01:46
I can confirm this as well with Breath of the Wild camera / bow targeting. The camera keeps moving erratically or resetting to the previous view.

**Comment by amphyvi** [comment] 2023-04-15 23:08
having this issue as well, using an 8bitdo Pro 2 in Switch pro controller mode.

**Comment by SpicerXD** [comment] 2023-04-16 07:50
I'm having the same issue as well with a DS5 controller. Using the built in motion support and the cemuhook DS4Windows support.
The issue seems to occur anytime the controller isn't moving enough.

**Comment by SpicerXD** [comment] 2023-04-17 14:48
Seems the MotionInput.Update function enters calibration way too easily. Or not correctly.

**Comment by SpicerXD** [comment] 2023-04-22 05:07
I tried building Ryu without the calibration code. Works flawlessly now. Not sure what the purpose of the code is.

**Comment by SixelAlexiS90** [comment] 2023-04-22 08:00
> I tried building Ryu without the calibration code. Works flawlessly now. Not sure what the purpose of the code is.

Thank you for this! I really hope is going to be approved, we have this issue for so long now and it doesn't seem like a priority at all even if it's quite game breaking.

**Closed** 2023-04-22 13:31 UTC
Labels: bug, input
