### ISSUE TITLE
All games display a black screen on Steam Deck (unless I move the mouse)

### ISSUE THREAD

**Issue by jlar0che** [Ryujinx/Ryujinx#4167] opened 2022-12-23 09:26 UTC
After the last update to Ryujinx (v 1.1.488) all games just have a black screen. If I move the mouse with the Steam Deck trackpad the screen is visible, but as soon as the mouse cursor disappears the screen goes black again.

Everything was working fine in the previous version of Ryujinx (v1.1.487).

**YouTube video I made documenting the issue:**
https://youtu.be/GrDhsISDPx0

**What I have tried to fix this:**
In the Steam Deck options I went to "Display" and noticed "Enable Adaptive Brightness" was turned ON. I turned it OFF and restarted the Deck. This did not solve the issue.

**NOTE:**
To be perfectly clear I updated my Steam Deck from v3.3.3 to v3.4.2 _and_ I also updated Ryujinx from v1.1.487 to v1.1.488, so I can't tell 100% if the issue was caused by the Ryujinx or Steam OS upgrades.

**Comment by TSRBerry** [comment] 2022-12-23 09:54
Duplicate of #3874

Sadly, we can't reproduce this issue and don't know why it happens now when it works just fine on Linux.

**Closed by TSRBerry** 2022-12-23 09:54 UTC

**Comment by jlar0che** [comment] 2022-12-23 15:05
Do you all have a Steam Deck to test on? If not, of course there is no way for you to reproduce.

**Comment by swangy** [comment] 2022-12-23 15:17
so i updated to latest preview version of steamOS and issue has resolved!

**Comment by TSRBerry** [comment] 2022-12-23 15:41
> Do you all have a Steam Deck to test on? If not, of course there is no way for you to reproduce.

I tested this multiple times on a Steam Deck already, but couldn't reproduce it. It just works for me.

**Comment by Dragonisser** [comment] 2022-12-23 17:12
> so i updated to latest preview version of steamOS and issue has resolved!

Still the same on my end.

**Comment by Squall-Leonhart** [comment] 2022-12-28 09:32
This was also reported on cemu iirc, it is only fixed in the preview releases of steamdeck os so far.

**Comment by TSRBerry** [comment] 2022-12-28 13:27
@Squall-Leonhart Could you comment that on #3874 perhaps with a link to the issue on cemu as well?
