### ISSUE TITLE
[Rune Factory 5 (USA)] Glitchy terrain texture when using upscaler

### ISSUE THREAD

**Issue by goudekid** [Ryujinx/Ryujinx#3229] opened 2022-03-23 03:00 UTC
Edit: Comments seem to indicate the issue happens only when upscaling resolution

### What's the issue you encountered?

Just outside the town gate, there is a large raised section of textured terrain with no collision; screenshot below. This does not exist when playing on actual hardware.

![image](https://user-images.githubusercontent.com/13862763/159615511-2c63e0ae-5e31-47f8-8d23-d6f58c10c123.png)

Tried both openGL and vulkan versions, same result on both.

### How can the issue be reproduced?

Seems to happen regardless of circumstance, based on what others have told me.

### Environment?

- Ryujinx version: 1.1.0+e9819d0 Vulcan as well as 1.1.0 OpenGL</br>
- Game version: 1.0.1</br>
- System Specs:
  - OS: Win10
  - CPU: i7-9700k
  - GPU: NVIDIA RTX 2070 Super
  - RAM:  16GB
- Applied Mods : No

**Comment by GamerzHell9137** [comment] 2022-03-24 13:09
Since its the Vulkan build this should be at least labeled Vulkan since its not happening on OpenGL.
Also, can't reproduce it on Vulkan. I know it was an issue before but why its resurfacing idk.

**Comment by goudekid** [comment] 2022-03-24 23:17
> Since its the Vulkan build this should be at least labeled Vulkan since its not happening on OpenGL. Also, can't reproduce it on Vulkan. I know it was an issue before but why its resurfacing idk.

I did mention in the body of the text the issue occurs on both OpenGL and Vulcan, but then neglected to actually have that listed in the versions; will edit the post.

**Comment by GamerzHell9137** [comment] 2022-03-24 23:53
> > Since its the Vulkan build this should be at least labeled Vulkan since its not happening on OpenGL. Also, can't reproduce it on Vulkan. I know it was an issue before but why its resurfacing idk.
> 
> I did mention in the body of the text the issue occurs on both OpenGL and Vulcan, but then neglected to actually have that listed in the versions; will edit the post.

Im guessing the issue is random and doesn't happen consistently?

![image](https://user-images.githubusercontent.com/2002038/160028338-466d7e56-f04b-4f02-b110-dca005549d61.png)

**Comment by goudekid** [comment] 2022-03-24 23:55
I believe it will happen on a new game every time; I'm not sure what resolves it later on but both of my games experienced this at the start, and both of the friends I have who also played on an emulator got it as well. In all cases it resolves randomly after some time.

**Comment by ddrake2006** [comment] 2022-03-25 23:23
I can confirm that I get it as well. It appears at all borders between zones, including the invisible zones (like the boundary of the ocean).

**Comment by GamerzHell9137** [comment] 2022-03-28 02:23
@ddrake2006 @goudekid I think i found the reason why its bugging. Its the upscaler. If you set it to x2 it will break the ground but on native its fine. Can you two confirm that? Test the game on native, check the places, close the emulator, open it, change to x2 and check for it again.

**Comment by Avrution** [comment] 2022-03-30 20:48
Same thing happens in yuzu, just fyi

**Comment by GamerzHell9137** [comment] 2022-03-30 20:51
@goudekid You can change the topic name to the upscaler being the issue and adding it to the main post. Its confirmed that that's the reason. Anything above native breaks everything in game.

**Comment by benderscruffy** [comment] 2022-09-24 01:36
Close this as now only tracking game-specific issues on the compatibility list. Thanks.

**Comment by MetrosexualGarbodor** [comment] 2022-12-05 16:20
Please post about this in #1488 if it still occurs.

**Closed by MetrosexualGarbodor** 2022-12-05 16:20 UTC
Labels: bug, gpu
