### ISSUE TITLE
Add Home/Capture button. Simple. 

### ISSUE THREAD

**Issue by andrewmyles2** [Ryujinx/Ryujinx#4331] opened 2023-01-22 13:43 UTC
Simple. Joycons have Capture and Home buttons. there is no way to map them in settings. And some games REQUIRE to use them for certain features. To add salt to your wounds, yuzu can do it. So you should do to. otherwise people have to do stupid workarounds like here: https://www.reddit.com/r/Ryujinx/comments/ytnpsy/whats_the_capture_button_and_where_to_find_it/ 

so... yeah, whenever you are ready. It's just two buttons, not Riemann's hypothesis.

**Comment by MutantAura** [comment] 2023-01-22 13:46
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2718 and https://github.com/Ryujinx/Ryujinx/issues/3875.
I would also advise not being obnoxious when opening feature requests.

**Closed by MutantAura** 2023-01-22 13:46 UTC

**Comment by riperiperi** [comment] 2023-01-22 13:50
Read the first comment on the reddit post you linked. It's not Riemann's hypothesis.
