### ISSUE TITLE
[Bug] After updating, it’s easy for the Mac version to crash

### ISSUE THREAD

**Issue by Shihta** [Ryujinx/Ryujinx#4631] opened 2023-04-02 13:00 UTC
### Description of the issue

I’m using MacBook Air M2 and playing Sakuna Of Rice and Ruin [0100B1400E8FE000].
It was stable before updating to the latest version, but now it crashes easily and goes back to the login screen of Mac.
I’m not sure which version I was using before that was stable, probably a version from about a week ago.
The current version that keeps crashing is 1b41b28.
I will gradually roll back to older versions until I find a stable one and then report back.

### Reproduction steps

Starting the game and playing it doesn’t necessarily cause a crash at any particular step, but it usually happens within 5 minutes.

### Log file

[Ryujinx_1.1.1+0_2023-04-02_20-29-36.log](https://github.com/Ryujinx/Ryujinx/files/11132244/Ryujinx_1.1.1%2B0_2023-04-02_20-29-36.log)
[Ryujinx_1.1.1+0_2023-04-02_21-33-57.log](https://github.com/Ryujinx/Ryujinx/files/11132323/Ryujinx_1.1.1%2B0_2023-04-02_21-33-57.log)

### OS

MacOS Monterey 12.5.1

### Ryujinx version

1b41b28

### Game version

1.0.8

### CPU

Apple M2

### GPU

Apple M2

### RAM

24GB

**Comment by Shihta** [comment] 2023-04-13 06:42
update:
after update to latest version(e187a88), it crash again.
and then I directly revert the commit 2105579, it back to stable
as shown below:
![截圖 2023-04-12 下午8 26 36](https://user-images.githubusercontent.com/5186176/231675470-8c26374c-6a92-403c-a644-6e4b9ded4eb6.png)

**Comment by joschkoeter** [comment] 2023-04-21 21:51
Hey Shihta, 
im somewhat new to git and never worked with GitHub. I just installed the 1.1.0-macOS1 Version on my M2 MacBook Air from the Ryuijnx website to play Pokemon brilliant diamond and it crashes pretty often. Last time was even before I started the game. I don't really get what Ryujinx repository you are using. I saw there is an Ryujinx release channel macOS, but I can't find the commits you are talking about there. Neither in the release channel master repository. Could you explain to me which repository I need to clone? Or do you think my issue and your issue are different problems? 
Sorry if this is a stupid question, but I would be happy if you could help me.
Looking forward to hearing from you,
Josch

**Comment by Shihta** [comment] 2023-04-22 06:49
I built myself version with reference to this article: https://www.reddit.com/r/macgaming/comments/116fewn/guide_how_to_build_the_latest_version_of_ryujinx/

I haven't tried to play Pokemon Brilliant Diamond, but I think there's a chance you can improve your problem with the new version of Ryujinx.

This is my own built version, I think you can try it: https://drive.google.com/file/d/17Ao4Gll60cWVqz4E0XLIURL_Sjn5n_i-/view?usp=sharing

**Comment by joschkoeter** [comment] 2023-04-23 21:34
Thank you! I'll try it sometime next week and report back.

**Comment by AcK77** [comment] 2023-05-02 14:30
```
00:00:25.231 |W| GPU.MainThread Gpu Log: Shader translator: Invalid exit on non-main function.
00:00:25.487 |E| .NET ThreadPool Worker [mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 3):
00:00:25.487 |E| .NET ThreadPool Worker Gpu DebugMessenger: VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 3):
Fragment input(s) `user(locn6)` mismatching vertex shader output type(s) or not written by vertex shader.
00:00:25.487 |E| .NET ThreadPool Worker Fragment input(s) `user(locn6)` mismatching vertex shader output type(s) or not written by vertex shader.
00:00:25.487 |E| .NET ThreadPool Worker Gpu : Background Compilation failed: Unexpected API error "ErrorInitializationFailed".
```

Provided logs doesn't say it come from Avalonia or anything else than a GPU issue. Have you tried our macOs build instead of build the incomplete code yourself ?
We do not support custom build, but in the case of macOs we are fine with it, but please, do not share build publicaly because it will be a mess for us to provide help and support.

**Comment by Shihta** [comment] 2023-05-02 15:42
> ```
> 00:00:25.231 |W| GPU.MainThread Gpu Log: Shader translator: Invalid exit on non-main function.
> 00:00:25.487 |E| .NET ThreadPool Worker [mvk-error] VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 3):
> 00:00:25.487 |E| .NET ThreadPool Worker Gpu DebugMessenger: VK_ERROR_INITIALIZATION_FAILED: Render pipeline compile failed (Error code 3):
> Fragment input(s) `user(locn6)` mismatching vertex shader output type(s) or not written by vertex shader.
> 00:00:25.487 |E| .NET ThreadPool Worker Fragment input(s) `user(locn6)` mismatching vertex shader output type(s) or not written by vertex shader.
> 00:00:25.487 |E| .NET ThreadPool Worker Gpu : Background Compilation failed: Unexpected API error "ErrorInitializationFailed".
> ```
> 
> 
>      
>   
> 
> Provided logs doesn't say it come from Avalonia or anything else than a GPU issue. Have you tried our macOs build instead of build the incomplete code yourself ?
> We do not support custom build, but in the case of macOs we are fine with it, but please, do not share build publicaly because it will be a mess for us to provide help and support.

First of all, I'm sorry that I didn't notice that providing the version compiled by myself in here would cause trouble to you. I will avoid this in the future.

I have used the version you compiled (1.1.0-MACOS1), but it is true as some articles say, a new version built by myself is much more powerful in FPS.

I am curious, do you think there is something wrong with my building steps?
if using `distribution/macos/create_macos_release.sh` is not recommended, could you share some advice?

**Comment by AcK77** [comment] 2023-05-02 15:45
I suggest you to read https://github.com/Ryujinx/Ryujinx/issues/4062
The current code of `1.1.0-macos1` isn't fully released, that's why some things can differ.
I close this issue in that way, we can reopen it if there is a real issue.

**Closed by AcK77** 2023-05-02 15:45 UTC
Labels: bug, os:macOS

**Comment by gdkchan** [comment] 2023-05-02 15:57
FWIW I don't have those crashes with a local build using Avalonia on macOS here. But I didn't really play on it for too long, I will post an update if I manage to reproduce the issue.
