### ISSUE TITLE
Pokemon Sword Or Shield LDN 2.4 LAN Issue with Switch

### ISSUE THREAD

**Issue by elendil98** [Ryujinx/Ryujinx#3365] opened 2022-05-26 17:45 UTC
Ryujinx LDN 2.4

I've followed the whole guide of the Ryujinx LDN 2.4 (https://github.com/Ryujinx/Ryujinx/wiki/Multiplayer-(LDN-Local-Wireless)-Guide)
Tried everything I've found here in the issues and in Reddit, but I couldn't manage to link the Ryujinx emulator with the Switch.
I've tried with 2 Ryujinx open and it works just fine, even with one with Pokemon Sword and the other emulator with Pokemon Shield.

Ryujinx that I've used: https://www.patreon.com/file?h=45268370&i=9248983

What I've tried so far with the Ryujinx here and didn't worked: 
Firmware Version 14.1.1 (downloaded here: https://darthsternie.net/switch-firmwares/)
prod.keys got on a youtube video for the 14.1.1 firmware (not sure if it's good, looks like it's fine)
Pokemon Shield and Sword NSP (I'll try XCI soon and check if that matters)
User Profile just like the guide
User Profile changed with different names
Settings -> System -> Region/Language/Time Zone just like the Switch (Europe / Italian / Rome)
Multiplayer Mode Ryujinx Ldn Selected
Disable P2P Network Hosting with: ON and OFF
Enable LAN Connectivity ON
Enable LAN Connectivity OFF (Necessary to make it work between two emulators tried with one Sword and one Shield)
Network Interface Default / Ethernet / Wifi - (tried with phone hotspot connected on both PC and Switch)
Disabled IPv6 on Windows
Removed every Windows Firewall
On both emulator and switch activated LAN Mode (L + R + Left Stick Button in the Options)

What happens all the time?
On the Ryujinx: while searching for trade, the player name shows up multiple times, like 4 times in a minute
On the Switch: while searching for trade, the player name shows up one time

Logs of my last tries:
[Ryujinx_1.0.0-ldn2.4_2022-05-26_18-49-52.log](https://github.com/Ryujinx/Ryujinx/files/8780934/Ryujinx_1.0.0-ldn2.4_2022-05-26_18-49-52.log)
[Ryujinx_1.0.0-ldn2.4_2022-05-26_18-50-05.log](https://github.com/Ryujinx/Ryujinx/files/8780935/Ryujinx_1.0.0-ldn2.4_2022-05-26_18-50-05.log)
[Ryujinx_1.0.0-ldn2.4_2022-05-26_18-58-07.log](https://github.com/Ryujinx/Ryujinx/files/8780936/Ryujinx_1.0.0-ldn2.4_2022-05-26_18-58-07.log)

### Environment?\

- Ryujinx version: 1.0.0-ldn2.4</br>
- Pokemon Spada (Sword) / Pokemon Scudo (Shield): 1.3.2</br>
- With DLC Expansion Pack
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 7 3700X 
  - GPU: NVIDIA GeForce RTX 2070
  - RAM: 16GB
- Applied Mods : No

Want to figure out why it does not work, if someone have tried different things or it works and wanna share the settings, I will gladly check if that works for me too.
The Ryujinx server works fine, maybe are not that stable for my connection but works, I just wanna link Ryujinx with the Switch with Pokemon Sword and Shield :)

I've alredy checked the issue 2074: https://github.com/Ryujinx/Ryujinx/issues/2074
The only thing I didn't checked is the wild area news matching with the switch ones before trading.

If someone want images or more informations just tell me! Nice work guys :)

**Comment by MetrosexualGarbodor** [comment] 2022-05-26 17:47
Duplicate of #2074

**Closed by MetrosexualGarbodor** 2022-05-26 17:47 UTC
