### ISSUE TITLE
[Bug]eBaseball Powerful Pro Yakyuu 2022

### ISSUE THREAD

**Issue by Mario9699** [Ryujinx/Ryujinx#4616] opened 2023-03-28 22:59 UTC
Game Update Version : 1.8.0

Current on master : Emulator Build Version : 1.1.694
Graphics Backend : Vulkan

This game have words mistakes and crash.

Hardware Specs :

OS: Windows 10
CPU: i5-8400
GPU: NVIDIA GeForce GTX 1050
RAM: 16GB

Screenshots :
![未命名4](https://user-images.githubusercontent.com/103609670/229644036-2285accf-0b9d-4ea3-b745-6eed97916426.jpg)
![未命名3](https://user-images.githubusercontent.com/103609670/229644046-29d6e98b-4ff3-421c-9e3f-5b6b1d366ff8.jpg)
![未命名2](https://user-images.githubusercontent.com/103609670/229644051-da0982dc-8bc6-49c7-b2e1-b40a40bfcc06.jpg)
![未命名1](https://user-images.githubusercontent.com/103609670/229644055-83064fd0-21cf-4ed5-a51d-766e1517dc13.jpg)
![未命名](https://user-images.githubusercontent.com/103609670/229644058-1170c791-f292-4cae-b133-0b5be89bda08.jpg)

Log file :
[Ryujinx_1.1.694_2023-04-04_06-46-03.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/11143030/Ryujinx_1.1.694_2023-04-04_06-46-03.log)
00:03:56.225 |E| GPU.MainThread Application : Unhandled exception caught: System.ArgumentException: An item with the same key has already been added. Key: Ryujinx.Graphics.Gpu.Image.TextureDescriptor
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey, TValue, InsertionBehavior)
   at Ryujinx.Graphics.Gpu.Image.TexturePool.InvalidateRangeImpl(UInt64 address, UInt64 size) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TexturePool.cs:line 333
   at Ryujinx.Memory.Tracking.MultiRegionHandle.QueryModified(UInt64 address, UInt64 size, Action`2 modifiedAction) in D:\a\Ryujinx\Ryujinx\Ryujinx.Memory\Tracking\MultiRegionHandle.cs:line 198
   at Ryujinx.Graphics.Gpu.Image.TextureBindingsManager.CommitBindings(ShaderSpecializationState specState) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Image\TextureBindingsManager.cs:line 319
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 firstIndex, Int32 indexCount, Int32 drawFirstVertex, Int32 drawVertexCount) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 120
   at Ryujinx.Graphics.Gpu.Engine.Threed.DrawManager.DrawEnd(ThreedClass engine, Int32 argument) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\Threed\DrawManager.cs:line 107
   at Macro(MacroJitContext, IDeviceState, Int32)
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoClass.CallMme(Int32 index, IDeviceState state) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoClass.cs:line 245
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, Int32 offset, Int32 argument, Int32 subChannel, Boolean isLastCall) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 213
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 82
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 207
   at Ryujinx.Ui.RendererWidgetBase.<Render>b__78_0() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 430
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.<>c__DisplayClass51_0.<RunLoop>b__0() in D:\a\Ryujinx\Ryujinx\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 107
   at System.Threading.Thread.StartCallback()

**Comment by Mario9699** [comment] 2023-03-29 09:42
Who can fix it?

**Comment by Mario9699** [comment] 2023-05-03 22:18
It's fin

Ac_K ***@***.***> 於 2023年5月2日 週二 下午10:44寫道：

**Comment by Mario9699** [comment] 2023-05-03 22:19
It's fix,thank you

Ac_K ***@***.***> 於 2023年5月2日 週二 下午10:44寫道：

**Comment by gdkchan** [comment] 2023-05-03 22:21
Closing since it was confirmed to be fixed, likely by #4745.

**Closed by gdkchan** 2023-05-03 22:21 UTC
Labels: bug, gpu
