### ISSUE TITLE
Game won't launch after 1.1.150 update

### ISSUE THREAD

**Issue by TehChozinOne** [Ryujinx/Ryujinx#3404] opened 2022-06-17 22:31 UTC
### What's the issue you encountered?

Game won't launch after 1.1.150 update

### How can the issue be reproduced?

Start the game, any games

### Log file

Attached

### Environment?

- Ryujinx version: 1.1.150</br>
- Game version: FETH 1.20
- System Specs:
  - OS: Win 10
  - CPU: Ryzen 5900X
  - GPU: RTX 3080
  - RAM: 32GB
- Applied Mods : No

[Ryujinx_1.1.150_2022-06-18_08-26-24.log](https://github.com/Ryujinx/Ryujinx/files/8931615/Ryujinx_1.1.150_2022-06-18_08-26-24.log)

**Comment by MetrosexualGarbodor** [comment] 2022-06-18 12:38
Closing as this is most likely caused by an antivirus and not by the update.

**Closed by MetrosexualGarbodor** 2022-06-18 12:38 UTC
