### ISSUE TITLE
Unimplemented VBIC.I32 ARM32 instruction

### ISSUE THREAD

**Issue by B3astTech** [Ryujinx/Ryujinx#1113] opened 2020-04-14 16:24 UTC
Requires the ARM32 VBIC.I32 instruction (immediate variant).

```
The instruction at 0x00000000021d4f94 (opcode 0xf2c0617f) is undefined!
```

#### Description:
```
VBIC.I32	Q11, #0xF
```

## Required by:
https://github.com/Ryujinx/Ryujinx-Games-List/issues/750

**Comment by B3astTech** [comment] 2020-04-14 16:27
Duplicate of 1005. Closed

**Comment by B3astTech** [comment] 2020-04-14 16:31
https://github.com/Ryujinx/Ryujinx/issues/1005 has similar opcode but the sting before that is different comparing this one is  `0x00000000021d4f94` and 1005 is `0x0000000003a30f94` and it required a different issue for this

**Comment by gdkchan** [comment] 2020-04-14 17:26
The issue looks incorrect. First it says it's MOVK, but the disassembly has VBIC. Which one it is? This is most likely a 32-bit title.

**Comment by B3astTech** [comment] 2020-04-14 17:28
I Fixed it up

**Comment by gdkchan** [comment] 2020-04-14 17:31
Closing as duplicate of #1005

**Closed by gdkchan** 2020-04-14 17:31 UTC
