### ISSUE TITLE
Microphone Support [Feature Request]

### ISSUE THREAD

**Issue by nicknick25** [Ryujinx/Ryujinx#6524] opened 2024-03-18 12:24 UTC
### Overview

I would like to use games like Let's Sing songs, my USB microphones are not recognized.

### Smaller details

I used the normal USB microphones from the Playstation

### Nature of request

Extension for gamepads

### Why would this feature be useful?

To use games like Lets Sing

**Comment by TSRBerry** [comment] 2024-03-18 12:31
Duplicate of 4254

**Closed by TSRBerry** 2024-03-18 12:31 UTC
