### ISSUE TITLE
[Bug] Interface freeze on multiple CreateErrorDialog

### ISSUE THREAD

**Issue by Berbe** [Ryujinx/Ryujinx#6609] opened 2024-04-06 13:54 UTC
### Description of the issue

The main interface froze, making it uninteractive, while still "responding" system wise, with no other way than closing the console screen to stop it.

### Reproduction steps

1. Use \<Game> > `Manage Title Updates`
2. Select two or more invalid updates (I used files unrelated to the selected game)
3. Close the first two error dialog boxes (the appropriate number of `CreateErrorDialog: The specified file does not contain an update for the selected title!` log entries have been created)
4. Boom: interface frozen

### Log file

00:00:00.045 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.052 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.052 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.053 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.053 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.054 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.054 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x249D
00:00:00.055 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.056 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.056 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.057 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.062 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.062 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.062 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.062 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.062 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.063 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.063 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.064 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.064 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.064 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.064 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.067 |I| Configuration LogValueChange: MultiplayerMode set to: Disabled
00:00:00.070 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1258
00:00:00.073 |N| Application Print: Operating System: Microsoft Windows 10.\<redacted> (X64)
00:00:00.074 |N| Application Print: CPU: \<redacted> ; 16 logical
00:00:00.075 |N| Application Print: RAM: Total \<redacted> GiB ; Available \<redacted> GiB
00:00:00.077 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.078 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:02:26.322 |E| Application CreateErrorDialog: The specified file does not contain an update for the selected title!
00:02:26.350 |E| Application CreateErrorDialog: The specified file does not contain an update for the selected title!

### OS

Windows 10

### Ryujinx version

1.1.1258

### Additional context?

#6485 partially mentioned this without entering details

The bug happens the first two dialog windows. even if there are more having popped up: you won't be able to reach them anymore, per frozen interface.

**Comment by piplup55** [comment] 2024-04-06 20:22
duplicate of #6207

**Closed by piplup55** 2024-04-06 20:22 UTC
Labels: bug
