### ISSUE TITLE
[Feature Request] Separate app settings per game

### ISSUE THREAD

**Issue by demboos** [Ryujinx/Ryujinx#7362] opened 2024-09-26 08:24 UTC
### Overview

Per-game emulator settings for things like CPU/Graphics/Controller options.

### Smaller details

Same settings window launchable in per-game context. 

Per game settings override global settings.

### Nature of request

Unfortunately on Apple Silicon Mac some games (BOTW for example) don't work in hypervisor. It is quite annoying to have to turn this option on or off when switching between games (and it makes a noticeable performance difference for titles that work properly with it).

### Why would this feature be useful?

It would be nice to be able to specify per-game settings, for the CPU, Graphics, Controller options etc. Turning on/off the hypervisor for games that do and don't support it is one example.

**Comment by GamerzHell9137** [comment] 2024-09-26 08:31
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1796

**Comment by demboos** [comment] 2024-09-26 08:32
ah sorry, tried to look for sth similar but didn't find it.

**Closed** 2024-09-26 08:38 UTC
Labels: enhancement
