### ISSUE TITLE
Joy-Cons work in yuzu but not in Ryujinx (XInput missing)

### ISSUE THREAD

**Issue by ANTALIFE** [Ryujinx/Ryujinx#2636] opened 2021-09-12 13:46 UTC
### What's the issue you encountered?

I have a bit of an odd issue. I am able to get my official Joy-Cons working in yuzu, but when I try Ryujinx (via Better Joy) XInput is missing and so I can't get them to work

### How can the issue be reproduced?

Start yuzu and check if Joy-Cons appear as option (below I am pushing random buttons to show they are working)
![1](https://user-images.githubusercontent.com/21979291/132990076-d1fff557-6d71-4f9e-9d69-1e8c4ec0b10c.png)

Close yuzu and start Better Joy, make sure Joy-Cons are connected
![2](https://user-images.githubusercontent.com/21979291/132990079-c9d772f9-7258-4685-94b1-c59c6da5cedd.png)

Start Ryujinx and check if Joy-Cons appear as option. In my case they do but XInput is not an option. If I try select "Nintendo Switch Joy-Con Right" or "Nintendo Switch Joy-Con Left" I am unable to map any of the buttons
![3](https://user-images.githubusercontent.com/21979291/132990069-3d261e0d-888c-42ab-83e3-a36bd4bd480a.png)

### Log file

00:00:00.013 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.014 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.014 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.015 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.015 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.018 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.018 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.018 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.018 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.019 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.019 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.019 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.020 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.020 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.020 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.024 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.7032
00:00:00.028 |N| Application Print: Operating System: Microsoft Windows 10.0.19043 (X64)
00:00:00.028 |N| Application Print: CPU: Intel(R) Core(TM) i7-10700KF CPU @ 3.80GHz ; 16 logical
00:00:00.028 |N| Application Print: RAM: Total 16302 MB ; Available 11169 MB
00:00:00.029 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.030 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### Environment?

- Ryujinx v1.0.7032
- Better Joy v6.4b
- yuzu v746
- System Specs:
  - OS: Windows 10 21H1
  - CPU: i7-10700KF
  - GPU: NVIDIA RTX 3070
  - RAM: 16GB
- Applied Mods : N/A

### Additional context?

N/A

**Comment by ANTALIFE** [comment] 2021-09-12 13:55
I just noticed that if I select "Nintendo Switch Joy-Con Right" then I can get the right controller buttons to come through, and if I select "Nintendo Switch Joy-Con Left" then I can get the left controller. So looks like I can only use left or right, but not both...

**Comment by MutantAura** [comment] 2021-09-12 14:26
Native dual joycons are not supported yet. You'll have to use betterjoy or DS4windows in the meantime.

**Comment by AcK77** [comment] 2021-09-13 23:27
Duplicate of #2127

**Closed by AcK77** 2021-09-13 23:27 UTC
