### ISSUE TITLE
[Bug] Crash when scanning ACNH amiibo in linux (steam deck) 

### ISSUE THREAD

**Issue by Bateman421** [Ryujinx/Ryujinx#4850] opened 2023-05-07 23:48 UTC
### Description of the issue

Emulator completely crashes after trying to scan an amiibo in linux Steam OS distro

### Reproduction steps

Scan an animal crossing new horizon amiibo on the steam deck using the OS that it comes with

### Log file

[Ryujinx_1.1.767_2023-05-07_17-52-13.log](https://github.com/Ryujinx/Ryujinx/files/11416397/Ryujinx_1.1.767_2023-05-07_17-52-13.log)

### OS

Linux Steam OS

### Ryujinx version

1.1.775

### Game version

2.0.6

### CPU

Steam Deck cpu

### GPU

Steam Deck gpu

### RAM

16

**Comment by AcK77** [comment] 2023-05-07 23:50
It will be hard to help or try to fix the issue without any log file...

**Comment by Bateman421** [comment] 2023-05-08 00:41
> It will be hard to help or try to fix the issue without any log file...

Sorry about that, was really struggling to get the file but finally managed, I've updated the post with the log file

**Comment by AcK77** [comment] 2023-05-11 16:44
Sadly the provided log doesn't contains any error message, anyone able to reproduce the issue?

**Comment by TSRBerry** [comment] 2023-05-11 16:51
Pretty sure this is a duplicate and they just need to update.

Duplicate of #4877

**Comment by TSRBerry** [comment] 2023-05-11 16:51
Duplicate of #4877

**Closed by TSRBerry** 2023-05-11 16:51 UTC
Labels: bug

**Comment by Bateman421** [comment] 2023-05-11 16:59
> Duplicate of #4877

Hi, Sorry, I think I made a mistake with the version I was using, as my ruyjinx was updated and didn't remember what previous version I was using, so I putted the one that showed after the update but the error is still happening and its related to trying to use an amiibo in ACNH, I don't know if the issue is with all linux or only on steamOS, in any case, Issue is still persistent on 1.1.779.

**Comment by Bateman421** [comment] 2023-05-11 18:09
> Sadly the provided log doesn't contains any error message, anyone able to reproduce the issue?

Want me to try in a different manner to reproduce this error? add anything to get more context?

**Comment by gdkchan** [comment] 2023-05-11 18:41
In the past a few games had issues when scanning Amiibos on Windows because the signal handler was not working properly. It seems that some code path on the Amiibo scan causes a `NullReferenceException`. Since this is implemented on .NET with the application accessing a null pointer and invoking the CLR signal handler, and the emulator overrides the signal handler, it might not work properly if the emulator signal handler is not working properly. And it doesn't right now on Linux. This is just a guess though, I didn't actually test it.

**Comment by TSRBerry** [comment] 2023-05-12 00:06
This is fixed by launching Ryujinx through `Ryujinx.sh` which sets `DOTNET_EnableAlternateStackChange=1`.

**Comment by Bateman421** [comment] 2023-05-12 00:36
> This is fixed by launching Ryujinx through `Ryujinx.sh` which sets `DOTNET_EnableAlternateStackChange=1`.

huh, yeah, you are right!, Thanks so much!
