### ISSUE TITLE
[Bug] Ryujinx Recompiles shaders every time if game launched from external  drive

### ISSUE THREAD

**Issue by d9j** [Ryujinx/Ryujinx#5503] opened 2023-07-30 11:10 UTC
### Description of the issue

I use external samsung t7 ssd for keeping games.

For example launching Totk  complies shaders takes around 5 min on m1 max.  and every time i launch games it recompiles shaders. 

### Reproduction steps

launch games stored on external ssd drive

### Log file

[Ryujinx_1.1.970_2023-07-30_18-56-02.log](https://github.com/Ryujinx/Ryujinx/files/12209015/Ryujinx_1.1.970_2023-07-30_18-56-02.log)

### OS

ventura 13.2.1 (22D68)

### Ryujinx version

1.1.970

### CPU

m1 max

**Comment by Eli0t77** [comment] 2023-07-30 14:16
Must be another factor, because I don't have this problem with my external drive on windows 11

**Comment by Eli0t77** [comment] 2023-08-01 16:25
Ryu compiles any shaders available every time but recompiling is a different thing and takes longer

**Comment by alessandro893** [comment] 2023-08-02 09:08
Is it possible to save compiled shader to disk, and load it on launch without new compilation? It'll better to allocate more space on HDD than wait for a half hour every launch.

**Comment by gdkchan** [comment] 2023-08-02 12:58
Shader compilation takes longer on macOS than other platforms because it has to translate SPIR-V to MSL, and then compile that. Possible ways to make it faster are:
- Using pipeline caches instead of saving the SPIR-V binary.
- Generating MSL directly instead of SPIR-V to skip the SPIR-V -> MSL step, but we would need to generate MSL with the shape that MoltenVK expects. It could become a maintenance nightmare depending on changes made to future versions of MoltenVK/SPIRV-Cross, although long term I do think this is the better solution as it will also reduce stuttering in-game and is a step towards a Metal backend.

**Comment by d9j** [comment] 2023-08-08 13:34
right now it compiles about 6000~7000 shaders. hopefull it wont grow more  :(

**Comment by MutantAura** [comment] 2023-08-13 18:48
Closing as not a bug.

**Closed by MutantAura** 2023-08-13 18:48 UTC
Labels: bug
