### ISSUE TITLE
[Bug ] In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this  ?

### ISSUE THREAD

**Issue by krishna134** [Ryujinx/Ryujinx#7258] opened 2024-08-30 17:07 UTC
### Description of the issue

In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this ?

### Reproduction steps

In Hogwarts Legacy, Version 1.0.2 in Vulkan mode the game fps is amost always at 0fps in cutscenes. Any fix for this ?

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.1380 

### Game version

1.0.2

### CPU

i5-10400f

### GPU

GTX 1650

### RAM

16GB

**Comment by IsaacMarovitz** [comment] 2024-08-31 19:51
Duplicate of #6905

**Closed by IsaacMarovitz** 2024-08-31 19:51 UTC
Labels: bug
