### ISSUE TITLE
Sandboxing in flatpak

### ISSUE THREAD

**Issue by albfan** [Ryujinx/Ryujinx#1515] opened 2020-08-29 21:29 UTC
## Feature Request

Lately some executions ends in a fail where all the system became unresponsive. I cannot even kill the process, just restart by hardware.

Sandboxing ryujinx can help to isolate it and to easily distribute

#### Overview:
- Sanboxing with flatpak

#### Smaller Details: 
flatpak manifest:

```
{
    "app-id": "com.github.Ryujinx",
    "runtime": "org.freedesktop.Platform",
    "runtime-version": "19.08",
    "sdk": "org.freedesktop.Sdk",
    "command": "Ryujinx",
    "finish-args" : [
        "--share=ipc",
        "--share=network",
        "--device=dri",
        "--socket=x11",
        "--socket=wayland",
        "--filesystem=host"
    ],
    "modules": [
        {
            "name": "ryujinx",
            "buildsystem": "simple",
            "build-commands": [
                "install -D Ryujinx /app/bin/Ryujinx"
            ],
            "sources": [
                {
                    "type": "file",
                    "path": "Ryujinx"
                }
            ]
        }
    ]
}
```

copy to Ryujinx/Ryujinx directory.

From root directory:

```
dotnet publish -c Release
cd Ryujinx
dotnet tool install -g dotnet-warp
dotnet warp
flatpak-builder build-dir com.github.Ryujinx.json 
flatpak-builder --repo=repo --force-clean build-dir com.github.Ryujinx.json 
flatpak --user remote-add --no-gpg-verify ryujinx-repo repo
flatpak --user install ryujinx-repo com.github.Ryujinx
cp -r ~/.config/Ryujinx ~/.var/app/com.github.Ryujinx/config/
```

To run it:

    flatpak run com.github.Ryujinx

### Why would this feature be useful?
- Easier distribution
- Isolation from host

-TODO: As you can see build is done on host, but I suppose it can be build on top of flatpak dotnet core runtime.

**Comment by albfan** [comment] 2020-08-29 21:49
At this moment this fails with:

```
00:00:00.199 |N| Application LoadApplication: Using Firmware Version: 10.1.0
00:00:00.932 |N| Application : Unhandled exception caught: System.InvalidCastException: Unable to cast object of type 'OpenTK.Platform.X11.X11WindowInfo' to type 'OpenTK.Platform.Linux.LinuxWindowInfo'.
   at OpenTK.Platform.Linux.LinuxFactory.CreateGLContext(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Boolean directRendering, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, IGraphicsContext shareContext, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.Graphics.GraphicsContext..ctor(GraphicsMode mode, IWindowInfo window, Int32 major, Int32 minor, GraphicsContextFlags flags)
   at OpenTK.GLWidget.Initialize()
   at OpenTK.GLWidget.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

**Comment by albfan** [comment] 2020-08-30 10:57
https://github.com/flathub/flathub/pull/1778

**Comment by Thog** [comment] 2020-08-30 11:14
Duplicate of #1077, closing.

**Closed by Thog** 2020-08-30 11:14 UTC
