### ISSUE TITLE
Upscaling causes red tints to appear in some games

### ISSUE THREAD

**Issue by Theslees** [Ryujinx/Ryujinx#3456] opened 2022-07-09 19:10 UTC
### What's the issue you encountered?
Upscaling both A Hat in Time or Say No More causes a strange redness to appear on some of the geometry in both games. The more you upscale in SNM the more visible it becomes.

### How can the issue be reproduced?
Booting any of the mentioned games, then upscale past native resolution

### These games were tested under 2 enviroments, one is mine (AHiT) and the other is a different user's (SNM).
# A Hat in Time Enviroment
### Logs?
[Ryujinx_1.1.171_2022-07-08_23-18-53.log](https://github.com/Ryujinx/Ryujinx/files/9075784/Ryujinx_1.1.171_2022-07-08_23-18-53.log)

### Environment?

- **Ryujinx version: 1.1.171**</br>

- **Game version: 1.0.4**</br>

- **System Specs:**
  - OS: *Arch linux 5.18.9-arch1-1 x86_64*
  - CPU: *AMD Ryzen 5 5600G*
  - GPU: *Vega 8 APU(integrated)*
  - RAM: *32GB Dual channel SODIMM*
- Applied Mods : **Yes, 60fps mod. Issue persists without mods though**

### Pictures:
![image](https://user-images.githubusercontent.com/59808149/178089930-7c38a1c9-b893-4faf-90fc-e961c03c92d3.png)
`Without upscale`
![image](https://user-images.githubusercontent.com/59808149/178089937-dc525400-37a2-4554-9174-a119a9610594.png)
`With 2x upscale`
![image](https://user-images.githubusercontent.com/59808149/178119419-f560a808-813a-482e-ab72-14b20f9e8e87.png)
`Without upscale`
![image](https://user-images.githubusercontent.com/59808149/178119437-70d0b388-61de-4d03-82de-fac4ad5efd1d.png)
`With 2x upscale`
# Say No More Enviroment
### Logs?
[Ryujinx_1.1.166_2022-07-08_21-34-46.txt](https://github.com/Ryujinx/Ryujinx/files/9075801/Ryujinx_1.1.166_2022-07-08_21-34-46.txt)

### Environment?

- **Ryujinx version: 1.1.166**</br>

- **Game version: 1.0**</br>

- **System Specs:**
  - OS: *Windows 10.0.22000 (X64)*
  - CPU: *AMD Ryzen 7 5800H*
  - GPU: *NVIDIA GeForce RTX 3060 Laptop*
  - RAM: *16GB*
- Applied Mods : **No**
### Pictures:
![image](https://user-images.githubusercontent.com/59808149/178119197-12dbf367-4d66-4173-8183-f8ddfd8a079c.png)
`Without upscale`
![image](https://user-images.githubusercontent.com/59808149/178119206-2e34ec28-bbad-408a-bf7b-aa673b50fa23.png)
`With 2x upscale`
![ryujinx_capture_2022-07-09_19-52-12](https://user-images.githubusercontent.com/59808149/178119374-1391ee93-dce2-4f9b-ada3-aec3810ac1dd.png)
`With 3x upscale`
# Additional Context
The red tint gets worst the more you upscale for SNM, but looks fine at 4x for some reason. For AHiT though, the game also has no red tints when it's upscaled to 3x too, but persists when going to 4x. 

AHiT is a UE4 game and SNM is a Unity game, and the way the red tint appear is slightly different in both games (much more aggressive and noticible in SNM) We don't know if any other games have an issue like this so this is all we can provide for the bug report

**Comment by mjcox244** [comment] 2022-07-09 19:21
There is another branch of this red tint with Say No! More where the tables in Chapter 3's meeting rooms also do not display propperly

![ryujinx_capture_2022-07-09_20-18-40](https://user-images.githubusercontent.com/66311016/178119852-fc4eb97b-d9a3-4bd3-b844-6c8665c3bf91.png)
[2x res]

![ryujinx_capture_2022-07-09_20-18-55](https://user-images.githubusercontent.com/66311016/178119863-41c6a846-d109-4a98-b974-e4c015d04583.png)
[1X res]

**Comment by riperiperi** [comment] 2022-07-09 19:24
This is likely related to colour LUTs that the games use for tonemapping, which can be 2d textures that are essentially a line of 3d slices. If they're scaled, it's possible for the edge of one slice to bleed into the other, so the solution would be to not scale them. I haven't yet looked into a good way to detect this.

**Comment by EliEron** [comment] 2022-07-10 11:17
The same issue occurs in _**World's End Club**_ which is also a Unity game.

**1x**:
![Ryujinx_1DTNvkaqEY](https://user-images.githubusercontent.com/22575945/178142404-40dd206f-99d8-4cc1-916b-261d4deae0f7.png)

**2x**:
![Ryujinx_IlhVa4eXaC](https://user-images.githubusercontent.com/22575945/178142412-32811795-2081-4d03-99e3-8469a4c08f19.png)

**3x**:
![Ryujinx_jLjH6aLDCR](https://user-images.githubusercontent.com/22575945/178142416-6a3d60f8-6f54-48ea-be63-2defae9a8f70.png)

**4x**:
![Ryujinx_whA9H6HDRY](https://user-images.githubusercontent.com/22575945/178142420-3d0ee27e-80d2-4a72-88de-e44c46fded3f.png)

And according to the game compatibility database the issue also occurs in _**[Sherlock Holmes: The Devil's Daughter](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3935)**_ and **_[Lost in Random](https://github.com/Ryujinx/Ryujinx-Games-List/issues/3724)_**

**Comment by Niwu34** [comment] 2022-07-10 12:43
This issue is kind of a duplicate of https://github.com/Ryujinx/Ryujinx/issues/1488

**Comment by gdkchan** [comment] 2022-07-16 01:55
Fixed by #3464.

**Closed by gdkchan** 2022-07-16 01:55 UTC
Labels: bug, gpu
