### ISSUE TITLE
[Bug Report] super mario party crashed

### ISSUE THREAD

**Issue by Augus1217** [Ryujinx/Ryujinx#7185] opened 2024-08-09 03:43 UTC
### Description of the issue

When i select "OK!" button, the ryujinx is crashed..
It happend every time when i open super mario party.
I never seen it in another ryujinx games.

### Reproduction steps

https://github.com/user-attachments/assets/74efc742-8274-4a2b-b361-b5e9d91d780d

watch the video

### Log file

Unhandled exception. Ryujinx.Graphics.Vulkan.VulkanException: Unexpected API error "ErrorDeviceLost".
   at Ryujinx.Graphics.Vulkan.CommandBufferPool.Return(CommandBufferScoped cbs, ReadOnlySpan`1 waitSemaphores, ReadOnlySpan`1 waitDstStageMask, ReadOnlySpan`1 signalSemaphores) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\CommandBufferPool.cs:line 279
   at Ryujinx.Graphics.Vulkan.PipelineFull.FlushCommandsImpl() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\PipelineFull.cs:line 261
   at Ryujinx.Graphics.Vulkan.SyncManager.Create(UInt64 id, Boolean strict) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.Vulkan\SyncManager.cs:line 50
   at Ryujinx.Graphics.GAL.Multithreading.CommandHelper.<>c.<InitLookup>b__5_1[T](Span`1 memory, ThreadedRenderer threaded, IRenderer renderer) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\CommandHelper.cs:line 43
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 144
   at Ryujinx.Graphics.GAL.Multithreading.ThreadedRenderer.RunLoop(ThreadStart gpuLoop) in D:\a\Ryujinx\Ryujinx\src\Ryujinx.Graphics.GAL\Multithreading\ThreadedRenderer.cs:line 113
   at Ryujinx.Ava.AppHost.RenderLoop() in D:\a\Ryujinx\Ryujinx\src\Ryujinx\AppHost.cs:line 995
   at System.Threading.Thread.StartCallback()

### OS

Windows 11

### Ryujinx version

1.1.1373

### Game version

1.1.0

### CPU

Ultra 5 125H

### GPU

Intel(R) Arc(TM) Graphics

### RAM

16GB

**Comment by gdkchan** [comment] 2024-08-09 03:55
Duplicate of #6478.

**Closed by gdkchan** 2024-08-09 03:55 UTC
Labels: bug
