### ISSUE TITLE
Monster Hunter Rise crashes AMD GPU upon entering game menu

### ISSUE THREAD

**Issue by Stooovie** [Ryujinx/Ryujinx#2195] opened 2021-04-11 06:14 UTC
build 1.0.6824 as well as LDN 2.2 crash AMD GPU driver every time Monster Hunter Rise reaches the in-game menu (the prompts and intro screens display fine). 

Tried AMD drivers 21.3.1 and 21.3.2, both crash (black screen, can recover). Windows 10 build 19042.906

**Comment by jochuan** [comment] 2021-04-11 15:35
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1114

**Closed** 2021-04-11 19:14 UTC
