### ISSUE TITLE
MacBook wont let the game runn. 

### ISSUE THREAD

**Issue by Tuketu** [Ryujinx/Ryujinx#2067] opened 2021-02-27 20:39 UTC
### What's the issue you encountered?
00:00:01.905 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path '/Users/sascha/Downloads/Pokémon Shield [NSP]/Pokemon Shield [2 DLC Expansion Pass]/Pokemon Shield [DLC][01008DB008C2D001][v0].nsp'.
   at Interop.ThrowExceptionForIoErrno(ErrorInfo errorInfo, String path, Boolean isDirectory, Func`2 errorRewriter)
   at Microsoft.Win32.SafeHandles.SafeFileHandle.Open(String path, OpenFlags flags, Int32 mode)
   at System.IO.FileStream.OpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ryujinx.HLE.FileSystem.Content.ContentManager.AddAocItem(UInt64 titleId, String containerPath, String ncaPath, Boolean enabled) in C:\projects\ryujinx\Ryujinx.HLE\FileSystem\Content\ContentManager.cs:line 254
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNca(Nca mainNca, Nca patchNca, Nca controlNca) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 338
   at Ryujinx.HLE.HOS.ApplicationLoader.LoadNsp(String nspFile) in C:\projects\ryujinx\Ryujinx.HLE\HOS\ApplicationLoader.cs:line 283
   at Ryujinx.Ui.MainWindow.LoadApplication(String path) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 506
   at Ryujinx.Ui.MainWindow.Row_Activated(Object sender, RowActivatedArgs args) in C:\projects\ryujinx\Ryujinx\Ui\MainWindow.cs:line 842
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)

### Log file
[Ryujinx_1.0.6732_2021-02-27_21-13-41.log](https://github.com/Ryujinx/Ryujinx/files/6055330/Ryujinx_1.0.6732_2021-02-27_21-13-41.log)

### Environment?

- Ryujinx version: 1.0.6732

- Game version: Pokemon Shield [01008DB008C2C000][v0](nsw2u.com)</br>
- System Specs:
  - OS: *MAC OS BigSure*
  - CPU: *2.3 GHz Dual-Core Intel Core i5*
  - GPU: *Intel Iris Plus Graphics 640 1536 MB*
  - RAM: *8*
- Applied Mods : [No]

Thank you for reading

**Comment by EmulationFanatic** [comment] 2021-02-27 21:03
The client does not work properly on macOS in either x86 or Apple silicon. Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/348

**Closed by EmulationFanatic** 2021-02-27 21:03 UTC
