### ISSUE TITLE
Ryujinx application issue on macOS Big Sur on a MacBook Pro 16-inch AMD Radeon GPU, 16 Core CPU

### ISSUE THREAD

**Issue by KohlerVG** [Ryujinx/Ryujinx#2075] opened 2021-03-03 17:15 UTC
Hi Ryujinx Team,

I'm trying to get Ryujinx running on my MacBook Pro but when I download the latest mac build there is no application to open from the publish file? am I doing something wrong? please help!

Thanks for any help,
Kohler

**Comment by EmulationFanatic** [comment] 2021-03-03 17:17
macOS is currently unsupported, both on x86 and apple silicon. Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/348

**Closed by EmulationFanatic** 2021-03-03 17:17 UTC
