### ISSUE TITLE
ryujinx stop emulation deadlock

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#3402] opened 2022-06-14 12:37 UTC
### What's the issue you encountered?

play a game (not just run, but play) for ~1hr or more then stop emulation, the emulator will freeze and it must be killed.

### Log file

none

### Environment?

- Ryujinx version: 1.1.146</br>
- System Specs:
  - OS: archlinux
  - CPU: i7-1165g7
  - GPU: xe
  - RAM: 16gb
- Applied Mods : no

### Additional context?

this happens with vulkan build too ofc, but there, it is annoying, because some zombie ryujinx processes will remain active and they have to be killed to free your ram and to able to run games when you restart ryujinx or you will get "Unknown API error" on any game

the api error will affect master builds too, ie, if the vulkan build will deadlock and some zombie processes reamins, if you run ogl build you will get the same api error with ogl

i did not notice zombie processes with master builds, but maybe it was pure luck, no idea

**Comment by MutantAura** [comment] 2022-06-14 12:53
Duplicate of #2863

**Closed by MutantAura** 2022-06-14 12:53 UTC
