### ISSUE TITLE
[Bug] Ryujinx's popup window doesn't show in full screen mode on macOS

### ISSUE THREAD

**Issue by HubertZhang** [Ryujinx/Ryujinx#4939] opened 2023-05-14 06:02 UTC
### Description of the issue

I'm using Ryujinx on M1 Max MacStudio. When using Ryujinx in full screen mode, popup window will not show and blocks the whole program.

### Reproduction steps

- Open "Mii edit applet"
- Enter fullscreen mode
- Choose Actions > Stop emulation
- Confirmation popup doesn't show and whole program stops responding.

### Log file

[Ryujinx_1.1.799_2023-05-14_14-00-14.log](https://github.com/Ryujinx/Ryujinx/files/11471249/Ryujinx_1.1.799_2023-05-14_14-00-14.log)

### OS

macOS 13.3.1

### Ryujinx version

1.1.799

### CPU

M1 Max

### GPU

M1 Max

### RAM

32GB

**Comment by MutantAura** [comment] 2023-06-24 23:44
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5186

**Closed by MutantAura** 2023-06-24 23:44 UTC
Labels: bug, gui
