### ISSUE TITLE
Pokemon sword/shield pokemon center crash

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#2388] opened 2021-06-22 10:09 UTC
### What's the issue you encountered?

random ryujinx crash when entering or exiting any pokemon center

### How can the issue be reproduced?

enter or exit a pokemon center or try to heal your pokemons (seems to be a trigger too, just rare)

### Log file
[Ryujinx_1.0.6917_2021-06-22_13-31-14.log](https://github.com/Ryujinx/Ryujinx/files/6693235/Ryujinx_1.0.6917_2021-06-22_13-31-14.log)

### Environment?

- Ryujinx version: 1.0.6917
- Game version: 1.3.2
- System Specs:
  - OS: archlinux
  - CPU: 1165g7
  - GPU: iris xe
  - RAM: 16
- Applied Mods : no

**Comment by SinFlame** [comment] 2021-06-27 11:08
`00:00:00.008 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.009 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.009 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.009 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.015 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.0-ldn2.3
00:00:00.018 |N| Application Print: Operating System: Microsoft Windows 10.0.19042 (X64)
00:00:00.018 |N| Application Print: CPU: Intel(R) Core(TM) i7-7700K CPU @ 4.20GHz ; 8 logical
00:00:00.018 |N| Application Print: RAM: Total 32644 MB ; Available 27553 MB
00:00:00.019 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.019 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.467 |N| Application LoadApplication: Using Firmware Version: 12.0.2
00:00:20.060 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce GTX 1060 6GB/PCIe/SSE2 (4.6.0 NVIDIA 471.11)
00:03:06.913 |N| GUI.RenderLoop Application : Unhandled exception caught: System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.BindBuffers(BuffersPerStage[] bindings, Boolean isStorage) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 819
   at Ryujinx.Graphics.Gpu.Memory.BufferManager.CommitGraphicsBindings() in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Memory\BufferManager.cs:line 800
   at Ryujinx.Graphics.Gpu.Engine.Methods.UpdateState(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\Methods.cs:line 125
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 firstIndex, Int32 indexCount) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 71
   at Ryujinx.Graphics.Gpu.Engine.Methods.DrawEnd(GpuState state, Int32 argument) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\MethodDraw.cs:line 40
   at Macro(MacroJitContext , GpuState , Int32 )
   at Ryujinx.Graphics.Gpu.Engine.MME.Macro.Execute(ReadOnlySpan`1 code, GpuState state) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\MME\Macro.cs:line 78
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Send(UInt64 gpuVa, MethodParams meth) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 145
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoProcessor.Process(UInt64 baseGpuVa, ReadOnlySpan`1 commandBuffer) in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoProcessor.cs:line 68
   at Ryujinx.Graphics.Gpu.Engine.GPFifo.GPFifoDevice.DispatchCalls() in C:\project\ryujinx\Ryujinx.Graphics.Gpu\Engine\GPFifo\GPFifoDevice.cs:line 178
   at Ryujinx.Ui.RendererWidgetBase.Render() in C:\project\ryujinx\Ryujinx\Ui\RendererWidgetBase.cs:line 307
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
`

This is my log, hope it helps too

Also, not sure if this info helps,  maybe its just a path that wasnt fixed. I dont have  C:\project path, my ryujinx folder is somewhere else. Seeing OP's log, shows that path too

**Comment by SinFlame** [comment] 2021-06-30 06:09
Still crashing after 1.0.6945 update

**Comment by AcK77** [comment] 2021-07-17 12:54
Could you please upload a log file with all logs informations enabled, for a strange reason you seems to have disabled them in previous log files. Thanks.

**Comment by A-w-x** [comment] 2021-07-20 10:50
here you go

7z archive, remove .zip extension, multipart due to github limits

[Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.001.zip](https://github.com/Ryujinx/Ryujinx/files/6847617/Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.001.zip)
[Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.002.zip](https://github.com/Ryujinx/Ryujinx/files/6847618/Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.002.zip)
[Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.003.zip](https://github.com/Ryujinx/Ryujinx/files/6847621/Ryujinx_1.0.6974_2021-07-20_13-34-23.7z.003.zip)

**Comment by pipeysh** [comment] 2021-08-05 09:51
experiencing the same issue, but my crashes happen during transitions, like entering or exiting buildings, start or end of cutscenes.

i tried both the latest build and recently, the latest ldn build

[Ryujinx_1.0.0-ldn2.3_2021-08-05_17-01-54.log](https://github.com/Ryujinx/Ryujinx/files/6937655/Ryujinx_1.0.0-ldn2.3_2021-08-05_17-01-54.log)

**Comment by gdkchan** [comment] 2021-11-22 22:14
Duplicate of #1641.

**Closed by gdkchan** 2021-11-22 22:14 UTC
Labels: bug, gpu
