### ISSUE TITLE
Unable to use dedicated GPU on Linux.

### ISSUE THREAD

**Issue by EeveeEuphoria** [Ryujinx/Ryujinx#3215] opened 2022-03-19 14:07 UTC
### What's the issue you encountered?

Running Ryujinx with my dedicated GPU in linux causes it to crash when trying to play any game. This happens regardless of game choice, in my case I chose VVVVVV just because it's the quickest to load on-hand.

When loading this with the integrated graphics, everything responds normally. But when I use prime-run to engage the dedicated GPU, the software crashes. This is a software crash that seems unique to Ryujinx, since it doesn't happen in any other game, and using it to force Yuzu to use the DGPU doesn't cause any issues there.

### How can the issue be reproduced?

With a laptop that utilizes Nvidia Prime/Optimus, install [Nvidia's propietary PRIME](https://wiki.archlinux.org/title/PRIME#PRIME_render_offload) utilities. Use this to run `prime-run ./Ryujinx`.

### Log file
[Full log here.](https://pastebin.com/Yn2FsTGp)

```
00:00:01.374 |I| ModLoader LoadCheats: Build ids found for title 0100B1E0022F8000:
    4044ECA5ABC5055B1B0BB8B9BABE1C9B524A4579000000000000000000000000
    0F3B1EC3E3BF0614A7C96F45FF05AC3900000000000000000000000000000000
    A82AA14C5D5A359AD04DC4EAB9F5D5901315EE5E000000000000000000000000
    11204A6CF18573BB3820E9C80540E769F0072E53000000000000000000000000
    C871C614793A419581104BEC9379EFA3CFF00276000000000000000000000000
00:00:01.375 |I| Loader LoadNca: Application Loaded: VVVVVV v1.1 [0100b1e0022f8000] [64-bit]
00:00:01.395 |I| GUI.WindowThread Hid Configure: Configured Controller ProController to Player1
XError: 0 result is 160
00:00:01.528 |E| Application : Unhandled exception caught: SPB.Graphics.Exceptions.ContextException: MakeCurrent() failed.
   at SPB.Platform.GLX.GLXOpenGLContext.MakeCurrent(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL() in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\GLRenderer.cs:line 50
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr) in D:\a\Ryujinx\Ryujinx\Ryujinx\Ui\GLRenderer.cs:line 36
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)
```

### Environment?

- Ryujinx version: 1.1.77</br>
- System Specs:
  - OS: EndeavourOS Linux x86_64, with kernel 5.16.15-arch1-1
  - CPU: Intel i5-9300H
  - iGPU: Intel CoffeeLake-H GT2 [UHD Graphics 630] 
  - dGPU: NVIDIA GeForce GTX 1650 Mobile / Max-Q 
  - RAM: *(e.g. 16GB)*

### Additionally

Running Yuzu without prime-run seems to utilize the Nvidia gpu regardless, since it seems to detect it all on it's own, not necessitating the need for prime-run.

**Comment by MetrosexualGarbodor** [comment] 2022-03-19 14:10
Duplicate of #2112.

**Closed by MetrosexualGarbodor** 2022-03-19 14:10 UTC
