### ISSUE TITLE
Latest AMD GPU Drivers output no graphics

### ISSUE THREAD

**Issue by yuwenhua653** [Ryujinx/Ryujinx#2311] opened 2021-05-25 07:10 UTC
In the latest mainline version.I use AMD Ryzen 7 5700U CPU and its own core graphics card, there is no image, only sound, the driver is the latest version

**Comment by jduncanator** [comment] 2021-05-25 07:22
This is a duplicate of https://github.com/Ryujinx/Ryujinx/issues/2236 so closing this in lieu of that issue.

**Closed** 2021-05-25 07:22 UTC
Labels: bug, gpu

**Comment by l3eindiiz2** [comment] 2021-06-04 10:42
**what version can i use to play it please tell me**  @jduncanator
