### ISSUE TITLE
(Feature request) Shader compilation notification

### ISSUE THREAD

**Issue by ooa113y** [Ryujinx/Ryujinx#2369] opened 2021-06-15 09:30 UTC
#### Overview:
- A notification in the GUI for when shaders are being compiled, similar to that of e.g. RPCS3 or yuzu.

#### Nature of Request:  
- Addition

### Why would this feature be useful?
Currently, when shaders are being compiled, the game just freezes with zero actual feedback. While it may be possible to deduce that the freeze is due to shaders ("I haven't encountered this enemy before/haven't been in this area/etc, so a shader is probably being built for it"), such deductions are not intuitive to users who do not understand the shader compilation process well, nor are they guaranteed to be correct. Furthermore, in games where a huge amount of shaders needs to be built at once, the freeze from it can take quite a long time, to the point where the user might assume that the game itself froze.

A proper notification for when shaders are being built would allow the user to know whether the slowdown they are experiencing is simply a byproduct of building shaders and is something that would disappear as they play more, or the game "actually" being slow on their hardware.

This feature might be less relevant once Vulkan and/or ARB shaders drop, but since that won't reduce the shader compilation stutter to zero, it would still be useful even at that point.

**Comment by choppymaster** [comment] 2021-06-16 02:40
Duplicate of #1705 ?

**Closed** 2021-06-16 02:41 UTC
