### ISSUE TITLE
ฺBug AMD GPU RX570 version AMD  radeon-software-adrenalin-2020-21.3.1-win10-64bit 

### ISSUE THREAD

**Issue by l3eindiiz2** [Ryujinx/Ryujinx#2342] opened 2021-06-04 12:04 UTC
i use Version Ryujnx ldn2.3 
CPU Ryzen 5 2600 - 6 core / 12t speed 3.6 +
RAM 32GB
GPU RX570 - 4GB //version AMD radeon-software-adrenalin-2020-21.3.1-win10-64bit-mar24
Start the game and log out. ++

What do I have to do to be able to play monster hunter rise game?

**Comment by CrusadingNinja** [comment] 2021-06-04 12:09
You have to use Linux to be able to play MHR on AMD GPU. Alternatively you can wait for it to get fixed on AMD Windows but there is no timeline for when that might happen.

**Comment by l3eindiiz2** [comment] 2021-06-04 12:17
> You have to use Linux to be able to play MHR on AMD GPU. Alternatively you can wait for it to get fixed on AMD Windows but there is no timeline for when that might happen.

Is it possible to install linux version on windows?
May I have a download link ?

**Comment by Benedani** [comment] 2021-06-04 14:26
The problem isn't with Ryujinx, the problem is with the drivers. You need to use a Linux system to be able to use the open source Mesa driver instead which is significantly less broken. By the way, Linux isn't just for running Ryujinx on an AMD GPU, there are many more advantages such as reliability and control over your system. You can come on [Discord](https://discord.gg/ryujinx) into the #linux-master-race channel to get help with getting started.

**Comment by AcK77** [comment] 2021-06-05 21:04
Please open a new issue following our template with much informations as possible. Thanks.

**Closed by AcK77** 2021-06-05 21:04 UTC
