### ISSUE TITLE
Missing Text in Zelda TOTK on Linux with OpenGL; Audio Delay with SDL2

### ISSUE THREAD

**Issue by olavohrm** [Ryujinx/Ryujinx#7052] opened 2024-07-18 16:55 UTC
### Description of the issue

When playing Zelda TOTK on Linux using OpenGL, the text within the game does not display correctly. Instead of showing the expected font, the area where text should appear remains blank.

Additionally, when using the SDL2 Audio API with Vulkan, there is a noticeable delay in audio playback during gameplay. This results in a desynchronized audio experience, negatively impacting gameplay

### Reproduction steps

Launch Zelda TOTK on either Big Linux or Manjaro with Kernel 6.9.9-1 and Mesa driver 24.1.3-1. Ensure Ryujinx emulator is set to firmware version 18.1.0.

### Log file

[Ryujinx_1.1.1352_2024-07-18_13-17-59.log](https://github.com/user-attachments/files/16286503/Ryujinx_1.1.1352_2024-07-18_13-17-59.log)

### OS

Big Linux, Manjaro

### Ryujinx version

1.1.1352

### Game version

1.2.1

### CPU

Xeon 2667 V4

### GPU

RX 580 2048SP

### RAM

16GB

### List of applied mods

[Mods.zip](https://github.com/user-attachments/files/16286545/Mods.zip)

**Comment by piplup55** [comment] 2024-07-18 17:01
duplicate of #6993

**Closed by piplup55** 2024-07-18 17:01 UTC
Labels: bug
