### ISSUE TITLE
DirectInput or Dinput for RyujiNX Controls

### ISSUE THREAD

**Issue by FinaleRoyale** [Ryujinx/Ryujinx#2038] opened 2021-02-19 19:57 UTC
#### Overview:
I want support for DirectInput or Dinput in the RyujiNX Emulator as a controller input source.

#### Smaller Details: 
Maybe something that says PS4 Controller 1 or Dinput 1 for whenever you connect a dinput controller, for more diversity of controls. DS4Windows can be a bit buggy sometimes and this would be much appreciated.

#### Nature of Request:  
An addition to the current controller code.

### Why would this feature be useful?
Ease of use and multiple sources of controls that can be added to the emulator.

**Comment by EmulationFanatic** [comment] 2021-02-19 22:50
DirectInput is already supported, though it is known to be a tad on the buggy side. #1751 helps with this.

**Comment by AcK77** [comment] 2021-04-11 19:58
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by AcK77** [comment] 2021-04-14 16:19
Should be fixed in #2194

**Closed by AcK77** 2021-04-14 16:19 UTC
Labels: fix, service:hid
