### ISSUE TITLE
Unimplemented Trap instruction

### ISSUE THREAD

**Issue by yeboi51** [Ryujinx/Ryujinx#3580] opened 2022-08-13 14:57 UTC
### What CPU instruction is missing?

Requires the *trap* instruction.</br>

```
Unhandled exception caught: Ryujinx.HLE.Exceptions.UndefinedInstructionException: The instruction at 0x000000000c30ed14 (opcode 0xe7ffdefe) is undefined!
```

### Instruction name
```
trap 
```

### Required by: 
https://github.com/Ryujinx/Ryujinx-Games-List/issues/749

**Comment by EmulationFanatic** [comment] 2022-08-13 15:04
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1340

**Closed by EmulationFanatic** 2022-08-13 15:04 UTC
