### ISSUE TITLE
Depth buffer corruption in Mario Kart 8 Deluxe

### ISSUE THREAD

**Issue by treacherousfiend** [Ryujinx/Ryujinx#4335] opened 2023-01-23 03:46 UTC
### What's the issue you encountered?

The depth buffer on some maps in Mario Kart 8 Deluxe, most notably Berlin Byways, have parts of the map where the depth buffer will consistently corrupt in odd ways.
Sometimes this results in completely clearing the depth buffer, other times rendering some objects (like players) but not others to the depth buffer.
This doesn't seem to cause any visual glitches by default, but when using other programs that rely on the depth buffer, like Reshade, it becomes very apparent.

One thing I did note is that the issue seems to happen more in certain parts of the map, and also more often depending on how many other players are on screen, perhaps there's some issue with too many vertices or objects on screen?
Because of this, i'd recommend not using Time Trial mode when testing this, although it does still happen there it doesn't happen as often.

EPILEPSY WARNING - video taken with Reshade shader "display depth" active to show off the issue
https://user-images.githubusercontent.com/46549454/213961224-1b522833-be89-41cd-bcca-47dd6c526f1c.mp4

Ryujinx using default settings, Vulkan backend

### How can the issue be reproduced?

1. Start game on course Berlin Byways or watch MKTV recording of a game on Berlin Byways
2. Enable Reshade with "display depth" shader, or alternatively use some other method to view the depth buffer

### Log file
Log file of me watching back a recording on MKTV, doesn't seem to have anything too helpful, but i'll leave that for smarter people to decide
[Ryujinx_1.1.592_2023-01-22_20-25-52.log](https://github.com/Ryujinx/Ryujinx/files/10476548/Ryujinx_1.1.592_2023-01-22_20-25-52.log)

### Environment?

- Ryujinx version: 1.1.592</br>
- Game version: 2.2.1</br>
- System Specs:
  - OS: Windows 10 Home 22H2
  - CPU: Intel I7-7700k
  - GPU: *NVIDIA GTX 1070
  - RAM: 16GiB
- Applied Mods : Yes
  - Mario Kart 8 Deluxe - Booster Course DLC

### Additional context?

Version of Reshade installed: 5.6.0

**Comment by riperiperi** [comment] 2023-01-23 12:26
This is likely a problem with how reshade is configured to capture the depth buffer, not a bug with the game running under the emulator. It looks like it is getting an incomplete or unused depth buffer (perhaps could happen if it changed location).

When there are lots of characters on the screen on berlin byways, the game frequently flushes textures back to guest memory. I'm not sure if reshade is reacting negatively to this, but it is perfectly fine for correctness apart from being a bit slow.

**Comment by treacherousfiend** [comment] 2023-01-23 21:23
hmm, alright then, I'll report this issue to the reshade devs and see what they say, It just seemed more likely that it was an emulator problem to me

**Comment by AcK77** [comment] 2023-05-05 07:53
Since this is related to a reshade issue. I close it. Thanks.

**Closed by AcK77** 2023-05-05 07:53 UTC
