### ISSUE TITLE
[Bug] Black screen on TOTK

### ISSUE THREAD

**Issue by marco-carvalho** [Ryujinx/Ryujinx#5139] opened 2023-05-29 01:36 UTC
### Description of the issue

Black screen on title menu

### Reproduction steps

Just launch the game

### Log file

[Ryujinx_1.1.841_2023-05-28_22-28-50.log](https://github.com/Ryujinx/Ryujinx/files/11587448/Ryujinx_1.1.841_2023-05-28_22-28-50.log)

### OS

Windows 10

### Ryujinx version

1.1.841

### Game version

1.0.0

### GPU

i5-8250U

### RAM

8GB

**Comment by MetrosexualGarbodor** [comment] 2023-05-29 01:39
Please use discord for support queries: https://discord.gg/ryujinx
Closing as duplicate of #4922.

**Closed by MetrosexualGarbodor** 2023-05-29 01:39 UTC
Labels: bug

**Comment by marco-carvalho** [comment] 2023-05-29 01:47
I opened the issue because the black screen was not appearing after the commits of today...
