### ISSUE TITLE
PS5 Controller beeping

### ISSUE THREAD

**Issue by ghost** [Ryujinx/Ryujinx#3387] opened 2022-06-06 08:00 UTC
**What's the issue you encountered?**

The PS5 Controller has speaker which turn on and cause a high pitch beeping sound.

**How can the issue be reproduced?**

1. Close Ryujinx & turn PS5 Controller off
2. Start PS5 Controller
3. Start Ryujinx
4. Go into Options - Settings - Input
5. Click Configure Player 1 and select the PS5 Contrller
6. It turns the PS5 speaker ON and causes the high pitched beeping sound

**Log file**

N/A

**Environment?**

- Ryujinx version: 1.1.142
- System Specs:
  - OS: *Windows 11*
  - CPU: *i5 8600k*
  - GPU: *3060Ti*
  - RAM: *32GB*

**Comment by german77** [comment] 2022-06-06 16:08
Really weird issue. I don't think SDL even has access to the speaker. I would suggest closing other apps like steam and try again

**Comment by turkeynaruto** [comment] 2022-06-06 16:28
> Really weird issue. I don't think SDL even has access to the speaker. I would suggest closing other apps like steam and try again


I didnt had Steam ON or anything else.
I also tried it multiple times and everytime I clicked on Ryujinx "configure Player 1" OR I just started a game the beeping began.
Now I tried it again and suddenly it doesnt happen anymore.

**Comment by GamerzHell9137** [comment] 2022-06-06 16:31
Also in Sound -> Playback there should be an audio device for the PS5 speaker. Disable it if there is one. PS4 controller has it.

**Comment by marysaka** [comment] 2023-03-24 11:49
Can't reproduce.

**Closed by marysaka** 2023-03-24 11:49 UTC
