### ISSUE TITLE
Multiple games crash upon launch when using Host memory management + Linux on 1.1.110 and above

### ISSUE THREAD

**Issue by QuadPiece** [Ryujinx/Ryujinx#3372] opened 2022-05-30 14:10 UTC
## Bug Report

Repost of #3356 as per request from @MutantAura.

### What's the issue you encountered?

Shin Megami Tensei V crashes upon launch when running under Linux and with memory management set to Host or Host Unchecked.  
Setting memory management to Software allows the game to launch.

Additional game crashes reported by @HerrIrrtum:

- Triangle Strategy
- Bravely Default II
- Oceanhorn 2
- Tetris Effect Connected

Possibly related to #3349 

Ryujinx closes with a segfault or an "Out of memory" left in the terminal while launching a problematic game.

All games have been functional previously.

### How can the issue be reproduced?

1. Run any recent Linux distro (Arch, Ubuntu 22.04, etc.)
2. Ensure memory management is set to "Host" or "Host (Unchecked)"
3. Launch a problematic game in Ryujinx (for example SMT V)
4. Ryujinx crashes and closes during game launch

### Log file

[ryujinx-smtv.log](https://github.com/Ryujinx/Ryujinx/files/8798860/ryujinx-smtv.log)

### Environment?

- Ryujinx version: 1.1.132
- Game version: 1.0.0, 1.0.1 and 1.0.2  
- System Specs:
  - OS: *Arch Linux x86_64*
  - CPU: *Ryzen 5 5600X*
  - GPU: *AMD Radeon RX 6700 XT*
  - RAM: *32GB*
- Applied Mods : No

### Additional context?

Tested on Arch Linux, Chimera OS and Ubuntu.  
Tested with Intel Iris Xe and UHD 605 graphics, as well as RX 6700 XT.  
All machines have 16GB ram or more.  
Same crash happens on all machines.

SMT V is the only game I have personally tested.

**Comment by QuadPiece** [comment] 2022-05-30 14:14
I also went ahead and downloaded an older version of Ryujinx (1.1.109, first version before "Support Memory Aliasing") and tried to launch SMT V there.  
Same issue.

It's possible that this is a global issue on newer Linux kernels, regardless of Ryujinx build.  
But none of my machines boot on distros with older Linux kernels such as Debian, so I am unable to test.

**Comment by gdkchan** [comment] 2022-05-31 01:41
I took a look at this issue, and the problem is not the lack of physical memory, what it exceeds (at least on Shin Megami Tensei V) is the number of total mappings allowed on the process. By default on Ubuntu it is 65530, might be different on your distro. You can use the following command to increase it: `sysctl -w vm.max_map_count=262144` And the game should work then.

Ideally we should fix this by reducing the number of mappings the emulator does, but thats tricky since that's largely controlled by the game. We could remove the address space mirror on linux and use software page table translation for access outside of guest code, that would reduce the amount of mappings by half, maybe that's enough, but it would have a minor performance impact.

**Comment by piplup55** [comment] 2022-05-31 02:18
can confirm this issue is fixed on spongebob bfbb by setting vm.max_map_count from 65530 to 262144 on arch linux
![image](https://user-images.githubusercontent.com/100526773/171079656-9a1dfc81-6607-487c-8996-e8ada6d354dc.png)

**Comment by ReillyBrogan** [comment] 2022-06-08 19:28
This can also happen in Metroid Dread if you get hit by the ice attack from the Ghavoran EMMI.

**Closed** 2022-10-19 01:02 UTC
Labels: bug

**Comment by Vinicius881** [comment] 2023-03-02 20:01
@gdkchan If I make a persistent edit to the sysctl, will there be any problems?

Or is it better to do the map_count command every time before opening the emulator?

**Comment by sw0leymammoth** [comment] 2023-05-07 17:33
This happened to me, as gdkchan mentioned my ticket. #4839 
Switching to software made the game run and my distro's default count is 65530

**Comment by QuadPiece** [comment] 2023-05-09 07:20
> > And it always crashes if I try to load a save file with about 17 hours clocked
> 
> @QuadPiece could you share this save file? I'd like to experiment with it.

Unfortunately, I have since lost this save file. I reinstalled the computer and forgot to back up my Ryujinx saves.  
When I initially wrote the issue last year, SMT V's runtime before a crash got progressively shorter the further into the game I got. I got as far as the fairy forest before it became unplayably crashy (5-10 minutes tops).

I do not know if this still happens or has been fixed by some other Ryujinx update, as I completed the game using the vm.max_map_count workaround last year and hasn't had particularly long play sessions with it since.

**Comment by sw0leymammoth** [comment] 2023-05-11 20:39
[SMTV.zip](https://github.com/Ryujinx/Ryujinx/files/11456146/SMTV.zip)
I haven't done much testing since opening my ticket but here's a zip of save files I have for SMTV. Not sure if they run into the same issue.

**Comment by QuadPiece** [comment] 2023-05-12 05:16
@sw0leymammoth If you have the time, try setting your memory mappings to the initial suggestion once in a while: `sysctl -w vm.max_map_count=262144`

This should make the game run, but might still crash some places. And a while into the game (Around the fairy forest in my old testing) it crashes immediately or almost immediately.

If this doesn't happen, something must have changed since I tested with Ryujinx version 1.1.132, or the issue was somehow specific to my save file.

I will see if I can find some time to test next week, but no promises.
