### ISSUE TITLE
Major [Bug]

### ISSUE THREAD

**Issue by vampiregoat699** [Ryujinx/Ryujinx#4793] opened 2023-05-04 04:56 UTC
### Description of the issue

lockups and crashes

### Reproduction steps

1. MAJOR issue one is when stopping emulation the whole program will lock up and not be able to be shut down.
2. for some reason the controller that you configure with randomly disable itself and NOT stop with a pop up over and over, this mainly happens if the controller is not used and shuts itself off and you have to go back into the program after turning the controller back on then re-enabling it. THIS is VERY annoying.

### Log file

Why bother it will not accept the log as it says it is too long to post it

### OS

Win 10

### Ryujinx version

1.1.748

### Game version

not game problem

### CPU

i7-9600

### GPU

Nvidia RTX 3070

### RAM

32 gig

### List of applied mods

none

**Comment by MetrosexualGarbodor** [comment] 2023-05-04 04:58
duplicate of #3301 and #2863

**Closed by MetrosexualGarbodor** 2023-05-04 04:58 UTC
Labels: bug
