### ISSUE TITLE
[Bug] TOTK graphical texture bug with vulkan

### ISSUE THREAD

**Issue by Shadowhawk6** [Ryujinx/Ryujinx#5306] opened 2023-06-14 02:00 UTC
### Description of the issue

Graphical texture bug on TOTK version 1.1.1 while using vulkan. for some reason it seems to only be on certain textures and i have used opengl and it fixed the issue but for some reason its just vulkan that has the problem https://youtu.be/8zmWQgt5_ak youtube link because the video file was to big and i attached a screenshot 

![ryujinx_capture_2023-06-13_02-32-25](https://github.com/Ryujinx/Ryujinx/assets/136537991/f0ba732c-5714-464e-9904-789ba265bbcd)

### Reproduction steps

use vulkan and i am resolution scale native (720p/1080p) then load TOTK version 1.1.1

### Log file

[Ryujinx_1.1.890_2023-06-13_20-15-29.log](https://github.com/Ryujinx/Ryujinx/files/11740647/Ryujinx_1.1.890_2023-06-13_20-15-29.log)

### OS

Edition	Windows 11 Home Version	22H2 Installed on	‎4/‎14/‎2023 OS build	22621.1702 Experience	Windows Feature Experience Pack 1000.22641.1000.0

### Ryujinx version

1.1.738.0

### Game version

1.1.1

### CPU

13th Gen Intel(R) Core(TM) i5-13600K   3.50 GHz

### GPU

AMD Radeon RX 7900 XTX

### RAM

32GB

### List of applied mods

none 

### Additional context?

 i have only tested the starting area have not tested the open world also havent tested to see if it is a problem on other version of the game. i have attached a screenshot of my amd drivers and other info 
![Screenshot (8)](https://github.com/Ryujinx/Ryujinx/assets/136537991/164e8abd-d91f-4ed0-8ae2-aa9b7f252a47)

**Comment by piplup55** [comment] 2023-06-14 02:47
for a little bit of context, this is a rdna3 issue and it is known by amd, turning up the resolution can make it less noticeable (however i can't confirm this as i don't own a rdna3 card)
it can also happen on radv but it's way less common

**Comment by Shadowhawk6** [comment] 2023-06-14 03:00
> 

so i have to wait for amd to fix it then?

**Comment by Shadowhawk6** [comment] 2023-06-14 03:01
d

**Comment by Shadowhawk6** [comment] 2023-06-14 03:02
> for a little bit of context, this is a rdna3 issue and it is known by amd, turning up the resolution can make it less noticeable (however i can't confirm this as i don't own a rdna3 card) it can also happen on radv but it's way less common

so i have to wait for amd to fix it then?

**Comment by riperiperi** [comment] 2024-02-25 23:44
This is caused by AMD using a "general" texture layout that doesn't behave well when a texture is both an attachment and sampler at the same time. It took them more than one year (December 13 2022 - 24th January 2024) to implement a Vulkan extension that allows us to avoid this issue, and it's pretty high effort:

What needs to be done:
- Check if extension is supported, do nothing if it isn't.
- _Performantly_ determine whether a feedback loop is active for any current attachment. (how?)
  - Render pass cache needs to create new render passes when attachments have feedback loop image layout.
    - Render pass needs dependency flag `VK_DEPENDENCY_FEEDBACK_LOOP_BIT_EXT`
  - Pipeline needs to recreate with `VK_PIPELINE_CREATE_COLOR_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT` or `VK_PIPELINE_CREATE_DEPTH_STENCIL_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT`
    - May be able to use dynamic state for this? (`VK_DYNAMIC_STATE_ATTACHMENT_FEEDBACK_LOOP_ENABLE_EXT`)
  - Do not enable if the bindings and attachments are not really a feedback loop. (eg. same storage but different view aspects)
  - Renderable textures need `VK_IMAGE_USAGE_ATTACHMENT_FEEDBACK_LOOP_BIT_EXT` in general.
- Enable textures to swap their image layout before an operation. Ideally should be done with some kind of `EnsureLayout()` method.
  - Swap to `VK_IMAGE_LAYOUT_ATTACHMENT_FEEDBACK_LOOP_OPTIMAL_EXTT` when texture is in a feedback loop. This also needs to update relevant descriptor bindings.
    - NOTE: doing _anything else_ must swap back to general.

**Comment by atahual** [comment] 2024-03-23 11:25
Can confirm that I have this issue on Linux running a 7900xt with RADV drivers.
It's happening less and mostly in good weather on open fields but still noticeable.

**Comment by Cifer9516** [comment] 2024-04-06 21:39
7900xtx mesa-git Same issue. Does not happen in yuzu(suyu)

**Comment by asp0909** [comment] 2024-04-15 19:13
hello! I was wondering if there is any light on this rdna 3 problem maybe?

**Comment by Squall-Leonhart** [comment] 2024-04-28 06:03
[RDNA3] should probably be added to the bug title, since it only occurs there.

**Comment by rehmano** [comment] 2024-06-08 04:09
Any progress made on this?

**Comment by AARP41298** [comment] 2024-07-06 22:56
User of z1 extreme here, just to add, some glitches are purple.
Test it with OGL but the illumination has an offset and i cant use the Command Center button of the ROG Ally.

**Comment by asp0909** [comment] 2024-07-06 23:07
> User of z1 extreme here, just to add, some glitches are purple. Test it with OGL but the illumination has an offset and i cant use the Command Center button of the ROG Ally.

The topic doesn't look good! They say that the problem is with AMD in RDNA3...I don't think it will be fixed...those of us who have 7xxx GPUs can't play this game because of that!

**Comment by riperiperi** [comment] 2024-07-07 11:26
It is possible to fix, it's just a lot of effort for one GPU. It would be more interesting if the feedback loop extension also guaranteed other behaviour like fragment shader execution order guarantees, but I think all it does right now is silence validation errors and avoid this issue RDNA3 introduced.

**Comment by Squall-Leonhart** [comment] 2024-07-07 11:50
Fixes are not isolated to RDNA3, its just the case where the most prevalent and visible issues occur as they are rainbow speckled,

RDNA2 (Van Gogh specifically) also has black tiling in some titles that the extension resolves.

**Comment by riperiperi** [comment] 2024-07-07 13:39
I haven't seen this issue on RDNA2 van gogh in any of the games affected on RDNA3. If it was introduced in a newer RADV driver after this extension was implemented on DXVK, I think it's mostly on them for changing what the general image layout means again. (and i guess that would warrant a retest?) I would like to fix the issue, but it's going in completely blind if there isn't a clear test case that causes it.

**Comment by BooBerry** [comment] 2024-07-07 14:04
For me (using a RDNA3 7800 XT) Tears of the Kingdom is enough to get it to happen 100% of the time. All I have to do is load my save and there's rainbow/pink texture glitches most noticeable over the ground and various graphical glitches in the background.

If there's any data gathering or testing needed in order to try to fix this, I'm sure many of us (myself included) would be more than happy to help however we can.

**Comment by nickelberg** [comment] 2024-07-23 16:56
It's looks even worse on my screen.

Ryujinx version: 1.1.1359
GPU: AMD Radeon RX7900 GRE
GPU drivers: WHQL 24.6.1
OS: Windows 11 Pro 23H2
Backend: Vulkan

![image](https://github.com/user-attachments/assets/035861d3-8373-4640-b93f-9966d9322ddf)

**Comment by norawibb** [comment] 2024-08-04 18:18
> It is possible to fix, it's just a lot of effort for one GPU that we don't have. It would be more interesting if the feedback loop extension also guaranteed other behaviour like fragment shader execution order guarantees, but I think all it does right now is silence validation errors and avoid this issue RDNA3 introduced.

I am encountering this issue as well on my Framework 16 laptop with the RX 7700S. I wouldn't call this a lot of effort for 'one' random GPU. It's an entire line of GPUs from the second most prominent company that makes them. I understand the effort though and the game is otherwise playable.

**Comment by asp0909** [comment] 2024-08-05 18:46
So...we know it's a "bug" in the AMD drivers, but was this reported to them? Does anyone know where these reports are or how we could help report it? I think this problem also affects some other emulators...it would be nice to help in some way if we as users can do it.

**Comment by Squall-Leonhart** [comment] 2024-08-05 20:45
did you even read the bug comments?

**Comment by riperiperi** [comment] 2024-08-20 21:24
I've created a PR that works towards solving this. I'm doing a minimal first attempt to see if it can be resolved without doing anything too terrible:

https://github.com/Ryujinx/Ryujinx/pull/7226

If it doesn't work, then I'll do a second attempt with layout transitioning. I can't test this myself due to the validation layers not knowing what to do here, and not having an affected GPU, so if anyone could give it a shot that would help a bunch.

**Comment by BooBerry** [comment] 2024-08-20 21:36
Did a quick test on Windows 11 with my 7800 XT and so far it's looking pretty good. The pink graphical corruption that was on the ground and the graphical glitches in the distance seem to be completely gone now. It's a quick test but it seems fine now.

Thanks a lot!

**Comment by nickelberg** [comment] 2024-08-20 21:47
@riperiperi 
I can confirm this as well 😄 
![totk](https://github.com/user-attachments/assets/f6d6509a-152e-4510-b989-fa3d7062eef4)

**Comment by asp0909** [comment] 2024-08-20 23:02
![Captura de pantalla (5)](https://github.com/user-attachments/assets/aeeb662c-97fa-4bf7-bd9d-1f7c6312d3ca)
Ok, the texture flickering problem does persist, it is less constant but it does occur...this area affects the problem more, the purple lines on the water and the shadows at the entrance to the temples were solved...rx7900 xtx...I must say that to get to this area the emulator crashed 3 times..

**Comment by riperiperi** [comment] 2024-08-20 23:05
Can you post a crash log? It's impossible to know what's going on otherwise.

There's another issue in this game with AMD gpus in general where LODs flicker outside, I don't think that'll be sorted by this change.

**Comment by asp0909** [comment] 2024-08-20 23:13
> Can you post a crash log? It's impossible to know what's going on otherwise.
> 
[Ryujinx_1.1.0+5f82a53_2024-08-20_17-23-12.log](https://github.com/user-attachments/files/16683210/Ryujinx_1.1.0%2B5f82a53_2024-08-20_17-23-12.log)

> There's another issue in this game with AMD gpus in general where LODs flicker outside, I don't think that'll be sorted by this change.

**Comment by MetrosexualGarbodor** [comment] 2024-08-20 23:14
That log is empty, please post one with a bigger file size. If you don't have one, crash the game again and grab the biggest one afterwards.

**Comment by asp0909** [comment] 2024-08-20 23:18
> That log is empty, please post one with a bigger file size. If you don't have one, crash the game again and grab the biggest one afterwards.

[Ryujinx_1.1.0+5f82a53_2024-08-20_18-17-06.log](https://github.com/user-attachments/files/16683241/Ryujinx_1.1.0%2B5f82a53_2024-08-20_18-17-06.log)

**Comment by GamerzHell9137** [comment] 2024-08-20 23:21
> > That log is empty, please post one with a bigger file size. If you don't have one, crash the game again and grab the biggest one afterwards.
> 
> [Ryujinx_1.1.0+5f82a53_2024-08-20_18-17-06.log](https://github.com/user-attachments/files/16683241/Ryujinx_1.1.0%2B5f82a53_2024-08-20_18-17-06.log)

Redump your game.

**Comment by asp0909** [comment] 2024-08-21 00:44
Ok, if I had a bad dump...it doesn't break anymore...only the LOD flickering persists...but the other problems have been solved,...I thought it was a fix for LOD flickering.....my fault

**Comment by BooBerry** [comment] 2024-08-21 10:57
While on Windows this issue seems to be fixed, on Linux with RADV it seems to be a different story. I tried this using Ubuntu 24.04 LTS with the 7800 XT using RADV and TOTK 1.2.1. Like on Windows I downloaded Linux artifact from the PR.

There's still graphical glitches in the ground, that instead of being pink are now white and black. Unfortunately in the distance the graphical glitches still happen as well. This isn't related to the LOD issue mentioned above, that one still happens on Windows and Linux too but is a different issue than what's being tracked here.

Example of a graphical ground line issue:

![Screenshot from 2024-08-21 05-51-34](https://github.com/user-attachments/assets/f0deb90d-f588-47bb-a3ae-97ecec547856)

Of course not using any mods or anything else for this test.

**Comment by riperiperi** [comment] 2024-08-21 13:24
It's easier to see the issue in the cave at the start of the game, since the affected surface covers the entire screen. Can you show what it looks like? It's the first time you gain control after selecting "new game".

**Comment by BooBerry** [comment] 2024-08-21 13:32
Sure.

![Screenshot from 2024-08-21 08-31-56](https://github.com/user-attachments/assets/748362a1-a110-4bdf-8be4-6f88333b6fcf)

**Comment by BooBerry** [comment] 2024-08-21 13:43
And for reference here's the same build on Windows 11 with the latest AMD drivers.

![Screenshot 2024-08-21 084151](https://github.com/user-attachments/assets/e9373ddf-136b-4250-b58e-07eea9f39602)

![Screenshot 2024-08-21 084202](https://github.com/user-attachments/assets/e64c4b19-45dd-4fce-92ed-028bd1bb230b)

Hopefully that helps. :)

**Comment by Nassi88** [comment] 2024-08-26 07:24
Warum ist das Problem bei dir behoben in Windows? Ich habe es immer noch. Was hast du gemacht

**Comment by Eispfogel** [comment] 2024-08-30 04:11
1 Year later and AMD still has the same Problems. :/

**Comment by gdkchan** [comment] 2024-09-02 00:29
Fixed by #7226.

**Closed by gdkchan** 2024-09-02 00:29 UTC
Labels: bug, gpu, graphics-backend:vulkan, graphics-vendor:amd
