### ISSUE TITLE
Feature Request: Option to disable the automatic directory refresh.

### ISSUE THREAD

**Issue by TomTurbine** [Ryujinx/Ryujinx#4204] opened 2023-01-04 06:35 UTC
#### Overview:

Basically the option to stop Ryujinx from refreshing and rescanning the directories every time it loads and instead you can set it to refresh only when you want to.

#### Smaller Details: 
Having the emulator scan the directories repeatedly even when nothing has changed is pointless and while it might be fine on an SSD, when you have your games on a hard drive it can get really annoying, especially if it is a louder hard drive that starts to sound like an old school pencil sharpener.

### Why would this feature be useful?

Quicker start up with less needless scanning and much less noise for people with a louder hard drive.
And for some people who have a slower drive, it can lead to a substantial startup speed increase.

I have a larger hard drive I use for emulation and old school games that don't need an M2 for speed and starting up the emulator causes vastly more noise than any game I run off it and the longer your game list is, the longer you have to wait while the pencil sharpener goes.

**Comment by IsaacMarovitz** [comment] 2023-01-04 17:33
This isn't really possible IMO. Caching the state of the directories wouldn't solve this cause you would have to check if the cache is valid at some point, which would involve rechecking all the directories again. The scanning isn't 'needless' because Ryujinx has to check if the directories you've given exist. You could try putting all of your games in one folder, so it only has to enumerate one directory and not store anything else in that directory. Also try defragmenting your hard drive, or if possible, switching to a new hard driver or SSD/

**Comment by IsaacMarovitz** [comment] 2023-01-04 17:36
Also if your hard drive sounds like a pencil sharpener, there's probably something wrong with it. Hard drives are a little noisy but they arent that loud.

**Comment by TomTurbine** [comment] 2023-01-04 17:57
This is actually a raid box, the Seagate Evo drives are pretty silent but the Western Digital Red drive has been a pencil sharpener since day one, its just that loud when in full swing but put them all 3 going in a box and it gets louder.

I understand you would need to recheck the directories if you actually changed stuff which is completely understandable. But if your directories are setup and haven't changed in a while, why does it need to recheck those directories every time it loads?

I mean just going it the option of it not checking every time on load up and you can just hit the refresh icon on the bottom when you change something yourself.

Why does it need to recheck the directories even if you haven't added, removed, moved or otherwise changed anything in them?

**Comment by AcK77** [comment] 2023-01-04 21:49
Cache the games directories isn't really doable since check the cache validity leads to scan directories, as @IsaacMarovitz told you `if your hard drive sounds like a pencil sharpener, there's probably something wrong with it. Hard drives are a little noisy but they arent that loud.`

> But if your directories are setup and haven't changed in a while, why does it need to recheck those directories every time it loads?

How we could know the directories haven't changed, if we don't check into them?

I close this issue, as there isn't a really one. It can be reopened in case there is a really great alternative found.

**Closed by AcK77** 2023-01-04 21:49 UTC

**Comment by gdkchan** [comment] 2023-01-04 22:12
The emulator can't know that the directories haven't changed without checking them. We already have the option to refresh the list manually, so we could add a option to disable the automatic refresh of the list. But then you would need to manually refresh it when anything changes. And to achieve what you want we would also need some sort of cache for the game list entries

**Comment by TomTurbine** [comment] 2023-01-04 23:36
@gdkchan 

I meant this as a "Default Off" option that the user had to opt into. When this option is enabled the user has decided that the emulator doesn't need to check for changes anymore, the user will tell it to refresh manually when it changes.

With this one, the emulator doesn't bother checking the directories anymore unless told to by the user. 

Just having it cache the entries and use that on startup and disabling the auto-refresh would be great for users who use the option. No longer having to scan the drives over and over again when nothing has changed and the user knowing that when they actually change something, THEY have to refresh it manually.

Think of it this way, decide you have an arbitrarily long list of games, however long you want. Now, judge how long it takes to load that list off of a tradition hard drive versus just loading off of a cache. The time savings on an individual loading isn't a huge thing but for people who open it regularly, it adds up. Doubly so when the drive the are stored on gets loud.

**Comment by IsaacMarovitz** [comment] 2023-01-05 02:17
> I meant this as a "Default Off" option that the user had to opt into.

Having this sort of option is dangerous. People flick random settings without knowing what they do, and in this case, such settings could result in an onslaught of undesired behaviour and support requests. 

> When this option is enabled the user has decided that the emulator doesn't need to check for changes anymore

What if files/directories are *deleted* never mind added, the emulator would have no way of knowing.

> Now, judge how long it takes to load that list off of a tradition hard drive versus just loading off of a cache.

Hard drives are **FAST** losing market share and will be obsolete from the consumer perspective in the not-too-distant future. There is very little incentive for a forward-thinking emulator like Ryujinx to build specific potentially breaking features around a shrinking minority. 

> Western Digital Red drive has been a pencil sharpener since day one

WD Reds are NAS drives not intended to be used in close proximity to the user, hence why they are loud.

**Comment by TomTurbine** [comment] 2023-01-05 02:44
@IsaacMarovitz 

You are saying that you intend to treat all users with kid gloves and pretend they aren't capable of handling the settings even if they go out of their way to change them? And if you really wanted to avert that issue, you could just have it where if a person attempts to launch something, it does a check on that specific file instead of EVERYTHING when they do so. Prevents that issue while still allowing this option.

And if they are deleted, then the user would know about it because they were the one who deleted it at which point the user would tell it to refresh the list.

And it wouldn't be a feature unique to those using older hard drives, its literally making the emulator quicker for the average user who actually launches the system to play the games more regularly than just adding them.

And I know about the red drives, I have a raid box and just used it for now. Got it in Raid 5 and intend to swap it out eventually and rebuild.

But this feature isn't dangerous unless the programmers who made it screwed up royally which I doubt the programmers of this would do so.

Theoretical situation, I start up Ryujinx 5 games on it with DLC and updates linked. These are the same 5 games as before. Why should I have to reload the entire cache? I know that I have not added or removed anything.

Now, lets say I deleted a game and it's other files, how am I not going to know that I removed them to refresh the list?

Now, lets say that a virus deleted them or I have some secret beta dat from No-Intro and it deleted a game without me realizing it. Well, when I try to launch the game, Ryujinx will immediately check as it goes to launch it and when it sees it's missing it halts with an error message.

Where is the issue?

Now, lets say I have 25 games or 100 games, or heck 500 games as I am a hoarder who has owned the switch since the day it was released and have money to burn. How long do I spend each time the emulator starts up just reloading that list where nothing changed from the last time, I know nothing as changed, and I know nothing will change without me doing it personally. How much time do I spend each launch just to do something that pointless?

**Comment by Squall-Leonhart** [comment] 2023-01-06 23:07
> WD Reds are NAS drives not intended to be used in close proximity to the user, hence why they are loud.

Red's aren't noisy at all, theres a problem with this users particular disk,

Red Pro's are noisier, but still quieter than WD Golds, which aren't much louder than Blacks.

**Comment by TomTurbine** [comment] 2023-01-07 03:48
> > WD Reds are NAS drives not intended to be used in close proximity to the user, hence why they are loud.
> 
> Red's aren't noisy at all, theres a problem with this users particular disk,
> 
> Red Pro's are noisier, but still quieter than WD Golds, which aren't much louder than Blacks.

Mine isn't loud typically, it's only when it goes full tilt that it gets loud and being in a raid box with other drives it makes it a bit louder.

Typically it isn't an issue at all. I was mentioning it because the thing gets louder while Ryujinx is needlessly refreshing directories than when I run anything on it or copy anything to or from it.

I can copy 10GB on and off it or run games off it without it ever approaching the noise of refreshing the directories on this. Refreshing with Yuzu doesn't get that loud either.

But the purpose isn't just the noise, its also for the speed of it too. If someone has their collection on it and hasn't updated anything for a while there is no need to have to refresh the directories. Quite literally can just have it check the single file you are launching and anything attached to it as they are launched which would remove any issue that could potentially pop up.

**Comment by TomTurbine** [comment] 2023-01-12 19:01
An update to this, not sure what all you guys changed in the newer updates but the refresh is MUCH faster and more silent. 

Thank's for that.

**Comment by gdkchan** [comment] 2023-01-19 17:31
This seems to be a duplicate of #3285.

**Comment by TomTurbine** [comment] 2023-01-19 18:05
Yep, requested this exact feature a while back and, as you can see, got a lot of push back from a few people who tried to claim it was dangerous when it isn't unless you had no clue how to program around such a feature.

Just keep a list of the games/updates/dlc all cached and read from that, then when they launch something, only do a check on that specific game/update/dlc instead of all of it.

Until it is addressed, better just to launch Ryujinx from a command-line using a front end instead, the current GUI is just too slow and inefficient as is till this is addressed or until they can make it much faster.

If I haven't updated anything in a long time, then there is no need to pointlessly refresh the list and spending all that time every time it does.

The emulator is great, its ability to load Updates and DLC without installing to memory is great. Lacking this feature though brings it down greatly though to anyone with a collection above 5 games who actually plays them instead of collecting them.

Main things I could ask for to complete Ryujinx from a US perspective.
1) This feature
2) The ability to add updates and DLC the same way you can add game directories instead of having to manually assign them.
3) The ability to bind hotkeys to keyboard and controller.

They nail those 3 down and the GUI parts would be great outside of just presentation which they look like they are doing pretty good with Avalon.
