### ISSUE TITLE
Exit key/button?

### ISSUE THREAD

**Issue by Shituation** [Ryujinx/Ryujinx#3848] opened 2022-11-14 01:57 UTC
Maybe I'm missing it, but is there any way to configure a gamepad button to exit the app? 
I see that many other emulators are missing this feature too and I think its vital since its supposed to be used with a gamepad from couch or whatever, forcing the user to go to the pc to quit the app.

**Comment by MetrosexualGarbodor** [comment] 2022-11-14 02:00
Closing as duplicate of the issue above.

**Closed by MetrosexualGarbodor** 2022-11-14 02:00 UTC
