### ISSUE TITLE
[Feature Request] Emulate Right stick with Mouse

### ISSUE THREAD

**Issue by Garou312** [Ryujinx/Ryujinx#6746] opened 2024-04-29 03:41 UTC
### Overview

Emulate Right stick with Mouse just like yuzu

### Smaller details

Feature

### Nature of request

Feature

### Why would this feature be useful?

it will be useful for better controls

**Comment by piplup55** [comment] 2024-04-29 04:29
duplicate of #2063

**Closed by piplup55** 2024-04-29 04:29 UTC
