### ISSUE TITLE
NES - Ninteno online : game's update prevent to boot

### ISSUE THREAD

**Issue by fraf** [Ryujinx/Ryujinx#2363] opened 2021-06-12 12:04 UTC
## Bug Report
When I launch the game "Nes - Nintendo Switch online", the primary version works, ie 1.0.0. If I launch it with lastest update, ie 5.3.0, it prevents to boot making ryujinx crashing.

### Log file

See attachement

### Environment?
Ryujinx vanilla latest version as of june 2021

[Ryujinx_1.0.6910_2021-06-12_13-59-01.log](https://github.com/Ryujinx/Ryujinx/files/6642132/Ryujinx_1.0.6910_2021-06-12_13-59-01.log)

**Comment by EmulationFanatic** [comment] 2021-06-12 12:10
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1028

**Closed by EmulationFanatic** 2021-06-12 12:10 UTC
