### ISSUE TITLE
[Bug] Fire Emblem Engage crashing during battles

### ISSUE THREAD

**Issue by NoNomaer23** [Ryujinx/Ryujinx#4522] opened 2023-03-08 10:42 UTC
### Fire Emblem Engage Crashing in Gameplay

In Fire Emblem Engage the emulator crashes during gameplay in battles, I haven't experienced any crashes in the menus, overworld  and somniel only during battle maps. OpenGL and Vulkan both crash, in Ryujinx previous versions OpenGL was very stable and does not crash. I tried adjusting the graphics settings (Post processing, Resolution Scale, Upscale, etc.) yeah it still crashes. 

### Reproduction steps

Crashes during gameplay usually 5-20 minutes

### Log file

[Ryujinx_1.1.650_2023-03-08_16-58-54.log](https://github.com/Ryujinx/Ryujinx/files/10919735/Ryujinx_1.1.650_2023-03-08_16-58-54.log)

### OS

Windows 10 

### Ryujinx version

1.1.650

### Game version

1.2.0

### CPU

Ryzen 5 3400g

### GPU

NVIDIA GTX 1650

### RAM

16GB DDR4

### List of applied mods

none

### Additional context?

Game was not crashing in previous versions of Ryujinx

**Comment by TSRBerry** [comment] 2023-03-08 14:15
The uploaded log contains no crash.

**Comment by NoNomaer23** [comment] 2023-03-09 04:41
[Ryujinx_1.1.651_2023-03-09_11-56-31.log](https://github.com/Ryujinx/Ryujinx/files/10927840/Ryujinx_1.1.651_2023-03-09_11-56-31.log)
wrong file mb

**Comment by Ryan2603** [comment] 2023-03-09 07:19
Firmware Version: 14.1.2 might have issue

**Comment by TSRBerry** [comment] 2023-03-09 12:28
> I just tested it again and it seems to crash even when idle, it is probably a memory leak.

That's very unlikely.
Both of the uploaded logs don't contain crashes.

> Firmware Version: 14.1.2 might have issue

Firmware version doesn't matter.

**Comment by LazySoda** [comment] 2023-03-19 04:39
I've been experiencing crashes lately as well.
It only started happening after doing 1 (or more) of the following:
- Updated Fire Emblem Engage to v1.3.0
- Updated Ryujinx multiple times, currently on v1.1.669
- Updated installed firmware from v14.?.? to v16.0.0

**OS:** Windows 10
**Ryujinx:** 1.1.669
**Game:** 1.3.0 (w/ DLC)
**Specs:** Ryzen 7 5800X, RTX 3080Ti 12GB, 32GB DDR4 3200MHz
**Mods:** [Somniel Rebalanced](https://gamebanana.com/mods/425819), [Battle Outfits](https://gamebanana.com/mods/424968), Uncensored Patch v1.4
**Notes:** Emulator settings are all recommended, Texture Recompression both on & off, purged/rebuilt both PPTC & shader cache.
While I'm unsure if it's crashed without mods, all mods are up to date for the current game version, and none of them crashed when on an older Ryujinx version.
I used to use a mod that [forces 60fps](https://gamebanana.com/mods/432758), but stopped using it as I initially thought it was the cause.

[Crash log here bc I don't know github uploading](https://pastebin.com/EyVf97Au)
This most recent crash seems to be about this `Unhandled exception caught: System.ArgumentException: Destination array was not long enough.`
Also, just like #4536 my console also gets multiple `ServiceNv Wait: GPU processing thread is too slow, waiting on CPU...` and the occasional `HLE.OsThread.10 Gpu WaitOnSyncpoint: Wait on syncpoint 1 for threshold 139534 took more than 1000ms, resuming execution...` which seems concerning given my specs.

**Comment by gdkchan** [comment] 2023-03-19 04:45
This specific issue is supposed to be fixed by #4564.

**Comment by LazySoda** [comment] 2023-03-19 05:56
> This specific issue is supposed to be fixed by #4564.

Ah, thanks so much for the quick response!
I've downloaded the build linked in that thread, and so far it seems good, no crashes yet.

**Closed** 2023-05-02 15:37 UTC
Labels: bug
