### ISSUE TITLE
[Feature Request] Add Gaussian Filter for Downsampling/Downscaling

### ISSUE THREAD

**Issue by Synkro12** [Ryujinx/Ryujinx#6734] opened 2024-04-27 22:46 UTC
### Overview

Currently there is no good filter to use when downsampling games from a higher than native resolution image, using Bilinear scaling results in a noisy image.

### Smaller details

A Gaussian blur is used by Nvidia for their Dynamic Super Resolution feature and has favourable results for smoothing out image noise, edge aliasing and specular aliasing. Alex from Digital Foundry mentions this in this [video](https://youtu.be/c3voyiojWl4?si=zeThBidZ3OMqsHF6&t=306).

### Nature of request

User request

### Why would this feature be useful?

It would generally make Ryujinx nicer to use when able to run games at above native resolutions

**Comment by MutantAura** [comment] 2024-04-27 23:01
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4905

**Closed by MutantAura** 2024-04-27 23:01 UTC

**Comment by Synkro12** [comment] 2024-04-27 23:02
Whoops, sorry about that, I'd searched for Gaussian but nothing came up
