### ISSUE TITLE
Unexpected API error "ErrorOutOfDeviceMemory"

### ISSUE THREAD

**Issue by jlarmijos** [Ryujinx/Ryujinx#3632] opened 2022-08-26 22:09 UTC
Mario Odyssey runs almost perfectly under Vulkan on a Radeon R7 260 (graphics card runs at 70% on average) but at the end of the cutscene after the first power moon the emulator crashes. The log shows "Unexpected API error "ErrorOutOfDeviceMemory"". I have updated custom drivers, (I know, I know). I have paging file enabled. In other posts some who have enough VRAM (8GB) get crashes with other games. Is there a way to adjust that?
[Ryujinx_1.1.240_2022-08-26_16-47-59.log](https://github.com/Ryujinx/Ryujinx/files/9436646/Ryujinx_1.1.240_2022-08-26_16-47-59.log)

**Comment by MutantAura** [comment] 2022-08-28 13:20
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3523

**Closed by MutantAura** 2022-08-28 13:20 UTC
