### ISSUE TITLE
[Bug] Kirby and the Forgotten Land crash

### ISSUE THREAD

**Issue by MarcosLH1504** [Ryujinx/Ryujinx#5805] opened 2023-10-14 16:35 UTC
### Description of the issue

Kirby and the Forgotten Land closes at a certain point, and from what I've seen on forums and on the console, it's an audio bug.
I've been looking but I can't find a solution, even if you're on Windows, can you tell me what to do?

### Reproduction steps

At one point in the game.

### Log file

https://github.com/Ryujinx/Ryujinx/files/12906839/Bug.pdf

### OS

 MacBookAir10

### Ryujinx version

1.1.1052

### Game version

0

### RAM

8 GB

### Additional context?

I'm almost sure it's an audio error.

**Comment by MetrosexualGarbodor** [comment] 2023-10-14 16:49
Probably a duplicate of #3292

**Closed by MetrosexualGarbodor** 2023-10-14 16:49 UTC
Labels: bug

**Comment by MarcosLH1504** [comment] 2023-10-14 17:02
> Probablemente un duplicado del [n.° 3292](https://github.com/Ryujinx/Ryujinx/issues/3292)

I had not seen it. Could you tell me a solution to this?

**Comment by MetrosexualGarbodor** [comment] 2023-10-14 17:03
The issue is still open, which means there's no solution

**Comment by gdkchan** [comment] 2023-10-14 17:14
If its consistent, you should attach a save and instructions to reproduce the issue.

**Comment by escalinci** [comment] 2023-10-21 10:57
I think I have the same crash, it can be reproduced by starting certain levels from the world map. I could get it to crash thrice in a row by starting the 'sword treasure' on the second map.

[save.zip](https://github.com/Ryujinx/Ryujinx/files/13060474/save.zip)
https://github.com/Ryujinx/Ryujinx/assets/10742076/824d9e5b-260d-40a7-83fb-5d0edae6dc63
[Ryujinx_1.1.1057_2023-10-21_12-26-36.log](https://github.com/Ryujinx/Ryujinx/files/13060498/Ryujinx_1.1.1057_2023-10-21_12-26-36.log)

OS
MacOS Ventura 13.5.2

Ryujinx version
1.1.1057

Game version
1.0.0

CPU
10-Core M1 Pro

GPU
16-Core M1 Pro (integrated)

RAM
16 GB

List of applied mods
60 fps, disable dynamic resolution

Hypervisor is enabled.
