### ISSUE TITLE
[Bug] [Regression] Persona 5 Royal - 1.1.1066 Causes Graphical Regression on Vulkan [Flickering]

### ISSUE THREAD

**Issue by hakushiii** [Ryujinx/Ryujinx#5910] opened 2023-11-09 10:03 UTC
### Description of the issue

The screen flickers on occasion on scenes in P5R.

https://github.com/Ryujinx/Ryujinx/assets/58656012/26cf281d-7534-4803-be56-b730a4ffddb3

https://github.com/Ryujinx/Ryujinx/assets/58656012/42ebc785-6e3b-48b4-bb97-1bdd27052e49

### Reproduction steps

1. Use 1.1.1066+ Build
2. Run Persona 5 Royal
3. Load the save file from date 7/10/20XX from [P5R save.zip](https://github.com/Ryujinx/Ryujinx/files/13306677/P5R.save.zip)
4. Go down the stairs and stand like where in the video

### Log file

[Ryujinx_1.1.1066_2023-11-09_17-34-19.log](https://github.com/Ryujinx/Ryujinx/files/13306657/Ryujinx_1.1.1066_2023-11-09_17-34-19.log)

### OS

MacOS 14.1.1 Sonoma

### Ryujinx version

1.1.1066

### Game version

1.0.0

### CPU

M2 8C

### GPU

M2 8G

### RAM

8GB

### List of applied mods

nein

**Comment by hakushiii** [comment] 2023-11-09 10:29
I forgot to add the original report by trinity1828 from discord

https://github.com/Ryujinx/Ryujinx/assets/58656012/e0a5258f-651d-45e8-829b-adb57319b72d

[Ryujinx_1.1.1072_2023-11-09_11-47-51.log](https://github.com/Ryujinx/Ryujinx/files/13306897/Ryujinx_1.1.1072_2023-11-09_11-47-51.log)

**Comment by IsaacMarovitz** [comment] 2023-11-09 14:25
A similar problem in BOTW, which we discovered was caused by texture flushing see [convo](https://discord.com/channels/410208534861447168/692449072107225108/1171582206418886676).

https://github.com/Ryujinx/Ryujinx/assets/42140194/0754b4e2-761b-45ed-92b2-cb73bf4b90ca

**Comment by gdkchan** [comment] 2023-11-09 17:55
Duplicate of #5878.

**Closed by gdkchan** 2023-11-09 17:55 UTC
Labels: bug
