### ISSUE TITLE
[Bug]Mario Party Superstars Crashing at the same point in time

### ISSUE THREAD

**Issue by Sensoryy** [Ryujinx/Ryujinx#4797] opened 2023-05-04 10:01 UTC
### Description of the issue

I was playing mario party superstars with my friend and when we got to a certain point we lost connection but when we tried to load back into that game my emulator would crash im using the ldn build obviously

### Reproduction steps

I was playing mario party superstars with my friend and when we got to a certain point we lost connection but when we tried to load back into that game my emulator would crash im using the ldn build obviously. Now no matter what we cant load in the screen just turns white then itll either completely close or it will just stay white

### Log file

[Ryujinx_1.1.0-ldn3.1.3_2023-05-04_03-51-03.log](https://github.com/Ryujinx/Ryujinx/files/11396248/Ryujinx_1.1.0-ldn3.1.3_2023-05-04_03-51-03.log)

### OS

Windows 10

### Ryujinx version

1.1.0-ldn3.1.3

### Game version

1.0.0

### CPU

i7-8700k

### GPU

Nvidia Geforce GTX 1660 TI

### RAM

32GB

### List of applied mods

60 FPS

**Comment by trlbzr** [comment] 2023-05-04 17:57
I documented this a few weeks ago in #4683 , I will comment there as well to reference this same issue

**Comment by AcK77** [comment] 2023-05-05 07:21
Duplicate of #4683

**Closed by AcK77** 2023-05-05 07:21 UTC
Labels: bug
