### ISSUE TITLE
Paper Mario Origami King: Cant hit trees

### ISSUE THREAD

**Issue by coronabreadcat** [Ryujinx/Ryujinx#1502] opened 2020-08-25 10:53 UTC
## Bug Report

N/A

### What's the issue you encountered?

![image](https://user-images.githubusercontent.com/70204244/91165087-c9221580-e6d8-11ea-8f66-d1f247de50c3.png)
I'm hitting the A button and Mario doesn't hit the tree

### How can the issue be reproduced?

just by playing lmao

### Log file

00:00:00.019 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.5221
00:00:01.295 |N| Application PrintSystemInfo: Operating System: Microsoft Windows 10.0.17763 (X64)
00:00:01.296 |N| Application PrintSystemInfo: CPU: Intel(R) Core(TM) i3-9100F CPU @ 3.60GHz
00:00:01.296 |N| Application PrintSystemInfo: Total RAM: 16328 MB
00:00:01.297 |N| Application PrintSystemInfo: Logs Enabled: <None>
00:00:00.545 |N| Application LoadApplication: Using Firmware Version: 10.1.0
00:00:01.611 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 1060 3GB/PCIe/SSE2 (4.6.0 NVIDIA 441.66)

that aint the log file btw, just the console but i think it doesnt matter?? if so tell me ples

### Environment?

- Ryujinx version: 1.0.5221</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: Intel(R) Core(TM) i3-91004 CPU @ 3.60GHz  3.60 GHz
  - GPU: NVIDIA GeForce GTX 1060 3GB
  - RAM: 16GB
- Applied Mods : none

### Additional context?

no

**Comment by EmulationFanatic** [comment] 2021-01-08 17:20
Cannot reproduce this issue. I've tried multiple times and Mario always hits the tree. Make sure your A button is mapped properly!
Closing the issue as it does not seem to be an issue with the emulator.

**Closed by EmulationFanatic** 2021-01-08 17:20 UTC
Labels: bug, needs-feedback

**Comment by isaacmakessoftware** [comment] 2021-04-13 02:35
I'm also having this issue. I am using keyboard controls and ryujinx 1.0.6823. No matter what I do it just does not work.
