### ISSUE TITLE
Shin Megami Tensei V: Crash on exit after indeterminate time period

### ISSUE THREAD

**Issue by MadKingMidas** [Ryujinx/Ryujinx#2850] opened 2021-11-17 23:20 UTC
## Bug Report

</br>

### What's the issue you encountered?
Running Shin Megami Tensei V; did not stop emulation prior to exiting application from task bar (right-click, close all windows). Ryujinx became unresponsive, but the console is still responding. Had to end task from Task Manager. Confirmed issue re-occurred the next two days, but does not immediately occur if I load the game, then exit. 

### How can the issue be reproduced?

1. Open Ryujinx
2. Load Shin Megami Tensei V
3. Play for an undetermined period of time
4. Close application from Task Bar

### Log file
All three log files show a last modified date of today, so I included all three. Two of them are only 70 or so KB. 
[Ryujinx_1.0.7106_2021-11-17_18-12-18.log](https://github.com/Ryujinx/Ryujinx/files/7558579/Ryujinx_1.0.7106_2021-11-17_18-12-18.log)
[Ryujinx_1.0.7106_2021-11-17_18-12-58.log](https://github.com/Ryujinx/Ryujinx/files/7558580/Ryujinx_1.0.7106_2021-11-17_18-12-58.log)
[Ryujinx_1.0.7106_2021-11-17_16-39-16.log](https://github.com/Ryujinx/Ryujinx/files/7558581/Ryujinx_1.0.7106_2021-11-17_16-39-16.log)

### Environment?

- Ryujinx version: 1.0.7106</br>
- Game version: 1.0.1 (</br>
- System Specs:
  - OS: *Windows 10 Home v10.0.19042
  - CPU: *AMD Ryzen 5 3600 6-Core Processor, 3950 Mhz, 6 Core(s), 12 Logical Processor(s)
  - GPU: *NVIDIA GeForce RTX 3070
  - RAM: *32GB DDR4
- Applied Mods : N/A

### Additional context?
Issue does not immediately re-occur upon re-launching the game and exiting, but has occurred all 3 times I've played for an extended period. 
Additional info about your environment:</br>

**Comment by vocaab** [comment] 2022-02-02 01:19
Yeah, I get this issue as well, also seems to have an effect on the controller as well, where the next boot up of ryujinx will hang for like 30-50 secs. On a fresh restart the issue no longer persists.

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 00:54
Closing as a duplicate of #2863.

**Closed by MetrosexualGarbodor** 2022-02-11 00:54 UTC
Labels: bug
