### ISSUE TITLE
Dual Joycons Do Not Work (Disconnection Issue)

### ISSUE THREAD

**Issue by NikkMann** [Ryujinx/Ryujinx#2730] opened 2021-10-12 17:06 UTC
### What's the issue you encountered?

When attempting to use Dual Joycons either through DS4Windows or Betterjoy, Ryujinx cannot use the Joycons.
It recognizes the Xinput Controller that is created, but as soon as I press any button on either Joycon, I get a "battery low" notification (from DS4 and BetterJoy) and then the controllers continually disconnect and re-connect from the input handler. They only fully re-connect after Ryujinx is closed.
A single Joycon works just fine.

Other users have reported a similar issue with Ryujinx.

I thought it may have been my bluetooth controller, so I tried several bluetooth 4 and bluetooth 5 adapters but the issue persisted.

Nothing shows up in the log.

### How can the issue be reproduced?

As stated above.

### Environment?

- Ryujinx version: 1.0.7066
- System Specs:
  - OS: Windows 10 (Fully Updated)
  - CPU: AMD 5900X
  - GPU: NVIDIA RTX 3090
  - RAM: 32GB
 
### Additional Info

Here is what BetterJoy shows when attempting to press a button on the Joycons while connected through Ryujinx
![image](https://user-images.githubusercontent.com/90150509/136999275-c23bc739-0702-4cc3-b3c6-766a90420d7e.png)

**Comment by lunaleevip** [comment] 2022-02-11 14:44
https://github.com/Davidobot/BetterJoy/wiki/HIDGuardian-and-Steam-(Big-Picture)

> Here's how to make everything play nicely:

Navigate to the Drivers/HIDGuardian folder, after reading the README.txt in Drivers
Run HIDGuardian Install (Run as Admin).bat as admin
Open BetterJoyForCemu.exe.Config and change the line <add key="UseHIDG" value="false" /> to <add key="UseHIDG" value="true" />
Set PurgeWhitelist and PurgeAffectedDevices to false
Run BetterJoy
Restart your computer
Use Steam/BetterJoy as you like

**Comment by MetrosexualGarbodor** [comment] 2023-01-07 07:44
Closing this as it's essentially the same as #3293, but this one is more focused on issues caused by third party programs.

**Closed by MetrosexualGarbodor** 2023-01-07 07:44 UTC
Labels: bug, input
