### ISSUE TITLE
Implement accessibility API for Avalonia. [Feature Request]

### ISSUE THREAD

**Issue by RealAmethyst** [Ryujinx/Ryujinx#5601] opened 2023-08-19 21:17 UTC
### Overview

This allows for accessibility support via programs like screen readers, which will speak out the application content so that people with no vision or low vision can use it.

### Smaller details

There is accessibility API's for windows, mac and Linux. A good way to see what I'm talking about in action is to use a screen reader and test applications. Most of the time it will speak out what's on screen. I was not able to find any documentation on how to implement support for them in Avalonia, sorry.
I really hope that this can be implemented here, so that Ryujinx can be used by lots of new users.
Thanks for reading.

### Nature of request

UI improvement

### Why would this feature be useful?

For people with low or no vision to be able to use the application, letting lots of new users experience this emulator.

**Comment by MutantAura** [comment] 2023-08-19 21:26
Hello, while we appreciate your enthusiasm on this topic, you've already opened two identical prior issues and one is still open. As such I'm marking this as a duplicate of https://github.com/Ryujinx/Ryujinx/issues/4352

Track your issue there and also https://github.com/Ryujinx/Ryujinx/issues/4385 
Thanks.

**Closed by MutantAura** 2023-08-19 21:26 UTC
