### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Fisdack** [Ryujinx/Ryujinx#4660] opened 2023-04-09 16:35 UTC
### Description of the issue

Game Crash

### Reproduction steps

When Angel Hunter 3 opens a book bought in the store, the game crashes and displays an error code

### Log file

[Ryujinx_1.1.699_2023-04-09_22-23-48.log](https://github.com/Ryujinx/Ryujinx/files/11185878/Ryujinx_1.1.699_2023-04-09_22-23-48.log)

### OS

win11

### Ryujinx version

1.1.699 

### Game version

Angel Hunter 3   1.2.0

### CPU

amd 5800h

### GPU

rtx 3060

### RAM

16gb

**Comment by OldManKain** [comment] 2023-04-09 16:39
Closing as duplicate of #3811

**Closed by OldManKain** 2023-04-09 16:39 UTC
Labels: bug
