### ISSUE TITLE
Link's Awakening - Critical Crash during gameplay

### ISSUE THREAD

**Issue by Mav3r1ckHL** [Ryujinx/Ryujinx#2816] opened 2021-11-05 14:48 UTC
### What's the issue you encountered?
This appears to be due to the latest version of Ryujinx 1.0798 where Link's Awakening will hit a CPU error which hit an invalid memory address.

### How can the issue be reproduced?

Context:  This crashed occurred while attempting a custom dungeon run.

1. Play Link's awakening
2. Usually transitioning between screens or playing the game will eventually cause the crash

### Log file

[Ryujinx_1.0.7098_2021-11-05_10-32-06.log](https://github.com/Ryujinx/Ryujinx/files/7486821/Ryujinx_1.0.7098_2021-11-05_10-32-06.log)

Key point of failure:

00:05:13.105 |I| HLE.GuestThread.35 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 91
   0x000000000b06b4b8	sdk:0x3344b8	
   0x000000000b06f984	sdk:0x338984	
   0x0000000000000000

00:05:13.113 |I| HLE.GuestThread.35 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x00000010434af3a8
	X[01]:	0x00000000090d0f20 (main:0x10ccf20)	=> 
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000009c55358
	X[09]:	0x0000000000000000
	X[10]:	0x0000000000000000
	X[11]:	0x0000000000000000
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000001
	X[16]:	0x000000000b96aee8
	X[17]:	0x000000000b071020 (sdk:0x33a020)	=> nn::os::detail::InternalCriticalSectionImplByHorizon::Leave()
	X[18]:	0x000000000000002c
	X[19]:	0x00000010434962c0
	X[20]:	0x00000000ffffffff
	X[21]:	0x000000104358c6e8
	X[22]:	0x0000000000000000
	X[23]:	0x0000000000000000
	X[24]:	0x0000000000000000
	X[25]:	0x0000000000000000
	X[26]:	0x0000000000000000
	X[27]:	0x0000000000000000
	X[28]:	0x0000000000000000
	FP:	0x00000011a7c0bf80 (SP:-0x0020)
	LR:	0x00000000093c636c (main:0x13c236c)	=> 
	SP:	0x00000011a7c0bf60 (SP)
	PC:	0x0000000000000000

00:05:13.113 |E| HLE.GuestThread.35 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:05:13.117 |E| HLE.GuestThread.35 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise)
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address)
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.0.798</br>

- Game version: 1.0.1</br>

- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 5900x
  - GPU: NVIDIA 1080Ti
  - RAM: *(e.g. 16GB)*
- Applied Mods : No

**Comment by gdkchan** [comment] 2021-11-05 15:44
Can't reproduce after entering and exiting some houses in the village. I suggest attaching a save.

**Comment by Mav3r1ckHL** [comment] 2021-11-05 15:53
> Can't reproduce after entering and exiting some houses in the village. I suggest attaching a save.

Files attached.  I am using the first slot and running through the custom dungeon.

[Save.zip](https://github.com/Ryujinx/Ryujinx/files/7487299/Save.zip)

**Comment by MetrosexualGarbodor** [comment] 2022-04-22 18:53
Went through a couple custom dungeons, entered and exited some rooms back and forth, and couldn't reproduce. I'll close this and reopen it if there are any new reports, but it doesn't seem to be an issue anymore.

**Closed by MetrosexualGarbodor** 2022-04-22 18:53 UTC
Labels: bug
