### ISSUE TITLE
[功能请求] Handheld mode cannot be displayed on a vertical screen.

### ISSUE THREAD

**Issue by JiangYuf** [Ryujinx/Ryujinx#6933] opened 2024-06-12 07:43 UTC
### Overview

Handheld mode cannot be displayed on a vertical screen.
![Uploading IMG_1045.jpeg…]()

### Smaller details

Handheld mode cannot be displayed on a vertical screen.

### Nature of request

Handheld mode cannot be displayed on a vertical screen.

### Why would this feature be useful?

Handheld mode cannot be displayed on a vertical screen.

**Comment by MutantAura** [comment] 2024-06-12 22:43
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1104

**Closed by MutantAura** 2024-06-12 22:43 UTC
Labels: enhancement
