### ISSUE TITLE
Windows 11 Bug?

### ISSUE THREAD

**Issue by Legarad** [Ryujinx/Ryujinx#4197] opened 2023-01-01 21:10 UTC
I upgraded my computer to Windows 11 taking advantage of the fact that my Windows 10 was original. But now when I open Ryujinx even with the disabled option of "Show Console Log" it is still open and if I close it the emulator closes.

**Comment by merryhime** [comment] 2023-01-01 21:14
Duplicate of #3246.

**Closed** 2023-01-01 21:16 UTC
