### ISSUE TITLE
[Feature Request] Live update of system time

### ISSUE THREAD

**Issue by MinecraHD** [Ryujinx/Ryujinx#4018] opened 2022-12-05 00:56 UTC
#### Overview:
Time Updated live in games instead on restart of game when changing the system time and applying it

#### Smaller Details: 
- [ These may include specific methods of implementation etc. ]

#### Nature of Request:  
- Change
   After applying a new System time, the time in games changes directly instead of on restart
OR
- Addition 
   Keeping the time update on restart as default, but making an option so it can be applied directly
   

### Why would this feature be useful?
Best example that I can find right now is for the new Pokemon games S/V. On the switch you can change the system time, while the game is still running, and it will renew the mass outbreaks and tera raid battles. 

Right now to get the same effect on Ryujinx you would have to restart the game.

**Comment by gdkchan** [comment] 2022-12-05 01:01
Duplicate of #2866.

**Closed by gdkchan** 2022-12-05 01:01 UTC
