### ISSUE TITLE
[Bug] Crash Invalid memory access at virtual address

### ISSUE THREAD

**Issue by hermitoff** [Ryujinx/Ryujinx#6924] opened 2024-06-09 00:23 UTC
### Description of the issue

```00:02:06.326 |E| HLE.GuestThread.54 Cpu InvalidAccessHandler: Invalid memory access at virtual address 0x0000000000000000.
00:02:06.349 |E| HLE.GuestThread.54 Application : Unhandled exception caught: Ryujinx.Memory.InvalidMemoryRegionException: Attempted to access an invalid memory region.
   at Ryujinx.Memory.Tracking.MemoryTracking.VirtualMemoryEvent(UInt64 address, UInt64 size, Boolean write, Boolean precise, Nullable`1 exemptId, Boolean guest) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Memory/Tracking/MemoryTracking.cs:line 349
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.DataAbort(MemoryTracking tracking, UInt64 vcpu, UInt32 esr) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 240
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 200
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 159
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /home/runner/work/Ryujinx/Ryujinx/src/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1250
   at System.Threading.Thread.StartCallback()
```

### Reproduction steps

Simply play ACNH

### Log file

[Ryujinx_1.1.1330_2024-06-09_10-44-10.log](https://github.com/user-attachments/files/15749983/Ryujinx_1.1.1330_2024-06-09_10-44-10.log)
[Ryujinx_1.1.1330_2024-06-09_10-46-58.log](https://github.com/user-attachments/files/15749984/Ryujinx_1.1.1330_2024-06-09_10-46-58.log)
[Ryujinx_1.1.1330_2024-06-09_11-09-57.log](https://github.com/user-attachments/files/15749985/Ryujinx_1.1.1330_2024-06-09_11-09-57.log)

### OS

macOS Sonoma 14.5

### Ryujinx version

1.1.1330

### Game version

2.0.6

### CPU

Apple M1

### GPU

Apple M1

### RAM

8 Go

### List of applied mods

N/A

**Comment by MetrosexualGarbodor** [comment] 2024-06-09 00:55
Duplicate of #6365

**Closed by MetrosexualGarbodor** 2024-06-09 00:55 UTC
Labels: bug
