### ISSUE TITLE
[Bug] Ryujinx update consistently fails on Mac

### ISSUE THREAD

**Issue by livni** [Ryujinx/Ryujinx#5279] opened 2023-06-10 15:21 UTC
### Description of the issue

Last couple of days Ryujinx 1.1.869 consistently fails on update on Mac

### Reproduction steps

1. Open Ryujinx 1.1.869 on Mac
2. Approve update, e.g. to 1.1.881
3. What while it's "downloading update" and "extracting update"
4. Get a macOS "Ryujinx 1.1.869 quit unexpectedly" pop-up
5. Open Ryujinx again and see that it's still on 1.1.869

### Log file

[Ryujinx_1.1.869_2023-06-10_18-16-25.log](https://github.com/Ryujinx/Ryujinx/files/11712721/Ryujinx_1.1.869_2023-06-10_18-16-25.log)
[Ryujinx_1.1.869_2023-06-10_18-16-50.log](https://github.com/Ryujinx/Ryujinx/files/11712722/Ryujinx_1.1.869_2023-06-10_18-16-50.log)
[Ryujinx_1.1.869_2023-06-10_18-18-45.log](https://github.com/Ryujinx/Ryujinx/files/11712723/Ryujinx_1.1.869_2023-06-10_18-18-45.log)

### OS

macOS Ventura 13.3.1 (a)

### Ryujinx version

1.1.869

### CPU

Apple M1 Pro

### RAM

32GB

**Comment by Reclad** [comment] 2023-06-10 15:58
The issue is already fixed on 1.1.879.

1.1.879 - 2023-06-09
Fixed:

    macOS: Fix regression in macOS updater.
        Fixes an issue introduced with 1.1.869 that caused the macOS updater not to work.

You should download the last version of Ryujinx manually here : https://github.com/Ryujinx/release-channel-master/releases/tag/1.1.881.

**Comment by livni** [comment] 2023-06-10 18:46
Thank you @Reclad, but how do I upgrade if I have 1.1.869 and it still has the bug?

**Comment by MutantAura** [comment] 2023-06-12 10:37
Re-download the emulator from the release channel. 
https://github.com/Ryujinx/release-channel-master/releases

**Closed by MutantAura** 2023-06-12 10:37 UTC
Labels: bug
