### ISSUE TITLE
[Feature Request] Hotkeys and Reset Emulator

### ISSUE THREAD

**Issue by bjeardoe** [Ryujinx/Ryujinx#6053] opened 2023-12-19 14:48 UTC
### Overview

Add a Reset Emulator option that allows reloading the current rom without going back to rom selection menu and add hotkeys for Pause, Reset and Stop Emulation.

### Smaller details

Add a Reset Emulator option that allows reloading the current rom without going back to rom selection menu and add hotkeys for Pause, Reset and Stop Emulation.

### Nature of request

New feature for convenience.

### Why would this feature be useful?

Would allow user to manipulate emulation without having to leave fullscreen mode and navigate windows.  The reset emulation would save time by not making you have to stop emulation, go to main screen, and re-select rom.

**Comment by MetrosexualGarbodor** [comment] 2023-12-19 14:50
Duplicate of #2974

**Closed by MetrosexualGarbodor** 2023-12-19 14:50 UTC
