### ISSUE TITLE
[Bug] Certain Graphics Missing/Errored in Fate/Extella: The Umbral Star

### ISSUE THREAD

**Issue by Alexy-bubble** [Ryujinx/Ryujinx#4466] opened 2023-02-22 08:57 UTC
### Description of the issue

Certain graphics are currently missing/errored in Fate/Extella: The Umbral Star.

Screenshots for minorly glitched graphics:

Ryujinx (Handheld Mode):
![ryujinx_capture_2023-02-22_00-51-39](https://user-images.githubusercontent.com/60449252/220570020-a9c84b34-c063-4d0d-bda4-add8c6f31284.png)

Ryujinx (Docked Mode):
![ryujinx_capture_2023-02-22_00-51-22](https://user-images.githubusercontent.com/60449252/220570082-47970a01-4563-4390-8f9c-c2f2c919c2f9.png)

Screenshots for heavily glitched graphics:

Hardware (Handheld Mode):
![2023052103253300-E6AF6064232D0BC4FCC6C2F85794534D](https://user-images.githubusercontent.com/60449252/220568074-fe308ddd-3f74-41ec-9de7-b0524ed43d40.jpg)

Ryujinx (Docked Mode):
![ryujinx_capture_2023-02-22_00-41-49](https://user-images.githubusercontent.com/60449252/220567580-2b27233a-8738-440b-aeb5-1c62fecbc54c.png)

Ryujinx (Handheld Mode, post resolution fiddling):

![ryujinx_capture_2023-02-22_00-40-12](https://user-images.githubusercontent.com/60449252/220567395-3043f5c4-f090-48ec-95af-e266cc973edf.png)

### Reproduction steps

Launch the game. In Docked mode, some graphics are universally glitched. This includes various lines that appear at all times, and blocky graphical errors in menus.  In handheld mode, these graphics tend not to be glitched. In particular circumstances, there are more heavily glitched graphics. In these circumstances, in docked mode, these graphics don't appear. In handheld mode, these graphics appear corrupted, if they appear at all. Changing the game's resolution does seem to force the missing graphics to appear (as seen in the attached majorly glitched graphics handheld mode image above), and, in once instance, even caused the correct graphics to appear. This isn't consistent, though.

### Log file

[Ryujinx_1.1.632_2023-02-22_00-46-37.log](https://github.com/Ryujinx/Ryujinx/files/10801768/Ryujinx_1.1.632_2023-02-22_00-46-37.log)

### OS

Windows 11

### Ryujinx version

1.1.632

### Game version

1.0.0

### CPU

12th Gen Intel(R) Core(TM) i7-12650H

### GPU

NVIDIA GeForce RTX 3060 Laptop GPU

### RAM

16GB

### List of applied mods

None

**Comment by gdkchan** [comment] 2023-02-22 16:01
Does it do this everywhere? I don't remember noticing this last time I tested this game. If it happens on specific places you should probably attach a save.

**Comment by Squall-Leonhart** [comment] 2023-02-23 07:35
> Does it do this everywhere? I don't remember noticing this last time I tested this game. If it happens on specific places you should probably attach a save.

caused by #3828 as mentioned in #4468 but should have been commented here.

**Comment by GamerzHell9137** [comment] 2023-02-23 23:55
> > Does it do this everywhere? I don't remember noticing this last time I tested this game. If it happens on specific places you should probably attach a save.
> 
> caused by #3828 as mentioned in #4468 but should have been commented here.

There are 3 issues here, one's caused by something that got merged already, one because of #3828 and another one is probably not a regression but something not implemented yet. This should be reported on the compatibility github.

**Comment by Squall-Leonhart** [comment] 2023-02-24 04:59
yeah, no. its the same bug.

**Comment by GamerzHell9137** [comment] 2023-02-24 05:28
> 

Checked yesterday and the transparent objects in the cutscene, the line of black pixels and the flickering UI are caused by 3 different issues. The transparent object might be a regression from 1.0 era ryujinx.

**Comment by Alexy-bubble** [comment] 2023-03-13 22:44
I just tested the game again, and it looks like one of the newer versions of the emulator solved the black pixels and flickering UI. The missing objects/effects mentioned earlier in this thread are still missing, but at least the other two issues seem to be gone.

**Comment by Alexy-bubble** [comment] 2023-04-13 21:19
The issues from my last update seem to be back.

**Closed** 2023-04-17 08:13 UTC
Labels: bug, gpu
