### ISSUE TITLE
[Feature Request] “Calibration” option for gyro/motion control (to correct issues with gyro drift)

### ISSUE THREAD

**Issue by boymanguy** [Ryujinx/Ryujinx#5483] opened 2023-07-23 09:56 UTC
### Overview

This is a request for a button to calibrate the gyro sensor for controllers that have gyro drift. All other emulators I’ve tried + Steam have this feature. My switch pro controller’s gyro sensor constantly drifts to the left when using motion. This is rectified in other programs by hitting “calibrate” within the gyro section of the input settings. Increasing the deadzone keeps the sensor centered when stationary, but drift is still prevalent during movement. The sensor fights with the player’s control and constantly has to be reset in game. Increasing the deadzone is a band-aid solution and does not directly fix the problem.

I’ve seen this feature requested in previous threads but they have all been closed so I am opening this issue up again.

### Smaller details

I do not know how the implementation would work but I assume it would be quite simple considering gyro already works fine and there are many other programs that have calibration implemented.

### Nature of request

A simple button under controller input settings that says “calibrate motion” or “calibrate gyro” or just “calibrate” under the gyro setting. 

### Why would this feature be useful?

This feature would center/correct the gyro sensor for controllers using motion controls, eliminating gyro drift. This would benefit anyone who uses gyro controls within Ryujinx.

**Comment by MutantAura** [comment] 2023-07-23 10:19
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4917

**Closed by MutantAura** 2023-07-23 10:19 UTC
