### ISSUE TITLE
[Bug] Skyrim crashing frequently on macOS

### ISSUE THREAD

**Issue by Avimanyu1** [Ryujinx/Ryujinx#5618] opened 2023-08-27 12:41 UTC
### Description of the issue

[Ryujinx_1.1.0+d157c49_2023-08-27_18-01-32.log](https://github.com/Ryujinx/Ryujinx/files/12447971/Ryujinx_1.1.0%2Bd157c49_2023-08-27_18-01-32.log)
[Ryujinx_1.1.0+d157c49_2023-08-27_18-02-38.log](https://github.com/Ryujinx/Ryujinx/files/12447972/Ryujinx_1.1.0%2Bd157c49_2023-08-27_18-02-38.log)
[Ryujinx_1.1.0+d157c49_2023-08-27_18-04-37.log](https://github.com/Ryujinx/Ryujinx/files/12447973/Ryujinx_1.1.0%2Bd157c49_2023-08-27_18-04-37.log)

### Reproduction steps

No reliable way to replicate aside from playing for more then 10 minutes

### Log file

[Ryujinx_1.1.0+d157c49_2023-08-27_18-02-38.log](https://github.com/Ryujinx/Ryujinx/files/12447976/Ryujinx_1.1.0%2Bd157c49_2023-08-27_18-02-38.log)

### OS

macOS 14.0 Beta (23A5328b)

### Ryujinx version

1.1.0+d157c49

### Game version

1.1.177.3xxxx

### CPU

M1 16GB

### GPU

M1 16GB

### RAM

16GB

**Comment by shinra-electric** [comment] 2023-08-27 15:08
This is a duplicate of #4615

**Comment by AcK77** [comment] 2023-08-29 22:51
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4615

**Closed by AcK77** 2023-08-29 22:51 UTC
Labels: bug
