### ISSUE TITLE
[REGRESSION] Luigi's Mansion 3 - Shadow Maps not clearing.

### ISSUE THREAD

**Issue by INFINITY99K** [Ryujinx/Ryujinx#2791] opened 2021-10-28 00:19 UTC
Well, as the title says there is a problem with the shadows rendering in the game, the shadows draw in but when moving they will smear on the ground like in the photo below.
Apart from this issue, the FPS is great very stable but, there's a problem with the res. scaling in the game
![Annotation 2021-10-28 021539](https://user-images.githubusercontent.com/73315805/139165482-f88d7d6a-f92c-4bf6-a513-50da439ca5fe.png)
.
![Annotation 2021-10-28 021607](https://user-images.githubusercontent.com/73315805/139165491-c6076798-d8a9-46aa-a5de-1b98f1bf0089.png)

**Comment by Linear524** [comment] 2021-11-10 06:12
Latest Master branch shows the same shadow bug:
![ryujinx_capture_2021-11-08_19-24-26](https://user-images.githubusercontent.com/84367301/141059408-2e8cd9f9-4d76-4de9-bbbf-3f8e7ccd7ef8.png)
![ryujinx_capture_2021-11-08_19-24-38](https://user-images.githubusercontent.com/84367301/141059426-9b3834dc-df1a-47c9-a4fd-dff71d841f91.png)
![ryujinx_capture_2021-11-08_19-27-10](https://user-images.githubusercontent.com/84367301/141059480-5c24e633-a684-456a-aea0-194acd41f99c.png)

It looks like shadow buffer is not being updated correctly, or not being flushed from previous frame... (P.S. - on my hardware this issue appears after 2 or 3 minutes after game start. But on other hardware this issue occurs a bit faster. So I think it might depend on VRAM size...)
This issue appears after PR #2534 was merged into Master branch. To be more precise - after AMD fix was applied to tessellation fixup in that PR...

**Comment by INFINITY99K** [comment] 2021-11-12 19:53
I don't think that the problem appeared after PR was merged into master, I believe that it existed in the PR before it was implemented **(Look at the photos)** Weirdly enough it exhibits the behavior on Yuzu on OpenGL.
And here is sth that is even weirder, before the PR was merged into Master, variant 1.0.7077 suffered from this issue I am going to test variants before 1.0.7077 to make sure that this version didn't break things, and don't worry am not using Nvidia's latest drivers that broke older variants of Ryujinx.

**UPDATE**: Good news, well sorta versions before 1.0.7077 don't have that issue so, that's informative I think? maybe both 1.0.7077 and the PR version have sth wrong in common IDK.

**The changelog for 1.0.7077 was**:

* Add missing U8/S8 types from shader I2I instruction

* Better names (Probably not this or, it is who knows).

* Fix dstIsSignedInt

so it's maybe a thing from the changes above caused some sort of an issue and was implemented in the PR build.

![Screenshot 2021-11-12 212703](https://user-images.githubusercontent.com/73315805/141526603-ab51da96-417d-4fde-86be-d4a5a164910e.png)

**Comment by INFINITY99K** [comment] 2021-11-13 23:54
Apparently, The last iteration of the PR build is the one that had that issue and was the one that made it into master. 
The one before it didn't have that bug I hope they re-implement the version that didn't have that bug because I am gonna upgrade my NVIDIA Drivers sooner than later and that will break compatibility with older versions of Ryujinx making the game basically, unplayable.

**Comment by poudink** [comment] 2021-11-14 03:10
why would it break compatibility with older ryujinx?

**Comment by INFINITY99K** [comment] 2021-11-14 19:51
Drivers after 496.xx caused visual artifacts on Ryujinx then developers applied a workaround for it.

**Comment by INFINITY99K** [comment] 2021-11-14 22:30
### **New bugs found:**

- Audio De-Sync in some scenes.
- FPS Drops when there are a lot of alpha particles on display.

**Comment by INFINITY99K** [comment] 2021-11-15 00:10
Apparently, it is a regression issue since the versions from 1.0.7076 downwards didn't suffer from this and it started appearing in 1.0.7077 before the PR was merged into master.

**Comment by mrjo118** [comment] 2022-02-04 22:48
I've managed to find out which caused this issue originally when merging the tesselation PR (PR 2534) to master. It turns the commit immediately before it on master (PR 2740) is what caused the issue to appear!

I did a hard reset on master to commit 25fd4ef1 (PR 2727), then cherry picked d512ce12 (PR 2534) on top of it and it fixed the issue! However I then tried cherry picking the Nvidia driver fix 052deebf (PR 2750) and the issue came back. It turned out that the only thing in PR 2750 causing the issue to come back was updating the value of ShaderCodeGenVersion to 2750. When I set the value back to 2534 then the issue goes away again.

I tried reverting 7603dbe3 (PR 2740) on the latest build and changing ShaderCodeGenVersion back to 2534, however this caused all kinds of glitching, presumably because it's far too big a downgrade.

Bear in mind that when I say 'fixed' the issue, what I mean is the problem was reverted to how it was before merging the tesselation PR to master. The shadow trailing bug has been present in Ryujinx way before the tesselation PR was merged, but only causing a slight trail at times when running, rather than completely smearing the floor with shadow.

I hope these findings can help towards finding a fix in the latest version :)

**Comment by Linear524** [comment] 2022-06-07 11:11
@gdkchan  and @riperiperi 
This long standing issue is still persist in every PR, is there any way to just clear shadow buffer after every vsync is dine ? Or after gpu finishes rendering frame and sends it to output buffer ?

**Comment by mrjo118** [comment] 2022-06-11 17:00
Could someone explain what incrementing the value of ShaderCodeGenVersion in Ryujinx.Graphics.Gpu/Shader/ShaderCache.cs actually does? I have commercial experience as a software developer, but graphics rendering and emulation is foreign to me.

Is this constant in reference to a version of a third party library or is it used by other Ryujinx modules which gets updated from time to time in separate PR's? I noticed this value gets updated regularly. Initially I thought it was purely to trigger a rebuild of the shader cache if the cache was built with a Ryjinx build where it had a lower value, but as per my findings in my previous post it appears to have more of an effect than just that

**Comment by gdkchan** [comment] 2022-06-11 17:21
The only thing this shader codegen version does is forcing a rebuild of the shaders. It is changed when we fix a bug on the shader translator or make some change that requires the host GLSL or SPIR-V shader to be re-generated.

From what I recall, the issue that causes the shadow trailing issue on Luigi's Mansion 3 is related to texture copies, not shaders. It aliases the depth texture as a different format for the copy (which is expected since the 2D copy engine does not have any depth format), but the way how aliasing of depth and color formats is handled right now causes it to not find or pick the correct texture from the cache sometimes. Also, it is not a regression, this issue has always existed.

**Comment by mrjo118** [comment] 2022-06-11 23:49
Hi @gdkchan, thank you for your detailed analysis. I have retested my hypothesis and discovered that after deleting my existing shader cache and retesting my 'working' build which did not have ShaderCodeGenVersion incremented, it does indeed still have the shadow trailing issue.

"Also, it is not a regression, this issue has always existed" - I think there are actually 2 issues at play. As I mentioned in previous posts I did notice while investigating this issue that the shadow trailing issue did exist in builds prior to implementing the initial tessellation support (PR 2534). However it was nowhere near as bad as it is currently. I think that PR 2534 introduced a shader bug in Luigi's Mansion 3 at the point when the 2nd batch of commits was made to fix issues on AMD cards. I did not have an issue with shadows being smeared everywhere on the original dev build of PR 2534 (I have a Nvidia card, so it was working perfectly at that point, I have a backup of this build I retested, but unfortunately did not back up the source). However I did get issues with the 2nd revision of the PR. I believe that I have been able to avoid the issues by messing around with the commits in my own custom builds because I have been using a version of the shader cache I backed up from playing the game on the original PR 2534 dev build and lowering ShaderCodeGenVersion meant that it didn't get rebuilt. As the newer commits were since rebased though, we don't have a way of seeing which specific changes were added for the second revision of the PR

**Comment by mrjo118** [comment] 2022-06-12 01:56
So I found out I can actually view the original commit history and retrieve the full source at those points in time from GitHub by clicking the links on a PR on lines like this:
gdkchan force-pushed the tess branch from 37b4c7a to d9276b2 8 months ago

I downloaded the source at the various different states of the PR and rebuilt them (making sure to have deleted the shader cache before every test) and have been able to identify the point on the PR where the bug was introduced, which was when this commit was pushed on 18 October 2021 (not due to the fix for AMD cards a couple of days before):
https://github.com/Ryujinx/Ryujinx/commit/d9276b2172659e8d1fd9c5a8ca615148b3163838

I tried manually reverting the changes shown at that link having downloaded the source at that point in time and this did not remove the issue. I can see that at the same time as pushing this commit all the previous commits were rebased in preparation for merging the PR to master. Unfortunately this means that this bug was introduced in one of the PR's merged to master between the first rebase on 25 September 2021 and the the latest version on 18 October 2021, which doesn't narrow down that much what caused the issue :(

**Comment by INFINITY99K** [comment] 2022-06-12 02:21
I had the last build that didn’t have the issue but unfortunately I
accidentally deleted it though I remember it being either 1.0.7066 or
1.0.7067 important note: You need to use only 473.xx Nvidia Drivers since
versions afterwards introduced major issues in these older builds of
Ryujinx.

**Comment by mrjo118** [comment] 2022-06-20 20:28
So with some investigation and experimentation with reverting commits which update ShaderCodeGenVersion between the relevant window of commits, I have managed to identify the cause of the regression in the shader cache code. PR 2702 (https://github.com/Ryujinx/Ryujinx/pull/2702) is the offending commit. I have verified as well using the latest build of Ryujinx (v1.1.151) that if I revert the commit for this PR the shadow behavior goes back to how it was before merging the tessellation shader PR. Of course reverting the change is not the solution as this would mean undoing a fix or improvement for other games. But as the cause is now narrowed down to a very small amount code, could someone please investigate how the shadow issue can be fixed properly?

**Comment by mrjo118** [comment] 2022-06-20 21:34
Maybe the issue is relating to the circled line having a different behaviour due to the change in PR 2702? Possibly this line needs to call a slightly different leg of code to make it work?
![luigi](https://user-images.githubusercontent.com/6963004/174680150-0d5a5dc4-593d-4531-b07a-b30bdc26344c.PNG)

**Comment by riperiperi** [comment] 2022-06-21 00:13
I've already checked this and it's likely a texture cache issue relating to Depth<->Red aliasing. This has happened on the emulator for many years/ Anything else is likely placebo.

I've known it for a while but I haven't had time to fix it.

**Comment by mrjo118** [comment] 2022-06-21 00:56
This is a video from the current build after reverting the commit for https://github.com/Ryujinx/Ryujinx/pull/2702. This is the same behaviour as before PR 2534 was merged to master. After that PR had been tested, it was rebased onto master which pulled in PR 2702 in the process

https://user-images.githubusercontent.com/6963004/174694574-64546307-a56e-4a8d-9a5b-5b867dafec7b.mp4

Both videos were recorded after starting up Ryujinx fresh having deleted the shader cache and pptc cache beforehand. I think when you compare the two videos it's clearly more than a placebo. I can run around the hand rails for 5 minutes straight on a build without PR 2702, and it looks as shown the whole time. Whereas on the latest build I load up the game at the entrance of floor 14, circle around the hand rail once or twice, and every time I try attempt this in that room I can reproduce the issue. FYI I have a Nvidia gpu

**Comment by Linear524** [comment] 2022-11-16 05:44
With all latest versions of Ryujinx - all dynamic shadows are completely broken and does not clears between frames... 
Looks like this bug become even worse condition than it was before :P

**Comment by tvoracek** [comment] 2023-02-05 18:27
Version 1.1.599 completely broke rendering, only background and flashlight is rendered, everything else is not displaying. Was ok previously.

**Comment by gdkchan** [comment] 2023-02-05 18:28
> Version 1.1.599 completely broke rendering, only background and flashlight is rendered, everything else is not displaying. Was ok in previous versions.

It's a OpenGL only issue and should be fixed by #4369.

**Closed** 2023-10-31 22:00 UTC
Labels: bug, gpu
