### ISSUE TITLE
Any game "randomly" crashes Ryujinx 

### ISSUE THREAD

**Issue by WinnerNombre** [Ryujinx/Ryujinx#3098] opened 2022-02-07 23:20 UTC
### What's the issue you encountered?

Any game will freeze/crash Ryujinx at a random moment. It can be on the title screen a few seconds after booting the game while it can run fine and crash 10 minutes after booting the game.

### How can the issue be reproduced?

I really have no idea.

### Log file

Here's a log after a crash of Luigi's Mansion 3: 
[Ryujinx_1.1.20_2022-02-07_22-35-41.log](https://github.com/Ryujinx/Ryujinx/files/8019367/Ryujinx_1.1.20_2022-02-07_22-35-41.log)

And here is one after crashing SUPER MARIO ODYSSEY:
[Ryujinx_1.1.20_2022-02-07_21-12-05.log](https://github.com/Ryujinx/Ryujinx/files/8019374/Ryujinx_1.1.20_2022-02-07_21-12-05.log)

### Environment?

- System Specs:
  - OS: *(Windows 11)*
  - CPU: *(i9-10900KF)*
  - GPU: *(NVIDIA RTX 3070)*
  - RAM: *(32GB)*
- Applied Mods : Crash with and without mods

### Additional context?

I'm using version 22000.469 of Windows 11. I'm opening this issue after a member of the staff told me to, since no one could figure out what was wrong ¯\_(ツ)_/¯
If needed, here is where it started: https://discord.com/channels/410208534861447168/410208610455519243/940337796474892308

**Comment by AcK77** [comment] 2022-02-08 09:42
Seems to be an hardware issue more than a Ryujinx issue. Since the crash is random and you are the only one with it. Maybe double check your RAM?
I let the issue open in case anyone report the same behavior.

**Comment by dharmang1910** [comment] 2022-02-10 12:49
Today ryujinx updated to 1.1.23 and can not play any game. all the time it crash on booting. tried 3 different games. Games are working fine in ryujinx ldn2.4 build.

**Comment by MetrosexualGarbodor** [comment] 2022-02-10 12:52
@dharmang1910 Please come to Discord and send a log, this is not a post for troubleshooting. https://discord.gg/ryujinx

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 01:00
Closing this as no one else has reported or managed to reproduce it, sorry.

**Closed by MetrosexualGarbodor** 2022-02-11 01:00 UTC
Labels: bug

**Comment by justalex95** [comment] 2023-04-24 22:26
i know its closed but experiencing the same problem in mario odyssey and mario kart, using latest build with 2-3 mods enabled on each game  on the steam deck
