### ISSUE TITLE
[CPU] Wheel of fortune undefined instruction - opcode 0xe7ffdefe (trap)

### ISSUE THREAD

**Issue by TrevorSlobodnick** [Ryujinx/Ryujinx#6000] opened 2023-12-02 11:39 UTC
### CPU instruction

The instruction at 0x0000000009a15658 (opcode 0xe7ffdefe) is undefined!

### Instruction name

trap

### Required by

https://github.com/Ryujinx/Ryujinx-Games-List/issues/3756

**Comment by OldManKain** [comment] 2023-12-02 15:08
Duplicate of #1340.

**Closed by OldManKain** 2023-12-02 15:08 UTC
Labels: cpu, not-implemented
