### ISSUE TITLE
[Bug] Graphical Glitches in Red Dead Redemption starting on version 1.1.1014 (MacOS)

### ISSUE THREAD

**Issue by evanpaul14** [Ryujinx/Ryujinx#5714] opened 2023-09-21 23:49 UTC
### Description of the issue

Black squares keep flashing in the landscape.

Version 1.1.1014:

https://github.com/Ryujinx/Ryujinx/assets/120766197/38780af5-951f-4ff8-a01c-f6c2fa3b566b

Version 1.1.1013:

https://github.com/Ryujinx/Ryujinx/assets/120766197/5056a3a6-626e-4f3d-a89a-0c79ebd1fe09

### Reproduction steps

Run Red Dead Redemption on 1.1.1014

### Log file

[Ryujinx_1.1.1013_2023-09-21_16-36-36.log](https://github.com/Ryujinx/Ryujinx/files/12694247/Ryujinx_1.1.1013_2023-09-21_16-36-36.log)
[Ryujinx_1.1.1014_2023-09-21_16-41-02.log](https://github.com/Ryujinx/Ryujinx/files/12694248/Ryujinx_1.1.1014_2023-09-21_16-41-02.log)

### OS

MacOS

### Ryujinx version

1.1.1014 

### Game version

1.0.2

### CPU

M1

**Comment by gdkchan** [comment] 2023-09-21 23:59
Duplicate of #5685.

**Closed by gdkchan** 2023-09-21 23:59 UTC
Labels: bug
