### ISSUE TITLE
Input not being recognized on Ni no Kuni 2.

### ISSUE THREAD

**Issue by JaviBOT96** [Ryujinx/Ryujinx#2652] opened 2021-09-17 20:25 UTC
Hello, Good afternoon. 
I've been testing Ni no Kuni 2 on Ryujinx but unfortunately It does not work as expected. 
The issue is that the input is not being recognized. I tried 2 different gamepads, one Pro Controller and the other one a PowerA licensed controller wired, but the game didn't recognize it. I also tried handheld mod but no luck, At this point I'm not sure what to do so that's why I decided to open this issue. 

Thanks
[Ryujinx_1.0.7038_2021-09-17_15-05-39.log](https://github.com/Ryujinx/Ryujinx/files/7188280/Ryujinx_1.0.7038_2021-09-17_15-05-39.log)
s

**Comment by Sky0817** [comment] 2021-09-17 20:29
![image](https://user-images.githubusercontent.com/90934846/133849794-a6c891eb-12e6-4c51-8e47-fae8ee68aac0.png)
Did you try this? I'm having the same issue.

**Comment by JaviBOT96** [comment] 2021-09-17 20:32
I read all the conversation, no luck yet.

**Comment by RyzenDew** [comment] 2021-09-17 20:44
Just tested my xbox one and ps4/ps5/joycons/switch pro and all work without issue i can not reproduce the issue. ￼

**Comment by gdkchan** [comment] 2021-09-17 20:54
Also can't reproduce.
https://user-images.githubusercontent.com/5624669/133852378-aeaabf0e-fd35-42a4-9b73-226ef5062071.mp4
Unless the issue only happens with a save?

**Comment by Sky0817** [comment] 2021-09-17 20:55
I do not have a savefile :/

**Comment by Sky0817** [comment] 2021-09-17 21:21
It's a savefile issue, you can close this now.

**Comment by gdkchan** [comment] 2021-09-17 21:28
I will close as one of the users with the issue confirmed that is is solved with a fresh save, and I can't reproduce it myself. @JaviBOT96 please reopen if you can confirm it is an emulator issue, and not a save issue.

**Closed by gdkchan** 2021-09-17 21:28 UTC

**Comment by RyzenDew** [comment] 2021-09-17 22:15
I didn't need a save file so that isn't the issue

**Comment by gdkchan** [comment] 2021-09-17 22:27
The issue is *having* a save file that was not created by the emulator. I don't know what is wrong with the saves they used though, maybe it was from a different game version.

**Comment by gdkchan** [comment] 2021-09-17 22:31
If someone can confirm that a save from an actual Switch system on the same game version doesn't work on the emulator, then its something we should look at as it is supposed to work. But it could be also something like an user ID mismatch that the game doesn't expect, and in this case this is not the emulators fault. But it is worth looking at I think.
