### ISSUE TITLE
Super Mario Party crashes in a mini-game without any error in the log or console

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#2046] opened 2021-02-22 03:21 UTC
### What's the issue you encountered?

Super Mario Party crashes when trying to play the mini-game "It's the Pits". The emulator exits, but no log items nor console entries indicate a crash occurred.

### How can the issue be reproduced?

Try playing the mini-game "It's the Pits" on Super Mario Party.

### Log file

There is no error produced in either the log nor the console. As such I've included debug logs here (which stop at the time of the crash).
[Ryujinx_1.0.6670_2021-02-21_20-07-40.log.zip](https://github.com/Ryujinx/Ryujinx/files/6019338/Ryujinx_1.0.6670_2021-02-21_20-07-40.log.zip)

### Environment?

- Ryujinx version: 1.0.6667
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 7 5800X
  - GPU: NVIDIA GTX 1080
  - RAM: 32GB
- Applied Mods : No

### Additional context?

Originally reported by Discord users.

**Comment by matisptfan** [comment] 2021-03-01 14:57
Hi,

I am one of the people who reported this issue on Discord and would like to contribute with more data to hopefully find the root cause of this crash. 

I've made a two minute video replicating it: https://www.youtube.com/watch?v=XraJ3F7oivU

The log which was generated - using option "OpenGL Log Level - Error" - can be found below:

[Ryujinx_1.0.6769_2021-03-01_15-36-04.zip](https://github.com/Ryujinx/Ryujinx/files/6062362/Ryujinx_1.0.6769_2021-03-01_15-36-04.zip)

The crash naturally also generated an events viewer warning log, ID 4101, Nvidia driver crash. I am not sure how helpful that'd be, so if it isn't just dismiss the file below:

[Super Mario Driver Crash.zip](https://github.com/Ryujinx/Ryujinx/files/6062390/Super.Mario.Driver.Crash.zip)

My save game file can be found here:

[buffer_save.zip](https://github.com/Ryujinx/Ryujinx/files/6062397/buffer_save.zip)

Path to paste file is C:\Users\<username>\AppData\Roaming\Ryujinx\bis\user\save\0000000000000002\0

I've been testing different builds from PRs yet to be merged into the master branch to no avail. Therefore, I believe this is not yet addressed in any commit which is being considered for the near future.

Please let me know how can I help here, I am not a coder but will be more than happy to help with any testing. I've compiled Ryujinx before, so there should not be any issues If I need to do that.

PS: This is not the sole instance of where a crash occurs, but this particular mini-game crashes every time. There's a different mini-games called "Isthmus Be the way" which also crashes from time to time, but I wouldn't consider it as high priority as this one.

**Comment by matisptfan** [comment] 2021-03-05 20:54
While researching this issue a bit more, I kept seeing build 1.0.5574 heavily referenced on Youtube videos of Ryujinx running Super Mario Party.

I have downloaded that build (https://w.ryujinx.org/dl/1642) and, in my haste, didn't bother do set the executable  to "high performance" graphics mode, which defaulted then to the "power saving" option. In my laptop, that means:

![image](https://user-images.githubusercontent.com/15782559/110163667-9fb51580-7df0-11eb-9f6b-0091b9ef59ee.png)

On my first test of the "It's the Pits" mini-game (launching with the AMD card), I started by noticing that the weird pixelation present in the intro video on the latest Ryujinx's build did **not** show on build 1.0.5574.

This is what I mean:

**Running Super Mario Party v1.0.1, build 1.0.5574, v-sync, multicore and PPTC enabled, ignore missing services unticked, docked mode, with AMD graphics card**

![image](https://user-images.githubusercontent.com/15782559/110167487-199bcd80-7df6-11eb-9709-be3c434fca9f.png)

Lighting is a bit weird but there's no pixelation.
And most importantly, no crash.

![image](https://user-images.githubusercontent.com/15782559/110168094-f9b8d980-7df6-11eb-97c5-bc56f5f7b5c0.png)

Associated log: [Ryujinx_2021-03-05_20-57-50.log](https://github.com/Ryujinx/Ryujinx/files/6093112/Ryujinx_2021-03-05_20-57-50.log)

-------------
**Running Super Mario Party v1.0.1, build 1.0.5574, v-sync, multicore and PPTC enabled, ignore missing services unticked, docked mode, with Nvidia graphics card**

![image](https://user-images.githubusercontent.com/15782559/110168590-b4e17280-7df7-11eb-80d9-3fd8aa043080.png)

Once again, lighting is a bit weird but there's no pixelation.
And also no crash.

![image](https://user-images.githubusercontent.com/15782559/110168834-08ec5700-7df8-11eb-8773-ea1a6f3e5989.png)

Associated log: [Ryujinx_2021-03-05_21-11-36.log](https://github.com/Ryujinx/Ryujinx/files/6093148/Ryujinx_2021-03-05_21-11-36.log)

-------------
At this point I decided to go back to the current build (1.0.6774), purge both the PPTC and shader caches and run the same test scenario:

**Running Super Mario Party 1.0.1 on most recent build, 1.0.6774, v-sync, PPTC and shader cache enabled, ignore missing services unticked, docked mode, with AMD graphics card**

![image](https://user-images.githubusercontent.com/15782559/110170745-f32c6100-7dfa-11eb-9bb4-8f2d51230d70.png)

Lighting is the same but now pixelation can be seen once more.
However, there's no crash:

![image](https://user-images.githubusercontent.com/15782559/110171036-5c13d900-7dfb-11eb-9f0d-b584f83ef34b.png)

Associated log: [Ryujinx_1.0.6774_2021-03-05_21-32-54.log](https://github.com/Ryujinx/Ryujinx/files/6093273/Ryujinx_1.0.6774_2021-03-05_21-32-54.log)

-------------

_Had to purge shader cache once more_

**Running Super Mario Party 1.0.1 on most recent build, 1.0.6774, v-sync, PPTC and shader cache enabled, ignore missing services unticked, docked mode, with Nvidia graphics card**

![image](https://user-images.githubusercontent.com/15782559/110171798-8ade7f00-7dfc-11eb-81b7-42dc67a7832c.png)

The lightning is better - I can see new light sources on the top left and the top right - but the pixelation is even more noticeable.

And with this build with the Nvidia the game always crashes.

Associated log: [Ryujinx_1.0.6774_2021-03-05_21-45-38.log](https://github.com/Ryujinx/Ryujinx/files/6093306/Ryujinx_1.0.6774_2021-03-05_21-45-38.log)

----------------

Will continue, editing later

**Comment by legend800** [comment] 2021-03-05 22:23
Make sure you have resolution set to native. This game breaks with 2x+

**Comment by matisptfan** [comment] 2021-03-06 00:06
> Make sure you have resolution set to native. This game breaks with 2x+

Hi,

This issue is logged for a particular crash (possible regression) in an individual mini game of Super Mario Party. All of my tests, which you can check above, have been done running on native resolution. I am aware that at least in all of 2021x builds the resolution scaler casts extra shadows to the game's image. However, that is less of an issue and not the specific focus of 2046.
If you have an Nvidia GPU, may I suggest that you run Super Mario Party's "It's the Pits" mini-game in native resolution in any build past 1.0.5650 and report your findings with a log file?

**Comment by legend800** [comment] 2021-03-10 06:12
No crash for me. But pixelation is definitely a regression:

![2021-03-09 22_08_36-Ryujinx 1 0 6780 - Super Mario Party v1 0 0 (010036B0034E4000) (64-bit)](https://user-images.githubusercontent.com/20983844/110584619-53d1db80-8124-11eb-8b09-7986eed1eaf7.png)

**Comment by legend800** [comment] 2021-03-10 07:17
![2021-03-09 23_17_29-System Information](https://user-images.githubusercontent.com/20983844/110591222-a368d500-812d-11eb-8d1c-15fd02ec790b.png)

**Comment by matisptfan** [comment] 2021-03-19 11:23
I've done a bit more testing and would like to add two updates to this issue:

1.It is clear this crash doesn't affect everyone. At the very least, both AMD GPU users and people with RXT 30xx series GPUs are not affected - we have legend800's case of a 3070 above and a fellow Ryujinx enthusiast as also tested with his 3080 and says the crash doesn't occur after the caches are created - takes three runs but eventually stabilities. 

2. The other tests scenarios I'm aware of where crashing always occurs were done with a RTX 2060 and 2060 Mobile and a 1080, so for those with GPUs of the Pascal and Turing architectures the below can be of interest:

There's a potential workaround with setting the game to run on **handheld** mode and making sure to **skip any intro scenes** (logged as [MGBase]!!!! SKIP OPENING DEMO !!!!') every time any of the mini games below is ran:

Metal Detectors
It's the Pits
Isthmus be the way
Miner Set Backs
Strike it Rich
Take a stab

You can skip the intro by clicking on SL or SR. I'm singling out the mini-games above because the light textures are "broken" - pixelation can be seen - and my hunch and testing experience leads me to believe the crash be related to that.

I'll continue to test, but for the time being I've seen no crashes both with or without the 1.01 update, v-sync off, PTTC and shader caches enabled, build 1.0.6793.
Hopefully this helps anyone who reads this and motivates people with different Nvidia GPUs to share their testing and contribute to a potential solution. :)

**Comment by riperiperi** [comment] 2021-03-19 12:11
It seems like the flashing lighting is not a regression, but a result of some component of lighting that wasn't working at all before. I'll probably end up looking into this soon.

**Comment by matisptfan** [comment] 2021-04-02 22:06
I am happy to report that as of version 1.0.6816 the crash that originated this ticket is no more. I've tested several options and did multiple runs of the game and this seems to have been fixed. Thanks.

**Closed** 2021-04-02 22:09 UTC
Labels: bug, miscellaneous
