### ISSUE TITLE
Crashed when running "The Legend of Heroes Zero no Kiseki Kai"

### ISSUE THREAD

**Issue by aishen944** [Ryujinx/Ryujinx#2669] opened 2021-09-20 13:26 UTC
## Bug Report

"N/A" </br>

### What's the issue you encountered?

Can not boot game!

### Log file
[Ryujinx_1.0.7047_2021-09-20_21-18-50.log](https://github.com/Ryujinx/Ryujinx/files/7196010/Ryujinx_1.0.7047_2021-09-20_21-18-50.log)

### Environment?

- Ryujinx version: 1.0.7047</br>
- Game version: 1.0.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 9 4900HS
  - GPU: NVIDIA RTX 2060
  - RAM: 16GB
- Applied Mods : No

**Comment by d3xMachina** [comment] 2021-09-20 16:46
Try with this PR and report back : #2629

**Comment by aishen944** [comment] 2021-09-21 00:17
Zero no Kiseki does not crash anymore but it's frozen with black screen.

**Comment by gdkchan** [comment] 2021-09-21 00:18
The PR that fixes this game is https://github.com/Ryujinx/Ryujinx/pull/2646 not https://github.com/Ryujinx/Ryujinx/pull/2629.

**Comment by gdkchan** [comment] 2021-09-21 00:19
Closing as this is a duplicate of #2628.

**Closed by gdkchan** 2021-09-21 00:19 UTC

**Comment by aishen944** [comment] 2021-09-21 00:26
#2646 fixes this game!
