### ISSUE TITLE
[Bug] closes when trying to change the system time

### ISSUE THREAD

**Issue by erickgamer787** [Ryujinx/Ryujinx#6502] opened 2024-03-15 11:12 UTC
### Description of the issue

in the last update of Ryujinx, when you click to change the system time, Ryujinx closes by itself

### Reproduction steps

try changing the system time and it will happen again

### Log file

00:00:00.425 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.437 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.437 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.438 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.440 |I| Configuration LogValueChange: BackendThreading set to: On
00:00:00.441 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.442 |I| Configuration LogValueChange: PreferredGpu set to: 0x10DE_0x1381
00:00:00.443 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.445 |I| Configuration LogValueChange: ScalingFilter set to: Fsr
00:00:00.445 |I| Configuration LogValueChange: ScalingFilterLevel set to: 52
00:00:00.447 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.455 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.455 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.455 |I| Configuration LogValueChange: EnableTextureRecompression set to: True
00:00:00.455 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.455 |I| Configuration LogValueChange: EnableColorSpacePassthrough set to: False
00:00:00.455 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.456 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.456 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.456 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.457 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.458 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.460 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.461 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.461 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.461 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.466 |I| Configuration LogValueChange: MultiplayerMode set to: LdnMitm
00:00:00.471 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.1231
00:00:00.478 |N| Application Print: Operating System: Microsoft Windows 10.0.22631 (X64)
00:00:00.478 |N| Application Print: CPU: Intel(R) Core(TM) i7-6700 CPU @ 3.40GHz ; 8 logical
00:00:00.482 |N| Application Print: RAM: Total 16 GiB ; Available 9.2 GiB
00:00:00.486 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.487 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:02.417 |W| Application CheckScreenBounds: Failed to find valid start-up coordinates. Defaulting to primary monitor center.
00:01:05.660 |E| Application : Unhandled exception caught: System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values. (Parameter 'value')
   at Avalonia.Controls.Primitives.DateTimePickerPanel.set_SelectedValue(Int32)
   at Avalonia.Controls.TimePickerPresenter.InitPicker()
   at Avalonia.Controls.TimePickerPresenter.OnApplyTemplate(TemplateAppliedEventArgs)
   at Avalonia.Controls.Primitives.TemplatedControl.ApplyTemplate()
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness, Thickness)
   at Avalonia.Controls.Presenters.ContentPresenter.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness)
   at Avalonia.Controls.Decorator.MeasureOverride(Size)
   at Avalonia.Controls.Primitives.VisualLayerManager.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutHelper.MeasureChild(Layoutable, Size, Thickness)
   at Avalonia.Controls.Decorator.MeasureOverride(Size)
   at Avalonia.Controls.LayoutTransformControl.MeasureOverride(Size)
   at Avalonia.Layout.Layoutable.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.Layoutable.MeasureOverride(Size)
   at Avalonia.Controls.Primitives.PopupRoot.MeasureOverride(Size)
   at Avalonia.Controls.WindowBase.MeasureCore(Size)
   at Avalonia.Layout.Layoutable.Measure(Size)
   at Avalonia.Layout.LayoutManager.Measure(Layoutable)
   at Avalonia.Layout.LayoutManager.ExecuteInitialLayoutPass()
   at Avalonia.Controls.WindowBase.Show()
   at Avalonia.Controls.Primitives.Popup.Open()
   at Avalonia.Controls.Primitives.Popup.IsOpenChanged(AvaloniaPropertyChangedEventArgs`1)
   at Avalonia.Controls.Primitives.Popup.<>c.<.cctor>b__21_1(Popup x, AvaloniaPropertyChangedEventArgs e)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.PropertyStore.EffectiveValue`1.SetAndRaiseCore(ValueStore, StyledProperty`1, T, BindingPriority, Boolean , Boolean )
   at Avalonia.PropertyStore.ValueStore.SetValue[T](StyledProperty`1, T, BindingPriority)
   at Avalonia.AvaloniaObject.SetValue[T](StyledProperty`1, T, BindingPriority )
   at Avalonia.Controls.Primitives.Popup.set_IsOpen(Boolean)
   at Avalonia.Controls.TimePicker.OnFlyoutButtonClicked(Object sender, RoutedEventArgs e)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Controls.Button.OnClick()
   at Avalonia.Controls.Button.OnPointerReleased(PointerReleasedEventArgs)
   at Avalonia.Reactive.LightweightObservableBase`1.PublishNext(T)
   at Avalonia.Interactivity.EventRoute.RaiseEventImpl(RoutedEventArgs)
   at Avalonia.Interactivity.Interactive.RaiseEvent(RoutedEventArgs)
   at Avalonia.Input.MouseDevice.MouseUp(IMouseDevice, UInt64, IInputRoot, Point, PointerPointProperties, KeyModifiers, IInputElement )
   at Avalonia.Input.MouseDevice.ProcessRawEvent(RawPointerEventArgs)
   at Avalonia.Controls.TopLevel.HandleInput(RawInputEventArgs e)
   at Avalonia.Win32.WindowImpl.AppWndProc(IntPtr, UInt32, IntPtr, IntPtr)
   at Avalonia.Win32.WindowImpl.WndProc(IntPtr hWnd, UInt32 msg, IntPtr wParam, IntPtr lParam)
   at Avalonia.Win32.Interop.UnmanagedMethods.DispatchMessage(MSG&)
   at Avalonia.Win32.Win32DispatcherImpl.RunLoop(CancellationToken)
   at Avalonia.Threading.DispatcherFrame.Run(IControlledDispatcherImpl)
   at Avalonia.Threading.Dispatcher.PushFrame(DispatcherFrame)
   at Avalonia.Threading.Dispatcher.MainLoop(CancellationToken)
   at Avalonia.Controls.ApplicationLifetimes.ClassicDesktopStyleApplicationLifetime.Start(String[])
   at Avalonia.ClassicDesktopStyleApplicationLifetimeExtensions.StartWithClassicDesktopLifetime(AppBuilder, String[], Action`1 )
   at Ryujinx.Ava.Program.Main(String[] args) in D:\a\Ryujinx\Ryujinx\src\Ryujinx\Program.cs:line 51

### OS

Windows 11

### Ryujinx version

1.1.1231

### CPU

Intel(R) Core(TM) i7-6700 CPU 

### GPU

Nvidia Gerforce gtx 750

### RAM

16GB

### Additional context?

This happens without opening any game, it only happened in the last update

**Comment by piplup55** [comment] 2024-03-15 11:27
duplicate of #6377

**Closed by piplup55** 2024-03-15 11:27 UTC
Labels: bug
