### ISSUE TITLE
Hope to double joycon native support

### ISSUE THREAD

**Issue by KANGKANG2** [Ryujinx/Ryujinx#7017] opened 2024-07-11 00:52 UTC
### Overview

Through the third party to achieve double joycon is too difficult to use, some games need double joycon support, such as aerobic boxing, if the big guys have time, but also hope to be able to native support double joycon, thank you.

### Smaller details

Native dual joycon support

### Nature of request

Native dual joycon support

### Why would this feature be useful?

Third-party ones are hard to use

**Comment by MetrosexualGarbodor** [comment] 2024-07-11 00:58
duplicate of #3293

**Closed by MetrosexualGarbodor** 2024-07-11 00:58 UTC
Labels: enhancement
