### ISSUE TITLE
Stop Emulation doesn't unlock mod files.

### ISSUE THREAD

**Issue by Mou-Ikkai** [Ryujinx/Ryujinx#2604] opened 2021-08-30 01:07 UTC
### What's the issue you encountered?
After pressing Stop Emulation so I could delete a problematic mod for my game, I spotted that Ryujinx still had the mod folder "locked", meaning I was unable to delete the folder or files. This doesn't seem like it should occur. Seeing as when you freshly open Ryujinx, it doesn't lock the mod files.

### How can the issue be reproduced?
Play a game with mods, then press Stop Emulation, and try to delete a file from the mods folder while Ryujinx is back in the Game Select menu, you will see that the files are still locked.

### Environment?

- Ryujinx version: 1.0.7021</br>
- Game version: 1.0.4</br>
- System Specs:
  - OS: *Windows 10 19043.1165*
  - CPU: *Ryzen 9 3900X*
  - GPU: *AMD 5700XT 8GB*
  - RAM: *32GB DDR4*
- Applied Mods : Yes - Improved Ghost Rule, Additional Modules Pack, EdgyPsLightMod, AFT Shaders.

**Comment by AcK77** [comment] 2021-09-11 22:25
duplicate of #2149

**Closed by AcK77** 2021-09-11 22:25 UTC
Labels: bug
