### ISSUE TITLE
[Bug]Enabling shader cache caused the Pokémon Sword&Shield Dynamax Adventure save to freeze.

### ISSUE THREAD

**Issue by yemaowuxin** [Ryujinx/Ryujinx#6935] opened 2024-06-12 15:56 UTC
### Description of the issue

![image](https://github.com/Ryujinx/Ryujinx/assets/48284264/c1d823e0-8770-4b04-a716-0e81a2cba3b3)
Turn off the shader cache, after multiple tests, use the Wishing Piece and Dynamax Adventure save in the game no longer freezes.

### Reproduction steps

Turn off the shader cache, after multiple tests, use the Wishing Piece and Dynamax Adventure save in the game no longer freezes.

### Log file

none

### OS

window 11

### Ryujinx version

1.1.1330

### Game version

1.3.2

### CPU

10900K

### GPU

AMD Radeon RX 6900 XT

### RAM

32GB

**Comment by MetrosexualGarbodor** [comment] 2024-06-12 15:58
The freeze is random and any fixes you find are most likely placebo. Duplicate of #5837

**Closed by MetrosexualGarbodor** 2024-06-12 15:58 UTC
Labels: bug

**Comment by yemaowuxin** [comment] 2024-06-12 17:00
> use the Wishing Piece and Dynamax Adventure save

Enabling shader caching, there is a 90% chance use Wishing Piece and Dynamax Adventure will freeze when saved.
Turn off the shader cache and use Wishing Piece and Dynamax Adventure to save. After 6 hours of testing, the game no longer freezes.
This is not random!!!

**Comment by yemaowuxin** [comment] 2024-06-12 17:13
This is not random, and not placebo.
I tested with several players, and they gave me the same results.

**Comment by IgorEisberg** [comment] 2024-06-14 22:33
Speaking of "Shader cache", having it enabled also causes the whole emulator to crash most of the time when you do "Stop Emulation".

**Comment by Odizinne** [comment] 2024-06-21 17:56
I can confirm that shader cache has nothing to do with it as i can reproduce the crash with it disabled.
