### ISSUE TITLE
Super Mario Odyssey crashes on boot when using Speaker Setup (5.1) audio output in Windows

### ISSUE THREAD

**Issue by DarkMarioWahoo** [Ryujinx/Ryujinx#2332] opened 2021-05-31 18:16 UTC
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

Started Mario Odyssey as normal and then switched the sound output to my 5.1 Denon AVR. After the audio output source change, the game doesn't boot up anymore. When I change it back, it boots up again properly.

### How can the issue be reproduced?

In Windows 10, go to "Open Sound Settings" and use an output device that is set to "Speaker Setup (5.1)" in its device properties.

On boot of Mario Odyssey you will get an unhandled exception: System Argument Exception: No valid channel configuration found.

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

00:00:00.709 |N| Application LoadApplication: Using Firmware Version: 10.0.4
00:00:01.875 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation GeForce GTX 1080/PCIe/SSE2 (4.6.0 NVIDIA 446.14)
00:00:04.194 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:05.818 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:07.680 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.109 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.112 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.116 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.118 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.120 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.122 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.124 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.126 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.128 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.130 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.132 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.137 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.139 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.141 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.143 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.145 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.147 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.148 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.150 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.152 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.153 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.155 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.157 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.159 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.161 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.163 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.165 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.166 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.168 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.170 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.172 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.175 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.177 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.179 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.181 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.182 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.185 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.187 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.188 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.190 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.193 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.194 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.196 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.197 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.198 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.200 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.202 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.203 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.204 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.206 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.207 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.208 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.209 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.210 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.211 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.212 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.213 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.214 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.215 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.216 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.217 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.218 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.219 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.220 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.221 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.222 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.223 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.224 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.225 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.226 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.227 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.228 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.432 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.440 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.453 |W| HLE.GuestThread.15 KernelSvc PrintResult: SendSyncRequest64 returned error PortRemoteClosed.
00:00:08.493 |E| HLE.OsThread.7 Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: No valid channel configuration found!
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 61
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.SelectHardwareChannelCount(UInt32 targetChannelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 57
   at Ryujinx.Audio.Backends.CompatLayer.CompatLayerHardwareDeviceDriver.OpenDeviceSession(Direction direction, IVirtualMemoryManager memoryManager, SampleFormat sampleFormat, UInt32 sampleRate, UInt32 channelCount) in C:\projects\ryujinx\Ryujinx.Audio\Backends\CompatLayer\CompatLayerHardwareDeviceDriver.cs:line 116
   at Ryujinx.Audio.Integration.HardwareDeviceImpl..ctor(IHardwareDeviceDriver deviceDriver, UInt32 channelCount, UInt32 sampleRate) in C:\projects\ryujinx\Ryujinx.Audio\Integration\HardwareDeviceImpl.cs:line 35
   at Ryujinx.Audio.Renderer.Dsp.AudioProcessor.Start(IHardwareDeviceDriver deviceDriver) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Dsp\AudioProcessor.cs:line 87
   at Ryujinx.Audio.Renderer.Server.AudioRendererManager.StartLocked() in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 186
   at Ryujinx.Audio.Renderer.Server.AudioRendererManager.Register(AudioRenderSystem renderer) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 250
   at Ryujinx.Audio.Renderer.Server.AudioRendererManager.OpenAudioRenderer(AudioRenderSystem& renderer, IVirtualMemoryManager memoryManager, AudioRendererConfiguration& parameter, UInt64 appletResourceUserId, UInt64 workBufferAddress, UInt64 workBufferSize, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.Audio\Renderer\Server\AudioRendererManager.cs:line 296
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManager.OpenAudioRenderer(ServiceCtx context, IAudioRenderer& obj, AudioRendererConfiguration& parameter, UInt64 workBufferSize, UInt64 appletResourceUserId, KTransferMemory workBufferTransferMemory, UInt32 processHandle) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManager.cs:line 38
   at Ryujinx.HLE.HOS.Services.Audio.AudioRendererManagerServer.OpenAudioRenderer(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Audio\AudioRendererManagerServer.cs:line 37
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallHipcMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 122
   at Ryujinx.HLE.HOS.Services.ServerBase.Process(Int32 serverSessionHandle, UInt64 recvListAddr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 212
   at Ryujinx.HLE.HOS.Services.ServerBase.ServerLoop() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\ServerBase.cs:line 133
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1038
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

### Environment?

- Ryujinx version: 1.0.6898</br>
- Game version: 1.1.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-8700k
  - GPU: Nvidia GTX1080
  - RAM: 16GB

### Additional context?

Thanks for your amazing work. Always appreciate bug fixes and new updates! :)

**Comment by EmulationFanatic** [comment] 2021-05-31 18:20
Use either OpenAL or SDL2 audio backends to work around this. Closing as duplicate of https://github.com/Ryujinx/Ryujinx/issues/2270

**Closed by EmulationFanatic** 2021-05-31 18:20 UTC
