### ISSUE TITLE
[Bug] Indiscriminate deletion of files in install directory

### ISSUE THREAD

**Issue by MiniHerc** [Ryujinx/Ryujinx#4757] opened 2023-05-02 02:09 UTC
### Description of the issue

I just downloaded the project today to play a certain new title. I had copied the xci file directly to the ryujinx directory. It asked to install an update and the update deleted the xci file from the install directory.

### Reproduction steps

Copy a game xci file into the ryujinx executable directory, then have an auto update happen and watch the xci file be deleted.

### Log file

[Ryujinx_1.1.743_2023-05-01_21-02-13.log](https://github.com/Ryujinx/Ryujinx/files/11369166/Ryujinx_1.1.743_2023-05-01_21-02-13.log)

### OS

Windows 10

### Ryujinx version

1.1.743

### Additional context?

Fortunately I had a backup, but I am not very happy about this. Why is the updater deleting files not related to the program?

**Comment by gdkchan** [comment] 2023-05-02 02:13
This is a duplicate of #3102 though this issue is a subset of it and has a more descriptive title.

**Comment by Foul-Tarnished** [comment] 2023-05-10 10:17
As a workaround for ReShade, you can make all files as "hidden" in the (NTFS) files properties

**Closed** 2023-06-05 12:19 UTC
Labels: bug, miscellaneous
