### ISSUE TITLE
sockets: Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31 is not implemented

### ISSUE THREAD

**Issue by EmulationFanatic** [Ryujinx/Ryujinx#1803] opened 2020-12-11 15:28 UTC
### What service call is missing?

Ryujinx.HLE.HOS.Services.Sockets.Bsd.IClient: 31

There is no information for this service on Switchbrew or ReSwitched.

## Service description:
```
N/A
```

## Required by:

https://github.com/Ryujinx/Ryujinx-Games-List/issues/2966

**Comment by AcK77** [comment] 2020-12-14 21:02
duplicate of https://github.com/Ryujinx/Ryujinx/issues/1440

**Closed by AcK77** 2020-12-14 21:02 UTC
Labels: not-implemented, service:sockets
