### ISSUE TITLE
[Feature Request] Screenshots

### ISSUE THREAD

**Issue by juanestragon** [Ryujinx/Ryujinx#5125] opened 2023-05-28 12:27 UTC
### Overview

It should be a button to be able to take an screenshot

### Smaller details

As the switch controller has, these button will make an screenshot and save it in the nand or sd.

### Nature of request

I need a it for a secondary quest in Zelda TOTK

### Why would this feature be useful?

In some games you need to take screenshots for do some quests

**Comment by MutantAura** [comment] 2023-05-28 13:31
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3423 and https://github.com/Ryujinx/Ryujinx/issues/3875

**Closed by MutantAura** 2023-05-28 13:31 UTC
