### ISSUE TITLE
[Feature Request] Add the function to individually configure graphics options and other settings for each game in the simulator

### ISSUE THREAD

**Issue by hmglife** [Ryujinx/Ryujinx#4811] opened 2023-05-05 07:42 UTC
### Overview

Just like how Yuzu emulator allows for individual configuration of properties for each game.

### Smaller details

I think that implementing independent graphics configurations for each game directly would be a feasible solution, and should not be too complicated.

### Nature of request

n/a

### Why would this feature be useful?

With this feature added, I believe Ryujinx will become the most powerful emulator in terms of functionality, especially when running both new and old games without the need to modify graphics configurations each time in the settings.

**Comment by Neristee** [comment] 2023-05-05 07:51
Searching "individual" in the list of issues already opened leads me to this https://github.com/Ryujinx/Ryujinx/issues/1796 which is eerily close to what you're asking.

**Comment by OldManKain** [comment] 2023-05-05 07:58
Closing as duplicate of #1796 and already has a PR open in the works #4625.

**Closed by OldManKain** 2023-05-05 07:58 UTC
