### ISSUE TITLE
[Bug] TOTK is unable to exit or stop emulation normally

### ISSUE THREAD

**Issue by 2584191127** [Ryujinx/Ryujinx#5045] opened 2023-05-22 09:36 UTC
### Description of the issue

![issue](https://github.com/Ryujinx/Ryujinx/assets/78305714/c241a6a1-7d93-499f-b41a-b25ca47c75a4)
when click 'exist' or 'stop emulation', Ryujinx has no response.

### Reproduction steps

1. Open game ‘The Legend of Zelda: Tears of the Kingdom’
2. play
3. click 'exit' or 'stop emulation'

### Log file

[Ryujinx_1.1.815_2023-05-22_15-47-01.log](https://github.com/Ryujinx/Ryujinx/files/11529495/Ryujinx_1.1.815_2023-05-22_15-47-01.log)

### OS

win10

### Ryujinx version

1.1.815

### Game version

1.1.1

### CPU

AMD Ryzen 7 4800U with Radeon Graphics

### GPU

AMD Radeon(TM) Graphics

### RAM

16GB

### List of applied mods

no

**Comment by maioro** [comment] 2023-05-23 08:01
Same issue here

TOTK-v1.1.1 in 1.1.818
13600K+GTX970 Vulkan +32GB RAM 
no mod 
win10 22h2
![TOTK](https://github.com/Ryujinx/Ryujinx/assets/60441085/aca023be-ab1c-4476-b455-b924fc3105ae)

**Comment by LoneBoco** [comment] 2023-05-25 14:39
The program gets stuck here:
https://github.com/Ryujinx/Ryujinx/blob/274af65f69f25c88c50b626b785a33aade9a1b63/src/Ryujinx.Graphics.GAL/Multithreading/ThreadedRenderer.cs#L173-L179

It tries to dispose of the graphics pipeline and it starts to dispose of the textures, but it looks like the emulator assumes that when you dispose of a texture there will eventually be a next rendered frame.  We hit this while loop that is stalling for the next frame that never comes.

**Comment by gdkchan** [comment] 2023-05-31 21:48
Duplicate of #2863, fixed by #5144.

**Closed by gdkchan** 2023-05-31 21:48 UTC
Labels: bug
