### ISSUE TITLE
Xenoblade Chronicles 3 crash when opening menu after playing for a while (+incorrectly rendered grass [black models] )

### ISSUE THREAD

**Issue by Fonkay** [Ryujinx/Ryujinx#3617] opened 2022-08-22 17:43 UTC
### What's the issue you encountered?

Tried playing Xenoblade 3 on Vulkan as i've been waiting quite long for the crash to be finally fixed, and i didn't have any problems other than low framerate and a few incorrectly rendered grass models. I opened the menu not long after i launched the game, no problems. then went running around for a while, didn't use the menu, then opened it after about 20 minutes of playing and the emulator crashed, with my driver reporting an error. thought it might be my gpu so i tried it on Yuzu but it didn't happen there.
This same crash happened both times i tried to play on Ryujinx.

### How can the issue be reproduced?

Uh honestly i have no idea how i even did it, so no clue, but i provided images of my settings if it helps any

### Log file

[Ryujinx_1.1.227_2022-08-21_17-07-04.log](https://github.com/Ryujinx/Ryujinx/files/9396420/Ryujinx_1.1.227_2022-08-21_17-07-04.log)

### Environment?

- Ryujinx version: 1.1.227
- Game version: 1.0.0
- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 3 1200
  - GPU: AMD RX 480
  - RAM: 8GB
- Applied Mods : no

### Additional context?

![7](https://user-images.githubusercontent.com/105563549/185984625-94bcbd75-f1b4-472c-97bc-c48787757121.png)
![8](https://user-images.githubusercontent.com/105563549/185984690-d9586795-3cc7-4251-8fe5-4be784b0c0aa.png)

**Comment by gdkchan** [comment] 2022-08-22 20:09
That looks like a duplicate of #3530, #3550 and #3518.

**Comment by Fonkay** [comment] 2022-08-22 20:13
oh sorry i didn't see it has been reported already

**Comment by gdkchan** [comment] 2022-08-22 20:45
Closing as duplicate. If you have something new to add, please comment on the existing issues.

**Closed by gdkchan** 2022-08-22 20:45 UTC
