### ISSUE TITLE
SPB.Graphics.Exceptions.ContextException: CreateContext() failed.

### ISSUE THREAD

**Issue by DemonicSavage** [Ryujinx/Ryujinx#2220] opened 2021-04-17 15:21 UTC
### What's the issue you encountered?

I cannot boot any games.

### How can the issue be reproduced?

Open Ryujinx
Double-click a game

### Log file

[Ryujinx_1.0.0-dirty_2021-04-17_12-15-19.log](https://github.com/Ryujinx/Ryujinx/files/6329496/Ryujinx_1.0.0-dirty_2021-04-17_12-15-19.log)

### Environment?

- Ryujinx version: The latest ryujinx-git AUR build as of this post.</br>
- Game version: N/A</br>
- System Specs:
  - OS: *Arch Linux*
  - CPU: *Ryzen 5 5600X*
  - GPU: *NVIDIA 1050 Ti*
  - RAM: *16 GiB*
- Applied Mods : No
- 
### Additional context?

N/A

**Comment by nishantc1527** [comment] 2021-05-15 19:44
I am also getting this issue. My operating system is Arch Linux, my CPU is AMD Ryzen 5 5600X, my GPU is AMD ATI Radeon RX, and my RAM is 16 GiB.

**Comment by kedras** [comment] 2021-05-16 06:32
Confirming the same here.
System Specs:
OS: opensuse Leap 15.2
CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
GPU: NVIDIA TU117GLM / Intel CoffeeLake-H GT2 [UHD Graphics 630] (tested both)
RAM: 32 GiB

**Comment by AcK77** [comment] 2021-05-16 06:48
What’s your GLX version?

**Comment by kedras** [comment] 2021-05-16 07:20
GLX version: 1.4

**Comment by kedras** [comment] 2021-05-28 09:33
> Confirming the same here.
> System Specs:
> OS: opensuse Leap 15.2
> CPU: Intel(R) Core(TM) i7-9850H CPU @ 2.60GHz
> GPU: NVIDIA TU117GLM / Intel CoffeeLake-H GT2 [UHD Graphics 630] (tested both)
> RAM: 32 GiB

ok, correction from my side - works NVIDIA card in the end, so only remains for the Intel one

**Comment by marius851000** [comment] 2022-01-25 18:47
Did some bisection. On my side (working with AMD's IGPU, but not with NVidia DGPU), the error message change on 6cb22c9d38622225f9f787f483bd73369774cf77. This revision have the same error as shown here, but the previous commit instead crash with

```
(Ryujinx:45295): Gdk-ERROR **: 19:44:24.585: The program 'Ryujinx' received an X Window System error.
This probably reflects a bug in the program.
The error was 'GLXBadDrawable'.
  (Details: serial 11560 error_code 160 request_code 152 (GLX) minor_code 5)
  (Note to programmers: normally, X errors are reported asynchronously;
   that is, you will receive the error a while after causing it.
   To debug your program, run it with the GDK_SYNCHRONIZE environment
   variable to change this behavior. You can then get a meaningful
   backtrace from your debugger if you break on the gdk_x_error() function.)
```

This seems to be the same error as on https://github.com/Ryujinx/Ryujinx/issues/2112 . I also use a multi-gpu configuration.

**Comment by edisionnano** [comment] 2022-01-25 18:52
> Did some bisection. On my side (working with AMD's IGPU, but not with NVidia DGPU), the error message change on [6cb22c9](https://github.com/Ryujinx/Ryujinx/commit/6cb22c9d38622225f9f787f483bd73369774cf77). This revision have the same error as shown here, but the previous commit instead crash with
> 
> ```
> (Ryujinx:45295): Gdk-ERROR **: 19:44:24.585: The program 'Ryujinx' received an X Window System error.
> This probably reflects a bug in the program.
> The error was 'GLXBadDrawable'.
>   (Details: serial 11560 error_code 160 request_code 152 (GLX) minor_code 5)
>   (Note to programmers: normally, X errors are reported asynchronously;
>    that is, you will receive the error a while after causing it.
>    To debug your program, run it with the GDK_SYNCHRONIZE environment
>    variable to change this behavior. You can then get a meaningful
>    backtrace from your debugger if you break on the gdk_x_error() function.)
> ```
> 
> This seems to be the same error as on #2112 . I also use a multi-gpu configuration.

Are you using prime-run?

**Comment by marius851000** [comment] 2022-01-26 10:23
> > Did some bisection. On my side (working with AMD's IGPU, but not with NVidia DGPU), the error message change on [6cb22c9](https://github.com/Ryujinx/Ryujinx/commit/6cb22c9d38622225f9f787f483bd73369774cf77). This revision have the same error as shown here, but the previous commit instead crash with
> > ```
> > (Ryujinx:45295): Gdk-ERROR **: 19:44:24.585: The program 'Ryujinx' received an X Window System error.
> > This probably reflects a bug in the program.
> > The error was 'GLXBadDrawable'.
> >   (Details: serial 11560 error_code 160 request_code 152 (GLX) minor_code 5)
> >   (Note to programmers: normally, X errors are reported asynchronously;
> >    that is, you will receive the error a while after causing it.
> >    To debug your program, run it with the GDK_SYNCHRONIZE environment
> >    variable to change this behavior. You can then get a meaningful
> >    backtrace from your debugger if you break on the gdk_x_error() function.)
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This seems to be the same error as on #2112 . I also use a multi-gpu configuration.
> 
> Are you using prime-run?

I'm using nvidia-offload, coming from ``nixos-hardware``. It's a simple bash script

```
#!/nix/store/pbfraw351mksnkp2ni9c4rkc9cpp89iv-bash-5.1-p12/bin/bash
export __NV_PRIME_RENDER_OFFLOAD=1
export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
export __GLX_VENDOR_LIBRARY_NAME=nvidia
export __VK_LAYER_NV_optimus=NVIDIA_only
exec -a "$0" "$@"
```

**Comment by edisionnano** [comment] 2022-01-26 11:43
> > > Did some bisection. On my side (working with AMD's IGPU, but not with NVidia DGPU), the error message change on [6cb22c9](https://github.com/Ryujinx/Ryujinx/commit/6cb22c9d38622225f9f787f483bd73369774cf77). This revision have the same error as shown here, but the previous commit instead crash with
> > > ```
> > > (Ryujinx:45295): Gdk-ERROR **: 19:44:24.585: The program 'Ryujinx' received an X Window System error.
> > > This probably reflects a bug in the program.
> > > The error was 'GLXBadDrawable'.
> > >   (Details: serial 11560 error_code 160 request_code 152 (GLX) minor_code 5)
> > >   (Note to programmers: normally, X errors are reported asynchronously;
> > >    that is, you will receive the error a while after causing it.
> > >    To debug your program, run it with the GDK_SYNCHRONIZE environment
> > >    variable to change this behavior. You can then get a meaningful
> > >    backtrace from your debugger if you break on the gdk_x_error() function.)
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > This seems to be the same error as on #2112 . I also use a multi-gpu configuration.
> > 
> > 
> > Are you using prime-run?
> 
> I'm using nvidia-offload, coming from `nixos-hardware`. It's a simple bash script
> 
> ```
> #!/nix/store/pbfraw351mksnkp2ni9c4rkc9cpp89iv-bash-5.1-p12/bin/bash
> export __NV_PRIME_RENDER_OFFLOAD=1
> export __NV_PRIME_RENDER_OFFLOAD_PROVIDER=NVIDIA-G0
> export __GLX_VENDOR_LIBRARY_NAME=nvidia
> export __VK_LAYER_NV_optimus=NVIDIA_only
> exec -a "$0" "$@"
> ```

Same thing then, check my answer on #2112

**Comment by MetrosexualGarbodor** [comment] 2022-02-06 23:03
Duplicate of #2112.

**Closed by MetrosexualGarbodor** 2022-02-06 23:03 UTC
Labels: bug, gpu

**Comment by joezhouchenye** [comment] 2023-05-17 11:57
For me, switching from OpenGL to Vulkan works.
