### ISSUE TITLE
missing vtg instruction for : LOST DREAM  STARS and other

### ISSUE THREAD

**Issue by elcorsico** [Ryujinx/Ryujinx#4333] opened 2023-01-22 17:51 UTC
impacted by a missing vote vtg instruction

game : test 

LOST DREAM STARS

https://discord.com/channels/410208534861447168/410208534861447170/1066717715106119710

**Comment by MetrosexualGarbodor** [comment] 2023-01-22 17:52
Duplicate of #2794

**Closed by MetrosexualGarbodor** 2023-01-22 17:52 UTC
