### ISSUE TITLE
Games won't launch if the DLC list is invalidated

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1735] opened 2020-11-20 13:16 UTC
The problem right now is that when DLCs of a game get deleted the config file doesn't let the game run. Only way to fix it is to delete the DLC config file in ryujinx folder.

**Comment by AcK77** [comment] 2020-11-25 00:04
Duplicate of #1366

**Closed by AcK77** 2020-11-25 00:04 UTC
