### ISSUE TITLE
Lag every time i connect Nintendo Joycon

### ISSUE THREAD

**Issue by MagiusCHE** [Ryujinx/Ryujinx#2071] opened 2021-02-28 17:39 UTC
### What's the issue you encountered?
Starting every game without Nintendo joycons (via bluetooth) all works correctly and smothly.
If i just connect one Joycon games become super laggy from 60 to 10 fps every game.
If i just disconnect all joycons the game returns normally.

### How can the issue be reproduced?
Just connect a Joycon.

I've tried without success:
- Connect and disconnects joycons in game.
- Connect and disconnects joycons and restart game or Ryujinx.
- Restart pc.

Just to know: if i use another emulator it works without lag.

### Log file
[Ryujinx_1.0.0-dirty_2021-02-28_18-12-38.zip](https://github.com/Ryujinx/Ryujinx/files/6057381/Ryujinx_1.0.0-dirty_2021-02-28_18-12-38.zip)

### Environment?

- Ryujinx version: 1.0.0.dirty compiled just via github</br>
- System Specs:
  - OS: Linux-Manjaro
  - CPU: i5-7500
  - GPU: NVIDIA 980
  - RAM: 32gb
- Applied Mods : No

### Additional context?

n/a

Thx in advance. I hope my report will help someone.

**Comment by AcK77** [comment] 2021-04-11 19:57
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Closed** 2021-04-14 10:28 UTC

**Comment by MagiusCHE** [comment] 2021-04-14 16:15
Sorry but i cant test at the moment couse i had no more available joycons!!! (my children destroyed them).
Eventually when i will have new ones i will try it.

Thx for all your works!!! (and for the patience)
