### ISSUE TITLE
[Bug]Simulator automatic upgrade bug

### ISSUE THREAD

**Issue by taoyuancun123** [Ryujinx/Ryujinx#4847] opened 2023-05-07 21:32 UTC
### Description of the issue

When the emulator is automatically upgraded, if the game is just loading and the loading is successful, the upgrade process will be interrupted, for example, the original file is named old file, but the new file is not successfully written.
Older versions don't seem to have this problem, it's a recent one.

### Reproduction steps

Download any old version of the emulator. At this time, automatic update will be triggered. Click on automatic update. At the same time, click on any game to load. When the game is loaded successfully, the automatic update process will be interrupted.

### Log file

no log file

### OS

windows 11

### Ryujinx version

1.1.764

### Game version

1.0.0

**Comment by MutantAura** [comment] 2023-05-07 21:34
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3801

**Closed by MutantAura** 2023-05-07 21:34 UTC
Labels: bug

**Comment by taoyuancun123** [comment] 2023-05-07 21:45
It doesn't seem to be the same problem to #3801 , this problem just appeared recently. Didn't have this problem a few days ago.
The steps are to click on an old version, click to confirm automatic update, and click to start the game at the same time. In the version a few days ago, it can be updated normally.

Still, it's up to you to judge. Thank you for your work.
