### ISSUE TITLE
Feature Request: Per game settings configuration

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#1826] opened 2020-12-18 05:34 UTC
Would be nice if there would be a way to enable or disable/change certain things for certain games like set a specific resolution scaller, enable/disable PPTC, Vsync On/Off, Handheld/Docked mode, Start in Fullscreen On/Off, OpenAL/SoundIO etc per game basis, It mostly would be good for resolution scaling since not all games are equality heavy and the user needs to constantly change resolutions and restart the emulator. Some games audio works better on OpenAL and some on SoundIO, Docked/Portable for some games that run better in Portable mode, PPTC breaks some games etc.

**Comment by choppymaster** [comment] 2020-12-18 07:52
Duplicate of #1796

**Closed** 2020-12-18 11:09 UTC

**Comment by jucasleiva** [comment] 2024-09-07 21:09
That would be great, why haven't they done it yet?
