### ISSUE TITLE
[Bug] Remove unneeded firmware and production key requirements

### ISSUE THREAD

**Issue by davidhedlund** [Ryujinx/Ryujinx#7367] opened 2024-09-27 02:39 UTC
### Issue

![image](https://github.com/user-attachments/assets/841e9659-09b1-4b74-b4f9-04e58e564938)

The above dialog box pops up if the prod.keys are not installed, but it does not prevent you from playing homebrew games.

Demonstration that homebrew games work without the firmware and the production key:
* Download https://github.com/headshot2017/supertux-switch/releases/download/v0.1.1b/supertux-switch.zip
* Extract supertux-switch.zip
* Copy the "switch" directory to Ryujinx's "sdcard" directory.
* Start Ryujinx 
* File -> Load fie... -> supertux-switch.nro -- It will start and you will be able to play it.

![image](https://github.com/user-attachments/assets/caa1cc4d-e2ec-483a-a38b-d95d68e69bda)

### Solution
- Remove the prodkey dialog box (**Ryujink Error (RYU-0001)**).

Note: The dialog box that pops up if the firmware is not installed do not show up when you click on homebrew games, so it can be kept.

### Issue
> "_Your prod.keys and either your [dumped firmware](https://github.com/Ryujinx/Ryujinx/wiki/Firmware-Dumping-Guide) or game cartridge untrimmed XCI_" - https://github.com/Ryujinx/Ryujinx/wiki/Ryujinx-Setup-&-Configuration-Guide#system-requirements

### Solution
- Modify the text to inform users that homebrew games can be played without prod.keys and firmware.

## Benefits
- Improves user experience for those interested in homebrew development and applications
- Reduces potential legal risks by not encouraging users to seek out copyrighted Nintendo files unnecessarily
- Aligns with ethical considerations by promoting the use of freely available software
- Furthers the developer's efforts to safeguard the project from legal issues

By implementing these changes, Ryujinx can continue to differentiate itself from its predecessor and demonstrate an ongoing commitment to ethical and legal emulation practices, particularly in the realm of homebrew applications.

**Comment by piplup55** [comment] 2024-09-27 03:46
- Duplicate of #6519 
- some homebrew also require firmware
- the wiki could be updated to add a note about homebrew

**Closed by piplup55** 2024-09-27 03:46 UTC
Labels: bug

**Comment by davidhedlund** [comment] 2024-09-27 03:59
> * Duplicate of [[Feature Request] Option to not show prod.keys warning (RYU-0001) again #6519](https://github.com/Ryujinx/Ryujinx/issues/6519)
> 
>     * some homebrew also require firmware
> 
>     * the wiki could be updated to add a note about homebrew

Thank you for giving me the issue link. I merged the issue to it.
