### ISSUE TITLE
[Bug] Save Editing causes infinite saving in game (TOTK)

### ISSUE THREAD

**Issue by Sensei412** [Ryujinx/Ryujinx#5155] opened 2023-05-30 00:15 UTC
### Description of the issue

I haven't experienced or tried this with other games but with TOTK, if I use [this](https://www.marcrobledo.com/savegame-editors/zelda-totk/) save editor, after loading the save I get a infinite saving thing with the loading sign going on forever. Sometimes I delete the '1' save folder and lock files and it works, but now even that rarely works so I just put the save into yuzu save it there and transfer it back to Ryu.

### Reproduction steps

edit with [save editor](https://www.marcrobledo.com/savegame-editors/zelda-totk/)
load save
save again.

### Log file

unable to recreate issue but heres the latest log
[Ryujinx_1.1.841_2023-05-29_16-38-07.log](https://github.com/Ryujinx/Ryujinx/files/11594622/Ryujinx_1.1.841_2023-05-29_16-38-07.log)

### OS

Windows 10

### Ryujinx version

1.1.841

### Game version

1.1.2

**Comment by gdkchan** [comment] 2023-05-30 00:16
Duplicate of #5024.

**Closed by gdkchan** 2023-05-30 00:16 UTC
Labels: bug
