### ISSUE TITLE
[Bug] Glowing textures in TotK

### ISSUE THREAD

**Issue by sulapse** [Ryujinx/Ryujinx#5111] opened 2023-05-26 18:07 UTC
### Description of the issue

Some textures are brightly glowing white, I'll let the screenshots speak for themselves.

Things I've tested to try fix the issue:
* Full reinstall of Ryujinx
* Disable all mods
* Tweaked and played with settings

It couldn't possibly be the firmware, game file nor update file as these files are working perfectly fine on my desktop on Yuzu.

It's very possible this post is a duplicate but I couldn't find anyone with the exact same problem - Or a issue report with a serious answer whether this is being worked on or not.

<img width="1392" alt="Screenshot 2023-05-26 at 20 01 23" src="https://github.com/Ryujinx/Ryujinx/assets/20544749/cb000633-9488-4e19-9f4e-eefde40e11b5">
<img width="1273" alt="Screenshot 2023-05-26 at 20 00 07" src="https://github.com/Ryujinx/Ryujinx/assets/20544749/0252d5ae-9ee9-427d-82f5-0691b468ab15">
<img width="1275" alt="Screenshot 2023-05-26 at 19 59 43" src="https://github.com/Ryujinx/Ryujinx/assets/20544749/58ced295-8297-4e83-9590-1350a73505c1">

### Reproduction steps

1. Start game
2. Equip Hylian Armor
Literally don't have to do anything, textures are glowing the second the game is loaded.

### Log file

[Ryujinx_1.1.0+2440e81_2023-05-26_19-57-20.log](https://github.com/Ryujinx/Ryujinx/files/11578665/Ryujinx_1.1.0%2B2440e81_2023-05-26_19-57-20.log)

### OS

MacOS 13.4

### Ryujinx version

Ehh.. 1.1.0+2440e81

### Game version

1.1.0

### CPU

Apple M1 Pro

### GPU

Apple M1 Pro

### RAM

16GB

### List of applied mods

None.

**Comment by MutantAura** [comment] 2023-05-26 18:09
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4949

**Closed by MutantAura** 2023-05-26 18:09 UTC
Labels: bug
