### ISSUE TITLE
IndexOutOfRangeException at TimeZone.ToCalendarTimeInternal

### ISSUE THREAD

**Issue by ruslang02** [Ryujinx/Ryujinx#765] opened 2019-09-07 16:22 UTC
### Description:
Crashes both on Linux and Windows, regardless of time specified or timezone installed
```
Emulation CurrentDomain_UnhandledException: Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZone.ToCalendarTimeInternal(TimeZoneRule rules, Int64 time, CalendarTimeInternal& calendarTime, CalendarAdditionalInfo& calendarAdditionalInfo) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Time\TimeZone\TimeZone.cs:line 1377
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZone.ToPosixTimeInternal(TimeZoneRule rules, CalendarTimeInternal calendarTime, Int64& posixTime) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Time\TimeZone\TimeZone.cs:line 1632
   at Ryujinx.HLE.HOS.Services.Time.TimeZone.TimeZone.ToPosixTime(TimeZoneRule rules, CalendarTime calendarTime, Int64& posixTime) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Time\TimeZone\TimeZone.cs:line 1736
   at Ryujinx.HLE.HOS.Services.Time.ITimeZoneService.ToPosixTime(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\Time\ITimeZoneService.cs:line 172
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Ryujinx.HLE.HOS.Services.IpcService.CallMethod(ServiceCtx context) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Services\IpcService.cs:line 121
   at Ryujinx.HLE.HOS.Ipc.IpcHandler.IpcCall(Switch device, KProcess process, IMemoryManager memory, KThread thread, KClientSession session, IpcMessage request, Int64 cmdPtr) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Ipc\IpcHandler.cs:line 37
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SvcHandler.ProcessIpcRequest(Object state) in C:\projects\ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SvcIpc.cs:line 140
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

### Required by:
Ryujinx/Ryujinx-Games-List#115

**Comment by Thog** [comment] 2019-09-07 17:19
I cannot reproduce this, can you upload your Ryujinx.log and tell us what version of the game you are running?

**Comment by ruslang02** [comment] 2019-09-07 21:03
Linux: [Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/3587033/Ryujinx.log)
Windows: [Ryujinx.log](https://github.com/Ryujinx/Ryujinx/files/3587034/Ryujinx.log)
I am sorry if I maybe missed something out...
NSP 1.0.2

**Comment by Thog** [comment] 2019-09-07 21:30
Found a way to reproduce thanks! I will try to fix that

**Comment by Thog** [comment] 2019-09-07 22:03
For reference:

This happens because you don't have the timezone archive installed on your system.

The game tries to load the "GMT" timezone but LoadTimeZoneRule fail at finding it as it's not defined on the C# time API.

The game then ignore the error returned by LoadTimeZoneRule and send uninitialized data to ToCalendarTime and the result of that is this crash.

**Comment by AcK77** [comment] 2019-10-08 16:29
Fixed in #783

**Closed by AcK77** 2019-10-08 16:29 UTC
Labels: bug, horizon

**Comment by lloydheyrosa** [comment] 2020-03-31 05:21
[Ryujinx_2020-03-31_13-13-15.log](https://github.com/Ryujinx/Ryujinx/files/4406880/Ryujinx_2020-03-31_13-13-15.log)

I have an error in starting the game

**Comment by HorrorTroll** [comment] 2020-03-31 06:03
This is not the page to asking for help. It only for developer making issue

Need for help, join discord: https://discord.gg/N2FmfVc
