### ISSUE TITLE
[Bug] BOTW hangs in opening cutscene on Mac

### ISSUE THREAD

**Issue by livni** [Ryujinx/Ryujinx#5309] opened 2023-06-14 16:06 UTC
### Description of the issue

TOTK works great on Mac. Running BOTW though doesn't work - in the initial cutscene when you load the game,  when Link hears "open your eyes" and the tiny light takes over the screen it just hangs. Reproduced on two different macs

### Reproduction steps

1. Add BOTW XCI on Mac
2. Run BOTW
3. See how it hangs on the initial cutscene

### Log file

[Ryujinx_1.1.891_2023-06-14_18-51-03.log](https://github.com/Ryujinx/Ryujinx/files/11748091/Ryujinx_1.1.891_2023-06-14_18-51-03.log)

### OS

macOS Ventura 13.4

### Ryujinx version

1.1.891

### Game version

1.6.0

### CPU

M1 Pro

### RAM

32GB

**Comment by gdkchan** [comment] 2023-06-14 19:30
Duplicate of #5219.

**Closed by gdkchan** 2023-06-14 19:30 UTC
Labels: bug

**Comment by livni** [comment] 2023-06-15 11:02
I can confirm that [unchecking the Hypervisor setting](https://ibb.co/pXtQRqg) allowed the game to continue beyond that point. Curious as to the implications of unchecking that setting though?

**Comment by gdkchan** [comment] 2023-06-15 18:45
> I can confirm that [unchecking the Hypervisor setting](https://ibb.co/pXtQRqg) allowed the game to continue beyond that point. Curious as to the implications of unchecking that setting though?

The implications is that it uses JIT instead of Hypervisor. JIT recompiles the code, Hypervisor runs it directly. So JIT is slower. Also JIT uses 16KB pages since Apple Silicon macOS does not support 4KB pages, which makes GPU emulation slower and introduces bugs in some games that doesn't happen with 4KB pages.
