### ISSUE TITLE
There needs to be a null check to warn users that they may not be using the supported discrete graphics chipset.

### ISSUE THREAD

**Issue by tommai78101** [Ryujinx/Ryujinx#109] opened 2018-04-28 16:56 UTC
**Version:** Latest master branch from the repository.
**Info:** No modifications were added to Ryujinx. I wouldn't even have the knowledge to do so.

**EDIT**: Ok, found out what's really going on. My computer has Nvidia Optimus, but it was not running correctly. Therefore, when running Ryujinx, it didn't switch to the correct context to use the discrete graphics chipset. It was using the integrated graphics chipset, and that did not support certain features for Ryujinx.

But still, because Ryujinx is assuming the hardware it is run on is capable of initializing the shaders, there is no null checking mechanism to make sure that it successfully initializes the shaders. I would like to propose that there should be a null check, and warn the user that they are not using the correct settings for their graphics chipset on their device.

-------

**Original post:**

This is the error message displayed when debugging in Visual Studio:

![image](https://user-images.githubusercontent.com/6444116/39398899-be6f5cea-4ae2-11e8-9e8c-aede11889c32.png)

It seemed `Shader.Handle`  was not initialized, as it is referencing 0x00000000. (I think there should be a null check somewhere, but I'm not sure if we're either going to run an assertion that Shader.Handle will always be defined, or we actually implement a null check for this.)

The homebrew I'm running is a fairly simple SDL2 application.  Here's the full source code:

```
#include <SDL2\SDL.h>
#include <switch.h>

int main(int argc, char* argv[]) {
	SDL_Init(SDL_INIT_EVERYTHING);
	SDL_Delay(3000);
	SDL_QuitSubSystem(SDL_INIT_EVERYTHING);
	return 0;
}
```

And here's the compilation build that causes the error:

[SDLSwitch.zip](https://github.com/gdkchan/Ryujinx/files/1957931/SDLSwitch.zip)

For some reasons, before calling on `OGLFrameBuffer.SetWindowSize()`, it never called on `OGLFrameBuffer.EnsureInitialized()` at all.

**Comment by AcK77** [comment] 2020-01-17 03:21
Since #789 is merged, this code don’t exist anymore.
Until someone should be able to find an equivalent issue and a way to reproduce it, I close the issue.

**Closed by AcK77** 2020-01-17 03:21 UTC
Labels: enhancement, gpu
