### ISSUE TITLE
[Feature Request] Mouse Panning

### ISSUE THREAD

**Issue by Colmines92** [Ryujinx/Ryujinx#2857] opened 2021-11-19 01:11 UTC
#### Overview:
- Mouse Panning. So you can control the camera with the mouse, like yuzu does.

#### Smaller Details: 
- N/A

#### Nature of Request:  
- Addition
  - Mouse Panning feature

### Why would this feature be useful?
It will be very useful when playing with Keyboard & Mouse.

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 14:16
Duplicate of #2063.

**Closed by MetrosexualGarbodor** 2022-02-11 14:16 UTC
Labels: enhancement, input
