### ISSUE TITLE
mario tennis distorted audio

### ISSUE THREAD

**Issue by A-w-x** [Ryujinx/Ryujinx#2389] opened 2021-06-22 10:28 UTC
### What's the issue you encountered?
distorted audio output in game
game is full speed tho

### How can the issue be reproduced?
play a match

tested sdl2 and openAL

### Log file
[Ryujinx_1.0.6917_2021-06-22_14-16-32.log](https://github.com/Ryujinx/Ryujinx/files/6693371/Ryujinx_1.0.6917_2021-06-22_14-16-32.log)

### Environment?

- Ryujinx version: 1.0.6917
- Game version: 3.1.0
- System Specs:
  - OS: archlinux (mesa git)
  - CPU: 1165g7
  - GPU: iris xe
  - RAM: 16
- Applied Mods : no

**Comment by Thog** [comment] 2022-01-23 20:54
Cannot reproduce.

**Comment by Shahil-Ayato** [comment] 2022-02-25 08:02
This is potentially fixed by #3129

**Comment by A-w-x** [comment] 2022-03-16 17:12
> Cannot reproduce.

> This is potentially fixed by #3129

nope, i still get solid 30fps but distorted audio in some cases, or anyway there is some weird noise

here is my save, load and select adventure, than start the match, a dialog will appear and audio is distorted

running latest ryu version as of now
game 3.1.0

[mt-save.zip](https://github.com/Ryujinx/Ryujinx/files/8266742/mt-save.zip)

**Comment by A-w-x** [comment] 2022-06-11 14:27
here is what i hear, game is full speed

https://user-images.githubusercontent.com/80461138/173191959-c50beae5-476d-42d1-ac20-a9ac4c3cee73.mp4

**Comment by EmulationFanatic** [comment] 2022-09-08 17:48
Please report game-specific issues on the applicable entry in the [game compatibility list.](https://github.com/Ryujinx/Ryujinx-Games-List/issues) Thanks!

**Closed by EmulationFanatic** 2022-09-08 17:48 UTC
Labels: bug, audio
