### ISSUE TITLE
Animal Crossing New Horizon v2.0 crashing on launch (New)

### ISSUE THREAD

**Issue by LB7333** [Ryujinx/Ryujinx#2824] opened 2021-11-07 12:57 UTC
### What's the issue you encountered?

I have the same issue (first time playing here) I;ve ensured the game is up to date with the latest dlc 2.0+ Key, I have also ensured that "Ignore Missing Services" is checked and the game still crashes after the first 2-3 seconds of the first ever cutscene.

I have attached the log file for info, hoping someone can help :S

### How can the issue be reproduced?

When starting the game, the island and palmtree logo starts and loks like its loading (moving), then the first cut scene starts where its the nook logo and then the game freezes and crashes.

### Log file

[Ryujinx_1.0.7098_2021-11-07_12-49-58.log](https://github.com/Ryujinx/Ryujinx/files/7492272/Ryujinx_1.0.7098_2021-11-07_12-49-58.log)

### Environment?

- Ryujinx version: 13.0.0
- Game version: 2.0.0 + Housing DLC

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 5 5600X 6-Core
  - GPU: AMD Radeon RX 6700 XT
  - RAM: 16
- Applied Mods : None

**Comment by gdkchan** [comment] 2021-11-07 22:25
Duplicate of #2453.

**Closed by gdkchan** 2021-11-07 22:25 UTC
