### ISSUE TITLE
Save file corruption in Pokemon Sword (Linux)

### ISSUE THREAD

**Issue by C1fer** [Ryujinx/Ryujinx#3024] opened 2022-01-22 13:39 UTC
### What's the issue you encountered?
If there's a save file present in Pokemon Sword's save  directory, launching the game always results in the screen seen below.

![Pkmn Sword Save Corruption](https://user-images.githubusercontent.com/41005657/150640584-0f0c2392-be7f-446d-bad8-925c2e01fa1f.png)

### How can the issue be reproduced?

1. Launch the game without a save
2. Save in game
3. Close the emulator
4. Launch the game again

**Alternatively:**

1. Copy a save file to the game's user save directory
2. Launch the game.

### Log file

[Ryujinx_1.0.0+9e1316e_2022-01-22_09-15-13.log](https://github.com/Ryujinx/Ryujinx/files/7918417/Ryujinx_1.0.0%2B9e1316e_2022-01-22_09-15-13.log)

### Environment?

- Ryujinx version: 1.0.7181.</br>
- Game version: 1.3.2</br>
- System Specs:
  - OS: Arch Linux
  - CPU: i5 10400F
  - GPU: RX 480 4GB
  - RAM: 16GB
- Applied Mods : No
### Additional context?
I'm not sure, but it seems to only happen while running the emulator under linux. Windows doesn't seem to have this issue.

**Comment by ghalib5000** [comment] 2022-01-22 13:52
having the same issue, really want to play it on linux cause i have amd gpu...

**Comment by greyryan** [comment] 2022-01-22 18:09
the issue also in Pokémon Legends Arceus. the same Save file is available under windows but corrupted in linux(Manjaro)

**Comment by gdkchan** [comment] 2022-01-22 20:26
Have you tried creating a new user profile and starting/saving the game with the new profile?

**Comment by C1fer** [comment] 2022-01-22 21:41
Yes, just tried that. On a new profile, you can save and later load the save file, but only if you don't close the emulator. Stopping emulation and relaunching the game lets you load the save just fine, but once you close the app, it won't be able to load it again.

I made a backup of a save file (which was working fine when using Stop Emulation) and tried loading it into pkhex to see if it was corrupted. Pkhex couldn't load the file and marked it as corrupted.

**Comment by CeledonianError** [comment] 2022-01-23 01:37
Hi! Popping in to say I'm saving what sounds to be the same issue (saves getting corrupted after restarting Ryujinx), albeit with Legends: Arceus. I've tried backing up and replacing the save data (tried just main and everything in the parent folder) upon restart, and the issue persists. I've heard you can use saves from Yuzu or Ryujinx with the other, so I've also tried taking a working save from Yuzu and putting it in Ryujinx: save corrupted. Took the backed up, should-be-working save from Ryujinx and put it in Yuzu: save corrupted.

Environment:
Ryujinx 1.1.4
Linux Mint 20.2, kernel 5.13.0-22
Core i5-9300H
GTX 1650 Mobile
16GB of RAM

Log:
[Ryujinx_1.1.4_2022-01-22_20-09-02.log](https://github.com/Ryujinx/Ryujinx/files/7919580/Ryujinx_1.1.4_2022-01-22_20-09-02.log)

**Comment by yoursred** [comment] 2022-01-23 03:57
I'm experiencing something on a certain game that for sure doesn't exist. Running on linux too.

**Comment by Sh4kE** [comment] 2022-01-23 08:37
I have exactly the same behaviour!

## Environment
Ryujinx version: (own build from git: r1967.646d4dd5c-1)
System Specs:
    OS: Arch Linux (Manjaro 21.2.1 Qonos)
    CPU: AMD Ryzen 5 5600X
    GPU: GeForce RTX 3070
    RAM: 16GB
Applied Mods : No

**Comment by yoursred** [comment] 2022-01-23 08:39
> I have exactly the same behaviour!
> 
> 
> 
> ## Environment
> 
> Ryujinx version: (own build from git: r1967.646d4dd5c-1)
> 
> System Specs:
> 
>     OS: Arch Linux (Manjaro 21.2.1 Qonos)
> 
>     CPU: AMD Ryzen 5 5600X
> 
>     GPU: GeForce RTX 3070
> 
>     RAM: 16GB
> 
> Applied Mods : No
> 
> 

Too bad my comment was deleted, thanks Nintendo.

**Comment by A-w-x** [comment] 2022-01-23 09:47
duplicate #2805 

you can play the game if you create a new save **from** ryujinx, but this is not a solution ofc.

the problem is that ryujinx always creates a save that is a few kb smaller than a real save.
if you import a real save from switch, you get that error.

**Comment by C1fer** [comment] 2022-01-23 13:27
Creating a new save from Ryujinx only works if you don't close the emulator. Once it tries to load the save after a relaunch of the application, the file will be corrupted and won't work.

**Comment by C1fer** [comment] 2022-01-23 14:12
I just recorded a video of the issue, reproducing it step by step. 

[Link to video](https://www.youtube.com/watch?v=2palpi_DhKo)

**Comment by CeledonianError** [comment] 2022-01-23 17:57
I too am having the same issue. I've tried:
- Importing a working save from Yuzu
- Backing up a should-be-working save both while Ryujinx is running and after closing
- Backing up the entire parent directory while Ryujinx is running
- Backing up the entirety of ~/.config/Ryujinx + the "publish" folder I'm running Ryujinx from while Ryujinx is running
- Taking the Ryujinx save and using it with Yuzu
- Only letting the same auto-save
- Probably some other variations that I can't remember off the top of my head
All to no avail.

Environment:
- Ryujinx 1.1.4
- Linux Mint 20.2, kernel 5.13.0-22
- Core i5-9300H
- GTX 1650 Mobile/Max-Q
- 16GB of RAM

**Comment by yoursred** [comment] 2022-01-23 17:59
I suspect there’s a synchronization issue or something along those lines,
the save files have the correct feader for the game.

**Comment by C1fer** [comment] 2022-01-23 18:02
> duplicate #2805
> 
> you can play the game if you create a new save **from** ryujinx, but this is not a solution ofc.
> 
> the problem is that ryujinx always creates a save that is a few kb smaller than a real save. if you import a real save from switch, you get that error.

Could the difference in bytes be the issue? I loaded both a switch/yuzu save and a ryu one in a Hex editor, and the savefile made by ryu seems to be missing some data.

**Comment by CeledonianError** [comment] 2022-01-23 18:11
> > duplicate #2805
> > you can play the game if you create a new save **from** ryujinx, but this is not a solution ofc.
> > the problem is that ryujinx always creates a save that is a few kb smaller than a real save. if you import a real save from switch, you get that error.
> 
> Could the difference in bytes be the issue? I loaded both a switch/yuzu save and a ryu one in a Hex editor, and the savefile made by ryu seems to be missing some data.

I just did the same and didn't see this. Both saves were exactly 1273310 bytes. That also wouldn't explain the fact that importing a save from Yuzu doesn't work.

**Comment by A-w-x** [comment] 2022-01-23 19:01
> > > duplicate #2805
> > > you can play the game if you create a new save **from** ryujinx, but this is not a solution ofc.
> > > the problem is that ryujinx always creates a save that is a few kb smaller than a real save. if you import a real save from switch, you get that error.
> > 
> > 
> > Could the difference in bytes be the issue? I loaded both a switch/yuzu save and a ryu one in a Hex editor, and the savefile made by ryu seems to be missing some data.
> 
> I just did the same and didn't see this. Both saves were exactly 1273310 bytes. That also wouldn't explain the fact that importing a save from Yuzu doesn't work.

yeah, that is the size of a save from ryujinx and it is the wrong size.

correct size is: 1,603,176 bytes (from switch and from yuzu, both generate a valid save with that size)

version 1.3.2

**Comment by gdkchan** [comment] 2022-01-23 19:04
I don't think this is the problem. Even if you use a save created by Ryujinx on Windows, it does not work. So the problem appears to be reading the save, not creating it (or maybe both).

**Comment by CeledonianError** [comment] 2022-01-23 19:08
> > > > duplicate #2805
> > > > you can play the game if you create a new save **from** ryujinx, but this is not a solution ofc.
> > > > the problem is that ryujinx always creates a save that is a few kb smaller than a real save. if you import a real save from switch, you get that error.
> > > 
> > > 
> > > Could the difference in bytes be the issue? I loaded both a switch/yuzu save and a ryu one in a Hex editor, and the savefile made by ryu seems to be missing some data.
> > 
> > 
> > I just did the same and didn't see this. Both saves were exactly 1273310 bytes. That also wouldn't explain the fact that importing a save from Yuzu doesn't work.
> 
> yeah, that is the size of a save from ryujinx and it is the wrong size.
> 
> correct size is: 1,603,176 bytes (from switch and from yuzu, both generate a valid save with that size)
> 
> version 1.3.2

Ok, there's an explanation for my sizes being different, but I cannot say without my comment being deleted. I hope you know what I mean by this.
Point still stands, though: Yuzu and Ryujinx saves are the same size for me, and if they do differ, you should be able to import a save from Yuzu into Ryujinx, which you can't. Hell, if you try to use a Yuzu save imported into Ryujinx then back into Yuzu, it breaks.

**Comment by raym55** [comment] 2022-01-23 19:11
> I don't think this is the problem. Even if you use a save created by Ryujinx on Windows, it does not work. So the problem appears to be reading the save, not creating it (or maybe both).

i don't think that's the case cause i took the save from ryujinx and put it on my switch and it said it was corrputed

**Comment by C1fer** [comment] 2022-01-23 19:53
Was testing some builds with older LibHac versions, and found that saves load just fine on releases that include versions 0.13.1 and below.

**Comment by B3astTech** [comment] 2022-01-23 19:54
> > I don't think this is the problem. Even if you use a save created by Ryujinx on Windows, it does not work. So the problem appears to be reading the save, not creating it (or maybe both).
> 
> i don't think that's the case cause i took the save from ryujinx and put it on my switch and it said it was corrputed

Well that does fall under write issues so he's still correct. But it's to be determined atm.

**Comment by CeledonianError** [comment] 2022-01-23 20:25
Ok. I was just playing the game with two instances of Ryujinx open in case it crashed. Who wants to guess what happened when it crashed? Anyone?

To those who guessed "the save file was corrupted," you are correct.

How the hell does this even happen?

**Comment by ghalib5000** [comment] 2022-01-23 20:40
so i tried building from the 13th august PR and the save files load properly in linux, so the issue is really with the libhac and how it's reading the saves... and that too only on linux, it loads saves fine on windows for some reason but not on linux

**Comment by B3astTech** [comment] 2022-01-24 00:06
## Well, My testings.

### What's the issue you encountered?

In all of these case's I ran into crash's with only one exception, And that is when I ran the debugger build with lldb.
And even then I am fairly certain that there may be no good info from it. My situation doesnt even hit pkm swords save corrupt but I do know for certain that its the same issue because when I removed my saves from my config the game booted in-game, But when I saved it in-game, Rebooted Ryujinx, and loaded into it again it crashed essentially the same way.

## Last Part of lldb debugger

### First Try
````
00:00:25.278 |I| HLE.OsThread.9 ServiceNv DecrementMapRefCount: Deleted map 38!
Process 19594 stopped
* thread #42, name = 'HLE.GuestThread', stop reason = signal SIGSEGV: address access protected (fault address: 0x7f8e4b37a000)
    frame #0: 0x00007efd8c46214f
->  0x7efd8c46214f: movb   %cl, (%rax,%r10)
    0x7efd8c462153: movq   %r14, %rcx
    0x7efd8c462156: subq   $0x3, %rcx
    0x7efd8c46215a: testq  %rcx, %rcx
````

### Second Try
````
00:00:19.812 |D| HLE.GuestThread.14 KernelSvc PrintResult: QueryMemory64 returned result Success.
Process 6108 stopped
* thread #45, name = 'HLE.GuestThread', stop reason = signal SIGSEGV: address access protected (fault address: 0x7f8e4b37a000)
    frame #0: 0x00007efd8c460cf7
->  0x7efd8c460cf7: movb   %cl, (%rax,%r10)
    0x7efd8c460cfb: movq   %r14, %rcx
    0x7efd8c460cfe: subq   $0x3, %rcx
    0x7efd8c460d02: testq  %rcx, %rcx
````

## Last Part of Log
````
00:00:39.724 |S| HLE.OsThread.15 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72246641462509568}
00:00:39.740 |S| HLE.OsThread.15 ServiceAcc IsUserAccountSwitchLocked: Stubbed. 
00:00:39.767 |S| HLE.OsThread.15 ServiceFriend GetFriendList: Stubbed. {UserId: 00000000000000010000000000000000 ; offset: 0 ; PresenceStatus: None ; IsFavoriteOnly: False ; IsSameAppPresenceOnly: False ; IsSameAppPlayedOnly: False ; IsArbitraryAppPlayedOnly: False ; PresenceGroupId: 0}
00:00:40.263 |S| HLE.OsThread.15 ServiceAm GetPseudoDeviceId: Stubbed. 
00:00:40.264 |S| HLE.OsThread.15 ServiceAcc CheckAvailability: Stubbed. 
00:00:40.265 |S| HLE.OsThread.15 ServiceAcc GetAccountId: Stubbed. {NetworkServiceAccountId: 51966}
00:00:40.537 |S| HLE.OsThread.15 ServiceAm SetRestartMessageEnabled: Stubbed. {restartMessageEnabled: True}
00:00:40.587 |S| HLE.OsThread.6 ServiceAudio QueryAudioDeviceOutputEvent: Stubbed. 
00:00:40.686 |S| HLE.OsThread.8 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 4294967296 ; sixAxisSensorHandle: 139268}
00:00:40.686 |S| HLE.OsThread.8 ServiceHid StopSixAxisSensor: Stubbed. {appletResourceUserId: 4294967296 ; sixAxisSensorHandle: 139268}
00:00:40.693 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadStyleSet: Stubbed. {appletResourceUserId: 4294967296 ; type: ProController, Handheld, JoyconPair}
00:00:40.694 |S| HLE.OsThread.8 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Player1,Handheld
00:00:40.694 |S| HLE.OsThread.8 ServiceHid SetNpadHandheldActivationMode: Stubbed. {appletResourceUserId: 1 ; _npadHandheldActivationMode: Dual}
00:00:40.694 |S| HLE.OsThread.8 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Player1 ; npadStyleSet: 6465020962780741632}
00:00:40.694 |S| HLE.OsThread.8 ServiceHid AcquireNpadStyleSetUpdateEventHandle: Stubbed. {appletResourceUserId: 4294967296 ; npadId: Handheld ; npadStyleSet: 6465021168939171840}
````

### Log file
[Ryujinx_1.1.5 Master With Linux Save.log](https://github.com/Ryujinx/Ryujinx/files/7921737/Ryujinx_1.1.5.Master.With.Linux.Save.log)

[Ryujinx_1.1.5 Master With Win Save.log](https://github.com/Ryujinx/Ryujinx/files/7921738/Ryujinx_1.1.5.Master.With.Win.Save.log)

[Ryujinx With Enabled Debugger lldb.log](https://github.com/Ryujinx/Ryujinx/files/7921740/Ryujinx.With.Enabled.Debugger.lldb.log)

### Environment?

- Ryujinx version: 1.1.5/br>
- Game version: 1.0.0</br>

- System Specs:
  - OS: *Fedora 35*
  - CPU: *i7-2600k*
  - GPU: *1050ti*
  - RAM: *16GB*

### How can the issue be reproduced?
Linux > Save > Bingo

### Additional context?

Additional info about your environment:</br>
I tried my save from Ryujinx's Windows variant that I know for a fact works. and used it on my Linux distro and it crash's Ryujinx. When that did not work I removed save from directory and made a Linux save when I went in-game, When I restarted Ryujinx and loaded the Linux save it crashed the same way. So it may or may not be a write issue, but a read issue. This is just my uneducated opinion.

**Comment by C1fer** [comment] 2022-01-24 00:12
I tested older builds, and found that the regression was caused on #2515

**Comment by B3astTech** [comment] 2022-01-24 00:18
> I tested older builds, and found that the regression was caused by #2515

Fun Fact, If you remove your current save and make a new one and go into actions and stop emulation and click onto the game it'll boot into the game. But if you close Ryujinx is when it starts crashing

**Comment by C1fer** [comment] 2022-01-24 01:38
Can confirm PR #3034 fixes the issue
![image](https://user-images.githubusercontent.com/41005657/150708540-c288cfa6-cd5a-4cbd-b66a-383ec8f56a62.png)

**Comment by CeledonianError** [comment] 2022-01-24 02:01
Just tested myself. Still broken. Annoyingly as mentioned earlier I can't discuss any specifics here without my comment getting deleted. Welp, that sucks. Glad to see SwSh is fixed, though!

**Closed** 2022-01-24 10:23 UTC
Labels: bug, cpu
