### ISSUE TITLE
ACNH - 700+ FPS on loading screen, crashes on loading screen (Vulkan)

### ISSUE THREAD

**Issue by Aspien** [Ryujinx/Ryujinx#3613] opened 2022-08-21 03:44 UTC
## What's the issue you encountered?
When running ACNH on Vulkan versions (1.223 - 1.226), the FPS on the loading screen reaches 100 - 700 fps. The game crashes immediately after the game reaches the "Nook Inc Deserted Island Package" board.  Rarely does the game reaches the choose your birthdate screen or choose your avatar screen. If the game reaches the "Nook Inc Deserted Island Package" board, the game's fps will reach 60 - 100 fps without mods.

![image](https://user-images.githubusercontent.com/99775853/185774267-5ce0c1ac-e257-415b-8eae-36d9ee83daa6.png)

Images & Videos (from non-loading screen crash session, crashed after reload)
![acnl_120fps_1](https://user-images.githubusercontent.com/99775853/185771878-bffaf8a7-46ff-4416-8513-e18a88b69ad3.png)

https://user-images.githubusercontent.com/99775853/185772029-3aadf5b4-15c8-439f-83ce-67a86c5bc1b3.mov

https://user-images.githubusercontent.com/99775853/185772163-7bc5b32a-6a52-4d2b-ba5e-e744a0bba513.mp4

### How can the issue be reproduced?

- Run ACNH on 1.223 - 1.226 builds (not known if issue is in 1.100 - 1.222)
- Use Vulkan as graphics backend

### Log file
[Ryujinx_1.1.226_2022-08-21_09-38-44.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9388295/Ryujinx_1.1.226_2022-08-21_09-38-44.log)
[Ryujinx_1.1.226_2022-08-21_10-11-29.log](https://github.com/Ryujinx/Ryujinx-Games-List/files/9388297/Ryujinx_1.1.226_2022-08-21_10-11-29.log) 
[Ryujinx_1.1.226_2022-08-21_11-40-33.log](https://github.com/Ryujinx/Ryujinx/files/9388376/Ryujinx_1.1.226_2022-08-21_11-40-33.log)

### Environment?

- Ryujinx version: 1.0.226</br>

- Game version: 2.0.3</br>

- System Specs:
  - OS: Windows 11
  - CPU: AMD Ryzen 9 3900X
  - GPU:  NVIDIA RTX 2080 TI
  - RAM: 32 GB
- Applied Mods : None

**Comment by MetrosexualGarbodor** [comment] 2022-08-21 04:09
Animal Crossing requires a device save to get past the intro. The high fps is because you've disabled Vsync. Please head to Discord for help next time.
Closing as duplicate of #2453.

**Closed by MetrosexualGarbodor** 2022-08-21 04:09 UTC
