### ISSUE TITLE
Metroid Dread (Hard Crashes)

### ISSUE THREAD

**Issue by MrMendelli** [Ryujinx/Ryujinx#4110] opened 2022-12-13 00:20 UTC
### What's the issue you encountered?

When using the Vulkan API, the game crashes upon entering Navigation Rooms. It only happens in these rooms regardless of which one it is. This has been tested and replicated consistently on v1.0.0 and v2.1.0 of the game. Additionally, this has also been tested both with and without mods.

### How can the issue be reproduced?

Enable Vulkan, enter any Navigation Room. It does not matter which Navigation Room it is or which side you enter from _(if it has more than one door)_. This does not occur with OGL.

### Log file

```
00:00:00.096 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.102 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.102 |I| Configuration LogValueChange: MaxAnisotropy set to: 16
00:00:00.104 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.106 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.107 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.108 |I| Configuration LogValueChange: PreferredGpu set to: 0x1002_0x163F
00:00:00.113 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.129 |I| Configuration LogValueChange: EnableVsync set to: False
00:00:00.129 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.129 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.129 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.129 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.129 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.130 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: False
00:00:00.130 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.131 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.131 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.132 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.132 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.132 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.137 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.468
00:00:00.152 |N| Application Print: Operating System: Linux 5.13.0-valve21.3-1-neptune #1 SMP PREEMPT Mon, 03 Oct 2022 23:17:36 +0000 (X64)
00:00:00.152 |N| Application Print: CPU: AMD Custom APU 0405   AmdCcxVhFf3PeiInit Entry ; 8 logical
00:00:00.154 |N| Application Print: RAM: Total 14836 MiB ; Available 12336 MiB
00:00:00.158 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, AccessLog, Stub
00:00:00.159 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:04.892 |I| ModLoader GetTitleDir: Creating mods directory for Title 010093801237C000
```

### Environment?

- Ryujinx version: <br>1.1.468</br>
- Game version: <br>1.0.0 & 2.1.0</br>
- System Specs:
  - OS: SteamOS
  - CPU: Zen 2 4c/8t, @ 2.4~3.5**GHz**
  - GPU: AMD APU
  - RAM: 16**GB** LPDDR5 (5500 MT/s quad 32-bit channels)
- Applied Mods : Yes (w/ texture mods) & no

### Additional context?

The specific hardware this issue happens on is the Steam Deck. I am reporting on behalf of other users with the same hardware/environment that are experiencing the same issue.

**Comment by gdkchan** [comment] 2022-12-13 00:32
Duplicate of #4072.

**Closed by gdkchan** 2022-12-13 00:32 UTC
