### ISSUE TITLE
Program crashes without opening any game

### ISSUE THREAD

**Issue by username227** [Ryujinx/Ryujinx#3204] opened 2022-03-15 21:58 UTC
## What's the issue you encountered?

[ After setup, i tried to start games and the program simply closes. Attempted with Dragon Quest XI, Dragon Quest Builders, and Dragon Quest ]</br>
[ I had just installed it; never got a game to start ]</br>

### How can the issue be reproduced?

n/a

### Log file

Log file attached.

### Environment?

- Ryujinx version: 1.1.69</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Linux Mint
  - CPU: AMD Ryzen 5 5500H series
  - GPU: *Nvidia GeForce GTX 1650/PCIe/SSE2
  - RAM: 16 GB
- Applied Mods : [ Yes (Which ones) / No ] No
[Ryujinx_1.1.69_2022-03-15_17-40-57.log](https://github.com/Ryujinx/Ryujinx/files/8257485/Ryujinx_1.1.69_2022-03-15_17-40-57.log)

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by MetrosexualGarbodor** [comment] 2022-03-16 15:54
Duplicate of #2112.

**Closed by MetrosexualGarbodor** 2022-03-16 15:54 UTC
