### ISSUE TITLE
1.1.220 lags horribly but doesn't register fps drops on shadowplay

### ISSUE THREAD

**Issue by Missingphy** [Ryujinx/Ryujinx#3600] opened 2022-08-17 23:55 UTC
### What's the issue you encountered?

I was playing build .217 without lag/tearing, then I updated to .220 and all of my games lag. (No FPS drops, somehow it only lags but it still runs at 60fps, weird.)

### How can the issue be reproduced?

Update to version .220 with my exact same settings. Downgrading to .217 makes it work again.

### Log file

N/A

### Environment?

- Ryujinx version: 1.1.220</br> (1.1.17 works fine).

- System Specs:
  - OS: *(e.g. Windows 10)*
  - CPU: *(e.g. Ryzen 7 5800H)*
  - GPU: *(e.g. NVIDIA RTX 3060 Laptop)*
  - RAM: *(e.g. 16GB)*
- Applied Mods : [ No ]

### Additional context?

![thxtttt](https://user-images.githubusercontent.com/49085233/185263457-705c377d-ba14-40cc-93d9-65e9be5be6fb.png)

Additional info about your environment:</br>

My settings are exactly the same for both versions.

**Comment by MetrosexualGarbodor** [comment] 2022-08-17 23:57
You got any video or something? What game are you seeing this in?

**Comment by riperiperi** [comment] 2022-08-18 12:36
Don't turn nvidia threaded optimization on at the same time as Ryujinx multithreading, as they essentially do the same thing. (though nvidia threading only affects opengl) Apart from that, changes since 217 _shouldn't_ cause anything to get any slower. A demonstration would help.

**Comment by MutantAura** [comment] 2022-08-30 16:27
Likely duplicate of https://github.com/Ryujinx/Ryujinx/issues/3609 ? (will re-open if not)

**Closed by MutantAura** 2022-08-30 16:27 UTC
