### ISSUE TITLE
[Bug] TOTK Repeated Crashing when trying to register a horse at the stable

### ISSUE THREAD

**Issue by ewoolsey** [Ryujinx/Ryujinx#5067] opened 2023-05-23 03:31 UTC
### Description of the issue

Pretty much the title. Looks like the crash occurs just as the prompt to provide a name comes up.

### Reproduction steps

Using Mac OS with TOTK 1.1.1 and Ryujinx 1.1.818

### Log file

00:00:00.036 |I| Configuration LogValueChange: ResScale set to: 2
00:00:00.038 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.038 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.038 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.039 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.039 |I| Configuration LogValueChange: GraphicsBackend set to: Vulkan
00:00:00.039 |I| Configuration LogValueChange: PreferredGpu set to: 0x106B_0xD0303EF
00:00:00.039 |I| Configuration LogValueChange: AntiAliasing set to: None
00:00:00.040 |I| Configuration LogValueChange: ScalingFilter set to: Bilinear
00:00:00.040 |I| Configuration LogValueChange: ScalingFilterLevel set to: 80
00:00:00.041 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.045 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.045 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.045 |I| Configuration LogValueChange: EnableTextureRecompression set to: False
00:00:00.045 |I| Configuration LogValueChange: EnableMacroHLE set to: True
00:00:00.045 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.045 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.045 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.045 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.045 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.045 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.045 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.045 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.045 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.045 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.047 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.818
00:00:00.050 |N| Application Print: Operating System: Darwin 22.4.0 Darwin Kernel Version 22.4.0: Mon Mar  6 20:59:28 PST 2023; root:xnu-8796.101.5~3/RELEASE_ARM64_T6000 (Arm64)
00:00:00.050 |N| Application Print: CPU: Apple M1 Max ; 10 logical
00:00:00.051 |N| Application Print: RAM: Total 32768 MiB ; Available 18778 MiB
00:00:00.052 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.052 |N| Application PrintSystemInfo: Launch Mode: UserProfile

### OS

MacOs Ventura 13.3.1

### Ryujinx version

1.1.818

### Game version

TOTK 1.1.1

### CPU

m1 max

### GPU

m1 max

### RAM

32

### List of applied mods

FPS++ 60fps

**Comment by ewoolsey** [comment] 2023-05-23 18:58
> If im playing in full screen I can't make it windowed again and I need to Alt+Tab or Ctrl+Alt+Supr to be able to get into the keyboard popup.

Oh okay cool thanks for the tip. I was definitely full screened. I'll trying going into windowed and seeing if that helps. Will report back tomorrow.

**Comment by Foul-Tarnished** [comment] 2023-05-24 09:38
The log is obviously cut off

Being in fullscreen when the game request a name to be entered cause no issue on GTK or Ava, on Windows, but it's worth trying in windowed on Mac, for sure

**Comment by MutantAura** [comment] 2023-06-24 23:36
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/5186

**Closed by MutantAura** 2023-06-24 23:36 UTC
Labels: bug
