### ISSUE TITLE
[Feature Request] Add mod manager

### ISSUE THREAD

**Issue by jojodunet** [Ryujinx/Ryujinx#3819] opened 2022-11-01 20:33 UTC
## Feature Request
Add a mod manager in Ryujinx

### What feature are you suggesting?
Mod manager with auto-download/self-update

#### Overview:
Same mods manager like CEMU, that’s the best example I can share, with our own repository for downloading.

Maybe, the first step is to port the previous PR #2651 to Avalonia GUI and then extend it to the new request.

### Why would this feature be useful?
Simplify the community mods sharing and the application in the games.

**Comment by MutantAura** [comment] 2022-11-01 20:35
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1566

**Closed by MutantAura** 2022-11-01 20:35 UTC
