### ISSUE TITLE
Updater sometimes doesn't apply new files.

### ISSUE THREAD

**Issue by Mou-Ikkai** [Ryujinx/Ryujinx#2594] opened 2021-08-27 12:21 UTC
### What's the issue you encountered?
This is not one I have encountered myself, but there have been several reports over the months about how the updater will change all files into .ryuold, but never make the new updated files appear. Forcing the user to download Ryujinx again manually.

### How can the issue be reproduced?
Unknown cause of the issue. Possibly a permission or Updater.cs specific issue.

### Log file
**POSTING REPORTS**
https://discord.com/channels/410208534861447168/410208610455519243/863976122374815744
https://discord.com/channels/410208534861447168/410208534861447170/840518069339553793
https://discord.com/channels/410208534861447168/410208534861447170/844283791786770452
https://discord.com/channels/410208534861447168/410208610455519243/824611598118158398

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 01:07
Closing as the root cause is addressed in #3102.

**Closed by MetrosexualGarbodor** 2022-02-11 01:07 UTC
Labels: bug
