### ISSUE TITLE
[Bug] TLOZ: Tears of the Kindom, Gloom effect not matching texture

### ISSUE THREAD

**Issue by IsmaelOlj** [Ryujinx/Ryujinx#4915] opened 2023-05-12 21:41 UTC
### Description of the issue

Gloom's area of effect (the red stuff) doesn't match it's texture in the underground areas, on AMD cards, with vulkan.

### Reproduction steps

1-AMD card
2-Turn on vulkan
3-go to depths and stand on the red stuff, see that no effect will occur.

### Log file

[Ryujinx_1.1.794_2023-05-12_22-22-32.log](https://github.com/Ryujinx/Ryujinx/files/11467940/Ryujinx_1.1.794_2023-05-12_22-22-32.log)

### OS

Windows 11

### Ryujinx version

1.1.794

### Game version

1.0

### CPU

Ryzen 5 5600

### GPU

RX 570 8GB

### RAM

32GB

**Comment by IsmaelOlj** [comment] 2023-05-12 21:42
Also worth noting, this doesn't happen with OpenGL on, on that same setup.

**Comment by TheShotte** [comment] 2023-05-13 01:35
I'm not sure if it's the texture itself or what. Gloom doesn't seem to be doing any damage to link where it should be (gloom is purple on mini-map, and in world too for me), and I can step in it with no problems. However, I was exploring random parts of the Depths yesterday, and areas that did not have ANY gloom (minimap or otherwise) were killing me.

**Comment by gdkchan** [comment] 2023-05-13 01:39
Does the issue happen at native resolution (no resolution scaling)?

**Comment by NotNite** [comment] 2023-05-13 03:02
Can confirm this happens on native resolution, RX 6800 XT, Vulkan.

**Comment by gdkchan** [comment] 2023-05-13 03:03
Did you have the resolution set to native before starting the game, or did you change it with the game running?

**Comment by NotNite** [comment] 2023-05-13 03:05
Resolution was already set to native before game start, no changes to settings in gameplay. I'm in the process of starting the game after switching to OpenGL to test, I can get logs if needed.

**Comment by TheShotte** [comment] 2023-05-13 11:38
I can confirm with the resolution too. Set it to Native before I started the game, changes nothing. Fire Temple is completely undoable because you can't set foot in it.

**Comment by riperiperi** [comment] 2023-05-13 11:57
I guess everyone with this issue has an AMD gpu?

**Comment by piplup55** [comment] 2023-05-13 12:08
> I guess everyone with this issue has an AMD gpu? (windows or linux?)

it seems to be windows only, as i can't reproduce it on linux

**Comment by IsmaelOlj** [comment] 2023-05-13 14:30
Yes, I'm on windows too. Also can confirm changing resolution doesn't fix it. Only going OpenGL works, but that has serious performance issues so it's not the best solution.

**Comment by KdudeDev** [comment] 2023-05-13 19:38
Also experiencing this, on an AMD gpu and on Windows. Makes the Fire Temple and many other areas inaccessible, I can't test if OpenGL works as it can't even get to the title screen before crashing.

**Comment by TheShotte** [comment] 2023-05-13 22:24
Furthermore, I would like to add that this seems to happen only in the Depths. The Gloom does damage like it's supposed to in the regular world.

**Comment by NezcalSpindrake** [comment] 2023-05-14 21:51
As someone also having this issue, is there any way I can contribute to helping solve it?
Windows 10
AMD RX 6500 XT GPU
AMD Ryzen 5 3600 CPU
Also can confirm it's an issue on game version 1.1.0 as well.

**Comment by dantezero0403** [comment] 2023-05-17 21:27
I am also having a similar problem 
Getting stuck in the Fire Temple

Windows11
AMD Ryzen 9 6900HX
game ver 1.1.0

**Comment by 70daniel** [comment] 2023-05-17 21:30
> Has there been any fix on this whatsoever?

Until there is a fix, use this as a workaround
https://github.com/Ryujinx/Ryujinx-Games-List/issues/4598#issuecomment-1546721351

**Comment by shalofty** [comment] 2023-05-17 23:03
Thanks! The bug had temporarily resolved itself in a recent update, but has since reverted back? Hopefully that means it's something simple that's being overlooked.

**Comment by 70daniel** [comment] 2023-05-17 23:07
Bug hasn't been fixed as far as I am aware, it is just not very consistent

**Comment by dantezero0403** [comment] 2023-05-17 23:15
ryujinx ver1.1.803
Not fixed. There are still bugs. I am avoiding it by applying another patch.

https://github.com/Ryujinx/Ryujinx/assets/133920073/f8ee23a5-5019-43e3-ab73-b0ac9e2f7cd4

**Comment by SpandexWizard** [comment] 2023-05-19 07:08
i've yet to confirm myself but a lot of chat on the net suggests it has something to do with how deep you go. and that seems to relate to my experience. there are higher spots in the depths that do not cause problems but if you go too deep the game starts killing you. also of note, it does this whether or not you are climbing, or standing on a statue, but it wont affect you if you are standing on a building, like the pads that have all the zonai parts. ALSO will not kill you if you are riding a zonai machine, or otherwise 'off the ground'. 

amd rx 570, vulkan only. i've tried changing most of the settings to no effect.  opengl allows me to play the game but it's laggy as hell in the depths, and i crash almost immediately upon reaching the surface so i have to swap back to vulkan afterwards

**Comment by TheShotte** [comment] 2023-05-19 15:27
Yup, I completely agree with the above statement. I'm thinking the main gloom effect is done with a heightmap or something similar, and it's just incorrectly overlaying it (whether it's offset, or scaled incorrectly, whatever be the case). 

Now, that's the main Gloom. What I have noticed however, is that in certain spots (shrines and whatnot), the Gloom still works 100% as it should. I am assuming this gloom was placed/painted manually by an artist.

**Comment by 70daniel** [comment] 2023-05-19 22:12
There is now a version of the No Environmental Damage mod that removes _only environmental gloom_ damage. They also fixed not being able to restore gloom damaged hearts normally. Please use this as a workaround for now. (and please go thank them for making the mod)

[No Environmental Gloom Damage.zip](https://github.com/Ryujinx/Ryujinx/files/11520828/No.Environmental.Gloom.Damage.zip)

https://gamebanana.com/mods/443356

**Comment by gdkchan** [comment] 2023-05-20 15:54
Fixed by #5026.

**Closed by gdkchan** 2023-05-20 15:54 UTC
Labels: bug, gpu, graphics-vendor:amd, os:windows
