### ISSUE TITLE
crash when I changed the motion control settings from wasd to arrows

### ISSUE THREAD

**Issue by JIuBeP** [Ryujinx/Ryujinx#2023] opened 2021-02-16 08:26 UTC
## Bug Report
Hello!
### How can the issue be reproduced?

noticed Crash when I changed the motion control settings from wasd to arrows, when I clicked on the Wasd buttons, I got a crash. I assigned the control to wasd and the crash disappeared. i.e. when wasd is not assigned and push them = crash (game Super Mario Odyssey)

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]
[Ryujinx_1.0.6575_2021-02-16_11-12-58.log](https://github.com/Ryujinx/Ryujinx/files/5987102/Ryujinx_1.0.6575_2021-02-16_11-12-58.log)

### Environment?

- Ryujinx version: 1.0.6575</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *( Windows 7)*
  - CPU: *( ryzen-2600)*
  - GPU: *( NVIDIA gtx 950)*
  - RAM: *(8GB)*
- Applied Mods : [ Yes (Which ones) / No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by AcK77** [comment] 2021-04-11 19:58
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by AcK77** [comment] 2021-04-14 16:18
Since motion isn't possible with keyboard anymore, I close the issue.

**Closed by AcK77** 2021-04-14 16:18 UTC
