### ISSUE TITLE
Emulator freezes when closing and stopping the game

### ISSUE THREAD

**Issue by Abyss777111** [Ryujinx/Ryujinx#4012] opened 2022-12-04 18:15 UTC
Emulator freezes when closing and stopping the game

[Ryujinx_1.1.418_2022-12-04_20-43-19.log](https://github.com/Ryujinx/Ryujinx/files/10149168/Ryujinx_1.1.418_2022-12-04_20-43-19.log)

**Comment by AcK77** [comment] 2022-12-04 18:23
The issue template isn't followed.
I suggest you to come on our Discord for support, if a real issue exist, then reopen a new one well completed. Thanks.

**Comment by MetrosexualGarbodor** [comment] 2022-12-04 18:23
Duplicate of #2863

**Closed by MetrosexualGarbodor** 2022-12-04 18:23 UTC
