### ISSUE TITLE
Controller don’t support hot-swapping

### ISSUE THREAD

**Issue by lostromb** [Ryujinx/Ryujinx#1098] opened 2020-04-08 22:53 UTC
Or, in other words, hot-swapping doesn't seem to be supported. At the very least I would like to be able to start up the emu without having to worry about turning on the controller beforehand.

Related to this would be making sure that controller disconnects don't require an emulator restart, and allowing new controllers (players) to join in the middle of a game.

I'm not actually using an Xbox controller, this is DS4 using DS4Windows so they may be some discrepancies in how the XInput layer is accessed. But I do have various controllers I can test with.

**Comment by ToppestOfDogs** [comment] 2020-04-09 20:40
I have an Xbox One controller with the same problem so I'm pretty sure it's a hot-swapping issue

**Comment by ameisen** [comment] 2020-04-15 19:40
The XInput implementation is incomplete. I have a TODO locally to look into it.

**Comment by LeDragoX** [comment] 2020-08-25 21:47
Controller: Razer Serval
Connection Type: USB
I tested on Linux my Razer Serval, and after the controller disconnect, when it come back, its not working anymore, even if restarted Ryujinx. 
The Serval uses a Xbox 360 Controller Layout, but still generic. On windows it only works full with Razer Synapse 2.0.

i don't know if this would be useful, but this is the SDL 2 Game Controller Mapping String (Got on Antimicro)
`03000000321500000009000011010000,Razer Serval,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,guide:b8,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a5,righttrigger:a4,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,`

**Comment by AcK77** [comment] 2021-04-11 19:56
Could you test the build in https://github.com/Ryujinx/Ryujinx/pull/2194 and let us know if the issue is fixed with it?
Thanks!

**Comment by LeDragoX** [comment] 2021-04-12 19:53
> Could you test the build in #2194 and let us know if the issue is fixed with it?
> Thanks!

So, i tested on Linux Mint, and seems to be fine now, i'm using the PS5 controller now, i tried disconnecting and reconnecting again, and it returned normally.

Got the build from the GitHub Actions Bot: https://github.com/Ryujinx/Ryujinx/pull/2194#issuecomment-817209823

#### Controller connected (1st time):
![image](https://user-images.githubusercontent.com/27643047/114452625-0cb98900-9baf-11eb-89f2-2db76777efa9.png)

#### Controller disconnected:
![image](https://user-images.githubusercontent.com/27643047/114452877-52765180-9baf-11eb-990c-897c67067925.png)

#### Then connected again (tested on other USB ports):
![image](https://user-images.githubusercontent.com/27643047/114452969-6d48c600-9baf-11eb-8ce4-60e57ff45d8b.png)

Hope this helps!

**Closed** 2021-04-14 10:28 UTC
Labels: bug, gui, miscellaneous
