### ISSUE TITLE
Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.

### ISSUE THREAD

**Issue by justifun** [Ryujinx/Ryujinx#3524] opened 2022-08-01 17:47 UTC
## Bug Report

While loading an .NSP file an Unhandled exception caught error occurs

### What's the issue you encountered?

Upon loading Mario Strikers game it throughs an unhandled exception error - see attached text file for full log text

[ Did you make any changes related to Ryujinx itself? ] - NO </br>

### How can the issue be reproduced?

Load Mario Strikers NSP file

### Log file

Attached

### Environment?

- Ryujinx version: 1.1.200 and 1.1.201</br>

- Game version: X.X.X</br>
[ Replace X's with the game version at time of crash. ]
[ryujinx_error_log.txt](https://github.com/Ryujinx/Ryujinx/files/9236031/ryujinx_error_log.txt)

- System Specs:
  - OS: Windows 10
  - CPU: AMD Ryzen 3950x
  - GPU: Nvidia RTX 3090
  - RAM: 64GB
- Applied Mods : None

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by gdkchan** [comment] 2022-08-01 17:50
Are you sure that you are not trying to load an update NSP or some DLC rather than the actual game? Look at the file size, if it has less than 3 GB that is likely the case.

**Comment by ExE-Boss** [comment] 2022-08-02 20:27
Sounds like a partial duplicate of <https://github.com/Ryujinx/Ryujinx/issues/2810>.

**Comment by AcK77** [comment] 2022-08-02 22:03
> Sounds similar to #2810.

This error is `LibHac.Common.HorizonResultException: ResultFsPathNotFound (2002-0001)` so it's not related to the issue you linked... It's more like a bad dump or they trying to load the wrong NSP (Update or DLC).
I suggest the author to came on our discord for support. I close the issue for now, we can reopen it if there is really an issue.

**Closed by AcK77** 2022-08-02 22:03 UTC
