### ISSUE TITLE
[Bug] Pressing "-" in Super Mario 3D All Stars in a game will permanently freeze the game

### ISSUE THREAD

**Issue by FrizouWasThere** [Ryujinx/Ryujinx#5410] opened 2023-06-28 19:42 UTC
### Description of the issue

Pressing "-" while inside one of the 3 games offered in Super Mario 3D All Stars normally allows the player to see the controls, but in this case, the game will instead darken and permanently become frozen in a state where the player cannot do any further action. The only way to return is to stop the emulation entirely and restart it.
A video demonstates the bug here: https://youtu.be/T6pxJOJ4E-I (Shown in Mario Sunshine, all 3 games have been tested and have shown to also have the same bug)

### Reproduction steps

1. Enter one of the 3 games shown in the main menu
2. Press "-" on the controller to attempt to access the controls menu. The game will then darken and the player will be unable to do anything else until the game is restarted fully.

### Log file

(Taken from a test done in Mario 64)
[Ryujinx_1.1.941_2023-06-28_15-37-30.log](https://github.com/Ryujinx/Ryujinx/files/11899410/Ryujinx_1.1.941_2023-06-28_15-37-30.log)

### OS

Windows 10

### Ryujinx version

1.1.941

### Game version

1.1.1

### CPU

AMD Ryzen 3

### GPU

NVIDIA GeForce GT1030

### RAM

12GB

**Comment by AcK77** [comment] 2023-07-01 06:08
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1004

**Closed** 2023-07-01 06:08 UTC
Labels: bug
