### ISSUE TITLE
[Bug] Can't open game save folders on a fresh install on macOS

### ISSUE THREAD

**Issue by lwouis** [Ryujinx/Ryujinx#4710] opened 2023-04-23 18:15 UTC
### Description of the issue

Hello,

On a fresh install of Ryujinx, I can't open save folder of any game. It shows this popup every time:

<img width="536" alt="image" src="https://user-images.githubusercontent.com/106195/233857373-e10bd232-10b1-456b-866b-5e8cc31b1ff9.png">

Thank you

### Reproduction steps

* Fresh install of the mac release (1.1.0-macos1)
* Install keys and firmware 16.0.0
* Add path to games
* Pick any game listed > right-click it > `Open User Save Directory`
* See error popup instead of save folder

### Log file

```
00:00:00.037 |I| Configuration LogValueChange: UseHypervisor set to: True
00:00:00.039 |N| Application PrintSystemInfo: Ryujinx Version:  1.1.0-macos1
00:00:00.041 |N| Application Print: Operating System: Darwin 22.3.0 Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:43 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T8112 (Arm64)
00:00:00.041 |N| Application Print: CPU: Apple M2 ; 8 logical
00:00:00.042 |N| Application Print: RAM: Total 16384 MiB ; Available Unknown
00:00:00.043 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.043 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:01.108 |W| Application FixUnindexedSystemSaves: Error ResultFsPathAlreadyExists (2002-0002) when fixing extra data for system save data 0x8000000000000030
00:00:05.171 |E| Application CreateErrorDialog: There was an error finding the specified savedata: ResultFsPathAlreadyExists (2002-0002)
```

### OS

macOS 13.2.1

### Ryujinx version

1.1.0-macos1

### CPU

M2

### GPU

M2

### RAM

16GB

### Additional context?

It may be useful to note that if I launch some game, it also crashes with this log mentionning `00:00:02.611 |I| HLE.OsThread.17 ServiceAm SetTerminateResult: Result = 0x0035f202 (ResultFsNotMounted (2002-6905)).`:

```
00:00:32.151 |E| Application CreateErrorDialog: There was an error finding the specified savedata: ResultFsPathAlreadyExists (2002-0002)
00:00:00.878 |I| Gpu : Backend Threading (Auto): True
00:00:01.359 |N| Application LoadGuestApplication: Using Firmware Version: 16.0.0
00:00:01.359 |I| Application LoadGuestApplication: Loading as NSP.
00:00:01.394 |I| ModLoader QueryContentsDir: Searching mods for Title 0100000000010000
00:00:01.394 |I| ModLoader QueryContentsDir: Searching mods for Title 0100000000010000
00:00:01.400 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.404 |E| Application EnsureSaveData: Error calling EnsureApplicationSaveData. Result code ResultFsPathAlreadyExists (2002-0002)
00:00:01.405 |I| Loader LoadExeFs: Loading rtld...
00:00:01.440 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.440 |I| Loader LoadExeFs: Loading main...
00:00:01.605 |I| Loader PrintRoSectionInfo: main:
    Module: D:\home\JenkinsSlave\Jenkins\jobs\workspace\RedStar\GameNx_milestone\.result\RedStar\NX64\bin\Product\RedStar.nss
    SDK Libraries: SDK MW+Nintendo+NEX_DS-4_1_2
                   SDK MW+Nintendo+NEX-4_1_2-apprs
                   SDK MW+Nintendo+NintendoSDK_libcurl-3_5_1-Release
                   SDK MW+Nintendo+NintendoSDK_gfx-3_5_1-Release
                   SDK MW+Nintendo+NintendoWare_G3d-3_5_1-Release
                   SDK MW+Nintendo+NintendoWare_Atk-3_5_1-Release
                   SDK MW+Nintendo+NEX_RK-4_1_2
                   SDK MW+Nintendo+NEX_UT-4_1_2
                   SDK MW+Nintendo+NintendoWare_Ui2d-3_5_1-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-3_5_1-Release
                   SDK MW+Nintendo+NintendoWare_Font-3_5_1-Release
00:00:01.605 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.645 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-3_5_1-Release
00:00:01.645 |I| Loader LoadExeFs: Loading sdk...
00:00:01.676 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 3.5.1
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-3_5_1-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-3_5_1-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-3_5_1-Release
00:00:01.710 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:01.729 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:01.730 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:01.741 |I| Loader LoadNsos: Loading image 2 at 0x000000000a5ac000...
00:00:01.746 |I| Loader LoadNsos: Loading image 3 at 0x000000000ac67000...
00:00:01.751 |I| ModLoader LoadCheats: Build ids found for title 0100000000010000:
    A75512BE30BB2A8C880177505D7A0B3E24E9D642000000000000000000000000
    3CA12DFAAF9C82DA064D1698DF79CDA100000000000000000000000000000000
    798C30E126697F2222CF843F78F5C1406287619A000000000000000000000000
    AE34E75D02925F4417B24499AD80C39412FC76DB000000000000000000000000
00:00:01.751 |I| Loader LoadNca: Application Loaded: SUPER MARIO ODYSSEY v1.0.0 [0100000000010000] [64-bit]
00:00:01.814 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:01.821 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:01.822 |S| HLE.OsThread.17 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:01.825 |S| HLE.OsThread.17 ServiceAm AcquireForegroundRights: Stubbed. 
00:00:01.825 |S| HLE.OsThread.17 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:01.825 |S| HLE.OsThread.17 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:01.882 |N| GUI.RenderThread Gpu PrintGpuInformation: MoltenVK Apple M2 (Vulkan v1.2.231, Driver v0.2.2008)
00:00:01.887 |I| GPU.MainThread Gpu LoadShaders: Loading 0 shaders from the cache...
00:00:01.904 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:02.454 |S| HLE.OsThread.17 ServiceAm InitializeGamePlayRecording: Stubbed. 
00:00:02.455 |S| HLE.OsThread.17 ServiceAm SetGamePlayRecordingState: Stubbed. {_gamePlayRecordingState: True}
00:00:02.482 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed. 
00:00:02.486 |I| HLE.OsThread.17 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:02.499 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed. 
00:00:02.507 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed. 
00:00:02.532 |S| HLE.OsThread.10 ServiceNv SetNvMapFd: Stubbed. 
00:00:02.532 |S| HLE.OsThread.10 ServiceNv AllocGpfifoEx2: Stubbed. 
00:00:02.532 |S| HLE.OsThread.10 ServiceNv AllocObjCtx: Stubbed. 
00:00:02.533 |S| HLE.OsThread.10 ServiceNv SetErrorNotifier: Stubbed. 
00:00:02.533 |S| HLE.OsThread.10 ServiceNv SetUserData: Stubbed. 
00:00:02.534 |S| HLE.OsThread.10 ServiceNv SetPriority: Stubbed. 
00:00:02.535 |S| HLE.OsThread.10 ServiceNv ZcullBind: Stubbed. 
00:00:02.596 |S| HLE.OsThread.17 ServiceAcc InitializeApplicationInfo: Stubbed. {TitleId: 72057594037993472}
00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '
User Backtrace'

00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x0000000008b5ead0 (unknown)'

00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000acab2e8 (unknown)'

00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000acaa050 (unknown)'

00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000acaa114 (unknown)'

00:00:02.609 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000acb553c (unknown)'

00:00:02.610 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000877643c _ZN4sead17NinFileDeviceBase7doOpen_EPNS_10FileHandleERKNS_14SafeStringBaseIcEENS_10FileDevice12FileOpenFlagE + 0x1ac'

00:00:02.610 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000876e6a0 _ZN4sead10FileDevice7tryOpenEPNS_10FileHandleERKNS_14SafeStringBaseIcEENS0_12FileOpenFlagEj + 0x3c'

00:00:02.610 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x0000000008a83600 _ZN2al20SaveDataSequenceRead4readEPN4sead10FileDeviceEPKcPj + 0x68'

00:00:02.610 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x0000000008a83510 _ZN2al20SaveDataSequenceRead10threadFuncEPKc + 0x60'

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x0000000008a82ffc _ZN2al16SaveDataDirector8readSyncEPKcjj + 0x104'

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x00000000085194d0 _ZN11Application4initEiPPc + 0x2dc'

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000853b02c nnMain + 0x9c'

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: '  0x000000000accf6b4 (unknown)'

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: ''

00:00:02.611 |G| HLE.OsThread.17 ServiceLm Log: Guest Log:
  Log level: Info
    Line: 18
    Filename: 'D:/home/TokyoProject/RedStar/Library/sead/engine/library/modules/src/basis/nin/seadRawPrintNin.cpp'
    Function: 'PrintStringImpl'
    Module: ''
    Thread: 'MainThread'
    Message: 'SDK has been aborted or failed assertion with no message.'

00:00:02.611 |I| HLE.OsThread.17 ServiceAm SetTerminateResult: Result = 0x0035f202 (ResultFsNotMounted (2002-6905)).
00:00:03.064 |I| HLE.GuestThread.16 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 93
   0x000000000acaa05c	sdk:0x4305c	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, nn::Result const*, nn::os::UserExceptionInfo const*, char const*, ...)
   0x000000000acaa114	sdk:0x43114	nn::diag::detail::AbortImpl(char const*, char const*, char const*, int, char const*, ...)
   0x000000000acb553c	sdk:0x4e53c	nn::fs::OpenFile(nn::fs::FileHandle*, char const*, int):0x014c
   0x000000000877643c	main:0x77243c	sead::NinFileDeviceBase::doOpen_(sead::FileHandle*, sead::SafeStringBase<char> const&, sead::FileDevice::FileOpenFlag):0x01ac
   0x000000000876e6a0	main:0x76a6a0	sead::FileDevice::tryOpen(sead::FileHandle*, sead::SafeStringBase<char> const&, sead::FileDevice::FileOpenFlag, unsigned int):0x003c
   0x0000000008a83600	main:0xa7f600	al::SaveDataSequenceRead::read(sead::FileDevice*, char const*, unsigned int*):0x0068
   0x0000000008a83510	main:0xa7f510	al::SaveDataSequenceRead::threadFunc(char const*):0x0060
   0x0000000008a82ffc	main:0xa7effc	al::SaveDataDirector::readSync(char const*, unsigned int, unsigned int):0x0104
   0x00000000085194d0	main:0x5154d0	Application::init(int, char**):0x02dc
   0x000000000853b02c	main:0x53702c	nnMain:0x009c
   0x000000000accf6b4	sdk:0x686b4	nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)()):0x004c
   0x00000000080000ac	rtld:0x00ac	


00:00:03.065 |I| HLE.GuestThread.16 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
	X[00]:	0x0000000000000000
	X[01]:	0x0000000000000000
	X[02]:	0x0000000000000000
	X[03]:	0x0000000000000000
	X[04]:	0x0000000000000000
	X[05]:	0x0000000000000000
	X[06]:	0x0000000000000000
	X[07]:	0x0000000000000000
	X[08]:	0x0000000000008000
	X[09]:	0x0000000000000000
	X[10]:	0xfefefefefefefeff
	X[11]:	0x0000000000000080
	X[12]:	0x0000000000000000
	X[13]:	0x0000000000000000
	X[14]:	0x0000000000000000
	X[15]:	0x0000000000000000
	X[16]:	0x000000000ad10dec (sdk:0xa9dec)	=> nn::svc::aarch64::lp64::Break(nn::svc::BreakReason, unsigned long, unsigned long)
	X[17]:	0x000000000b5844a8
	X[18]:	0x0000000000000000
	X[19]:	0x0000000000000000
	X[20]:	0x000000118b903948 (SP:-0x0178)
	X[21]:	0x000000118b9039ac (SP:-0x01dc)
	X[22]:	0x000000000035f202
	X[23]:	0x000000000035f202
	X[24]:	0x0000000000000001
	X[25]:	0x0000001013c48790
	X[26]:	0x0000000000000500
	X[27]:	0x000000000a477aa8
	X[28]:	0x0000000009c520d8
	FP:	0x000000118b9037d0 (SP)
	LR:	0x000000000acab290 (sdk:0x44290)	=> nn::diag::detail::Abort():0x0018
	SP:	0x000000118b9037d0 (SP)
	PC:	0x0000000056000026


00:00:03.066 |W| HLE.GuestThread.18 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:03.066 |W| HLE.GuestThread.19 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:03.097 |E| HLE.GuestThread.16 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/SupervisorCall/Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/Ryujinx.Horizon.Generators/Ryujinx.Horizon.Generators.Kernel.SyscallGenerator/SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/Ryujinx.Horizon.Generators/Ryujinx.Horizon.Generators.Kernel.SyscallGenerator/SyscallDispatch.g.cs:line 3460
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/SupervisorCall/SyscallHandler.cs:line 38
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SupervisorCallHandler(UInt64 address, Int32 imm) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 104
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.SynchronousException(HvMemoryManager memoryManager, HvVcpu& vcpu) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 188
   at Ryujinx.Cpu.AppleHv.HvExecutionContext.Execute(HvMemoryManager memoryManager, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvExecutionContext.cs:line 146
   at Ryujinx.Cpu.AppleHv.HvCpuContext.Execute(IExecutionContext context, UInt64 address) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.Cpu/AppleHv/HvCpuContext.cs:line 30
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in /runner/_work/Ryujinx_Eve/Ryujinx_Eve/Ryujinx.HLE/HOS/Kernel/Threading/KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
```

**Comment by TimeZlicer** [comment] 2023-04-28 23:53
Good day

I cross check on `commit 21c4176157a1c7ef3086333ddb5036325869eac3 tag: 1.1.738`, this is not reproducible

The new behavior is as such
- right click on a game
- select 'Open User Save Directory'
- if the save folder is absent it would be created, hence no error

---

2 options
- wait for upsteam work to be done (and we get regular official releases) -> https://github.com/Ryujinx/Ryujinx/issues/4062
- build your own -> https://github.com/Ryujinx/Ryujinx/wiki#building

**Comment by AcK77** [comment] 2023-05-29 04:51
You can use our macOS universal build available on https://github.com/Ryujinx/release-channel-master/releases too.
I close this issue since it's currently fixed in master.

**Closed** 2023-05-29 04:51 UTC
Labels: bug, os:macOS
