### ISSUE TITLE
[Bug] Mario Odyssey action Guide Won't Open

### ISSUE THREAD

**Issue by Gronlyz** [Ryujinx/Ryujinx#6863] opened 2024-05-24 01:16 UTC
### Description of the issue

When Google for this issue. Found someone mentioning webapplet. Tried finding it in the settings but couldn't. 

When I press Action guide a small animation happens then screen when black for half seconds. Then nothing happens. Action Guide won't open. No crash

### Reproduction steps

Press action guide in Mario Odyssey. 

### Log file

https://github.com/Ryujinx/Ryujinx/assets/170687394/a4821fb5-6681-4c73-91a2-15d04b8bc6b1

### OS

Steam OS

### Ryujinx version

17.0.1

**Comment by MetrosexualGarbodor** [comment] 2024-05-24 01:21
Essentially a duplicate of #1004

**Closed by MetrosexualGarbodor** 2024-05-24 01:21 UTC
Labels: bug

**Comment by Gronlyz** [comment] 2024-05-24 01:26
Can someone please explain to me what should I do? I did saw that post https://github.com/Ryujinx/Ryujinx/issues/1004

But not sure what to do. Please help

**Comment by MetrosexualGarbodor** [comment] 2024-05-24 01:29
There's nothing you can do. In the future please use Discord for support questions.
