### ISSUE TITLE
[Pokemon Legends Arceus] Expand DRAM size to 6GB causes crash on start

### ISSUE THREAD

**Issue by d3xMachina** [Ryujinx/Ryujinx#3477] opened 2022-07-19 08:00 UTC
### What's the issue you encountered?

When the option "Expand DRAM size to 6GB" is checked in the options, the game crash at the very start.
This option is necessary to play with some mods to avoid crashes (I didn't have mods installed at the time of the test)

### How can the issue be reproduced?

Check the option "Expand DRAM size to 6GB" and start the game.

### Log file

[Ryujinx_1.1.182_2022-07-19_09-57-10.log](https://github.com/Ryujinx/Ryujinx/files/9138820/Ryujinx_1.1.182_2022-07-19_09-57-10.log)

### Environment?

- Ryujinx version: 1.1.182</br>
- Firmware : 14.1.2
- Game version: 1.0.0 and 1.1.1 (1.0.0 in the logs)</br>
- System Specs:
  - OS: Windows 10
  - CPU: Ryzen 3900X
  - GPU: GTX 1060 6GB
  - RAM: 32GB
- Applied Mods : No

### Additional context?

I tried with the 3 audio backends, the memory manager set to "Host (fast)" and "Software", the resolution scale set to native, PTC cache enabled and disabled.
I had 27GB memory available and 6GB GPU memory available (no other app using it in the background).
I tested with both 512.77 and 516.59 nvidia drivers.
With another game (Shin Megami Tensei V) I didn't have the issue.

**Comment by MetrosexualGarbodor** [comment] 2022-07-19 08:01
Duplicate of #3314.

**Closed by MetrosexualGarbodor** 2022-07-19 08:01 UTC
