### ISSUE TITLE
[Pokemon Shield] Random crash during battle.

### ISSUE THREAD

**Issue by mrmatt91** [Ryujinx/Ryujinx#2872] opened 2021-11-22 22:10 UTC
### What's the issue you encountered?

I entered the Budew Drop Inn in Motostoke City and confronted the Team Yell grunts. When the first grunt challenged me and sent out his zigzagoon, the game hung for a moment, then crashed abruptly. Before this point, I had wandered around the city and completed a few side quests such as finding a boy's minccino and discovering a Pay Day TM down near the waterfront. I haven't made any other changes to Ryujin outside of graphic settings.

Graphics Settings: 
VSync: Disabled
Enable Shader Cache: True
Anistropic Filtering: 16x
Resolution Scale: 4x
Aspect Ratio: 16:9
Graphics Backend Multithreading: Auto

### How can the issue be reproduced?

I was not able to reproduce this. Reloaded the game and repeated the above steps. The game works as expected.

### Log file

[Ryujinx_1.0.0-ldn2.4_2021-11-22_16-16-53.log](https://github.com/Ryujinx/Ryujinx/files/7584679/Ryujinx_1.0.0-ldn2.4_2021-11-22_16-16-53.log)

### Environment?

- Ryujinx version: 1.0.0-ldn2.4</br>
- Game version: 1.3.1</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Win 10
  - CPU: 10900k
  - GPU: NVIDIA RTX 2080
  - RAM: 32GB
- Applied Mods : [ Yes (Which ones) / No ]
No

**Comment by gdkchan** [comment] 2021-11-22 22:14
Duplicate of #1641.

**Closed by gdkchan** 2021-11-22 22:14 UTC
