### ISSUE TITLE
Big Brain Academy: Brain vs. Brain [0100620012D6E800] Multiplayer Crash

### ISSUE THREAD

**Issue by pavethem** [Ryujinx/Ryujinx#3519] opened 2022-08-01 15:07 UTC
### What's the issue you encountered?
Crash when attempting to start multiplayer

### How can the issue be reproduced?
1. Start Game
2. Select Party
3. Select number of players
4. Select "With Buttons"
5. Ryujinx freezes
### Log file

[Ryujinx_1.1.201_2022-08-01_17-03-24.log](https://github.com/Ryujinx/Ryujinx/files/9234946/Ryujinx_1.1.201_2022-08-01_17-03-24.log)

### Environment?

- Ryujinx version: 1.1.201</br>
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: 1.1.0</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Arch Linux
  - CPU:  i7-7700k)
  - GPU: NVIDIA GTX 1060
  - RAM: 16GB
- Applied Mods : No

**Comment by AcK77** [comment] 2022-08-08 11:50
Duplicate of #3503

**Closed** 2022-08-08 14:13 UTC
