### ISSUE TITLE
[Feature Request] Support for Gamepad

### ISSUE THREAD

**Issue by NetterTyp666** [Ryujinx/Ryujinx#7269] opened 2024-09-02 15:25 UTC
### Overview

Please enable gamepad input so that no mouse is required to move through the tiles, scroll up and down and start a game.

In addition, please enable silent auto updates.

### Smaller details

Ryujinx runs on my Windows HTPC and it's set to autorun in full screen right after boot. This works almost perfectly, but one thing is very bothersome: always a mouse input is required, which is quite a hassle to deal with in front of the living room TV. Instead, it would be very nice to just grab the gamepad and navigate the GUI.

Another thing is also a bit bothersome: when an update is available, always a user interaction is neccessary for confirmation. Why? I already set within the options that I wish to have updates, so please just execute it when available.

### Nature of request

Implement an option to enable gamepad navigation (similar to Yuzu).

Implement auto updates without the need for additional confirmation (similar to Yuzu), or implement an option to do so.

### Why would this feature be useful?

Greatly improve comfort for everyone who runs Ryujinx on a HTPC.

**Comment by ekuland** [comment] 2024-09-02 15:50
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/2793

**Closed by ekuland** 2024-09-02 15:50 UTC
Labels: enhancement
