### ISSUE TITLE
[Bug] Invisible Gloom Damage TOTK AMD

### ISSUE THREAD

**Issue by baranaksoy** [Ryujinx/Ryujinx#5017] opened 2023-05-19 15:28 UTC
### Description of the issue

Invisible Gloom Damage on specific parts of depths (lower than -600)

### Reproduction steps

1-) Go to depths where its around -530 and downwards (prefably death mountain crater)
2-) Walk around the level and you will get damage from gloom where the texture doesnt match

### Log file

[Ryujinx_1.1.807_2023-05-19_18-10-49.log](https://github.com/Ryujinx/Ryujinx/files/11518265/Ryujinx_1.1.807_2023-05-19_18-10-49.log)

### OS

Windows 11

### Ryujinx version

1.1.807

### Game version

1.1.0

### CPU

Ryzen 5 3600

### GPU

RX 570

### RAM

16 GB

### List of applied mods

30FPS Mod

### Additional context?

I will upload both my Save file where I get gloom damage and a video that supports my issue

https://www.youtube.com/watch?v=e033_semnwM

[Save_file.zip](https://github.com/Ryujinx/Ryujinx/files/11518326/Save_file.zip)

You can directly try it

**Comment by MetrosexualGarbodor** [comment] 2023-05-19 15:30
Duplicate of #4915

**Closed by MetrosexualGarbodor** 2023-05-19 15:30 UTC
Labels: bug
