### ISSUE TITLE
fsp-srv IFileSystemProxy: 53 (OpenReadOnlySaveDataFileSystem) not implemented.

### ISSUE THREAD

**Issue by HorrorTroll** [Ryujinx/Ryujinx#729] opened 2019-07-13 09:30 UTC
fsp-srv IFileSystemProxy: 53 (OpenReadOnlySaveDataFileSystem) is not implemented.

## Service description:
[Reswitched](https://reswitched.github.io/SwIPC/ifaces.html#nn::fssrv::sf::IFileSystemProxy(53))
```
OpenReadOnlySaveDataFileSystem(u8 save_data_space_id, nn::fssrv::sf::SaveStruct save_struct) -> object<nn::fssrv::sf::IFileSystem>
```

## Required by:
* https://github.com/Ryujinx/Ryujinx-Games-List/issues/188

**Comment by AcK77** [comment] 2019-09-02 03:47
Duplicate of #627

**Closed by AcK77** 2019-09-02 03:47 UTC
Labels: horizon, needs-re, not-implemented
