### ISSUE TITLE
Zelda TOTK Crashes when trying to use Autobuild ability[Bug]

### ISSUE THREAD

**Issue by klundtasaur** [Ryujinx/Ryujinx#5356] opened 2023-06-24 08:37 UTC
### Description of the issue

In an un-modded 1.1.2 version of TOTK, trying to gain the Autobuild ability (the mission requires you to use it to help 'researchers')--Ryujinx crashes immediately on any attempt to use the ability. 

### Reproduction steps

Load game (I've tried using save files from up to 20 minutes previous to the bug just in case--same problem). 
Try to use Autobuild power (I've tried using it in a different location, or far away from the quest area, same issue). 

Fixes I've attempted:
Use different save point
Update graphics drivers (AMD 7900XTX)
Clear PPTC and Shader cache

### Log file

[Ryujinx_1.1.905_2023-06-24_02-12-14.log](https://github.com/Ryujinx/Ryujinx/files/11855978/Ryujinx_1.1.905_2023-06-24_02-12-14.log)

### OS

Win11

### Ryujinx version

1.1.905

### Game version

1.1.2

### CPU

AMD Ryzen 7 5800x3d

### GPU

AMD 7900XTX

### RAM

32

### List of applied mods

None.

**Comment by klundtasaur** [comment] 2023-06-24 09:01
JK. Clearing PPTC and Shaders _again_ ended up fixing it. IDK why.

**Comment by klundtasaur** [comment] 2023-06-24 09:28
Ok, but now it crashes if I try to use Autobuild more than once.

**Comment by MutantAura** [comment] 2023-06-24 22:50
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4950

**Closed by MutantAura** 2023-06-24 22:50 UTC
Labels: bug
