### ISSUE TITLE
zelda TOTK  multiple failures on RDNA 3 amd 7900 xtx [Bug]

### ISSUE THREAD

**Issue by asp0909** [Ryujinx/Ryujinx#6566] opened 2024-03-27 05:15 UTC
### Description of the issue

the game plays with various graphical issues, texture flickering and shadows
In this video you can see a little of the problems that occur

https://youtu.be/OUXSahJQ6HI

### Reproduction steps

play the game on amd serial 7xxx rdna 3 gpu

### Log file

[Ryujinx_1.1.1247_2024-03-26_23-56-17.log](https://github.com/Ryujinx/Ryujinx/files/14767925/Ryujinx_1.1.1247_2024-03-26_23-56-17.log)

### OS

windows 11 pro 23h2

### Ryujinx version

1.1.1247

### Game version

1.20

### CPU

amd rizen  7800 x3d

### GPU

amd rx 7900 xtx

### RAM

32@6000 mhz

### List of applied mods

mods off...all default

**Comment by piplup55** [comment] 2024-03-27 06:58
duplicate of #6498 and #5306

**Closed by piplup55** 2024-03-27 06:58 UTC
Labels: bug
