### ISSUE TITLE
[Bug] Ryujinx does not recognize roms with several games (Five Nights at Freddy's: Core Collection)

### ISSUE THREAD

**Issue by willianholtz** [Ryujinx/Ryujinx#5907] opened 2023-11-08 21:04 UTC
### Description of the issue

The core version of Five Nights At Freddys does not work on Ryujinx, simply close the application when starting the rom!

### Reproduction steps

Try opening the game, and notice that Ryujinx only shows one version of the game (on mine it's 4):

![Screenshot_20231108_180125](https://github.com/Ryujinx/Ryujinx/assets/23488207/a37abcf4-07a9-40c8-9bba-c0f70a43d759)

### Log file

[Ryujinx_1.1.1069_2023-11-08_17-52-42.log](https://github.com/Ryujinx/Ryujinx/files/13301259/Ryujinx_1.1.1069_2023-11-08_17-52-42.log)

### OS

Arch Linux

### Ryujinx version

ryujinx-git

### CPU

Ryzen 7 5700x

### GPU

Nvidia RTX 2060

### RAM

64

### Additional context?

The same version of the game tested on Yuzu, identifies the 5 games contained in the rom. I believe that Ryujinx should do the same thing, or at least have an option that shows the game selection.

![Screenshot_20231108_180319](https://github.com/Ryujinx/Ryujinx/assets/23488207/695d837d-e162-43a1-85fb-f949cfc68719)

**Comment by gdkchan** [comment] 2023-11-08 21:05
Fixed by #5638?

**Comment by gdkchan** [comment] 2023-11-08 21:07
Duplicate of #3234.

**Closed by gdkchan** 2023-11-08 21:07 UTC
Labels: bug
