### ISSUE TITLE
Unhandled exception caught: SPB.Platform.Exceptions.PlatformException: WGL.CreateContext failed

### ISSUE THREAD

**Issue by treehub99** [Ryujinx/Ryujinx#2781] opened 2021-10-25 02:22 UTC
### What's the issue you encountered?

Ryujinx crashes silently when opening a game (Metroid Dread).

### How can the issue be reproduced?

For me, simply install keys/firmware then open a game.

### Log file

```
00:00:00.018 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.019 |I| Configuration LogValueChange: ResScale set to: 1
00:00:00.020 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.020 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.021 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.023 |I| Configuration LogValueChange: EnableDockedMode set to: True
00:00:00.024 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.024 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.024 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.024 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.025 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.025 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.026 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.026 |I| Configuration LogValueChange: ExpandRam set to: False
00:00:00.026 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.030 |N| Application PrintSystemInfo: Ryujinx Version: 1.0.7082
00:00:00.035 |N| Application Print: Operating System: Microsoft Windows 6.1.7601 Service Pack 1 (X64)
00:00:00.035 |N| Application Print: CPU: AMD Ryzen 9 5900X 12-Core Processor ; 3 logical
00:00:00.035 |N| Application Print: RAM: Total 16383 MB ; Available 12424 MB
00:00:00.037 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.037 |N| Application PrintSystemInfo: Launch Mode: Portable
00:00:18.898 |I| Application HandleInstallerDialog: Installing firmware 13.0.0
00:00:24.966 |I| Application HandleInstallerDialog: System version 13.0.0 successfully installed.
00:00:00.072 |I| Gpu : Backend Threading (Auto): True
00:00:00.804 |N| Application LoadApplication: Using Firmware Version: 13.0.0
00:00:00.804 |I| Application LoadApplication: Loading as XCI.
00:00:01.677 |I| ModLoader QueryContentsDir: Searching mods for Title 010093801237C000
00:00:01.689 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.975 |I| Loader LoadExeFs: Loading rtld...
00:00:02.039 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:02.039 |I| Loader LoadExeFs: Loading main...
00:00:02.627 |I| Loader PrintRoSectionInfo: main:
    Module: C:\perforcelocal\[ws00]\PRJ_04\GAME\Code\_output\NX64\apps\gameapp\Retail\cazadora.nss
    SDK Libraries: SDK MW+Nintendo+NintendoWare_Atk-11_4_3-Release
00:00:02.627 |I| Loader LoadExeFs: Loading subsdk0...
00:00:02.748 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_3-Release
00:00:02.748 |I| Loader LoadExeFs: Loading sdk...
00:00:02.989 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.3
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_3-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_3-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_3-Release
00:00:03.339 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:03.782 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:03.786 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:04.243 |I| Loader LoadNsos: Loading image 2 at 0x000000007a9c1000...
00:00:04.245 |I| Loader LoadNsos: Loading image 3 at 0x000000007b067000...
00:00:04.253 |I| ModLoader LoadCheats: Build ids found for title 010093801237C000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    49161D9CCBC15DF944D0B6278A3C446C006B0BE8000000000000000000000000
    507F19D1240D09D00992248E8A0FD77EBD784EB4000000000000000000000000
    2D369D9999E3E10E665106F840FFFF9BDAA0BB8E000000000000000000000000
00:00:04.253 |I| Loader LoadNca: Application Loaded: Metroid Dread v1.0.0 [010093801237c000] [64-bit]
00:00:04.262 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:04.600 |E| Application : Unhandled exception caught: SPB.Platform.Exceptions.PlatformException: WGL.CreateContext failed for dummy context: 2000
   at SPB.Platform.WGL.WGLHelper.EnsureInit()
   at SPB.Platform.WGL.WGLHelper.CreateContext(IntPtr& windowHandle, FramebufferFormat framebufferFormat, Int32 major, Int32 minor, OpenGLContextFlags flags, Boolean directRendering, IntPtr shareContext)
   at SPB.Platform.WGL.WGLOpenGLContext.Initialize(NativeWindowBase window)
   at Ryujinx.Ui.GlRenderer.IntializeOpenGL()
   at Ryujinx.Ui.GlRenderer.OnDrawn(Context cr)
   at Gtk.Widget.Drawn_cb(IntPtr inst, IntPtr cr)

```

### Environment?

- Ryujinx version: 1.0.7082
- Game version: 1.0
- System Specs:
  - OS: Windows 7
  - CPU: AMD Ryzen 9 5900X 12-Core
  - GPU: Nvidia GTX 1080
  - RAM: 16GB
- Applied Mods : No

**Comment by jagiella** [comment] 2021-11-12 17:36
i had the same problem on a newly installed system (Ubuntu 22.04 jammy jellyfish - developement release). 
After some googleing for an other issue making wayland run as window manager (instead of X11) with hardware acceleration, I read that one needs to install libnvidia-egl-wayland1.

So after
```bash
sudo apt install libnvidia-egl-wayland1
sudo reboot
```
also Ryujinx seems to work :) Who knows why.

**Comment by jagiella** [comment] 2021-11-13 09:17
The issue seems to be identical to #2220 already reported in April.

**Comment by MetrosexualGarbodor** [comment] 2022-02-11 03:35
Duplicate of #2112.

**Comment by edisionnano** [comment] 2022-02-13 14:44
I'm guessing the issue is Windows 7. We also dont know how old your drivers are.

**Comment by Eli0t77** [comment] 2022-02-13 18:00
i have windows 7 and cant reproduce this on Metroid Dread and Ryujinx 1.1.25

**Comment by edisionnano** [comment] 2022-02-13 19:38
> i have windows 7 and cant reproduce this on Metroid Dread and Ryujinx 1.1.25

They probably have old drivers

**Closed** 2022-03-15 17:37 UTC
Labels: bug
