### ISSUE TITLE
Nintendo 64 Collection not loading games on Ryujinx!!!!

### ISSUE THREAD

**Issue by jvhellraiser** [Ryujinx/Ryujinx#2790] opened 2021-10-27 14:50 UTC
Nintendo 64 Collection crashes as soon you try to load a game.

### When trying to load a game within the app it crashes.

[i load the Nintendo 64 collection app/ryujinx loads it nicely sadly once you try to load a game ryujinx crashes.
[ Did you make any changes related to Ryujinx itself? ] ( That's a N/A)

### How can the issue be reproduced?
Same as before just loaded and try to launch a game.

### Log file 
[Ryujinx_1.0.7091_2021-10-27_10-14-37.log](https://github.com/Ryujinx/Ryujinx/files/7427082/Ryujinx_1.0.7091_2021-10-27_10-14-37.log)

### Environment?

- Ryujinx version: Ryujinx_1.0.7091
- Game version: Nintendo 64 - Nintendo Switch Online v1.0.0

- System Specs:
  - OS: (Windows 11)
  - CPU: ( i7-9700K)
  - GPU: (NVIDIA RTX 2060)
  - RAM: (16GB)*
- Applied Mods : [ No ]

![Screenshot 2021-10-27 104900](https://user-images.githubusercontent.com/16488761/139090419-0f198f2a-f0d2-409f-a607-2993e9433c33.png)

**Comment by AcK77** [comment] 2021-11-06 17:04
Duplicate of #2042

**Closed by AcK77** 2021-11-06 17:04 UTC
Labels: not-implemented, service-implementation
