### ISSUE TITLE
Diablo II Resurrected - Not preserving save games consistently

### ISSUE THREAD

**Issue by oldskool75** [Ryujinx/Ryujinx#2757] opened 2021-10-19 01:49 UTC
## Bug Report

</br>

### What's the issue you encountered?

Save games not preserving / persisting correctly. </br>
</br>
Save games are stored in:
 .../bis/user/save/xxxxx/0/...
On game start, this is copied to:
 .../bis/user/save/xxxxx/1/...
And this seems to be the active directory that is used throughout the game session - when game is saved, the files in the '1' dir are updated (and '0' dir remains the same).</br>
</br>
When one exits the game (Esc),  ryujinx asks for confirmation of exit. Upon confirmation, seemingly randomly, the dir '1' contents will be copied over to the '0' dir. This is a successful preservation of the same game state. Other times, dir '1' is NOT copied back to dir '0', and on next game load, dir '0' will copy over dir '1' again,  removing the previous progress. There doesn't seem to be any console/log indication that the game can or cannot preserve dir '1' back to dir '0' on exit (I will check more thoroughly later tonight).

### How can the issue be reproduced?
Open explorer window at game's user save dir with some game progress. Note the .../0/\<charName>/\<files> timestamps.</br>
Start game, notice .../0/\<charName>/\<files> timestamps now match dir 0's... okay game, make some progress, then 'save and exit'. Note the timestamps update in dir '1'. (Game is back at character select screen)</br>
Press ESC, ryujinx will confirm exit... if successful, dir 0 contents will be updated to match dir 1 contents. If not successful, dir0 will not be updated (dir1 will have more recent timestamps).</br>
Restart/relaunch game from ryujinx, dir0 contents will copy over dir1 contents again. If dir1 was more recent, it won't be anymore and all previous progress made will be lost. 

### Log file

No reference at all to "save" (savegame dir, save actions, etc) </br>
Will try again and attach log file. 

### Environment?

- Ryujinx version: 1.0.7058</br>
- Game version: 1.0.0.2 (also all previous versions)</br>
- System Specs:
  - OS: *Windows 10 (21H1)*
  - CPU: *i7-6700k*
  - GPU: *NVIDIA RTX 3060Ti*
  - RAM: *16GB*
- Applied Mods : none

### Additional context?

Additional info about your environment:</br>
N/a

**Comment by Thealexbarney** [comment] 2021-12-19 00:53
How often does saving the game not work? Every time? Rarely?

**Comment by LV99VIVI** [comment] 2021-12-24 05:43
had this bug too, i think it has to do with file write permissions or something. tested with and without portable folder, portable folder would always work, appdata [default] directory wouldnt. doing take ownership and stuff stiff didnt work for me either.

idk why devs insist on putting things in weird write protected areas like program files and appdata. Good thing you guys implemented an optional portable mode. got some devs with head screwed on straight here.

have saves in a folder like C/games/ryujinx/portable/xxx/xxx/xx/xxx/xx/x

**Comment by Thealexbarney** [comment] 2021-12-24 09:26
> 20 times in a row black screen is kinda annoying

That doesn't sound like the original issue. The issue was about save commits not "sticking". Or is the black screen unrelated?

**Comment by systox** [comment] 2022-01-03 08:38
I have also had this issue with Metroid Dread.

**Comment by oldskool75** [comment] 2022-01-04 00:40
> How often does saving the game not work? Every time? Rarely?

Sorry, i stopped playing the game and had moved on. But it wasn't 100% of the time, but it was more frequent than not. By just watching the save game for timestamps on quitting and startup, you can see when it updates dir0 and/or dir1.

When I did look for it in the logs, i never saw any lines indicating savegame for copy (or not copy), unfortunately.

**Comment by systox** [comment] 2022-01-04 14:11
> How often does saving the game not work? Every time? Rarely?

Rarely, seemed to happen more if I x'd out of the emulator. I have since converted the emulator to 'portable' mode and haven't run into the issue again. Will update here if it recurs.

**Comment by AcK77** [comment] 2022-02-07 11:13
Is this still happen on the latest Ryujinx version (some changes have been made to the FS service) ?

**Comment by AcK77** [comment] 2022-03-15 17:29
No anwser after a month, I close it. (feel free to reply if you want to)

**Closed by AcK77** 2022-03-15 17:29 UTC
Labels: bug, service:fs

**Comment by nativepapaya** [comment] 2024-02-22 23:54
I can confirm this is still happening. I several ours of progress in BOTW due to this. Like mentioned above, it doesn't happen often, seems completely random. Sometimes 0 will be updated from the contents of 1, but not always. It has made me pretty paranoid and has me checking the save directory every single time.
