### ISSUE TITLE
Monster hunter rise sunbreak not opening past menu on macOS

### ISSUE THREAD

**Issue by 07alvii** [Ryujinx/Ryujinx#5747] opened 2023-09-29 13:55 UTC
### Description of the issue

the game starts off by loading saved data and checking for add ons but crashes every time on the latest Ryujinx. Base game is playable but not the sun break title update.

### Reproduction steps

downloaded Ryujinx and monster hunter rise, sun break update and dlc. applied all add ons and title update, but did not run Base game runs.

### Log file

[Ryujinx_1.1.1035_2023-09-29_08-45-21.log](https://github.com/Ryujinx/Ryujinx/files/12766264/Ryujinx_1.1.1035_2023-09-29_08-45-21.log)
[Ryujinx_1.1.1037_2023-09-29_08-46-05.log](https://github.com/Ryujinx/Ryujinx/files/12766265/Ryujinx_1.1.1037_2023-09-29_08-46-05.log)
[Ryujinx_1.1.1037_2023-09-29_08-51-46.log](https://github.com/Ryujinx/Ryujinx/files/12766266/Ryujinx_1.1.1037_2023-09-29_08-51-46.log)

### OS

macOS Sonoma

### Ryujinx version

1.1.1037

### CPU

M 1
### GPU

M1 8 core
### RAM

8 gb

### List of applied mods

none

**Comment by gdkchan** [comment] 2023-09-29 15:01
Duplicate of #5235, but it might be better to keep this one open to keep compatibility on macOS (and becuse this is more organized than the other one).

**Comment by GamerzHell9137** [comment] 2023-12-04 21:20
This one can be closed too.

**Closed** 2024-02-22 14:03 UTC
Labels: bug
