### ISSUE TITLE
Custom folders for game organization! 

### ISSUE THREAD

**Issue by theStyleWithin** [Ryujinx/Ryujinx#6445] opened 2024-03-09 00:16 UTC
### Overview

Make viewing your games easier and organized. 

### Smaller details

Organization feature

### Nature of request

new idea for Ryujinx

### Why would this feature be useful?

So that I can find my games easier

**Comment by minimar** [comment] 2024-03-09 00:20
Duplicate of #3144

**Comment by piplup55** [comment] 2024-03-10 22:18
as mentioned above it's a duplicate

**Closed by piplup55** 2024-03-10 22:18 UTC
