### ISSUE TITLE
[Bug] Latset update frequent vertex explosions in tottk

### ISSUE THREAD

**Issue by d9j** [Ryujinx/Ryujinx#5557] opened 2023-08-12 11:31 UTC
### Description of the issue

So far i see it's happening in depths.. if just go around depth especially areas with enemies 

<img width="1705" alt="截屏2023-08-12 下午7 24 01" src="https://github.com/Ryujinx/Ryujinx/assets/2436637/997ce729-2e04-49c6-af71-5f3c62f79eb7">

### Reproduction steps

So far i see it's happening in depths.. if just go around depths especially areas with enemies 

[save.zip](https://github.com/Ryujinx/Ryujinx/files/12327262/save.zip)

### Log file

[Ryujinx_1.1.980_2023-08-12_18-49-19.log](https://github.com/Ryujinx/Ryujinx/files/12327249/Ryujinx_1.1.980_2023-08-12_18-49-19.log)

### OS

m1 macos ventura 13.2.1 (22D68)

### Ryujinx version

1.1.980

### Game version

1.1.1

### CPU

m1 max

**Comment by IsaacMarovitz** [comment] 2023-08-12 11:36
This would not be caused by 1.1.980, the update was entirely UI-side and did not touch emulator functionality.

**Comment by piplup55** [comment] 2023-08-12 11:41
adding on to the latest comment vertex explosions are completely random, also you should really be using https://github.com/Ryujinx/Ryujinx/pull/4899#issuecomment-1545007093

**Comment by d9j** [comment] 2023-08-12 12:53
Surprisingly after relaunching game. killing emulator and opening again . the problem no longer occurs  in extent shown in screenshot

**Comment by MutantAura** [comment] 2023-08-12 15:44
As this is random and unrelated to any recent update I'll close this.

**Closed by MutantAura** 2023-08-12 15:44 UTC
Labels: bug
