### ISSUE TITLE
m1 mac support

### ISSUE THREAD

**Issue by janhp** [Ryujinx/Ryujinx#2053] opened 2021-02-23 16:02 UTC
any chance to get m1 mac support?

if there is a possibilty to compile it myself, can someone please create a step by step instruction?

thanks a lot and keep going!

**Comment by Shahil-Ayato** [comment] 2021-02-23 16:04
There are a lot of things needed for support on MacOS and M1 Macs

Metal API support is needed so graphics can render

ARM support is needed 

and .net needs to be supported on MacOS and .net 6 seems to be support MacOS

**Comment by EmulationFanatic** [comment] 2021-02-23 16:08
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1805

**Closed by EmulationFanatic** 2021-02-23 16:08 UTC
