### ISSUE TITLE
[Regression] #3828 causes UI flickering in Fate/Extella: The Umbral Star

### ISSUE THREAD

**Issue by GamerzHell9137** [Ryujinx/Ryujinx#4468] opened 2023-02-23 01:38 UTC
### Description of the issue

#3828 causes flickering of the UI in Fate/Extella: The Umbral Star

### Reproduction steps

Just going to the main menu of the game

https://user-images.githubusercontent.com/2002038/220802965-9aed5c63-d94d-471e-81b1-217c3be2c063.mp4

### Log file

N/A

### OS

Windows 10

### Ryujinx version

1.1.635

### Game version

v1.0.0

### CPU

Ryzen 3600

### GPU

NVIDIA RTX 3060 Ti

### RAM

16 GB

**Comment by Squall-Leonhart** [comment] 2023-02-23 07:33
duplicate of #4466

**Comment by GamerzHell9137** [comment] 2023-02-23 19:36
> duplicate of #4466

The linked thread is more like a bug report for a game that should be in the compatibility github rather than here.
The one i made is a regression report with the linked PR that broke the game which is fine on reporting here.

**Closed** 2023-05-02 15:55 UTC
Labels: bug

**Comment by gdkchan** [comment] 2023-05-02 15:56
I don't think that issue was fixed.
