### ISSUE TITLE
Missing applet cause SOR4 to crash at end of levels

### ISSUE THREAD

**Issue by legend800** [Ryujinx/Ryujinx#1187] opened 2020-04-30 23:49 UTC
Streets of Rage 4 is fully playable other than a crash that happens at the end of levels.

![122](https://user-images.githubusercontent.com/20983844/80769598-91c4a300-8b02-11ea-8da2-0cca3e70a44b.png)

Build:
Master 1.0.4378

Error:
System.NotImplementedException: 0 applet is not implemented.

Log:
[Ryujinx_2020-04-29_23-23-56.zip](https://github.com/Ryujinx/Ryujinx/files/4561893/Ryujinx_2020-04-29_23-23-56.zip)

**Comment by HorrorTroll** [comment] 2020-05-01 00:51
Can you update full log? That doesn’t help much for knowing issue anyway

**Comment by legend800** [comment] 2020-05-01 01:06
Full log doesn't help much for knowing issue anyway? It's going to take me half an hour to beat the first stage again to get that. If needed _**and**_ it'll help diagnose, I can supply that.

**Comment by gdkchan** [comment] 2020-05-01 01:21
It can be tested on Dead or Alive Xtreme 3 Scarlet, it has the same error and only takes a few seconds to trigger.

**Comment by HorrorTroll** [comment] 2020-05-01 02:00
It need GetAppletInfo from NIFM Service, if that service was ignored. It will cause 0 applet is missing

GetAppletInfo is trying to read NetConnect Applet, since we didn’t support that yet so when ignored the service. The game just read at unknown 0 applet

**Comment by Seker-0** [comment] 2020-05-01 13:23
**The game Samurai Shodown also has issues**
`0 applet is not implemented`

**I have to use the stub applet from here: https://github.com/Ryujinx/Ryujinx/pull/1048 In order to be able to boot** 
![SS](https://user-images.githubusercontent.com/35269098/80808166-243f7200-8be9-11ea-9614-9f9eda0b5964.jpg)
Of course, this game is UE4. There are still graphics problems

**master version**
![ss2](https://user-images.githubusercontent.com/35269098/80808306-7a141a00-8be9-11ea-8e7b-c5d07713bd9d.jpg)
Logs
[SS.log](https://github.com/Ryujinx/Ryujinx/files/4564312/SS.log)

**Comment by HorrorTroll** [comment] 2020-05-01 14:44
Caused by missing service like i said above, just again. Try turn off ignore service before report

**Comment by Seker-0** [comment] 2020-05-01 15:30
**turn off ignore service**
`Ryujinx.HLE.HOS.Services.Nifm.StaticService.IRequest: 21`
Full logs @HorrorTroll 
[IIRC.log](https://github.com/Ryujinx/Ryujinx/files/4564942/IIRC.log)

**Comment by AcK77** [comment] 2020-07-07 02:06
I think this should be fixed in #1326 now. Can anyone confirm ?

**Comment by Seker-0** [comment] 2020-07-07 11:36
Yes, it is resolved. We should close this issue @AcK77 
Samurai Shatab is now booted. But there is still a problem of crashes With other errors
Dead or Alive Xtreme 3 Scarlet and Tetris 99 are also booting.

**Closed** 2020-07-20 23:42 UTC
