### ISSUE TITLE
[Bug] Intel Arc graphics using ANV on Linux performs poorly under some conditions

### ISSUE THREAD

**Issue by kode54** [Ryujinx/Ryujinx#4412] opened 2023-02-13 10:13 UTC
### Description of Issue

The ANV driver performs poorly at certain things, like the overworld of some levels in Super Mario Odyssey, like Desert Kingdom after finishing the underground level and the desert is hot again. It achieves around 10fps, with a FIFO usage between 60% and 100%, and the CPU is hitting 300% for the Ryujinx process, indicating that all threads are maxed out.

### Reproduction Steps

1. Install Super Mario Odyssey
2. Install the latest patch
3. Configure Ryujinx to use Vulkan
4. Boot the game
5. Reach a complex level such as Sand Kingdom
6. Observe the horrible frame rates

### Log File

[ryujinx_log.txt](https://github.com/Ryujinx/Ryujinx/files/10721104/ryujinx_log.txt)

### OS

Arch Linux

### Ryujinx version

1.1.617

### Game version

1.3.0

### CPU

Ryzen 7 2700

### GPU

Intel Arc A770 FE 16GB

### RAM

32GB

### Additional context?

This performance is actually worse than when I was originally running the game using the RADV driver with my previous video card, an AMD RX 480 8GB.

Apparently nobody has reported this here on the bug tracker yet, even though someone called it to my attention over a month ago, even before I actually bought the A770.

In fact, Super Mario Odyssey manages to achieve better and more playable frame rates on this A770 using the OpenGL driver, where it gets 45-60fps on the same desert level. Of course, it also takes about three times as long to compile the shaders on startup.

Is the problem entirely my CPU? Or is this also the fault of the ANV driver not being nearly up to the job of utilizing the GPU's full power? I haven't found a relevant bug on the Mesa bug tracker, either. Thank you kind Linux Gaming Dev user for simply whining about the problem on Discord instead of actually posting bug reports.

**Comment by Squall-Leonhart** [comment] 2023-02-14 09:19
the ANV driver is only optimized for CPU based Graphics adapters at the present time, and the Arc add in cards require Resizable Bar for full performance.

**Comment by kode54** [comment] 2023-02-14 10:23
I am running on 23.0 tip, which I update almost daily, on a 6.2-rc7 kernel. Resizable Bar is most definitely turned on. ANV needs work. I guess I should report this to them as an example of where they could use some attention.

**Comment by AcK77** [comment] 2023-05-05 07:51
As it doesn't seems to be an issue specific to Ryujinx and more like a driver issue.
I close this, thanks.

(It could be reopened in case the issue is really a Ryujinx's one)

**Closed by AcK77** 2023-05-05 07:51 UTC
Labels: bug

**Comment by kode54** [comment] 2023-05-06 00:38
Following up: This does not affect the new Xe kernel driver, and it didn't affect the VM_BIND version of the i915 kernel driver and matching Mesa, even though those have been dropped before being merged. The Xe driver does look like it will be merged eventually, though.

This is definitely a driver issue, and one which is being worked on presently.
