### ISSUE TITLE
[Bug] Stretchy textures in Tears of the Kingdom

### ISSUE THREAD

**Issue by morceaudebois** [Ryujinx/Ryujinx#4962] opened 2023-05-15 10:21 UTC
### Description of the issue

When playing Tears of the Kingdom, some NPCs can have their 3D models completely stretched. Notable examples include blue chuchus, flux constructs and glowing fish.

![photo_2023-05-15 12 09 39](https://github.com/Ryujinx/Ryujinx/assets/50768582/d398f62d-2d64-46b0-aa78-755a71903a90)

### OS

macOS 12

### Ryujinx version

1.1.799

### Game version

1.0.0

### CPU

M1 Pro

### RAM

16GB

### List of applied mods

30fps mod and VisualFixes

**Comment by Foul-Tarnished** [comment] 2023-05-15 10:55
Duplicate of #4949

**Closed** 2023-05-15 17:57 UTC
Labels: bug
