### ISSUE TITLE
[Feature Request] Custom options per game

### ISSUE THREAD

**Issue by Rafacasari** [Ryujinx/Ryujinx#6660] opened 2024-04-13 01:47 UTC
### Overview

Currently the only way to change a setting for a game is by changing the global settings but this affect all other games, my request is to add some type of "**Override Settings**" menu for each game (when right-clicking the game), so you can choose specific settings for that game.

### Smaller details

When right-clicking a game in the game-list, add a "Override Settings" button that would popup a window similar to the settings window, in this window you can override options like system language, graphic settings and more

### Nature of request

I'm using a translation for Animal Crossing that requires the game to be in Spanish, but at the same time I want to play other games in English/Portuguese, so I always need to remember changing language before launching a game. 

### Why would this feature be useful?

Would be useful for games that you want a specific language or a specific graphic setting (maybe even a specific controller layout?)

**Comment by MetrosexualGarbodor** [comment] 2024-04-13 01:48
Duplicate of #1796

**Closed by MetrosexualGarbodor** 2024-04-13 01:48 UTC
