### ISSUE TITLE
[Feature Request]

### ISSUE THREAD

**Issue by YingDoge** [Ryujinx/Ryujinx#6692] opened 2024-04-20 07:12 UTC
### Overview

More filter for downsampling

### Smaller details

That we need more filter espically for down sampling buecase a lot of people now day have a good GPU and CPU but still stuck on 1080p monitors 

### Nature of request

For better grafic for people has 1080p and good GPU

### Why would this feature be useful?

It will improve the grafic of the games

**Comment by MutantAura** [comment] 2024-04-20 14:24
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4905

**Closed by MutantAura** 2024-04-20 14:24 UTC
