### ISSUE TITLE
Choosing "Manage DLC" for a title throws an Unhandled Exception

### ISSUE THREAD

**Issue by zimmertr** [Ryujinx/Ryujinx#2003] opened 2021-02-08 05:52 UTC
### What's the issue you encountered?

Selecting "Manage DLC" for a title in Ryujinx throws an unhanded exception. 

### How can the issue be reproduced?

Select "Manage DLC"

### Log file

```
00:16:59.369 |E| Application : Unhandled exception caught: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'G:\Games\Switch\temp\v-acronh_pocket_camp_dlc_01006f800232712c.nsp'.
   at System.IO.FileStream.ValidateFileHandle(SafeFileHandle fileHandle)
   at System.IO.FileStream.CreateFileOpenHandle(FileMode mode, FileShare share, FileOptions options)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options)
   at Ryujinx.Ui.Windows.DlcWindow..ctor(Builder builder, VirtualFileSystem virtualFileSystem, String titleId, String titleName) in C:\projects\ryujinx\Ryujinx\Ui\Windows\DlcWindow.cs:line 76
   at Ryujinx.Ui.Widgets.GameTableContextMenu.ManageDlc_Clicked(Object sender, EventArgs args) in C:\projects\ryujinx\Ryujinx\Ui\Widgets\GameTableContextMenu.cs:line 460
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at System.Delegate.DynamicInvokeImpl(Object[] args)
   at GLib.Signal.ClosureInvokedCB(Object o, ClosureInvokedArgs args)
   at GLib.SignalClosure.MarshalCallback(IntPtr raw_closure, IntPtr return_val, UInt32 n_param_vals, IntPtr param_values, IntPtr invocation_hint, IntPtr marshal_data)
```

### Environment?

- Ryujinx version: 1.0.6521</br>
- Game version: 1.7.0</br>
- System Specs:
  - OS: Windows 10
  - CPU: i7-8700k
  - GPU: RTX 3090
  - RAM: 32GB DDR4
- Applied Mods: No

**Comment by EmulationFanatic** [comment] 2021-02-08 13:52
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/1366
To workaround this issue, which occurs if you have deleted or moved the dlc file after applying it to a game, delete the dlc.json file in appdata\roaming\ryujinx\games\game ID\

**Closed by EmulationFanatic** 2021-02-08 13:52 UTC

**Comment by zimmertr** [comment] 2021-02-08 19:34
Thanks :) 

I did try and search before posting but for some reason didn't find that issue.
