### ISSUE TITLE
Changing system date

### ISSUE THREAD

**Issue by GucciHassan** [Ryujinx/Ryujinx#4031] opened 2022-12-05 22:51 UTC
## Bug Report

[ ]</br>
[ ]

### What's the issue you encountered?

[ Changing the date of the system does not affect the date in the game, for me this occurred in Pokémon scarlet. ]</br>
[ No ]</br>
[ N/A ]

### How can the issue be reproduced?

[ Open pokemon Scarlet or Violet. In the game open your map to see mass outbreaks, while having your map open change the date of your system and look if the outbreaks change in the game. ]

### Log file

[ N/A ]</br>
[ ]

### Environment?

- Ryujinx version: 1.1.428</br>
[  ]
- Game version: 1.0.1</br>
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: *Windows 10*
  - CPU: **
  - GPU: **
  - RAM: **
- Applied Mods : [ No ]

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by gdkchan** [comment] 2022-12-05 22:53
Duplicate of #2866.

**Closed by gdkchan** 2022-12-05 22:53 UTC
