### ISSUE TITLE
No More Heroes 3 Deathman Error

### ISSUE THREAD

**Issue by Chayannekun** [Ryujinx/Ryujinx#2608] opened 2021-08-30 17:36 UTC
This ocurrs after the Deathman Cutscene when you enter the game, i have tried to look a fix on the forums but nothing yet
![image](https://user-images.githubusercontent.com/89801855/131380825-1a892b82-27a7-4b8a-a243-a8590b9236ff.png)
Any solution?

**Comment by gdkchan** [comment] 2021-08-30 17:39
Intel does not support ARB_shader_ballot on Windows (and has other issues).

**Comment by Chayannekun** [comment] 2021-08-30 17:40
Oh....so the only solution is change the the processor right?

**Comment by gdkchan** [comment] 2021-08-30 17:42
Do you have a graphics card? If so you can try to make the emulator use it, otherwise you'll need to wait for improvements to Intel iGPUs. You can also try Vulkan (#2518 and #2520), as it works better on Intel in general.

**Comment by gdkchan** [comment] 2021-09-09 18:36
Can't reproduce the issue here with a Intel UHD 630, the game renders fine.
![image](https://user-images.githubusercontent.com/5624669/132743570-75a8b72b-0170-4577-a5f0-c29161517555.png)

**Comment by AcK77** [comment] 2022-06-24 01:04
No more informations from the user, since a dev can’t reproduce the issue, I close it.

**Closed by AcK77** 2022-06-24 01:04 UTC
Labels: bug, gpu
