### ISSUE TITLE
[Feature Request] Mouse to motion control

### ISSUE THREAD

**Issue by LexyDrow44WasTaken** [Ryujinx/Ryujinx#4621] opened 2023-03-30 23:12 UTC
Hello devs
suggestion : 
add support for mouse-controlled motion controls (for 3d games with camera motion controls)

i know there is a tool that allows to map the mouse to a right stick input. this would also be good to have on ryujinx. the problem is that it's kinda janky, it doesn't move like you would move a mouse on a pc game. the max speed of the camera stays the max speed of the stick.

motion controls don't have the same limitations, and it's possible and viable on a physical switch (example : https://www.youtube.com/watch?v=h-j140DV7Sk )
it appears to be impossible on ryujinx however.

a lot of players would appreciate full on PC FPS controls i believe, especially people like me that have a HARD time managing the camera on a stick lmao. 
many PC enjoyers simply aren't used to it.
what do you think?

**Comment by MutantAura** [comment] 2023-04-18 17:31
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/3749

**Closed by MutantAura** 2023-04-18 17:31 UTC

**Comment by LilyArlatto** [comment] 2024-09-04 02:36
I apologize for bringing this issue back from the dead but while it does have something to do with motion controls mentioned in #3749, it is, in fact, not the same suggestion. #3749 is asking for the ability to remap the Gyro directions to some other axis/button so that controllers that lack proper gyro can still complete sections of games that absolutely require Gyro.

#4621 is asking for Ryujinx to accept mouse inputs like a first-person-shooter style game, which is currently impossible as far as I can tell. Adding a feature like this would be incredible for PC users, as being able to play FPS motion control games with actual mouse control would be a nice alternative to using a controller.

**Comment by MetrosexualGarbodor** [comment] 2024-09-04 02:41
#2063
