### ISSUE TITLE
[Feature Request] Silent auto updates

### ISSUE THREAD

**Issue by NetterTyp666** [Ryujinx/Ryujinx#7273] opened 2024-09-03 05:42 UTC
### Overview

Please enable silent auto updates.

### Smaller details

When an update is available, always a user interaction is neccessary for confirmation. Why? I already set within the options that I wish to have updates, so please just execute it immediately when available.

### Nature of request

Implement auto updates without the need for additional confirmation (similar to other emus), or implement an option to enable this explicitly.

### Why would this feature be useful?

Improve comfort, especially for anyone who runs Ryujinx on a HTPC (because the less mouse interactions are necessary the better).

**Comment by piplup55** [comment] 2024-09-03 08:18
Duplicate of #7245

**Closed by piplup55** 2024-09-03 08:18 UTC
Labels: enhancement
