### ISSUE TITLE
[Bug] Mario Odyssey Random Screen Flashes

### ISSUE THREAD

**Issue by shehzman** [Ryujinx/Ryujinx#6472] opened 2024-03-12 18:08 UTC
### Description of the issue

When playing Super Mario Odyssey, I would get these flashes of multiple colors at seemingly random times throughout my playthrough. I've attached some screenshots of what they look like:

![image](https://github.com/Ryujinx/Ryujinx/assets/65638519/80c0d10b-0998-4291-b477-d1094d33f673)
 
![image](https://github.com/Ryujinx/Ryujinx/assets/65638519/dae4a573-a6ab-4604-b369-f4e15ad2f744)

![image](https://github.com/Ryujinx/Ryujinx/assets/65638519/17069b62-3e8b-4569-b34f-84307f59e997)

![image](https://github.com/Ryujinx/Ryujinx/assets/65638519/88889057-d13d-4bd6-9a8e-282a3d915ee7)

### Reproduction steps

Boot up the game and play it for a couple of minutes. At seemingly random times, these flashes will appear for a split second then disappear.

### Log file

[Ryujinx_1.1.1224_2024-03-12_11-57-01.log](https://github.com/Ryujinx/Ryujinx/files/14576680/Ryujinx_1.1.1224_2024-03-12_11-57-01.log)

### OS

Windows 10

### Ryujinx version

1.1.1224

### Game version

1.3.0

### CPU

AMD Ryzen 7 5800X3D

### GPU

NVIDIA RTX 3080

### RAM

32GB

### List of applied mods

None

**Comment by gdkchan** [comment] 2024-03-12 21:02
This is a resolution scale issue.

**Comment by MutantAura** [comment] 2024-03-14 18:54
Duplicate of https://github.com/Ryujinx/Ryujinx/issues/4580

**Closed by MutantAura** 2024-03-14 18:54 UTC
Labels: bug, gpu
