### ISSUE TITLE
[Bug] Fullscreen Crash on Macbook Air M2 with macOS Sonoma

### ISSUE THREAD

**Issue by tokimpoi15** [Ryujinx/Ryujinx#5734] opened 2023-09-27 11:49 UTC
### Description of the issue
The whole laptop freezes when I toggled Fullscreen mode. This happened after updating to macOS Sonoma.

### Reproduction steps
1. Load the game
2. Toggle fullscreen mode

### Log file
[Ryujinx_1.1.1032_2023-09-27_13-45-22.log](https://github.com/Ryujinx/Ryujinx/files/12738516/Ryujinx_1.1.1032_2023-09-27_13-45-22.log)

### OS
macOS Sonoma 14.0

### Ryujinx version
1.1.1032

### Game version
No response

### CPU
M2

### GPU
M2

### RAM
16GB

### List of applied mods
No response

### Additional context?
To resolve the problem I had to force restart the laptop. This also happens if you toggle fullscreen mode while compiling shaders.

**Comment by AcK77** [comment] 2023-09-27 23:56
Duplicate of #5524

**Closed by AcK77** 2023-09-27 23:56 UTC
Labels: bug, os:macOS
