### ISSUE TITLE
[Bug] [Mac]

### ISSUE THREAD

**Issue by ballo** [Ryujinx/Ryujinx#6036] opened 2023-12-14 23:47 UTC
### Description of the issue

If you pause the game long enough for the controller to sleep (dualsense in this case) it will complain about it then fail to use the controller even after it's reconnected. 

### Reproduction steps

1) pause game
2) do something that takes a while like write a bug report
3) try to recover control of the game in progress to no avail. End up retarting ryujinx and continuing from the last safe state (assuming you have one). 

### Log file

[Ryujinx_1.1.1098_2023-12-14_16-46-26.log](https://github.com/Ryujinx/Ryujinx/files/13679332/Ryujinx_1.1.1098_2023-12-14_16-46-26.log)

### OS

MacOS Ventura 

### Ryujinx version

1.1.1098

### Game version

any

### CPU

M1 8 core

### GPU

M1 8 core

### RAM

16GB

**Comment by ballo** [comment] 2023-12-14 23:48
Crap, I can't edit the title

**Comment by OldManKain** [comment] 2023-12-14 23:52
Duplicate of #3973

**Closed by OldManKain** 2023-12-14 23:52 UTC
Labels: bug
