### ISSUE TITLE
intelARCa750 TOTK crashes after the first CG[Bug][intel][ARCA750]

### ISSUE THREAD

**Issue by QLZZ597** [Ryujinx/Ryujinx#4948] opened 2023-05-14 15:31 UTC
### Description of the issue

intelARCa750 TOTK crashes after the first CG crash.
It also crashes in the subsequent CGs.
After my test on intel driver only 4257 4255 can open TOTK normally.
Intel drivers above 4257 can not open TOTK. 

### Reproduction steps

Open TOTK with an intel discrete or integrated graphics card.
Start the game from the beginning.

### Log file

[Ryujinx_1.1.800_2023-05-14_22-46-30.zip](https://github.com/Ryujinx/Ryujinx/files/11472242/Ryujinx_1.1.800_2023-05-14_22-46-30.zip)

### OS

Win11

### Ryujinx version

1.1.800

### Game version

1.1

### CPU

AMD5700xCPU

### GPU

intelARCA750

### RAM

16GB

### Additional context?

[Test Video.zip](https://github.com/Ryujinx/Ryujinx/files/11472281/Test.Video.zip)
[zip format to z01.zip](https://github.com/Ryujinx/Ryujinx/files/11472282/zip.format.to.z01.zip)
[zip format to z02.zip](https://github.com/Ryujinx/Ryujinx/files/11472283/zip.format.to.z02.zip)
[zip format to z03.zip](https://github.com/Ryujinx/Ryujinx/files/11472285/zip.format.to.z03.zip)
![111](https://github.com/Ryujinx/Ryujinx/assets/133491479/1453a537-d0a2-42f7-aa36-9c5511fdf96a)

**Comment by QLZZ597** [comment] 2023-05-14 15:42
![Uploading 111.png…]()

**Comment by MetrosexualGarbodor** [comment] 2023-05-14 15:50
Duplicate of #4922

**Closed by MetrosexualGarbodor** 2023-05-14 15:50 UTC
Labels: bug

**Comment by armadio-cocco** [comment] 2023-05-15 10:58
so i only have to install the 4257 driver and it will be fine?

**Comment by armadio-cocco** [comment] 2023-05-15 15:59
just install the 4257 driver (https://www.intel.com/content/www/us/en/download/729157/intel-arc-iris-xe-graphics-beta-windows.html) 
after that, open the game in openGL and play trough all the first part, for me it was really glitchy with the shaders.
at the point you can save the game, create a save and exit the game, then open it in vulkan

i have done this and it worked
