### ISSUE TITLE
[Bug]Failed to setup time-zone in ava-ryujinx-1.1.0-ldn3.1.3

### ISSUE THREAD

**Issue by WaveBird** [Ryujinx/Ryujinx#5109] opened 2023-05-26 15:58 UTC
### Description of the issue

Setting up time zone for in system doesn't have any effect and it will go back to UTC.
Version: ava-ryujinx-1.1.0-ldn3.1.3-win_x64
![Video_2023-05-26_234926](https://github.com/Ryujinx/Ryujinx/assets/51294125/4ca1c920-e602-4922-9229-e598c9437d67)

### Reproduction steps

1. Set up time zone in setting from UTC to UC+8 and Save
2. Reopen timezone and it will go back to UTC

### Log file

None

### OS

windows 10

### Ryujinx version

ava-ryujinx-1.1.0-ldn3.1.3

### Game version

2.000

### CPU

i7

### GPU

1060

### RAM

8

**Comment by IsaacMarovitz** [comment] 2023-05-27 17:06
The dialogue is a little confusing; you aren't free to type whatever you want. If you type "UTC+08" it should supply you with a list of results which you can select. Those should save as intended.

**Comment by WaveBird** [comment] 2023-05-28 03:45
Thanks for your reply, I try several values, the video above just show one case. And I looked into the code, and created a file named binaryList.txt, and place it under `%APPDATA%\Ryujinx` or `%APPDATA%\Ryujinx\config` and they all didn't work.
https://github.com/Ryujinx/Ryujinx/blob/42b9c1e8fede88880454154f8c3683f1f8424ed9/src/Ryujinx.HLE/HOS/Services/Time/TimeZone/TimeZoneContentManager.cs#L100
binaryList.txt looks like below
```
Europe/Andorra
Asia/Kabul
America/Anguilla
Asia/Yerevan
Antarctica/McMurdo
Antarctica/Casey
Antarctica/Davis
Antarctica/DumontDUrville
Antarctica/Mawson
Antarctica/Palmer
Antarctica/Rothera
Antarctica/Syowa
Antarctica/Troll
Antarctica/Vostok
America/Argentina/Buenos_Aires
America/Argentina/Cordoba
America/Argentina/Salta
America/Argentina/Jujuy
America/Argentina/Tucuman
America/Argentina/Catamarca
America/Argentina/La_Rioja
America/Argentina/San_Juan
America/Argentina/Mendoza
America/Argentina/San_Luis
America/Argentina/Rio_Gallegos
America/Argentina/Ushuaia
Pacific/Pago_Pago
Australia/Lord_Howe
Antarctica/Macquarie
Australia/Hobart
Australia/Melbourne
Australia/Sydney
Australia/Broken_Hill
Australia/Brisbane
Australia/Lindeman
Australia/Adelaide
Australia/Darwin
Australia/Perth
Australia/Eucla
America/Aruba
Asia/Baku
America/Barbados
Europe/Brussels
Europe/Sofia
Africa/Bujumbura
America/St_Barthelemy
Asia/Brunei
America/Kralendijk
America/Belem
America/Fortaleza
America/Recife
America/Araguaina
America/Maceio
America/Bahia
America/Sao_Paulo
America/Campo_Grande
America/Cuiaba
America/Santarem
America/Porto_Velho
America/Boa_Vista
America/Manaus
America/Eirunepe
America/Rio_Branco
America/Nassau
Africa/Gaborone
America/Belize
America/Halifax
America/Glace_Bay
America/Moncton
America/Goose_Bay
America/Blanc-Sablon
America/Toronto
America/Iqaluit
America/Atikokan
America/Winnipeg
America/Resolute
America/Rankin_Inlet
America/Regina
America/Swift_Current
America/Edmonton
America/Cambridge_Bay
America/Inuvik
America/Creston
America/Dawson_Creek
America/Fort_Nelson
America/Whitehorse
America/Dawson
America/Vancouver
Indian/Cocos
Africa/Lubumbashi
Africa/Bangui
Europe/Zurich
Pacific/Rarotonga
America/Punta_Arenas
Pacific/Easter
Africa/Douala
Asia/Urumqi
America/Bogota
America/Havana
America/Curacao
Asia/Nicosia
Asia/Famagusta
Europe/Prague
Europe/Busingen
Africa/Djibouti
America/Dominica
Africa/Algiers
Pacific/Galapagos
Europe/Tallinn
Africa/El_Aaiun
Europe/Madrid
Africa/Ceuta
Atlantic/Canary
Africa/Addis_Ababa
Pacific/Fiji
Pacific/Chuuk
Pacific/Pohnpei
Pacific/Kosrae
Atlantic/Faroe
Africa/Libreville
America/Grenada
America/Cayenne
Africa/Accra
America/Nuuk
America/Danmarkshavn
America/Scoresbysund
America/Thule
Africa/Banjul
America/Guadeloupe
Europe/Athens
America/Guatemala
Africa/Bissau
Asia/Hong_Kong
Europe/Zagreb
Europe/Budapest
Asia/Pontianak
Asia/Makassar
Asia/Jayapura
Europe/Dublin
Europe/Isle_of_Man
Indian/Chagos
Asia/Tehran
Europe/Rome
America/Jamaica
Asia/Tokyo
Asia/Bishkek
Pacific/Tarawa
Pacific/Kanton
Pacific/Kiritimati
Indian/Comoro
Asia/Pyongyang
Asia/Kuwait
Asia/Almaty
Asia/Qyzylorda
Asia/Qostanay
Asia/Aqtobe
Asia/Aqtau
Asia/Atyrau
Asia/Oral
Asia/Vientiane
America/St_Lucia
Asia/Colombo
Africa/Maseru
Europe/Luxembourg
Africa/Tripoli
Europe/Monaco
Europe/Podgorica
Indian/Antananarivo
Pacific/Kwajalein
Europe/Skopje
Asia/Yangon
Asia/Hovd
Asia/Choibalsan
Asia/Macau
America/Martinique
America/Montserrat
Indian/Mauritius
Africa/Blantyre
America/Cancun
America/Merida
America/Monterrey
America/Matamoros
America/Chihuahua
America/Ciudad_Juarez
America/Ojinaga
America/Mazatlan
America/Bahia_Banderas
America/Hermosillo
America/Tijuana
Asia/Kuala_Lumpur
Asia/Kuching
Africa/Maputo
Pacific/Noumea
Pacific/Norfolk
America/Managua
Europe/Oslo
Pacific/Nauru
Pacific/Auckland
Pacific/Chatham
Asia/Muscat
America/Lima
Pacific/Marquesas
Pacific/Gambier
Pacific/Port_Moresby
Pacific/Bougainville
Asia/Manila
Europe/Warsaw
Pacific/Pitcairn
Asia/Gaza
Asia/Hebron
Europe/Lisbon
Atlantic/Madeira
Atlantic/Azores
Pacific/Palau
Asia/Qatar
Europe/Bucharest
Europe/Kaliningrad
Europe/Moscow
Europe/Simferopol
Europe/Kirov
Europe/Volgograd
Europe/Astrakhan
Europe/Saratov
Europe/Ulyanovsk
Europe/Samara
Asia/Yekaterinburg
Asia/Omsk
Asia/Novosibirsk
Asia/Barnaul
Asia/Tomsk
Asia/Novokuznetsk
Asia/Krasnoyarsk
Asia/Irkutsk
Asia/Chita
Asia/Yakutsk
Asia/Khandyga
Asia/Vladivostok
Asia/Ust-Nera
Asia/Magadan
Asia/Sakhalin
Asia/Srednekolymsk
Asia/Kamchatka
Asia/Anadyr
Africa/Kigali
Pacific/Guadalcanal
Africa/Khartoum
Asia/Singapore
Europe/Ljubljana
Europe/Bratislava
Europe/San_Marino
Africa/Mogadishu
Africa/Juba
America/El_Salvador
Asia/Damascus
America/Grand_Turk
Indian/Kerguelen
Asia/Bangkok
Pacific/Fakaofo
Asia/Ashgabat
Pacific/Tongatapu
America/Port_of_Spain
Asia/Taipei
Europe/Kyiv
Africa/Kampala
Pacific/Wake
America/New_York
America/Detroit
America/Kentucky/Louisville
America/Kentucky/Monticello
America/Indiana/Indianapolis
America/Indiana/Vincennes
America/Indiana/Winamac
America/Indiana/Marengo
America/Indiana/Petersburg
America/Indiana/Vevay
America/Chicago
America/Indiana/Tell_City
America/Indiana/Knox
America/Menominee
America/North_Dakota/Center
America/North_Dakota/New_Salem
America/North_Dakota/Beulah
America/Denver
America/Boise
America/Phoenix
America/Los_Angeles
America/Anchorage
America/Juneau
America/Sitka
America/Metlakatla
America/Yakutat
America/Nome
America/Adak
Pacific/Honolulu
America/Montevideo
Asia/Tashkent
Europe/Vatican
America/Caracas
America/St_Thomas
Pacific/Efate
Pacific/Apia
Indian/Mayotte
Africa/Lusaka
```

**Comment by AcK77** [comment] 2023-05-28 06:40
`binaryList.txt` file is readed from the firmware archive data, so put a file at different locations will not change anything. Does the issue occurs on main build too?

**Comment by WaveBird** [comment] 2023-05-31 09:44
What does main build means? other version of ryujinx is ok except ldn version.

**Comment by MutantAura** [comment] 2023-06-24 23:26
This issue was fixed in master. You will need to wait for a rebase of LDN.
Thanks.

**Closed by MutantAura** 2023-06-24 23:26 UTC
Labels: bug
