### ISSUE TITLE
[Bug] OpenGL backend crashes on Linux

### ISSUE THREAD

**Issue by rmvdesign** [Ryujinx/Ryujinx#4864] opened 2023-05-08 20:31 UTC
### Description of the issue

When trying to select the OpenGL backend, the preferred GPU setting becomes greyed out and empty. Any games launched when this setting is active makes Ryujinx crash to desktop.

### Reproduction steps

1. Run Linux (In this case, Ubuntu)
2. Have an NVIDIA Graphics Card
3. Select OpenGL as your graphics backend
4. Launch a game
5. Ryujinx tries to load the game, but crashes to desktop

### Log file

[Ryujinx_1.1.772_2023-05-08_22-30-26.log](https://github.com/Ryujinx/Ryujinx/files/11424936/Ryujinx_1.1.772_2023-05-08_22-30-26.log)

### OS

Linux (Ubuntu 22)

### Ryujinx version

1.1.772

### Game version

1.1.0

### CPU

R7 2700X

### GPU

RTX 2070 SUPER

### RAM

16GB

### List of applied mods

n/a

**Comment by TSRBerry** [comment] 2023-05-08 20:34
This bug is exclusive to Avalonia and only happens with Nvidia for some reason. Thank you for opening an issue about that, I forgot I wanted to look into that as well.

**Comment by CoolFrenchPerson** [comment] 2023-05-09 15:57
Duplicate of #4600

**Comment by TSRBerry** [comment] 2023-05-09 20:50
Ah crap, you are right. Thank you. The reminder still helped me! :D

Closing as duplicate of #4600

**Closed by TSRBerry** 2023-05-09 20:50 UTC
Labels: bug
