### ISSUE TITLE
Ryujinx staying open as active process no matter how game is exited

### ISSUE THREAD

**Issue by lolDayus** [Ryujinx/Ryujinx#4064] opened 2022-12-07 21:07 UTC
## Bug Report

[ If any section does not apply, replace its contents with "N/A". ]</br>
[ Lines between [ ] (square brackets) should be removed before posting. ]

### What's the issue you encountered?

[ Describe the issue in detail and what you were doing beforehand. ]</br> Ryujinx stays open in the task manager and still consumes resources as if I was still using it indefinitely after I exit from in-game. It'll just create instances over itself if I try to re-open the program without clearing the original from task manager
[ Did you make any changes related to Ryujinx itself? ]</br>only a couple of the latest updates
[ If so, make sure to include details relating to what exactly you changed. ]

### How can the issue be reproduced? Exit Ryujinx from inside a game (it doesn't seem to do it if you just load up the initial home screen and exit that without booting up a game).

[ Include a detailed step by step process for recreating your issue. ]

### Log file

[ Logs files can be found under ``Logs`` folder in Ryujinx program folder. ]</br>
[ If you don't include a crash report in instances of crash related issues, we will ask you one to provide one. ]

### Environment?

- Ryujinx version: 1.0.X</br> 1.14138
[ Replace X's with the Ryujinx version at time of crash. ]
- Game version: X.X.X</br>Tactics Ogre: Reborn 1.0.2
[ Replace X's with the game version at time of crash. ]
- System Specs:
  - OS: Windows 11
  - CPU: Intel(R) Core(TM) i7-8700K CPU @ 3.70GHz   
  - GPU: NVIDIA RTX 3070 Ti
  - RAM: 32 GB
- Applied Mods : [ Yes (Which ones) / No ]No

### Additional context?

Additional info about your environment:</br>
[ Any other information relevant to your issue. ]

**Comment by gdkchan** [comment] 2022-12-07 21:48
Isn't that the same as #2863?

**Comment by lolDayus** [comment] 2022-12-08 00:00
> Isn't that the same as #2863?

it's not "hanging" or freezing in any way. It just keeps running in the background (i.e. screen is fine, everything "looks" normal but it's taking up resources in the background) after you exit it even though there's no way to interact with that instance other than removing it out of the task manager

**Comment by Abyss777111** [comment] 2022-12-08 06:48
My game is emulated perfectly

when you need to exit, click stop emulation and the emulator hangs in the manager, 2 emulator processes hang after the emulator closes with an error with sending a report to microsoft, well, or you can remove it without waiting from the manager

smt 5 game

**Comment by Mclaneinc** [comment] 2023-01-14 12:53
I had that issue, I found out by research and trial and error that it was ZoneAlarm (in my case) stopping the emulator from fully terminating. Apparently it's a habit of some Virus checkers when they are set to real time care. In my case, if I switch off ZA when doing an update it all works fine, before if I had ran the emulator previously in the same session it would not allow me to update it as it was classed as open and no kill process type commands would work as the virus checker was pulling rank even over Admin rights..Weird..

**Comment by m3talslug** [comment] 2023-03-12 20:39
I have the same issue. Open Ryujinx, then just file>exit. The processes ryujinx and ryujinx.sh persist in the task manager. I'm doing this on a Steam Deck. Both standard and Ava build

**Comment by Mclaneinc** [comment] 2023-03-13 12:01
As said, some AV software tends to hang on to a process and just suspend it rather than terminating it, Rkill and the like will not kill it either. It's a pain as it's hogging CPU

**Comment by AcK77** [comment] 2023-05-05 07:58
> I have the same issue. Open Ryujinx, then just file>exit. The processes ryujinx and ryujinx.sh persist in the task manager. I'm doing this on a Steam Deck. Both standard and Ava build
This is not the same OS and as far as I remember it's already fixed in a merged PR.

For the OP, it could be you AV since no one are able to reproduce the issue. I close this issue and we'll reopen it if anyone else got the issue too. Thanks.

**Closed by AcK77** 2023-05-05 07:58 UTC

**Comment by Avrution** [comment] 2024-03-29 09:03
Oddly enough, I have the same issue.  1.1.1248 playing 13 Sentinels.  I can do Stop emulation right after starting the game and it will actually go back to the menu, but doing so after playing a while and the game will just hang.  Quitting Ryujinx keeps the program open and has to be force killed from task manager

**Comment by GamerzHell9137** [comment] 2024-03-29 10:36
> Oddly enough, I have the same issue. 1.1.1248 playing 13 Sentinels. I can do Stop emulation right after starting the game and it will actually go back to the menu, but doing so after playing a while and the game will just hang. Quitting Ryujinx keeps the program open and has to be force killed from task manager

I think this issue started happening again, was fixed before but its back now.
