### ISSUE TITLE
Fatal crash on 1.1.191 version 

### ISSUE THREAD

**Issue by Darcelsan** [Ryujinx/Ryujinx#3486] opened 2022-07-25 04:15 UTC
Hello! I updated my Ryujinx to the latest version (1.1.191) and the app crash everytime I try to launch my game with this log: 

```
00:00:34.948 |W| HLE.GuestThread.18 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.23 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.17 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.20 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.19 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.21 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.948 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.949 |W| HLE.GuestThread.22 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:34.949 |W| HLE.GuestThread.25 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.011 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 55
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 55
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()

```

**Comment by gdkchan** [comment] 2022-07-25 04:21
Please provide the full log and the game name. There's nothing we can do with the information you provided.

**Comment by Darcelsan** [comment] 2022-07-25 04:22
Here is the full log, sorry: 

`00:00:00.003 |I| Configuration LogValueChange: EnableFileLog set to: True
00:00:00.050 |I| Configuration LogValueChange: ResScale set to: 4
00:00:00.055 |I| Configuration LogValueChange: ResScaleCustom set to: 1
00:00:00.055 |I| Configuration LogValueChange: MaxAnisotropy set to: -1
00:00:00.056 |I| Configuration LogValueChange: AspectRatio set to: Fixed16x9
00:00:00.057 |I| Configuration LogValueChange: BackendThreading set to: Auto
00:00:00.058 |I| Configuration LogValueChange: EnableDockedMode set to: False
00:00:00.065 |I| Configuration LogValueChange: EnableVsync set to: True
00:00:00.065 |I| Configuration LogValueChange: EnableShaderCache set to: True
00:00:00.066 |I| Configuration LogValueChange: EnablePtc set to: True
00:00:00.066 |I| Configuration LogValueChange: EnableInternetAccess set to: False
00:00:00.066 |I| Configuration LogValueChange: EnableFsIntegrityChecks set to: True
00:00:00.066 |I| Configuration LogValueChange: FsGlobalAccessLogMode set to: 0
00:00:00.067 |I| Configuration LogValueChange: AudioBackend set to: SDL2
00:00:00.067 |I| Configuration LogValueChange: AudioVolume set to: 1
00:00:00.067 |I| Configuration LogValueChange: MemoryManagerMode set to: HostMappedUnsafe
00:00:00.068 |I| Configuration LogValueChange: ExpandRam set to: True
00:00:00.068 |I| Configuration LogValueChange: IgnoreMissingServices set to: False
00:00:00.072 |N| Application PrintSystemInfo: Ryujinx Version: 1.1.191
00:00:00.077 |N| Application Print: Operating System: Microsoft Windows 10.0.22000 (X64)
00:00:00.077 |N| Application Print: CPU: Intel(R) Core(TM) i7-10750H CPU @ 2.60GHz ; 12 logical
00:00:00.078 |N| Application Print: RAM: Total 16205 MB ; Available 11022 MB
00:00:00.080 |N| Application PrintSystemInfo: Logs Enabled: Info, Warning, Error, Guest, Stub
00:00:00.080 |N| Application PrintSystemInfo: Launch Mode: UserProfile
00:00:00.044 |I| Gpu : Backend Threading (Auto): True
00:00:01.085 |N| Application LoadApplication: Using Firmware Version: 13.0.0
00:00:01.085 |I| Application LoadApplication: Loading as XCI.
00:00:01.183 |I| ModLoader QueryContentsDir: Searching mods for Title 01001F5010DFA000
00:00:01.185 |I| ModLoader QueryContentsDir: Searching mods for Title 01001F5010DFA000
00:00:01.194 |I| Application EnsureSaveData: Ensuring required savedata exists.
00:00:01.202 |I| Loader LoadExeFs: Loading rtld...
00:00:01.280 |I| Loader PrintRoSectionInfo: rtld:
    Module: nnrtld
00:00:01.280 |I| Loader LoadExeFs: Loading main...
00:00:01.865 |I| Loader PrintRoSectionInfo: main:
    Module: C:\jenkins\workspace\hayabusa\rom\localrombuild\program\output\NX64\Release\main.nss
    SDK Libraries: SDK MW+NINTENDO+nlib_LZ4-20_0714
                   SDK MW+Nintendo+NintendoSDK_libcurl-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_libz-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Font-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Ui2d-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_Vfx-11_4_0-Release
                   SDK MW+Nintendo+NintendoWare_G3d-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NPLN-0_28_0-Release
                   SDK MW+Nintendo+gRPC-0_0_0+NPLN
                   SDK MW+Nintendo+OpenSSL-0_0_0+NPLN
                   SDK MW+Nintendo+PiaCommon-6_16_2
                   SDK MW+Nintendo+Pia-6_16_2
                   SDK MW+Nintendo+PiaLocal-6_16_2
                   SDK MW+Nintendo+PiaLan-6_16_2
                   SDK MW+Nintendo+PiaSession-6_16_2
                   SDK MW+Nintendo+PiaTransport-6_16_2
                   SDK MW+Nintendo+PiaNpln-6_16_2
                   SDK MW+Nintendo+NintendoSDK_gfx-11_4_0-Release
                   SDK MW+Microsoft+Havok_AI-2020_2
00:00:01.866 |I| Loader LoadExeFs: Loading subsdk0...
00:00:01.921 |I| Loader PrintRoSectionInfo: subsdk0:
    Module: multimedia
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_movie-11_4_0-Release
00:00:01.921 |I| Loader LoadExeFs: Loading subsdk1...
00:00:02.008 |I| Loader PrintRoSectionInfo: subsdk1:
    Module: glslc
00:00:02.008 |I| Loader LoadExeFs: Loading sdk...
00:00:02.119 |I| Loader PrintRoSectionInfo: sdk:
    Module: nnSdk
    FS SDK Version: 11.4.0
    SDK Libraries: SDK MW+Nintendo+NintendoSDK_libz-11_4_0-Release
                   SDK MW+Nintendo+NintendoSdk_nnSdk-11_4_0-Release
                   SDK MW+Nintendo+NintendoSDK_NVN-11_4_0-Release
00:00:02.167 |I| Ptc Initialize: Initializing Profiled Persistent Translation Cache (enabled: True).
00:00:04.588 |I| Ptc Load: Loaded Translation Cache (size: 216674584 bytes, translated functions: 91852).
00:00:04.609 |I| Ptc Load: Loaded Profiling Info (size: 303213 bytes, profiled functions: 91852).
00:00:05.369 |I| Loader LoadNsos: Loading image 0 at 0x0000000008000000...
00:00:05.370 |I| Loader LoadNsos: Loading image 1 at 0x0000000008004000...
00:00:05.393 |I| Loader LoadNsos: Loading image 2 at 0x000000000c310000...
00:00:05.395 |I| Loader LoadNsos: Loading image 3 at 0x000000000c9b6000...
00:00:05.398 |I| Loader LoadNsos: Loading image 4 at 0x000000000d37e000...
00:00:05.415 |I| ModLoader LoadCheats: Build ids found for title 01001F5010DFA000:
    6F8B1226CC8CD958021D6BFD226EBF23F892AB9B000000000000000000000000
    7FCAD279539DE183B25C11834FD4A030591CFE25000000000000000000000000
    535249A546887CAC875A099E9C8EF367077CF58B000000000000000000000000
    4DD097B435891C5E0E15A65DBE47124F4D7FD1C1000000000000000000000000
    B39ADD63421BE525D352E576DAB438D3812EFDF0000000000000000000000000
00:00:05.415 |I| Loader LoadNca: Application Loaded: Légendes Pokémon : Arceus v1.0.0 [01001f5010dfa000] [64-bit]
00:00:05.428 |I| GUI.WindowThread Hid Configure: Configured Controller JoyconPair to Player1
00:00:07.316 |I| GUI.WindowThread Hid SetupNpad: Connected Controller JoyconPair to Player1
00:00:07.495 |N| GUI.RenderLoop Gpu PrintGpuInformation: NVIDIA Corporation NVIDIA GeForce RTX 3060 Laptop GPU/PCIe/SSE2 (4.6.0 NVIDIA 516.59)
00:00:07.527 |I| GPU.MainThread Gpu LoadShaders: Loading 1425 shaders from the cache...
00:00:10.818 |I| GPU.MainThread Gpu LoadShaders: Shader cache loaded.
00:00:12.097 |I| HLE.GuestThread.15 Ptc LoadTranslations: 91852 translated functions loaded
00:00:12.276 |S| HLE.OsThread.16 ServiceAm GetAppletResourceUserId: Stubbed. {appletResourceUserId: 1}
00:00:12.286 |S| HLE.OsThread.16 ServiceAm AcquireForegroundRights: Stubbed.
00:00:12.286 |S| HLE.OsThread.16 ServiceAm SetFocusHandlingMode: Stubbed. {unknownFlag1: False ; unknownFlag2: False ; unknownFlag3: True}
00:00:12.286 |S| HLE.OsThread.16 ServiceAm SetOutOfFocusSuspendingEnabled: Stubbed. {outOfFocusSuspendingEnabled: False}
00:00:12.302 |S| HLE.OsThread.16 ServicePctl Initialize: Stubbed.
00:00:24.999 |W| HLE.GuestThread.15 KernelSvc : MapPhysicalMemory() = ResLimitExceeded
00:00:34.650 |S| HLE.OsThread.9 ServiceHid ActiveNpadImpl: Stubbed. {appletResourceUserId: 1 ; revision: 3}
00:00:34.655 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadIdType: Stubbed. 2 Players: Player1,Handheld
00:00:34.656 |S| HLE.OsThread.9 ServiceHid SetSupportedNpadStyleSet: Stubbed. {pid: 92 ; appletResourceUserId: 1 ; type: ProController, Handheld}
00:00:34.656 |S| HLE.OsThread.16 ServiceAm SetPerformanceModeChangedNotification: Stubbed. {performanceModeChangedNotification: True}
00:00:34.657 |I| GUI.WindowThread Hid SetupNpad: Connected Controller ProController to Player1
00:00:34.721 |S| HLE.OsThread.10 ServiceNv FinishInitialize: Stubbed.
00:00:34.732 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 1
00:00:34.734 |I| HLE.OsThread.16 SurfaceFlinger CreateLayerFromId: Creating layer 2
00:00:34.750 |S| HLE.OsThread.10 ServiceNv InitializeEx: Stubbed.
00:00:34.777 |S| HLE.OsThread.10 ServiceNv GetActiveSlotMask: Stubbed.
00:00:34.919 |W| HLE.GuestThread.15 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:34.919 |W| HLE.GuestThread.15 KernelSvc : MapPhysicalMemory() = OutOfMemory
00:00:34.976 |G| HLE.OsThread.16 ServiceLm Log: Guest Log:
  Log level: Info
    Time: 34s
    Line: 0
    Filename: ''
    Function: ''
    Module: ''
    Thread: 'MainThread'
    ProgramName: 'main'
    Message: 'Pure virtual function called!'

00:00:34.987 |I| HLE.OsThread.16 ServiceAm SetTerminateResult: Result = 0x000002a2 (ResultErrApplicationAborted (2162-0001)).
00:00:35.323 |I| HLE.GuestThread.15 Cpu PrintGuestStackTrace: Guest stack trace:
Process: Application, PID: 92
   0x000000000d4c3038   sdk:0x145038
   0x000000000d4c3164   sdk:0x145164
   0x000000000d4c4044   sdk:0x146044
   0x000000000d8e4094   sdk:0x566094
   0x000000000d89f3dc   sdk:0x5213dc
   0x000000000d88e3f8   sdk:0x5103f8
   0x000000000d88deb4   sdk:0x50feb4
   0x000000000d7f4668   sdk:0x476668
   0x000000000aa5f38c   main:0x2a5b38c
   0x000000000aa5b968   main:0x2a57968
   0x000000000aa87454   main:0x2a83454
   0x000000000aa6a954   main:0x2a66954
   0x000000000aa69750   main:0x2a65750
   0x000000000a99dda0   main:0x2999da0
   0x000000000a744a40   main:0x2740a40
   0x000000000a7437a0   main:0x273f7a0
   0x000000000a7484f4   main:0x27444f4
   0x000000000a7411e8   main:0x273d1e8  nnMain:0x0088
   0x000000000d62e4c4   sdk:0x2b04c4    nn::init::Start(unsigned long, unsigned long, void (*)(), void (*)(), void (*)()):0x0054
   0x00000000080000d4   rtld:0x00d4


00:00:35.326 |I| HLE.GuestThread.15 Cpu PrintGuestRegisterPrintout: Guest CPU registers:
        X[00]:  0x0000000000000000
        X[01]:  0x00000049f0708208 (SP:-0x01a8)
        X[02]:  0x0000000000000004
        X[03]:  0x000000000000000c
        X[04]:  0x0000000000000000
        X[05]:  0x0000000000000000
        X[06]:  0x0000000000000000
        X[07]:  0x0000000000000000
        X[08]:  0x0000000100000000
        X[09]:  0x000000000d37e000 (sdk:0x0000) =>
        X[10]:  0x0000000000c696c8
        X[11]:  0x0000000000800000
        X[12]:  0x0000000000000000
        X[13]:  0x000000000000000e
        X[14]:  0x0000000000000002
        X[15]:  0x0000000000000000
        X[16]:  0x000000000d4c4870 (sdk:0x146870)       => nn::diag::detail::Abort(nn::Result const*)
        X[17]:  0x000000000dfe76c8
        X[18]:  0x0000000000000000
        X[19]:  0x00000049f0708208 (SP:-0x01a8)
        X[20]:  0x0000000000000000
        X[21]:  0x000000000dd9cd5c
        X[22]:  0x000000000dd9cd5c
        X[23]:  0x0000000000000000
        X[24]:  0x000000000dd9cd5c
        X[25]:  0x00000049f07081e8 (SP:-0x0188)
        X[26]:  0x000000000dd9cd5c
        X[27]:  0x000000000d4c3164 (sdk:0x145164)       =>
        X[28]:  0x0000001dbfc72420
        FP:     0x00000049f0708060 (SP)
        LR:     0x000000000d4c4888 (sdk:0x146888)       => nn::diag::detail::Abort(nn::Result const*):0x0018
        SP:     0x00000049f0708060 (SP)
        PC:     0x000000000d71db54 (sdk:0x39fb54)       =>


00:00:35.327 |W| HLE.GuestThread.23 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.327 |W| HLE.GuestThread.18 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.327 |W| HLE.GuestThread.17 KernelSvc : WaitSynchronization(handleIndex: 0xFFFFFFFF) = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.20 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.19 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.24 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.21 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.22 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.328 |W| HLE.GuestThread.25 KernelSvc : WaitProcessWideKeyAtomic() = ThreadTerminating
00:00:35.394 |E| HLE.GuestThread.15 Application : Unhandled exception caught: Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 55
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
Unhandled exception. Ryujinx.HLE.Exceptions.GuestBrokeExecutionException: The guest program broke execution!
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.Syscall.Break(UInt64 reason) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\Syscall.cs:line 1852
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Break64(Syscall syscall, IExecutionContext context) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 1806
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallDispatch.Dispatch64(Syscall syscall, IExecutionContext context, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\Ryujinx.Horizon.Generators\Ryujinx.Horizon.Generators.Kernel.SyscallGenerator\SyscallDispatch.g.cs:line 3568
   at Ryujinx.HLE.HOS.Kernel.SupervisorCall.SyscallHandler.SvcCall(IExecutionContext context, UInt64 address, Int32 id) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\SupervisorCall\SyscallHandler.cs:line 17
   at ARMeilleure.Instructions.NativeInterface.SupervisorCall(UInt64 address, Int32 imm) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Instructions\NativeInterface.cs:line 55
   at ARMeilleure.Translation.Translator.Execute(ExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\ARMeilleure\Translation\Translator.cs:line 168
   at Ryujinx.Cpu.Jit.JitCpuContext.Execute(IExecutionContext context, UInt64 address) in D:\a\Ryujinx\Ryujinx\Ryujinx.Cpu\Jit\JitCpuContext.cs:line 32
   at Ryujinx.HLE.HOS.ArmProcessContext`1.Execute(IExecutionContext context, UInt64 codeAddress) in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\ArmProcessContext.cs:line 40
   at Ryujinx.HLE.HOS.Kernel.Threading.KThread.ThreadStart() in D:\a\Ryujinx\Ryujinx\Ryujinx.HLE\HOS\Kernel\Threading\KThread.cs:line 1265
   at System.Threading.Thread.StartCallback()
`

**Comment by gdkchan** [comment] 2022-07-25 04:24
You need to disable the "Expand DRAM to 6GB" option in the settings to run Legends Arceus, not a new issue. Closing as duplicate of #3314.

**Closed by gdkchan** 2022-07-25 04:24 UTC
